//
// sim/sim_register_state_handlers.h -- OUR registrar for the two strategic state-machine dispatch
// tables (RI-SIM / SIM1-DISPATCH, 2026-08-22).
//
// ---- WHAT THIS REPLACES, AND WHY IT IS A SEPARATE PIECE OF WORK ----------------------------------
//
// `llm_strat_register_state_handlers` @0x0045f26a (boot stage 4, called from llm_strat_mode_init)
// fills two 255-entry function-pointer tables:
//
//   _G_LLM_STRAT_UNIT_STATE_FUNCS[255] @0x00e15a3c -- dispatched by llm_strat_unit_tick as
//        unit_state_funcs[cur_unit.state]()   (the CALL at 0x0047c8dd)
//   _G_LLM_STRAT_BLDG_STATE_FUNCS[255] @0x00e15448 -- dispatched by llm_strat_building_tick as
//        bldg_state_funcs[cur_building.state]() (the CALL at 0x0046fedb)
//
// Each table is first filled 0..0xfe with a default handler and then overwritten at 44 (unit) and 34
// (bldg) specific states: 68 distinct handlers, ~35.5 KB, the per-tick behaviour of every unit and
// every building in the game.
//
// Those 68 handlers were the sim migration's structural blind spot: the
// closure is a forward DIRECT-CALL walk from llm_strat_sim_step, and 66 of the 68 have no inbound
// call edge at all -- only a PARAM data-ref from this registrar -- so the walk could not reach them.
// SIM1-G1..G5 have since translated and verified all 68. But translating a handler does not make the
// game RUN it: the table still holds the ORIGINAL's addresses, so a promoted unit_tick dispatches
// straight back into original code and a clean shadow or golden run says nothing about ownership.
//
// This file closes that: our registrar fills both tables with OUR handler pointers, so the dispatch
// layer the sim tick calls through is ours end to end.
//
// ---- WHY EACH SLOT IS AN ENTRY THUNK AND NOT THE C++ FUNCTION ITSELF -----------------------------
//
// The table entries are called by ORIGINAL Watcom code, which is entitled to Watcom's register
// contract. Two things make a raw `&mh::sim::unit_state_move_walker` in a slot wrong:
//
//   1. REGISTER PRESERVATION. Every original handler's prologue pushes EBX/ECX/EDX/ESI/EDI, i.e.
//      this build's __watcall preserves ECX and EDX across a call. MSVC's __cdecl does not. Dropping
//      a bare C++ function into the table would clobber two registers the caller expects to survive
//      -- a corruption with no crash at the corruption site.
//   2. FIVE HANDLERS TAKE REGISTER PARAMETERS. bldg_state_construction, bldg_state_prod_working,
//      bldg_state_mine_extracting, bldg_state_land_activate and bldg_state_deploy_start have a
//      committed 4-parameter __watcall prototype (EAX/EDX/EBX/ECX). At the table dispatch those
//      values are AMBIENT -- EAX holds state*4 and the rest are the caller's leftovers -- and two of
//      the five forward EBX/ECX verbatim into a callee. A __cdecl function in the slot would read
//      those four "parameters" off the STACK instead: different garbage, silently.
//
// So each slot gets that handler's GENERATED entry thunk (MH_EXPORT_REPLACE's
// mh_export_thunk_<fn>), which is the marshalling the export generator already derives from the
// committed prototype: it preserves ECX/EDX and, for those five, pushes EAX/EDX/EBX/ECX as the four
// arguments. Passing the ambient registers through unchanged is exactly what the original handler
// does with them, so this is the most faithful entry available, not a papering-over.
//
// ---- THE (state -> handler) PAIRING IS EXTRACTED, NOT TRANSCRIBED --------------------------------
//
// addr/mh_state_handlers.gen.h is generated by tools/gen_state_handler_table.py from the exported
// disassembly of the original registrar. 78 assignments hand-copied into C++ would be 78 chances to
// give one unit state another state's behaviour, and nothing would fail to compile or go red: the
// wrong handler is still a handler. The generated header also emits MH_STATE_HANDLERS(X) over the
// distinct handler set, which this TU expands to bind each original to its C++ reimplementation --
// so a handler present in the binary with no binding is a COMPILE error, not a silent gap.
//
// ---- WHAT THIS DOES NOT DO ----------------------------------------------------------------------
//
// It does not touch the original handlers' entry bytes. Filling the tables makes 66 of the 68
// original bodies unreachable, but TWO stay reachable by a direct call that does not go through a
// table -- llm_strat_unit_state_die_explode (called from llm_strat_unit_apply_damage @0x0047e53c)
// and llm_strat_bldg_state_destroyed (from llm_strat_bldg_apply_damage @0x0047117b). That is why
// this installer does NOT call mh::hook::note_promoted() for any of them: the C1 interlock's claim
// is "every byte of this body is dead", which would be a lie for those two and unverifiable for the
// rest without also owning the callers. Measured exposure today is nil -- no entry in
// tools/data/dll_patch_manifest.json falls inside any of the 68 bodies -- and the day one does, the
// right fix is a per-handler reachability fact in the generated table, not a blanket claim here.
//
#pragma once
#include <cstdint>

#include "sim/sim_state.h" // unit_state_fn / bldg_state_fn -- the table element types

namespace mh::sim {

// One original handler and the entry we install in its place.
struct handler_binding {
    const char   *name;        // the ORIGINAL Ghidra symbol, for the log and the oracle
    uintptr_t     original_va; // its entry in the game image (mh::exp::addr_<fn>)
    unit_state_fn ours;        // our generated entry thunk; same void(*)() shape for both tables
};

namespace detail {

// The 68 bindings, in the generated header's first-appearance order.
const handler_binding *handler_bindings();
int                    handler_binding_count();

// The binding for an ORIGINAL handler VA, or nullptr. A miss cannot happen in a correct build (the
// ASSIGN tables and the X-macro come from the same generated file) -- it is reported rather than
// asserted so the caller can refuse to install a half-filled table.
const handler_binding *binding_for(uintptr_t original_va);


// ---- THE STANDALONE BINDING TABLE, READABLE (fork F5I S2) ---------------------------------------
//
// Exposed for exactly the reason the hosted pair above is exposed: the offline oracle has to be able
// to read the rows the fill uses, or it can only compare the fill against itself. The hosted table
// is keyed by the ORIGINAL VA; this configuration has no original address to key by -- the VA rows
// are compiled out so that libmh.lib's initialised data carries none (LIB-REF-SPLIT's measured
// zero) -- so the same rows are keyed by NAME. That is the ONLY difference, and confining it here
// is what lets the oracle keep one body for both arms.
#ifdef MH_LIBMH_BUILD
// One row of it. `ours` is the body the slot will hold: the direct C++ function for the 63
// zero-argument handlers, and the zero-argument ADAPTER for the five whose committed prototype takes
// four __watcall register parameters (see the allow-list in the .cpp). It is never null for a name
// this returns a row for -- a name on the table but off the allow-list resolves to nullptr instead,
// which fill_tables turns into a refusal before it writes anything.
struct sa_binding {
    const char *name;
    void (*ours)();
};

int sa_handler_binding_count();
// The i-th binding's name, or "" out of range -- an index-free way to walk the set, so the oracle
// need not be handed the array itself.
const char       *sa_handler_binding_name(int i);
const sa_binding *sa_handler_binding_for(const char *name);
#endif // MH_LIBMH_BUILD

// Fill both tables exactly as the original registrar fills the game's: default everywhere first,
// then each assigned state. Writes NOTHING and returns false if a table is smaller than the
// generated one or any VA has no binding -- a partially-filled dispatch table is worse than none.
//
// Split out from register_state_handlers() so the offline oracle can drive it over local arrays:
// this is the whole of the logic, and the live entry point is only the binding around it.
bool fill_tables(unit_state_fn *unit_tbl, int32_t unit_slots, bldg_state_fn *bldg_tbl,
                 int32_t bldg_slots);

} // namespace detail

// Our replacement for llm_strat_register_state_handlers (`[promote] state_handlers=1`).
void register_state_handlers();

// Install the promotion. Ship default is PASSED IN rather than read from a header here -- the
// SHIP_PROMOTE_* constants live in mh/seams/net_internal.h and a reimplementation TU must not
// include a seams header (the layering lint). Same arrangement as install_promotion_dispatch.
// Returns 1 if the entry is ours in this run.
int install_promotion_state_handlers(int default_on);

// True once install_promotion_state_handlers() has taken the entry.
bool state_handlers_promoted();

// Is `target` one of our 68 entry thunks? Exact set membership against the binding table -- not a
// module-address-range guess, so it cannot be fooled by any other DLL code that happens to be
// nearby.
bool is_our_handler(const void *target);

// The ONE-TIME note each tick site emits on its first dispatch through its table, saying whether the
// entry it is about to call is OURS or the game's. SIM1-DISPATCH's done_when asks for exactly this
// and asks for it to be SHOWN rather than assumed: "the tables were filled" is an install-time
// claim, and the thing actually in question is whether the tick then dispatches through them.
// `table_tag` is "unit" or "bldg"; each tag notes once per run.
void note_first_dispatch(const char *table_tag, const void *target);

} // namespace mh::sim
