//
// sim/sim_register_bldg_type_callbacks.cpp -- see sim_register_bldg_type_callbacks.h for the whole
// rationale (what this replaces, why it is a TYPE pairing plus a runtime scan rather than an id
// table, and why every slot is an entry thunk).
//
// The (type -> callback) data is addr/mh_bldg_type_callbacks.gen.h, generated by
// tools/gen_state_handler_table.py --extract-bldg-type from the exported disassembly of
// llm_strat_register_bldg_type_callbacks @0x0045f76a. Nothing in this file transcribes a building
// type or a callback address.
//
#include "sim/sim_register_bldg_type_callbacks.h"

#include <cstring> // strcmp -- the standalone fill is keyed by callback NAME (LIB-DISPATCH-SA)

#include "addr/mh_bldg_type_callbacks.gen.h" // the extracted tables + MH_BLDG_TYPE_CALLBACKS(X)
#include "addr/mh_export.gen.h"              // MH_EXPORT_REPLACE -- the entry thunks AND the registrar's own
#include "ai/ai_state.h"                     // ai_say -- the shared trace sink, not AI state

#include "sim/sim_bldg_anim_state_online.h"
#include "sim/sim_bldg_anim_state_port.h"
#include "sim/sim_bldg_anim_tick.h"
#include "sim/sim_bldg_done_handlers.h"


// ---- the 30 entry thunks ------------------------------------------------------------------------
//
// One MH_EXPORT_REPLACE per distinct callback, at global scope (same placement as
// sim_register_state_handlers.cpp's 68). Each expands to the marshalling thunk the export generator
// derives from that callback's COMMITTED prototype -- 22 of them the plain preserve-ECX/EDX shape,
// 8 the EAX/EDX/EBX/ECX one -- plus an installer we deliberately never call: this file takes the
// TABLES, not the entry bytes (see the header's "what this does not do").
//
// The list is MH_BLDG_TYPE_CALLBACKS from the generated header, so it is the binary's own callback
// set. A callback that appears there without a matching mh::sim wrapper does not compile.
//
// C1 INTERLOCK: exactly as sim_register_state_handlers.cpp documents at length -- gen_dll_patches.py
// greps sources for a LITERAL `MH_EXPORT_REPLACE(<fn>,`, so uses arriving through a macro expansion
// are invisible to it and none of the 30 bodies lands in mh::addr::promotable_ranges. That is the
// CORRECT answer here for the same reason: this file never calls their installers, so their entry
// bytes are untouched and their bodies are not JMP'd away.
#define MH_SIM_BLDGCB_ARM(FULL, STEM) MH_EXPORT_REPLACE(FULL, &::mh::sim::STEM)
MH_BLDG_TYPE_CALLBACKS(MH_SIM_BLDGCB_ARM)
#undef MH_SIM_BLDGCB_ARM

// ---- our replacement for the registrar itself ---------------------------------------------------
MH_EXPORT_REPLACE(llm_strat_register_bldg_type_callbacks, mh::sim::register_bldg_type_callbacks)

namespace mh::sim {
namespace {

// The binding table: original symbol / original VA / our thunk, one row per distinct callback.
// `addr_<fn>` comes from mh_export.gen.h and the thunk from the macro above, so neither column is
// written out here -- the only thing this file contributes is the pairing of the two, and both
// sides are keyed by the SAME token.
#ifndef MH_LIBMH_BUILD
const bldg_type_callback_binding kBindings[] = {
#define MH_SIM_BLDGCB_BIND(FULL, STEM) {#FULL, ::mh::exp::addr_##FULL, &::mh_export_thunk_##FULL},
    MH_BLDG_TYPE_CALLBACKS(MH_SIM_BLDGCB_BIND)
#undef MH_SIM_BLDGCB_BIND
};

constexpr int kBindingCount = static_cast<int>(sizeof(kBindings) / sizeof(kBindings[0]));

// The generated header counts the same set independently (it emits the X-list AND the count from
// the same extraction). If these ever disagree the macro expansion has lost a row.
static_assert(kBindingCount == mh::addr::BLDG_TYPE_CALLBACK_DISTINCT_COUNT,
              "the binding table and the generated callback set disagree");
#else
// THE STANDALONE ARM (LIB-REF-SPLIT, 2026-09-11) -- the same refusal, and for the same reasons, as
// sim_register_state_handlers.cpp's; read that file's arm for the full argument. Short version: both
// columns here are injection (an ORIGINAL entry address and a naked Watcom entry thunk that is not
// generated standalone), the whole fill is keyed by original VA, and what a standalone table should
// hold instead is the standalone host's question (LIB-REF), not the build split's.
// ---- THE STANDALONE ARM (LIB-DISPATCH-SA, 2026-09-11) ---------------------------------------
//
// The sibling of sim_register_state_handlers.cpp's arm, and it exists for the same measured reason:
// the world blob carries these two tables with the RECORDING process's mh.dll thunk addresses in
// them (byte-band scan of the committed fixture: BLDG_DONE 68 in-band dwords / 16 distinct,
// BLDG_TICK2 68 / 14), and both are DISPATCHED THROUGH -- done on building completion, tick2 from
// sim_bldg_tick_animation_state. Left carried they are a call through a foreign pointer.
//
// Keyed by NAME, never by address: walking the VA-bearing rows at runtime would emit original-image
// addresses into libmh.lib's initialised data and break LIB-REF-SPLIT's measured zero. The
// generated header compiles those rows out of this configuration and offers name-keyed ones.
using sa_cb_fn = bldg_done_fn;

constexpr sa_cb_fn sa_cb_bind(void (*f)()) { return f; }
constexpr sa_cb_fn sa_cb_bind(void (*)(uint32_t, uint32_t, uint32_t, uint32_t)) { return nullptr; }

struct sa_cb_binding {
    const char *name;
    sa_cb_fn    ours;
};

constexpr sa_cb_binding kBindingsSA[] = {
#define MH_SIM_BLDGCB_BIND_SA(FULL, STEM) {#FULL, sa_cb_bind(&::mh::sim::STEM)},
    MH_BLDG_TYPE_CALLBACKS(MH_SIM_BLDGCB_BIND_SA)
#undef MH_SIM_BLDGCB_BIND_SA
};
constexpr int kBindingCountSA = static_cast<int>(sizeof(kBindingsSA) / sizeof(kBindingsSA[0]));

// NO register-parameter callback exists in this set, and this assertion is what keeps that true
// rather than remembered. If one ever appears it resolves to nullptr here and the build stops, so
// its parameters' liveness gets measured the way the state table's five did.
// ---- THE ZERO-PARAMETER ALLOW-LIST for this table (LIB-DISPATCH-SA, 2026-09-11) --------------
//
// EIGHT of the thirty have a 4-register __watcall prototype, and the guard below is what found
// them -- they were not in the item's opening scope, which named five.
//
// THE COMMITTED PROTOTYPE NAMES ALL FOUR `unused_eax/edx/ebx/ecx`, AND THAT NAME IS NOT THE PROOF.
// Read the bodies: eax/edx really are `(void)`-cast at every one of the eight, but ebx/ecx are
// FORWARDED -- sim_bldg_anim_state_online.cpp:70-71 and :143 pass them straight into the
// `bldg_online_*` family. A name that says unused over a value that is passed on is exactly the
// shape that gets waved through, so it was followed one more hop: the family discards them, 24
// `(void)param_3;`/`(void)param_4;` sites across sim_bldg_online_secondary.cpp and
// sim_bldg_register_online.cpp, which is the same 12-way fan-out the state table's
// bldg_state_land_activate was cleared through. Nothing reads either value.
//
// Measured on the real trajectory as well, not only read: with all thirteen register-parameter
// bodies (these eight plus the state table's five) fed literal zeros, a hosted replay of the
// committed LIB-REF fixture is BIT-IDENTICAL to the committed stream, per-step and per-region, over
// all 5000 steps.
#define MH_SIM_SA_ZERO_PARAM_CALLBACKS(X) X(llm_strat_bldg_anim_state_barracks_garage_a, bldg_anim_state_barracks_garage_a) X(llm_strat_bldg_anim_state_soldiers_h, bldg_anim_state_soldiers_h) X(llm_strat_bldg_anim_state_vehicles_h, bldg_anim_state_vehicles_h) X(llm_strat_bldg_anim_state_helipad, bldg_anim_state_helipad) X(llm_strat_bldg_anim_state_airfield_a, bldg_anim_state_airfield_a) X(llm_strat_bldg_anim_state_online_toggle, bldg_anim_state_online_toggle) X(llm_strat_bldg_anim_state_shuttle_a, bldg_anim_state_shuttle_a) X(llm_strat_bldg_anim_state_shuttle_h, bldg_anim_state_shuttle_h)

#define MH_SIM_SA_CB_ADAPTER(FULL, STEM) \
    void sa_zero_##STEM() { ::mh::sim::STEM(0u, 0u, 0u, 0u); }
MH_SIM_SA_ZERO_PARAM_CALLBACKS(MH_SIM_SA_CB_ADAPTER)
#undef MH_SIM_SA_CB_ADAPTER

const sa_cb_binding kZeroParamCbSA[] = {
#define MH_SIM_SA_CB_ROW(FULL, STEM) {#FULL, &sa_zero_##STEM},
    MH_SIM_SA_ZERO_PARAM_CALLBACKS(MH_SIM_SA_CB_ROW)
#undef MH_SIM_SA_CB_ROW
};
constexpr int kZeroParamCbCountSA =
    static_cast<int>(sizeof(kZeroParamCbSA) / sizeof(kZeroParamCbSA[0]));

constexpr int sa_cb_unbound_count() {
    int n = 0;
    for (int i = 0; i < kBindingCountSA; ++i)
        if (kBindingsSA[i].ours == nullptr) ++n;
    return n;
}
static_assert(sa_cb_unbound_count() == kZeroParamCbCountSA,
              "a building-type callback acquired (or lost) a 4-register __watcall prototype: its "
              "parameters' liveness must be measured -- FOLLOW THE FORWARDS, the committed "
              "prototype's `unused_` names are not proof -- and it must be added to (or removed "
              "from) MH_SIM_SA_ZERO_PARAM_CALLBACKS. Never let it default.");

const sa_cb_binding *sa_cb_binding_for(const char *name) {
    for (int i = 0; i < kBindingCountSA; ++i)
        if (std::strcmp(kBindingsSA[i].name, name) == 0) {
            if (kBindingsSA[i].ours != nullptr) return &kBindingsSA[i];
            for (int j = 0; j < kZeroParamCbCountSA; ++j)
                if (std::strcmp(kZeroParamCbSA[j].name, name) == 0) return &kZeroParamCbSA[j];
            return nullptr; // on the table, off the allow-list: refuse rather than zero it
        }
    return nullptr;
}

// The hosted-shaped table stays declared so the diagnostics compile unchanged; standalone it is
// empty, because "is this pointer one of the ORIGINAL-keyed bindings" has no standalone meaning.
const bldg_type_callback_binding kBindings[1]  = {{"", 0u, nullptr}};
constexpr int                    kBindingCount = 0;
#endif // MH_LIBMH_BUILD

bool g_promoted    = false;
bool g_tables_ours = false;

// The cfg type byte for one building id, read exactly as the setters read it. `cfg_building::type`
// is a uint8_t and the setters MOVZX it, so there is no sign question to get wrong here.
inline int type_of(const sim_bldg_callback_tables &t, int id) {
    return static_cast<int>(t.cfg[id].type);
}

#ifndef MH_LIBMH_BUILD
// One table's worth of the original's fill, in the original's ORDER: the default across the whole
// default-type range first, then each explicit assignment. Reproduced as two passes rather than
// collapsed into "resolve each id once" because the order is what decides the result if a type were
// ever assigned twice -- the extractor refuses that case today, and this keeps the code correct if
// it ever stops refusing.
void fill_one(const sim_bldg_callback_tables &t, bldg_done_fn *table, int id_limit,
              bldg_done_fn dflt, int type_lo, int type_hi,
              const mh::addr::bldg_type_callback_slot *assign, int assign_count, int *filled) {
    for (int id = mh::addr::BLDG_TYPE_FIRST_ID; id < id_limit; ++id) {
        const int ty = type_of(t, id);
        // Outside the default-fill loop's range the original NEVER touches this slot -- see the
        // header. Leaving it alone is the faithful choice, not an omission.
        if (ty < type_lo || ty > type_hi) continue;
        table[id] = dflt;
    }
    for (int i = 0; i < assign_count; ++i) {
        const mh::addr::bldg_type_callback_slot &a = assign[i];
        const bldg_type_callback_binding        *b = detail::bldg_type_binding_for(a.original_va);
        for (int id = mh::addr::BLDG_TYPE_FIRST_ID; id < id_limit; ++id)
            if (type_of(t, id) == static_cast<int>(a.type)) table[id] = b->ours;
    }
    int n = 0;
    for (int id = 0; id < id_limit; ++id)
        if (is_our_bldg_type_callback(reinterpret_cast<const void *>(table[id]))) ++n;
    *filled = n;
}
#endif // MH_LIBMH_BUILD


#ifdef MH_LIBMH_BUILD
// The standalone twin of fill_one, name-keyed. Deliberately a SEPARATE function rather than a
// templated merge: the two differ only in how a row resolves to a body, and keeping the hosted one
// byte-identical is worth more than sharing six lines (LIB-DISPATCH-SA's done_when requires the
// hosted registrar path untouched, and "untouched" is easiest to verify when it is literally so).
void fill_one_sa(const sim_bldg_callback_tables &t, bldg_done_fn *table, int id_limit,
                 bldg_done_fn dflt, int type_lo, int type_hi,
                 const mh::addr::bldg_type_callback_slot_sa *assign, int assign_count, int *filled) {
    for (int id = mh::addr::BLDG_TYPE_FIRST_ID; id < id_limit; ++id) {
        const int ty = type_of(t, id);
        if (ty < type_lo || ty > type_hi) continue; // outside the range the original never touches
        table[id] = dflt;
    }
    for (int i = 0; i < assign_count; ++i) {
        const mh::addr::bldg_type_callback_slot_sa &a = assign[i];
        const sa_cb_binding                        *b = sa_cb_binding_for(a.name);
        for (int id = mh::addr::BLDG_TYPE_FIRST_ID; id < id_limit; ++id)
            if (type_of(t, id) == static_cast<int>(a.type)) table[id] = b->ours;
    }
    int n = 0;
    for (int id = 0; id < id_limit; ++id)
        if (table[id] != nullptr) ++n;
    *filled = n;
}
#endif

} // namespace

namespace detail {

const bldg_type_callback_binding *bldg_type_callback_bindings() { return kBindings; }
int                               bldg_type_callback_binding_count() { return kBindingCount; }

const bldg_type_callback_binding *bldg_type_binding_for(uintptr_t original_va) {
    for (int i = 0; i < kBindingCount; ++i)
        if (kBindings[i].original_va == original_va) return &kBindings[i];
    return nullptr;
}

bool fill_bldg_callback_tables(const sim_bldg_callback_tables &t, int *filled_done,
                               int *filled_tick2) {
    if (filled_done) *filled_done = 0;
    if (filled_tick2) *filled_tick2 = 0;
#ifdef MH_LIBMH_BUILD
    // ---- THE STANDALONE FILL (LIB-DISPATCH-SA) ----------------------------------------------
    // Same shape and same ORDER as the hosted fill below -- default across the default-type range,
    // then each explicit assignment -- keyed by name. The hosted arm is textually untouched.
    if (t.done == nullptr || t.tick2 == nullptr || t.cfg == nullptr) return false;
    if (t.done_slots < mh::addr::BLDG_TYPE_ID_LIMIT) return false;
    if (t.tick2_slots < mh::addr::BLDG_TYPE_ID_LIMIT) return false;
    if (t.cfg_count < mh::addr::BLDG_TYPE_ID_LIMIT) return false;

    const sa_cb_binding *done_dflt  = sa_cb_binding_for(mh::addr::BLDG_DONE_DEFAULT_NAME);
    const sa_cb_binding *tick2_dflt = sa_cb_binding_for(mh::addr::BLDG_TICK2_DEFAULT_NAME);
    if (done_dflt == nullptr || tick2_dflt == nullptr) return false;
    for (int i = 0; i < mh::addr::BLDG_DONE_ASSIGN_SA_COUNT; ++i)
        if (sa_cb_binding_for(mh::addr::BLDG_DONE_ASSIGN_SA[i].name) == nullptr) return false;
    for (int i = 0; i < mh::addr::BLDG_TICK2_ASSIGN_SA_COUNT; ++i)
        if (sa_cb_binding_for(mh::addr::BLDG_TICK2_ASSIGN_SA[i].name) == nullptr) return false;

    int done_n = 0, tick2_n = 0;
    fill_one_sa(t, t.done, mh::addr::BLDG_TYPE_ID_LIMIT, done_dflt->ours,
                mh::addr::BLDG_DONE_DEFAULT_TYPE_LO, mh::addr::BLDG_DONE_DEFAULT_TYPE_HI,
                mh::addr::BLDG_DONE_ASSIGN_SA, mh::addr::BLDG_DONE_ASSIGN_SA_COUNT, &done_n);
    fill_one_sa(t, reinterpret_cast<bldg_done_fn *>(t.tick2), mh::addr::BLDG_TYPE_ID_LIMIT,
                tick2_dflt->ours, mh::addr::BLDG_TICK2_DEFAULT_TYPE_LO,
                mh::addr::BLDG_TICK2_DEFAULT_TYPE_HI, mh::addr::BLDG_TICK2_ASSIGN_SA,
                mh::addr::BLDG_TICK2_ASSIGN_SA_COUNT, &tick2_n);
    if (filled_done) *filled_done = done_n;
    if (filled_tick2) *filled_tick2 = tick2_n;
    return true;
#else
    if (t.done == nullptr || t.tick2 == nullptr || t.cfg == nullptr) return false;

    // REFUSE BEFORE WRITING, not half way through. The original's setters run their id loop
    // unconditionally over 1..BLDG_TYPE_ID_LIMIT-1; a region or a cfg table shorter than that means
    // something is unrebased or mis-sized, and writing what fits would leave a live dispatch table
    // part ours and part whatever was in .bss -- the one outcome worse than not installing.
    if (t.done_slots < mh::addr::BLDG_TYPE_ID_LIMIT) return false;
    if (t.tick2_slots < mh::addr::BLDG_TYPE_ID_LIMIT) return false;
    if (t.cfg_count < mh::addr::BLDG_TYPE_ID_LIMIT) return false;

    if (bldg_type_binding_for(mh::addr::BLDG_DONE_DEFAULT_VA) == nullptr) return false;
    if (bldg_type_binding_for(mh::addr::BLDG_TICK2_DEFAULT_VA) == nullptr) return false;
    for (int i = 0; i < mh::addr::BLDG_DONE_ASSIGN_SA_COUNT; ++i)
        if (bldg_type_binding_for(mh::addr::BLDG_DONE_ASSIGN[i].original_va) == nullptr) return false;
    for (int i = 0; i < mh::addr::BLDG_TICK2_ASSIGN_SA_COUNT; ++i)
        if (bldg_type_binding_for(mh::addr::BLDG_TICK2_ASSIGN[i].original_va) == nullptr) return false;

    int done_n = 0, tick2_n = 0;
    fill_one(t, t.done, mh::addr::BLDG_TYPE_ID_LIMIT,
             bldg_type_binding_for(mh::addr::BLDG_DONE_DEFAULT_VA)->ours,
             mh::addr::BLDG_DONE_DEFAULT_TYPE_LO, mh::addr::BLDG_DONE_DEFAULT_TYPE_HI,
             mh::addr::BLDG_DONE_ASSIGN, mh::addr::BLDG_DONE_ASSIGN_SA_COUNT, &done_n);
    // Both tables hold void(*)() and the two typedefs are distinct names for it, so the tick2 table
    // is passed through the same helper rather than duplicating it for a type that is the same type.
    fill_one(t, reinterpret_cast<bldg_done_fn *>(t.tick2), mh::addr::BLDG_TYPE_ID_LIMIT,
             bldg_type_binding_for(mh::addr::BLDG_TICK2_DEFAULT_VA)->ours,
             mh::addr::BLDG_TICK2_DEFAULT_TYPE_LO, mh::addr::BLDG_TICK2_DEFAULT_TYPE_HI,
             mh::addr::BLDG_TICK2_ASSIGN, mh::addr::BLDG_TICK2_ASSIGN_SA_COUNT, &tick2_n);

    if (filled_done) *filled_done = done_n;
    if (filled_tick2) *filled_tick2 = tick2_n;
    return true;
#endif // MH_LIBMH_BUILD
}

} // namespace detail

bool is_our_bldg_type_callback(const void *target) {
    for (int i = 0; i < kBindingCount; ++i)
        if (reinterpret_cast<const void *>(kBindings[i].ours) == target) return true;
    return false;
}

void note_first_bldg_type_dispatch(const char *table_tag, const void *target) {
    static bool noted_done  = false;
    static bool noted_tick2 = false;
    const bool  is_done     = (table_tag != nullptr && table_tag[0] == 'd');
    bool       &noted       = is_done ? noted_done : noted_tick2;
    if (noted) return;
    noted = true;
    mh::ai::ai_say("; [bldgcb] %s FIRST dispatch -> %s callback %p (tables_ours=%d)\n", table_tag,
                   is_our_bldg_type_callback(target) ? "OUR" : "ORIGINAL", target,
                   g_tables_ours ? 1 : 0);
}

void register_bldg_type_callbacks() {
    const sim_bldg_callback_tables t = writable_bldg_callback_tables();

    int done_n = 0, tick2_n = 0;
    if (!detail::fill_bldg_callback_tables(t, &done_n, &tick2_n)) {
        // Loud, and nothing written. The alternative -- a table we filled part of the way -- would
        // hand the building tick a dispatch through uninitialised .bss on the ids we did not reach.
        mh::ai::ai_say("; [promote] bldg_type_callbacks REFUSED to fill -- done_slots=%d "
                       "tick2_slots=%d cfg_count=%d (each needs >= %d); the ORIGINAL tables are "
                       "untouched and this run has NO per-building-type callbacks installed at "
                       "all\n",
                       t.done_slots, t.tick2_slots, t.cfg_count, mh::addr::BLDG_TYPE_ID_LIMIT);
        return;
    }
    g_tables_ours = true;

    // Non-vacuity, at the level the done_when asks about. The counts are CFG-DEPENDENT -- they are
    // how many building ids the scan actually matched, not how many assignments the header holds --
    // so a run whose cfg has not been parsed yet reports 0/0 here instead of looking installed. That
    // distinction is the whole reason this logs a count and not "installed".
    mh::ai::ai_say("; [promote] bldg_type_callbacks: scanned %d building ids -- done[%d] now %d "
                   "ours, tick2[%d] now %d ours, from %d distinct C++ callbacks (%d + %d type "
                   "assignments)\n",
                   mh::addr::BLDG_TYPE_ID_LIMIT - mh::addr::BLDG_TYPE_FIRST_ID, t.done_slots,
                   done_n, t.tick2_slots, tick2_n, kBindingCount,
                   mh::addr::BLDG_DONE_ASSIGN_SA_COUNT, mh::addr::BLDG_TICK2_ASSIGN_SA_COUNT);
}

bool bldg_type_callbacks_promoted() { return g_promoted; }

int install_promotion_bldg_type_callbacks(int default_on) {
    if (default_on == 0) return 0;
    if (!mh_export_install_llm_strat_register_bldg_type_callbacks()) {
        // The generated installer already logged WHY -- an entry-byte guard mismatch means the DLL
        // was built against a different image. Refuse loudly: with the registrar half-installed the
        // tables would keep the original callbacks and every later claim about ownership would be
        // false while every log line still said "promoted".
        mh::ai::ai_say("; [promote] bldg_type_callbacks REFUSED -- entry guard mismatch, NOT "
                       "promoted\n");
        return 0;
    }
    g_promoted = true;
    // Note the ORDER this run now has: the entry is ours from here, but the tables do not change
    // until the game actually calls the registrar (boot stage 5 / game load), which is AFTER this,
    // and the fill is only meaningful once the cfg Building table has been parsed. A reader of the
    // log needs both lines to conclude anything.
    mh::ai::ai_say("; [promote] bldg_type_callbacks: llm_strat_register_bldg_type_callbacks is LIVE "
                   "-- the two per-building-type tables become ours at the next game load\n");
    return 1;
}

} // namespace mh::sim
