//
// save/save_table.gen.h -- GENERATED by tools/gen_save_table_header.py from
// tools/data/save_block_table.json. DO NOT EDIT: regenerate.
//
// The save format IS an ordered list of (address, size) block calls, so it is carried as data rather
// than as ninety hand-written calls in two directions. The pairing between the two directions is
// checked by the generator, not asserted here -- see its header comment, and docs/save-format.md.
//
// KIND vocabulary:
//   STEP_BLOCK     one block, fixed address, fixed size.
//   STEP_REGIONS   the region graph -- four 4-byte header blocks, then N x REGION_RECORD_BYTES where
//                  N is the value of the FOURTH header block (G_LAST_MAP_INDEX), then one
//                  REGION_GRID_IDS_BYTES block and one REGION_TERRAIN_BYTES block. All unconditional.
//   STEP_PROGRESS  PROGRESS_COUNT blocks at PROGRESS_STRIDE, each 3 * (uint16)[PROGRESS_SLICE_WORD].
//                  The only data-derived SIZE in the whole format.
//   STEP_MEMBERS   per planet satisfying the embedded-member predicate: a plain uint32 length then
//                  that planet file's bytes VERBATIM, streamed in MEMBER_CHUNK-byte pieces. NOT
//                  blocks. The member count is implicit -- recomputed from state read earlier in the
//                  same file.
//   STEP_MEDIA     the write-only 0x400 media/CD-fingerprint block, the last thing the writer emits.
//   STEP_TAIL      its read-side counterpart: nothing in the original reads it, so a round-tripping
//                  reader captures the remaining bytes opaquely and re-emits them.
//
#pragma once
#include <cstdint>

// SB-HOSTFREE: BLOCK_SLICES names regions by `mh::state::region_id`, so the decomposition and
// the registry cannot drift into two different opinions about which region a run belongs to.
#include "addr/mh_regions.gen.h"

namespace mh::save::table {

enum step_kind : uint8_t {
    STEP_BLOCK = 0,
    STEP_REGIONS,
    STEP_PROGRESS,
    STEP_MEMBERS,
    STEP_MEDIA,
    STEP_TAIL,
};

struct step {
    uint32_t    addr;      // 0 when the step is not one fixed region
    uint32_t    size;      // 0 when derived at run time
    uint8_t     kind;
    uint8_t     ver_min;   // inclusive: applies when detected version >= this
    uint8_t     ver_max;   // inclusive
    bool        discard;   // read-side only: consumed and thrown away, never written
    uint32_t    write_at;  // the original's call address, writer side
    uint32_t    read_at;   // and reader side
    const char *name;
};

inline constexpr uint8_t VER_MIN_ANY = 0;
inline constexpr uint8_t VER_MAX_ANY = 255;

// The progress[] loop: 8 blocks at stride 0x384 from `progress`, each 3 * a word in .data
// (MOVZX EDX,word ptr [0x00e16305] / LEA EDX,[EDX+EDX*2] @ 0x004480a8).
inline constexpr uint32_t PROGRESS_BASE = 0x00c38750;
inline constexpr uint32_t PROGRESS_STRIDE = 0x384;
inline constexpr uint32_t PROGRESS_COUNT = 8;
inline constexpr uint32_t PROGRESS_SLICE_WORD = 0x00e16305;

// The region graph. N is G_LAST_MAP_INDEX, i.e. the fourth header block -- read from the FILE on load
// and from live state on save, which is why a mismatch between it and the linked list's length is a
// real (and unchecked) hazard in the original.
inline constexpr uint32_t REGION_RECORD_BYTES = 0x40c;
inline constexpr uint32_t REGION_COUNT_ADDR = 0x00708b18;
inline constexpr uint32_t REGION_GRID_IDS_BYTES = 0x40000;
inline constexpr uint32_t REGION_TERRAIN_BYTES = 0x10000;
inline constexpr uint32_t REGION_LIST_HEAD_ADDR = 0x0051de7c;
inline constexpr uint32_t REGION_NODE_BYTES = 0x420;   // malloc 0x420 @ 0x00424b76
inline constexpr uint32_t REGION_NODE_NEXT_OFF = 0x40c;
inline constexpr uint32_t REGION_NEIGHBOUR_PTRS_OFF = 0x0c;
inline constexpr uint32_t REGION_NEIGHBOUR_DATA_OFF = 0x20c;
inline constexpr uint32_t REGION_NEIGHBOUR_COUNT_OFF = 0x08;
inline constexpr uint32_t REGION_BY_INDEX_ADDR = 0x00684ac4;

// The embedded-member predicate, byte for byte the same test at 0x0044741a (save) and 0x004479c2
// (load):  Planets[i].system_index == CurrentSystem && (PlanetStatus[i] != 0 || PlanetIndex == i)
inline constexpr uint32_t PLANETS_BASE = 0x00be6da0;
inline constexpr uint32_t PLANET_STRIDE = 0x427;
inline constexpr uint32_t PLANET_SYSTEM_OFF = 0x08;
inline constexpr uint32_t CURRENT_SYSTEM_ADDR = 0x00e58781;
inline constexpr uint32_t PLANET_STATUS_ADDR = 0x00e5836b;   // + i * 4
inline constexpr uint32_t PLANET_INDEX_ADDR = 0x00e58366;
inline constexpr int32_t  MEMBER_FIRST = 1;                  // MOV [EBP-0x28],1 -- NOT 0
inline constexpr int32_t  MEMBER_LIMIT = 0x20;               // CMP [EBP-0x28],0x20 / JL
inline constexpr uint32_t MEMBER_CHUNK = 0x927c0;            // the streaming chunk, = BLOCK_READ_CAP
inline constexpr uint32_t MEDIA_BLOCK_BYTES = 0x400;

inline constexpr step CONTAINER[] = {
    { 0x00e4a098,     57500, STEP_BLOCK,      0, 255, false, 0x0044726e, 0x00447785, "Unit" },
    { 0x00d9ec80,    211400, STEP_BLOCK,      0, 255, false, 0x00447283, 0x0044779a, "Building" },
    { 0x00c3a520,     11648, STEP_BLOCK,      0, 255, false, 0x00447298, 0x004477af, "Weapon" },
    { 0x00000000,     30900, STEP_BLOCK,      0,   1, true,  0x00000000, 0x004477cb, "expr@0x004477cb" },
    { 0x00be1a30,       560, STEP_BLOCK,      0, 255, false, 0x004472ad, 0x004477e0, "System" },
    { 0x00be6da0,     34016, STEP_BLOCK,      0, 255, false, 0x004472c2, 0x004477f5, "Planets" },
    { 0x00be1c60,     20800, STEP_BLOCK,      0, 255, false, 0x004472d7, 0x0044780a, "Projects" },
    { 0x00bcf8d0,     10400, STEP_BLOCK,      0, 255, false, 0x004472ec, 0x0044781f, "Upgrades" },
    { 0x00cff060,     14848, STEP_BLOCK,      0, 255, false, 0x00447301, 0x00447834, "_G_LLM_STRAT_PLAYERS" },
    { 0x00c38730,        16, STEP_BLOCK,      0, 255, false, 0x00447316, 0x00447849, "DAT_00c38730" },
    { 0x00bd2170,     63680, STEP_BLOCK,      0, 255, false, 0x0044732b, 0x0044785e, "_G_LLM_PROD_SHUTTLE_SLOTS[0].src_building_index" },
    { 0x00c38750,      7200, STEP_BLOCK,      0, 255, false, 0x00447340, 0x00447873, "progress" },
    { 0x00e58344,      1623, STEP_BLOCK,      0, 255, false, 0x00447355, 0x00447888, "_G_LLM_GAME_SESSION_MODE" },
    { 0x00000000,      3600, STEP_BLOCK,      0,   3, true,  0x00000000, 0x004478a4, "expr@0x004478a4" },
    { 0x005ce484,      7200, STEP_BLOCK,      4, 255, false, 0x0044736a, 0x00447905, "MESSAGE_QUEUE" },
    { 0x00ae4b90,       240, STEP_BLOCK,      0, 255, false, 0x0044737f, 0x0044791a, "MESSAGE_TIME" },
    { 0x00e162a0,        60, STEP_BLOCK,      0, 255, false, 0x00447394, 0x0044792f, "_G_LLM_STRAT_FLOATING_MSG_COLOR" },
    { 0x00ae2b00,         8, STEP_BLOCK,      0, 255, false, 0x004473a9, 0x00447944, "_G_LLM_ANIM_PLACE_DENIED" },
    { 0x00bca820,       256, STEP_BLOCK,      5, 255, false, 0x004473be, 0x0044795f, "_G_LLM_STRAT_INVASION_ALERT_TIME" },
    { 0x00b64ba8,         8, STEP_BLOCK,      5, 255, false, 0x004473d3, 0x00447974, "_G_LLM_STRAT_ADVISOR_NEXT_TIME" },
    { 0x0050b077,      3200, STEP_BLOCK,      0, 255, false, 0x0041c181, 0x0041c1cb, "AvailableProjects" },
    { 0, 0, STEP_MEMBERS,  VER_MIN_ANY, VER_MAX_ANY, false, 0, 0, "STEP_MEMBERS" },
    { 0, 0, STEP_MEDIA,    VER_MIN_ANY, VER_MAX_ANY, false, 0, 0, "STEP_MEDIA" },
    { 0, 0, STEP_TAIL,     VER_MIN_ANY, VER_MAX_ANY, true,  0, 0, "STEP_TAIL" },
};
inline constexpr int CONTAINER_STEPS = (int)(sizeof CONTAINER / sizeof *CONTAINER);

inline constexpr step PLANET[] = {
    { 0x00bb4ed0,     20400, STEP_BLOCK,      0, 255, false, 0x00447d36, 0x00448222, "expr@0x00447d36" },
    { 0x005d0194,         4, STEP_BLOCK,      0, 255, false, 0x00447d4b, 0x00448237, "_G_LLM_STRAT_ORDER_QUEUE_COUNT" },
    { 0x00b63be0,      4040, STEP_BLOCK,      0, 255, false, 0x00447d60, 0x0044824c, "_G_LLM_STRAT_CTRL_GROUPS" },
    { 0x00e5813c,         6, STEP_BLOCK,      0, 255, false, 0x00447d75, 0x00448261, "_G_LLM_STRAT_UI_SELECTED_BLDG_INDEX" },
    { 0x00e1629c,         4, STEP_BLOCK,      0, 255, false, 0x00447d8a, 0x00448276, "_G_LLM_CLICK_SELECT_TARGET_ID" },
    { 0x00e5899b,        17, STEP_BLOCK,      0, 255, false, 0x00447d9f, 0x0044828b, "_G_LLM_MOUSE_BUTTONS_PREV" },
    { 0x00bf50e0,    210000, STEP_BLOCK,      0, 255, false, 0x00447db4, 0x004482a0, "expr@0x00447db4" },
    { 0x00e1db98,    181500, STEP_BLOCK,      0, 255, false, 0x00447dc9, 0x004482b5, "_G_LLM_STRAT_PROJECTILE_POOL" },
    { 0x005d0198,         8, STEP_BLOCK,      0, 255, false, 0x00447dde, 0x004482ca, "_G_LLM_STRAT_GAME_CLOCK" },
    { 0x00e58138,         4, STEP_BLOCK,      0, 255, false, 0x00447df3, 0x004482df, "_G_LLM_MAP_CAM_COL" },
    { 0x00e58134,         4, STEP_BLOCK,      0, 255, false, 0x00447e08, 0x004482f4, "_G_LLM_MAP_CAM_ROW" },
    { 0x00825084,         4, STEP_BLOCK,      0, 255, false, 0x00447e1d, 0x00448309, "width" },
    { 0x00825064,         4, STEP_BLOCK,      0, 255, false, 0x00447e32, 0x0044831e, "height" },
    { 0x00e15408,         4, STEP_BLOCK,      0, 255, false, 0x00447e47, 0x00448333, "file_size" },
    { 0x005586ee,         4, STEP_BLOCK,      0, 255, false, 0x00447e5c, 0x00448348, "_G_LLM_STRAT_MINIMAP_ZOOM_MODE" },
    { 0x00d1ec80,    524288, STEP_BLOCK,      0, 255, false, 0x00447e71, 0x0044835d, "tile_objects" },
    { 0x00c86660,    240000, STEP_BLOCK,      0, 255, false, 0x00447e86, 0x00448372, "expr@0x00447e86" },
    { 0x00cc46e0,    240000, STEP_BLOCK,      0, 255, false, 0x00447e9b, 0x00448387, "expr@0x00447e9b" },
    { 0x00d06c80,     65536, STEP_BLOCK,      0, 255, false, 0x00447eb0, 0x0044839c, "expr@0x00447eb0" },
    { 0x00c28530,     65536, STEP_BLOCK,      0, 255, false, 0x00447ec5, 0x004483b1, "expr@0x00447ec5" },
    { 0x00dd8b88,       192, STEP_BLOCK,      0, 255, false, 0x00447eda, 0x004483c6, "expr@0x00447eda" },
    { 0x00dd8c48,    186400, STEP_BLOCK,      0, 255, false, 0x00447eef, 0x004483db, "expr@0x00447eef" },
    { 0x00c3d2a0,    218400, STEP_BLOCK,      0, 255, false, 0x00447f04, 0x004483f0, "expr@0x00447f04" },
    { 0x00e0e5a8,     23200, STEP_BLOCK,      0, 255, false, 0x00447f19, 0x00448405, "expr@0x00447f19" },
    { 0x00e0e468,       320, STEP_BLOCK,      0, 255, false, 0x00447f2e, 0x0044841a, "expr@0x00447f2e" },
    { 0x00dd2648,     25920, STEP_BLOCK,      0, 255, false, 0x00447f43, 0x0044842f, "expr@0x00447f43" },
    { 0x00d03480,     14336, STEP_BLOCK,      0, 255, false, 0x00447f58, 0x00448444, "expr@0x00447f58" },
    { 0x00c727c0,     48800, STEP_BLOCK,      0, 255, false, 0x00447f6d, 0x00448459, "expr@0x00447f6d" },
    { 0x00cc0fe0,     14080, STEP_BLOCK,      0, 255, false, 0x00447f82, 0x0044846e, "expr@0x00447f82" },
    { 0x00d02d80,      1600, STEP_BLOCK,      0, 255, false, 0x00447f97, 0x00448483, "expr@0x00447f97" },
    { 0x00bf4fc0,       192, STEP_BLOCK,      0, 255, false, 0x00447fac, 0x00448498, "expr@0x00447fac" },
    { 0x00c3a370,       416, STEP_BLOCK,      0, 255, false, 0x00447fc1, 0x004484ad, "expr@0x00447fc1" },
    { 0x00bf4d00,       704, STEP_BLOCK,      0, 255, false, 0x00447fd6, 0x004484c2, "expr@0x00447fd6" },
    { 0x00c38530,       512, STEP_BLOCK,      0, 255, false, 0x00447feb, 0x004484d7, "expr@0x00447feb" },
    { 0x00aee8c0,    480000, STEP_BLOCK,      0, 255, false, 0x00448000, 0x004484ec, "expr@0x00448000" },
    { 0x00b74bb0,       800, STEP_BLOCK,      0, 255, false, 0x00448015, 0x00448501, "_G_LLM_STRAT_PATH_SLOT_FLAGS" },
    { 0x00b63bc0,        32, STEP_BLOCK,      0, 255, false, 0x0044802a, 0x00448516, "expr@0x0044802a" },
    { 0x00b64bb0,     65536, STEP_BLOCK,      0, 255, false, 0x0044803f, 0x0044852b, "expr@0x0044803f" },
    { 0, 0, STEP_REGIONS,  VER_MIN_ANY, VER_MAX_ANY, false, 0, 0, "STEP_REGIONS" },
    { 0x00794fa0,    589824, STEP_BLOCK,      0, 255, false, 0x0044805c, 0x0044855f, "fog_of_war" },
    { 0x00825008,         4, STEP_BLOCK,      0, 255, false, 0x00448071, 0x00448574, "is_human" },
    { 0x00825000,         4, STEP_BLOCK,      0, 255, false, 0x00448086, 0x00448589, "_G_LLM_STRAT_SAVE_MISC_DWORD" },
    { 0, 0, STEP_PROGRESS, VER_MIN_ANY, VER_MAX_ANY, false, 0, 0, "STEP_PROGRESS" },
    { 0x006616a8,         4, STEP_BLOCK,      0, 255, false, 0x004dda81, 0x004ddac0, "_G_LLM_STRAT_AI_ACTIVE_PLAYER_COUNT" },
    { 0x00e6ded0,   1329120, STEP_BLOCK,      0, 255, false, 0x004dda92, 0x004ddad1, "expr@0x004dda92" },
    { 0x0050aa37,      1600, STEP_BLOCK,      0, 255, false, 0x0041c215, 0x0041c279, "AvailableBuildings" },
    { 0x0050be03,        64, STEP_BLOCK,      0, 255, false, 0x0041c22a, 0x0041c28e, "_G_LLM_STRAT_UI_BASE_MARKER_COORDS" },
};
inline constexpr int PLANET_STEPS = (int)(sizeof PLANET / sizeof *PLANET);

inline constexpr step REGIONS[] = {
    { 0x0051de84,         4, STEP_BLOCK,      0, 255, false, 0x0042479b, 0x00424ad5, "counter" },
    { 0x00708acc,         4, STEP_BLOCK,      0, 255, false, 0x004247ad, 0x00424ae7, "_G_LLM_MAP_REGION_MERGE_THRESHOLD" },
    { 0x00708b1c,         4, STEP_BLOCK,      0, 255, false, 0x004247bf, 0x00424af9, "count" },
    { 0x00708b18,         4, STEP_BLOCK,      0, 255, false, 0x004247d1, 0x00424b0b, "G_LAST_MAP_INDEX" },
};
inline constexpr int REGIONS_STEPS = (int)(sizeof REGIONS / sizeof *REGIONS);


// ---- SB-HOSTFREE: the block DECOMPOSITION ----------------------------------------------------
//
// Ten save blocks run past the symbol they start at. In the in-process configuration that costs
// nothing -- every region is at its .bss address, so one `translate()` covers the whole window.
// Under a RELOCATING host it is silently wrong: `covering()` resolves a block against `reach`, and
// `reach` was widened so exactly these blocks would resolve (D6.5), so a block spanning four
// regions still gets ONE valid pointer -- to the region it STARTED in -- and reads the rest out of
// the copy that region abandoned. Nothing fails. The save is simply wrong, in bytes only the save
// format ever reads, which is why no determinism run can see it -- the fault class an oracle is
// STRUCTURALLY blind to: corrupt saves from a relocation, with every step green.
//
// A block is therefore decomposed into the runs a single region OWNS -- by its MEASURED size, never
// by `reach`, which is the number that caused this -- plus GAP runs no region describes. A region
// run follows its region through live_base(); a gap run stays at its stock address, which is
// correct because nothing relocates memory that no region claims.
//
// ONLY BLOCKS WITH TWO OR MORE REGION RUNS ARE HERE. One region run plus a trailing gap already
// resolves correctly: the gap lies inside the host's `reach`, and the host bind copies `reach`
// bytes, so the gap travels with it. Emitting those as well would buy a 1.3 MB staging buffer
// (player_data's block) and change nothing.
struct block_slice {
    uint16_t rid;   // mh::state::region_id, or SLICE_GAP
    uint32_t off;   // offset within that region; unused for a gap
    uint32_t stock; // this run's stock address -- where a GAP is served from
    uint32_t len;
};
inline constexpr uint16_t SLICE_GAP = 0xffffu;

struct sliced_block {
    uint32_t    addr;
    uint32_t    size;
    uint16_t    first; // index into BLOCK_SLICES
    uint16_t    count;
    const char *name;
};

inline constexpr block_slice BLOCK_SLICES[] = {
    { (uint16_t)mh::state::RID_UPGRADES,                  0, 0x00bcf8d0u,    10296 },
    { SLICE_GAP,                                          0, 0x00bd2108u,       84 },
    { (uint16_t)mh::state::RID_PROD_SHUTTLE_SLOTS,        0, 0x00bd215cu,       20 },
    { (uint16_t)mh::state::RID_GAME_SESSION_MODE,         0, 0x00e58344u,        4 },
    { (uint16_t)mh::state::RID_DEBUG_TAP_FLAG,            0, 0x00e58348u,        4 },
    { (uint16_t)mh::state::RID_GAME_TUTORIAL_STEP,        0, 0x00e5834cu,        4 },
    { (uint16_t)mh::state::RID_STRAT_AI_FOREIGN_BLDG_CHANGE_FLAG,        0, 0x00e58350u,        4 },
    { (uint16_t)mh::state::RID_PLAYERSIDE,                0, 0x00e58354u,        2 },
    { (uint16_t)mh::state::RID_STRAT_DEBUG_RESOURCE_YIELD_CUT,        0, 0x00e58356u,        8 },
    { (uint16_t)mh::state::RID_STRAT_LOCAL_PLAYER_SLOT,        0, 0x00e5835eu,        2 },
    { (uint16_t)mh::state::RID_STRAT_PROD_COMPLETE_THROTTLE,        0, 0x00e58360u,        1 },
    { (uint16_t)mh::state::RID_STRAT_PLAYER_RACE,         0, 0x00e58361u,        4 },
    { (uint16_t)mh::state::RID_STRAT_UI_BLDG_TAB_SELECT_BLOCKED,        0, 0x00e58365u,        1 },
    { (uint16_t)mh::state::RID_G_PLANET_INDEX,            0, 0x00e58366u,        4 },
    { (uint16_t)mh::state::RID_STRAT_PLANET_TRANSITION_STATE,        0, 0x00e5836au,        1 },
    { (uint16_t)mh::state::RID_G_PLANET_STATUS,           0, 0x00e5836bu,      128 },
    { (uint16_t)mh::state::RID_STRAT_FLOATING_MSG_SUPPRESS_FLAG,        0, 0x00e583ebu,        1 },
    { SLICE_GAP,                                          0, 0x00e583ecu,        3 },
    { (uint16_t)mh::state::RID_PLANET_TIME,               0, 0x00e583efu,      256 },
    { (uint16_t)mh::state::RID_STRAT_LOCKSTEP_STEP_MULT,        0, 0x00e584efu,        1 },
    { (uint16_t)mh::state::RID_STRAT_OUTER_PLANET_LAND_STATE,        0, 0x00e584f0u,        4 },
    { (uint16_t)mh::state::RID_STRAT_PLANET_MOTHER_LOST_TIME,        0, 0x00e584f4u,      256 },
    { (uint16_t)mh::state::RID_CHEAT_PENALTY_SCORE,        0, 0x00e585f4u,        4 },
    { (uint16_t)mh::state::RID_STRAT_INVASION_TIME,        0, 0x00e585f8u,      256 },
    { (uint16_t)mh::state::RID_STRAT_OUTER_PLANET_LANDED_FLAG,        0, 0x00e586f8u,        4 },
    { (uint16_t)mh::state::RID_STRAT_PLANET_INT_TABLE,        0, 0x00e586fcu,      128 },
    { (uint16_t)mh::state::RID_STRAT_BLDG_COMPLETION_SLOT_COUNT,        0, 0x00e5877cu,        1 },
    { (uint16_t)mh::state::RID_STRAT_BLDG_COMPLETION_ACCUM,        0, 0x00e5877du,        4 },
    { (uint16_t)mh::state::RID_CURRENTSYSTEM,             0, 0x00e58781u,        4 },
    { SLICE_GAP,                                          0, 0x00e58785u,        4 },
    { (uint16_t)mh::state::RID_NET_LOCKSTEP_SYNC_RETRY_COUNTDOWN,        0, 0x00e58789u,        4 },
    { (uint16_t)mh::state::RID_NET_LOCKSTEP_STALL_NAG_COUNT,        0, 0x00e5878du,        4 },
    { (uint16_t)mh::state::RID_NET_LOCKSTEP_RESYNC_TRIGGER_COUNT,        0, 0x00e58791u,        4 },
    { (uint16_t)mh::state::RID_STRAT_LOCKSTEP_STALL_COUNT,        0, 0x00e58795u,        4 },
    { (uint16_t)mh::state::RID_NET_LOCKSTEP_SYNC_WAIT_ELAPSED,        0, 0x00e58799u,        8 },
    { (uint16_t)mh::state::RID_NET_LOCKSTEP_PEER_TIMEOUT_ELAPSED,        0, 0x00e587a1u,        8 },
    { (uint16_t)mh::state::RID_NET_SYNC_WAIT_ACTIVE,        0, 0x00e587a9u,        4 },
    { (uint16_t)mh::state::RID_NET_RESYNC_IN_PROGRESS,        0, 0x00e587adu,        4 },
    { (uint16_t)mh::state::RID_CURRENT_GAME_TIME,         0, 0x00e587b1u,        8 },
    { (uint16_t)mh::state::RID_LAST_GAME_TIME,            0, 0x00e587b9u,        8 },
    { (uint16_t)mh::state::RID_TOTAL_GAME_TIME,           0, 0x00e587c1u,        8 },
    { (uint16_t)mh::state::RID_STRAT_SIM_STEP_INTERVAL,        0, 0x00e587c9u,        8 },
    { (uint16_t)mh::state::RID_GAME_TIME_DELTA,           0, 0x00e587d1u,        8 },
    { (uint16_t)mh::state::RID_GAME_SPEED,                0, 0x00e587d9u,        8 },
    { (uint16_t)mh::state::RID_STRAT_CAM_PAN_TARGET_COL,        0, 0x00e587e1u,        4 },
    { (uint16_t)mh::state::RID_STRAT_CAM_PAN_TARGET_ROW,        0, 0x00e587e5u,        4 },
    { (uint16_t)mh::state::RID_PLAYERS,                   0, 0x00e587e9u,      416 },
    { (uint16_t)mh::state::RID_STRAT_INJECTED_MAP_PLANET_SLOT,        0, 0x00e58989u,        1 },
    { (uint16_t)mh::state::RID_STRAT_RNG_SEED_BYTE,        0, 0x00e5898au,        1 },
    { (uint16_t)mh::state::RID_CHAT_TARGET_MASK,          0, 0x00e5898bu,        1 },
    { (uint16_t)mh::state::RID_GAME_HUMAN_PLAYER_MASK,        0, 0x00e5898cu,        1 },
    { (uint16_t)mh::state::RID_PLAYER_CONTROL_MASK,        0, 0x00e5898du,        1 },
    { SLICE_GAP,                                          0, 0x00e5898eu,        1 },
    { (uint16_t)mh::state::RID_STRAT_SHOW_UNIT_FLAGS,        0, 0x00e5898fu,        4 },
    { (uint16_t)mh::state::RID_STRAT_MP_ALLY_VICTORY_RULE_FLAG,        0, 0x00e58993u,        4 },
    { (uint16_t)mh::state::RID_STRAT_SYSTEM_LOST_MSG_SHOWN_FLAG,        0, 0x00e58997u,        4 },
    { (uint16_t)mh::state::RID_MESSAGE_TIME,              0, 0x00ae4b90u,        8 },
    { SLICE_GAP,                                          0, 0x00ae4b98u,      216 },
    { (uint16_t)mh::state::RID_ANIM,                      0, 0x00ae4c70u,       16 },
    { (uint16_t)mh::state::RID_CLICK_SELECT_TARGET_ID,        0, 0x00e1629cu,        2 },
    { (uint16_t)mh::state::RID_CLICK_SELECT_TARGET_FLAGS,        0, 0x00e1629eu,        2 },
};
inline constexpr int BLOCK_SLICE_COUNT = (int)(sizeof BLOCK_SLICES / sizeof *BLOCK_SLICES);

inline constexpr sliced_block SLICED_BLOCKS[] = {
    { 0x00bcf8d0u,    10400,    0,   3, "Upgrades" },
    { 0x00e58344u,     1623,    3,  53, "_G_LLM_GAME_SESSION_MODE" },
    { 0x00ae4b90u,      240,   56,   3, "MESSAGE_TIME" },
    { 0x00e1629cu,        4,   59,   2, "_G_LLM_CLICK_SELECT_TARGET_ID" },
};
inline constexpr int SLICED_BLOCK_COUNT = (int)(sizeof SLICED_BLOCKS / sizeof *SLICED_BLOCKS);

// The staging buffer a sliced block is gathered into / scattered out of. Derived from the
// table above, so it cannot be outgrown silently.
inline constexpr uint32_t MAX_SLICED_BLOCK = 10400u;


// ---- LIB-REF-SPLIT: every block's owning region, resolved at GENERATION -----------------------
//
// The driver needs two things from a block's address that only the registry can answer: is this
// block covered by a state region at all (the registration check), and which region + offset is it
// (the owned-block delegation). Hosted, mh::state::covering() answers both at compile time from the
// stock base column. The STANDALONE build does not carry that column -- there is no image, so an
// original .bss address is not a thing it can resolve -- and covering() is not declared there.
//
// So the answer is precomputed here, from the same decompose() that produces BLOCK_SLICES and the
// same tools/data/state_regions.json the registry is generated from. It is not a second derivation:
// it is the SAME derivation, read at generation time instead of at compile time.
//
// THE FILE FORMAT IS UNTOUCHED BY THIS, and that is the load-bearing property. `addr` remains the
// step's key and its stock value; nothing here is written to or read from a save. This table only
// answers "where do those bytes live now", which is a question about memory, never about the file.
struct block_owner {
    uint32_t addr; // the step's stock address -- the key, unchanged
    uint32_t size;
    uint16_t rid;  // mh::state::region_id, or RID_COUNT when no region covers the block
    uint32_t off;  // offset of `addr` within that region
};

inline constexpr block_owner BLOCK_OWNERS[] = {
    { 0x00e4a098u,    57500, (uint16_t)mh::state::RID_UNIT,                      0 },
    { 0x00d9ec80u,   211400, (uint16_t)mh::state::RID_BUILDING,                  0 },
    { 0x00c3a520u,    11648, (uint16_t)mh::state::RID_WEAPON,                    0 },
    { 0x00000000u,    30900, (uint16_t)mh::state::RID_COUNT,                     0 },
    { 0x00be1a30u,      560, (uint16_t)mh::state::RID_SYSTEM,                    0 },
    { 0x00be6da0u,    34016, (uint16_t)mh::state::RID_PLANETS,                   0 },
    { 0x00be1c60u,    20800, (uint16_t)mh::state::RID_PROJECTS,                  0 },
    { 0x00bcf8d0u,    10400, (uint16_t)mh::state::RID_UPGRADES,                  0 },
    { 0x00cff060u,    14848, (uint16_t)mh::state::RID_STRAT_PLAYERS,             0 },
    { 0x00c38730u,       16, (uint16_t)mh::state::RID_BLDG_PIP_ANIM_BASE_FRAME,        0 },
    { 0x00bd2170u,    63680, (uint16_t)mh::state::RID_PROD_SHUTTLE_SLOTS,       20 },
    { 0x00c38750u,     7200, (uint16_t)mh::state::RID_PROGRESS,                  0 },
    { 0x00e58344u,     1623, (uint16_t)mh::state::RID_GAME_SESSION_MODE,         0 },
    { 0x00000000u,     3600, (uint16_t)mh::state::RID_COUNT,                     0 },
    { 0x005ce484u,     7200, (uint16_t)mh::state::RID_MESSAGE_QUEUE,             0 },
    { 0x00ae4b90u,      240, (uint16_t)mh::state::RID_MESSAGE_TIME,              0 },
    { 0x00e162a0u,       60, (uint16_t)mh::state::RID_STRAT_FLOATING_MSG_COLOR,        0 },
    { 0x00ae2b00u,        8, (uint16_t)mh::state::RID_ANIM_PLACE_DENIED,         0 },
    { 0x00bca820u,      256, (uint16_t)mh::state::RID_STRAT_INVASION_ALERT_TIME,        0 },
    { 0x00b64ba8u,        8, (uint16_t)mh::state::RID_STRAT_ADVISOR_NEXT_TIME,        0 },
    { 0x0050b077u,     3200, (uint16_t)mh::state::RID_AVAILABLEPROJECTS,         0 },
    { 0x00bb4ed0u,    20400, (uint16_t)mh::state::RID_STRAT_ORDER_QUEUE,         0 },
    { 0x005d0194u,        4, (uint16_t)mh::state::RID_STRAT_ORDER_QUEUE_COUNT,        0 },
    { 0x00b63be0u,     4040, (uint16_t)mh::state::RID_STRAT_CTRL_GROUPS,         0 },
    { 0x00e5813cu,        6, (uint16_t)mh::state::RID_STRAT_UI_SELECTED_BLDG_INDEX,        0 },
    { 0x00e1629cu,        4, (uint16_t)mh::state::RID_CLICK_SELECT_TARGET_ID,        0 },
    { 0x00e5899bu,       17, (uint16_t)mh::state::RID_MOUSE_BUTTONS_PREV,        0 },
    { 0x00bf50e0u,   210000, (uint16_t)mh::state::RID_STRAT_FX_ANIMS,            0 },
    { 0x00e1db98u,   181500, (uint16_t)mh::state::RID_STRAT_PROJECTILE_POOL,        0 },
    { 0x005d0198u,        8, (uint16_t)mh::state::RID_STRAT_GAME_CLOCK,          0 },
    { 0x00e58138u,        4, (uint16_t)mh::state::RID_MAP_CAM_COL,               0 },
    { 0x00e58134u,        4, (uint16_t)mh::state::RID_MAP_CAM_ROW,               0 },
    { 0x00825084u,        4, (uint16_t)mh::state::RID_WIDTH,                     0 },
    { 0x00825064u,        4, (uint16_t)mh::state::RID_HEIGHT,                    0 },
    { 0x00e15408u,        4, (uint16_t)mh::state::RID_FILE_SIZE,                 0 },
    { 0x005586eeu,        4, (uint16_t)mh::state::RID_STRAT_MINIMAP_ZOOM_MODE,        0 },
    { 0x00d1ec80u,   524288, (uint16_t)mh::state::RID_TILE_OBJECTS,              0 },
    { 0x00c86660u,   240000, (uint16_t)mh::state::RID_MAP_OBJECTS,               0 },
    { 0x00cc46e0u,   240000, (uint16_t)mh::state::RID_MAP_OBJECT_TABLE,          0 },
    { 0x00d06c80u,    65536, (uint16_t)mh::state::RID_MAP_HALFRES_GRID,          0 },
    { 0x00c28530u,    65536, (uint16_t)mh::state::RID_RESOURCES,                 0 },
    { 0x00dd8b88u,      192, (uint16_t)mh::state::RID_STRAT_LANDING_SPOTS,        0 },
    { 0x00dd8c48u,   186400, (uint16_t)mh::state::RID_UNITS,                     0 },
    { 0x00c3d2a0u,   218400, (uint16_t)mh::state::RID_BUILDINGS,                 0 },
    { 0x00e0e5a8u,    23200, (uint16_t)mh::state::RID_STRAT_SOLDIERS,            0 },
    { 0x00e0e468u,      320, (uint16_t)mh::state::RID_PLAYER_RESOURCES,          0 },
    { 0x00dd2648u,    25920, (uint16_t)mh::state::RID_PRODUCTIONS,               0 },
    { 0x00d03480u,    14336, (uint16_t)mh::state::RID_MINES,                     0 },
    { 0x00c727c0u,    48800, (uint16_t)mh::state::RID_UNIT_STORAGE,              0 },
    { 0x00cc0fe0u,    14080, (uint16_t)mh::state::RID_TURRETS,                   0 },
    { 0x00d02d80u,     1600, (uint16_t)mh::state::RID_LABS,                      0 },
    { 0x00bf4fc0u,      192, (uint16_t)mh::state::RID_STRAT_POWER_STATS,         0 },
    { 0x00c3a370u,      416, (uint16_t)mh::state::RID_STRAT_POP_STATS,           0 },
    { 0x00bf4d00u,      704, (uint16_t)mh::state::RID_STRAT_STORAGE_STATS,        0 },
    { 0x00c38530u,      512, (uint16_t)mh::state::RID_STRAT_UNIT_HOUSING_STATS,        0 },
    { 0x00aee8c0u,   480000, (uint16_t)mh::state::RID_STRAT_PATH_BUFFERS,        0 },
    { 0x00b74bb0u,      800, (uint16_t)mh::state::RID_STRAT_PATH_SLOT_FLAGS,        0 },
    { 0x00b63bc0u,       32, (uint16_t)mh::state::RID_STRAT_PATH_FREE_SLOT_COUNT,        0 },
    { 0x00b64bb0u,    65536, (uint16_t)mh::state::RID_PASSABLE,                  0 },
    { 0x00794fa0u,   589824, (uint16_t)mh::state::RID_FOG_OF_WAR,                0 },
    { 0x00825008u,        4, (uint16_t)mh::state::RID_IS_HUMAN,                  0 },
    { 0x00825000u,        4, (uint16_t)mh::state::RID_STRAT_SAVE_MISC_DWORD,        0 },
    { 0x006616a8u,        4, (uint16_t)mh::state::RID_STRAT_AI_ACTIVE_PLAYER_COUNT,        0 },
    { 0x00e6ded0u,  1329120, (uint16_t)mh::state::RID_PLAYER_DATA,              16 },
    { 0x0050aa37u,     1600, (uint16_t)mh::state::RID_AVAILABLEBUILDINGS,        0 },
    { 0x0050be03u,       64, (uint16_t)mh::state::RID_STRAT_UI_BASE_MARKER_COORDS,        0 },
    { 0x0051de84u,        4, (uint16_t)mh::state::RID_COUNTER,                   0 },
    { 0x00708accu,        4, (uint16_t)mh::state::RID_MAP_REGION_MERGE_THRESHOLD,        0 },
    { 0x00708b1cu,        4, (uint16_t)mh::state::RID_MAP_REGION_COORD_WRAP_MASK,        0 },
    { 0x00708b18u,        4, (uint16_t)mh::state::RID_G_LAST_MAP_INDEX,          0 },
};
inline constexpr int BLOCK_OWNER_COUNT = (int)(sizeof BLOCK_OWNERS / sizeof *BLOCK_OWNERS);

// The owning region of the block at [addr, addr+size), or RID_COUNT. constexpr, so the standalone
// registration check below is a compile-time assert exactly as the hosted covering() one is --
// neither configuration gets a weaker check than the other, only a different route to it.
constexpr int block_owner_index(uint32_t addr, uint32_t size) {
    for (int i = 0; i < BLOCK_OWNER_COUNT; ++i)
        if (BLOCK_OWNERS[i].addr == addr && BLOCK_OWNERS[i].size == size) return i;
    return -1;
}

// Each block's runs really do TILE it -- first run starts at the block, last run ends at
// its end -- so a decomposition that lost or doubled a byte is a compile error rather than
// a save written from the wrong memory.
static_assert(BLOCK_SLICES[0].stock == 0x00bcf8d0u);
static_assert(BLOCK_SLICES[2].stock + BLOCK_SLICES[2].len == 0x00bd2170u);
static_assert(BLOCK_SLICES[3].stock == 0x00e58344u);
static_assert(BLOCK_SLICES[55].stock + BLOCK_SLICES[55].len == 0x00e5899bu);
static_assert(BLOCK_SLICES[56].stock == 0x00ae4b90u);
static_assert(BLOCK_SLICES[58].stock + BLOCK_SLICES[58].len == 0x00ae4c80u);
static_assert(BLOCK_SLICES[59].stock == 0x00e1629cu);
static_assert(BLOCK_SLICES[60].stock + BLOCK_SLICES[60].len == 0x00e162a0u);

} // namespace mh::save::table
