// GENERATED by tools/gen_libmh_hostapi.py -- DO NOT EDIT; regenerate instead.
// The mh.dll THIN IMPLEMENTATION of the host-callback ABI (LIB-ABI stage B),
// BOTH tables (LIB-IFACE-SPLIT): every entry forwards to its mh::call:: thunk, so
// the hosted configuration executes the ORIGINAL bodies bit-exactly through the
// tables. An entry in both tables shares one forwarder -- in this host the sim and
// tact bindings of a shared entry are the same code on purpose; a standalone host
// may bind them differently. HARNESS-side TU (mh.vcxproj only) -- it names fixed
// VAs via mh::call and can never join libmh.
#include "../../libmh/include/libmh_host_api.gen.h"
#include "../../libmh/include/libmh_tact_host_api.gen.h"
#include "addr/mh_calls.gen.h"
#include "include/mh_hostapi_bind.h"

namespace {
void f_apply_frame_input() { mh::call::llm_strat_input_update(); }
uint32_t f_cfg_ReadMapFile(void *a0) { return mh::call::cfg_ReadMapFile((mh::game::mh_cfg_struct_map_header *)a0); }
void f_map_ReadMap_pre(uint32_t a0) { mh::call::map_ReadMap_pre(a0); }
void f_map_load_regions(int32_t a0) { mh::call::llm_map_load_regions(a0); }
void f_map_save_regions(int32_t a0) { mh::call::llm_map_save_regions(a0); }
int32_t f_planet_tlo_load(uint32_t a0) { return mh::call::llm_planet_tlo_load(a0); }
void f_save_player_data(void *a0) { mh::call::llm_game_save_player_data(a0); }
int32_t f_transport_recv(int32_t *a0, void *a1, int32_t *a2) { return mh::call::llm_net_transport_recv(a0, a1, a2); }
void f_transport_send(void *a0, int32_t a1) { mh::call::llm_net_transport_send(a0, a1); }
void *f_ansi_to_wide(void *a0, char *a1) { return mh::call::llm_str_ansi_to_wide(a0, a1); }
void *f_ansi_to_wide_scratch(char *a0) { return mh::call::llm_str_ansi_to_wide_scratch(a0); }
char *f_wide_to_local(void *a0, char *a1) { return mh::call::utils_wide_to_short_str(a0, a1); }
uint32_t f_wide_to_local_bytes(void *a0) { return mh::call::getAsciiVer(a0); }
uint32_t f_ticks_ms() { return mh::call::llm_time_get_ticks_ms(); }
void f_fatal(int32_t a0) { mh::call::utils_abort(a0); }
void *f_media_diag_block() { return mh::call::llm_build_media_diag_report(); }
void f_llm_gfx_convert_pixels_565_to_555(int16_t *a0) { mh::call::llm_gfx_convert_pixels_565_to_555(a0); }
void f_llm_tlo_palette_convert_565_to_555() { mh::call::llm_tlo_palette_convert_565_to_555(); }
void f_llm_tlo_shade_table_build_tact() { mh::call::llm_tlo_shade_table_build_tact(); }
void f_llm_snd_play_matching_sample(uint32_t a0, void *a1, int32_t a2, int32_t a3, int32_t a4) { mh::call::llm_snd_play_matching_sample(a0, (mh::game::mh_llm_snd_cfg_entry *)a1, a2, a3, a4); }
void f_llm_gfx_apply_resolution_change() { mh::call::llm_gfx_apply_resolution_change(); }
void f_llm_gfx_apply_window_resolution(int32_t a0, int32_t a1) { mh::call::llm_gfx_apply_window_resolution(a0, a1); }
void f_llm_tact_render_view() { mh::call::llm_tact_render_view(); }
int32_t f_llm_view_set_size_mode(int32_t a0) { return mh::call::llm_view_set_size_mode(a0); }
void f_llm_input_key_dequeue(uint32_t a0) { mh::call::llm_input_key_dequeue(a0); }
int32_t f_llm_input_key_queue_empty() { return mh::call::llm_input_key_queue_empty(); }
int32_t f_llm_input_mouse_buttons_get() { return mh::call::llm_input_mouse_buttons_get(); }
void f_llm_input_mouse_delta_pump() { mh::call::llm_input_mouse_delta_pump(); }
uint8_t *f_GetResourseFilePtr(char *a0) { return mh::call::GetResourseFilePtr(a0); }
uint32_t f_rsr_GetFileRealSize(char *a0) { return mh::call::rsr_GetFileRealSize(a0); }
void f_llm_fatal_cleanup() { mh::call::llm_fatal_cleanup(); }
void f_utils_abort(int32_t a0) { mh::call::utils_abort(a0); }
}  // namespace

namespace mh::hostapi {

const libmh_host_api &mhdll_table() {
    static const libmh_host_api t = {
        f_apply_frame_input,
        mh::hostapi::io::asset_read,
        mh::hostapi::io::asset_size,
        mh::hostapi::io::vfs_close,
        mh::hostapi::io::vfs_open,
        mh::hostapi::io::vfs_read,
        mh::hostapi::io::vfs_seek,
        mh::hostapi::io::vfs_tell,
        mh::hostapi::io::vfs_write,
        f_cfg_ReadMapFile,
        f_map_ReadMap_pre,
        f_map_load_regions,
        f_map_save_regions,
        f_planet_tlo_load,
        f_save_player_data,
        f_transport_recv,
        f_transport_send,
        f_ansi_to_wide,
        f_ansi_to_wide_scratch,
        f_wide_to_local,
        f_wide_to_local_bytes,
        f_ticks_ms,
        f_fatal,
        f_media_diag_block,
    };
    return t;
}

const libmh_tact_host_api &mhdll_tact_table() {
    static const libmh_tact_host_api t = {
        f_llm_gfx_convert_pixels_565_to_555,
        f_llm_tlo_palette_convert_565_to_555,
        f_llm_tlo_shade_table_build_tact,
        f_llm_snd_play_matching_sample,
        f_llm_gfx_apply_resolution_change,
        f_llm_gfx_apply_window_resolution,
        f_llm_tact_render_view,
        f_llm_view_set_size_mode,
        f_llm_input_key_dequeue,
        f_llm_input_key_queue_empty,
        f_llm_input_mouse_buttons_get,
        f_llm_input_mouse_delta_pump,
        f_GetResourseFilePtr,
        f_rsr_GetFileRealSize,
        f_llm_fatal_cleanup,
        f_utils_abort,
    };
    return t;
}

}  // namespace mh::hostapi
