// mh_strided_regions.gen.h -- GENERATED by tools/lint_strided_regions.py. DO NOT EDIT.
//
// A region indexed [row * STRIDE + i] must be longer than ONE row. The registry measures reach in
// BYTES and the source strides in ELEMENTS, so only the compiler can compare them -- which is why
// these are static_asserts and not a Python check.
//
// The bug that earned this file is _G_LLM_STRAT_MOVE_MICROSTEPS: claimed 96 bytes (one row of 32
// 3-byte entries) while the sim indexes row `move_heading % 24`. Inside mh.exe the over-index lands
// in the game's own .bss where the other 23 rows really are, so every read was correct and no hash,
// shadow site or A/B could see anything wrong. The standalone host binds each region into its own
// allocation, so the same read took the NEXT region's bytes and LIB-REF's replay diverged at step 3
// in two bytes. A caution note about the short Ghidra type had existed for five weeks; a comment is
// not a gate.
//
// Included at the end of the state binder that names these members, and OPENED IN THAT MODULE'S
// NAMESPACE: the stride constants (MICROSTEPS_PER_HEADING, UNITS_PER_PLAYER, ...) and the element
// types are declared in mh::sim, so an assertion emitted anywhere else cannot name either of them.
#pragma once

namespace mh::sim {

// NOT ASSERTED -- the stride constant or the element type is not nameable in
// sim_state.h, so it is not in scope where these assertions land. LISTED rather
// than dropped, so the population is always visible: hoisting the constant or
// the type into sim_state.h is what makes one of these assertable.
//   _G_LLM_PROD_SHUTTLE_SLOTS                  stride       out of scope: SHUTTLES_PER_PLAYER / const prod_shuttle_slot src/mh_dll/libmh/sim/sim_player_presence_lost.cpp:150
//   _G_LLM_STRAT_DEPLOY_FORMATION_STENCIL      UNMEASURED   out of scope: 7 / const uint8_t            src/mh_dll/libmh/sim/libtrans/sim_lt_deploy_squad.cpp:85
//   _G_LLM_STRAT_HEADING_CANDIDATE_TABLE       stride       out of scope: GROUP_STEP_GROUND_CANDIDATE_SLOTS / const heading_slot src/mh_dll/libmh/sim/sim_unit_group_step_ground.cpp:129
//   System                                     stride       out of scope: SYSTEM_STRIDE_INTS / const int32_t src/mh_dll/libmh/sim/sim_game_notify_system_available.cpp:54

// _G_LLM_MAP_DIR_STEP_DELTAS -- map_dir_step_deltas, indexed [row * 2 + i] at src/mh_dll/libmh/sim/sim_group_move_order_pathfind.cpp:320
static_assert(::mh::state::reach_of(::mh::state::RID_MAP_DIR_STEP_DELTAS) > (2) * sizeof(const uint8_t),
              "_G_LLM_MAP_DIR_STEP_DELTAS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_MAP_REGION_ROUTE_STEP_DELTAS -- region_route_step_deltas, indexed [row * 4 + i] at src/mh_dll/libmh/sim/sim_map_region_routing.cpp:46
static_assert(::mh::state::reach_of(::mh::state::RID_MAP_REGION_ROUTE_STEP_DELTAS) > (4) * sizeof(const uint8_t),
              "_G_LLM_MAP_REGION_ROUTE_STEP_DELTAS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// player_resources -- player_resources, indexed [row * PLAYER_RESOURCE_SLOTS + i] at src/mh_dll/libmh/sim/sim_state.h:3734
static_assert(::mh::state::reach_of(::mh::state::RID_PLAYER_RESOURCES) > (PLAYER_RESOURCE_SLOTS) * sizeof(const int32_t),
              "player_resources is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_PROD_SHUTTLE_SLOTS -- prod_shuttle_slots, indexed [row * PROD_SHUTTLE_SLOTS_PER_PLAYER + i] at src/mh_dll/libmh/sim/sim_bldg_economy.cpp:42
static_assert(::mh::state::reach_of(::mh::state::RID_PROD_SHUTTLE_SLOTS) > (PROD_SHUTTLE_SLOTS_PER_PLAYER) * sizeof(const prod_shuttle_slot),
              "_G_LLM_PROD_SHUTTLE_SLOTS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// progress -- progress, indexed [row * PROGRESS_ROW_COUNT + i] at src/mh_dll/libmh/sim/sim_player_presence_lost.cpp:119
static_assert(::mh::state::reach_of(::mh::state::RID_PROGRESS) > (PROGRESS_ROW_COUNT) * sizeof(const player_progress),
              "progress is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// resources -- resources, indexed [row * 64 + i] at src/mh_dll/libmh/sim/sim_bldg_completion_dispatch.cpp:362
static_assert(::mh::state::reach_of(::mh::state::RID_RESOURCES) > (64) * sizeof(const map_resources),
              "resources is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_DEATH_ANIM_TABLE -- death_anim_table, indexed [row * 4 + i] at src/mh_dll/libmh/sim/sim_bldg_state_destroyed.cpp:106
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_DEATH_ANIM_TABLE) > (4) * sizeof(const int32_t),
              "_G_LLM_STRAT_DEATH_ANIM_TABLE is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_DIR8_STEP_OFFSETS -- dir8_step_offsets, indexed [row * 2 + i] at src/mh_dll/libmh/sim/sim_pathtrace_greedy.cpp:151
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_DIR8_STEP_OFFSETS) > (2) * sizeof(const int8_t),
              "_G_LLM_STRAT_DIR8_STEP_OFFSETS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_GROUP_MEMBER_TILE -- group_member_tile, indexed [row * 2 + i] at src/mh_dll/libmh/sim/sim_group_move_order_commit.cpp:89
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_GROUP_MEMBER_TILE) > (2) * sizeof(const uint8_t),
              "_G_LLM_STRAT_GROUP_MEMBER_TILE is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_HEADING_CANDIDATE_TABLE -- heading_candidates, indexed [row * 3 + i] at src/mh_dll/libmh/sim/sim_pathfind_grid_geometry.cpp:51
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_HEADING_CANDIDATE_TABLE) > (3) * sizeof(const heading_slot),
              "_G_LLM_STRAT_HEADING_CANDIDATE_TABLE is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_MOVE_MICROSTEPS -- move_microsteps, indexed [row * MICROSTEPS_PER_HEADING + i] at src/mh_dll/libmh/sim/sim_bldg_state_to_unit.cpp:118
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_MOVE_MICROSTEPS) > (MICROSTEPS_PER_HEADING) * sizeof(const move_microstep),
              "_G_LLM_STRAT_MOVE_MICROSTEPS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_PATH_BUFFERS -- path_buffers, indexed [row * PATH_WAYPOINTS_PER_PLAYER + i] at src/mh_dll/libmh/sim/sim_group_plan_formation_positions.cpp:186
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_PATH_BUFFERS) > (PATH_WAYPOINTS_PER_PLAYER) * sizeof(const path_waypoint),
              "_G_LLM_STRAT_PATH_BUFFERS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_PATH_BUFFERS -- path_buffers, indexed [row * PATH_WAYPOINTS_PER_SLOT + i] at src/mh_dll/libmh/sim/sim_path_step_check_and_request_detour.cpp:78
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_PATH_BUFFERS) > (PATH_WAYPOINTS_PER_SLOT) * sizeof(const path_waypoint),
              "_G_LLM_STRAT_PATH_BUFFERS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// _G_LLM_STRAT_SOLDIERS -- soldiers, indexed [row * SOLDIERS_PER_PLAYER + i] at src/mh_dll/libmh/sim/sim_unit_recruit.h:101
static_assert(::mh::state::reach_of(::mh::state::RID_STRAT_SOLDIERS) > (SOLDIERS_PER_PLAYER) * sizeof(const soldier),
              "_G_LLM_STRAT_SOLDIERS is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

// units -- units, indexed [row * UNITS_PER_PLAYER + i] at src/mh_dll/libmh/sim/sim_unit_state_flight.cpp:87
static_assert(::mh::state::reach_of(::mh::state::RID_UNITS) > (UNITS_PER_PLAYER) * sizeof(const unit),
              "units is claimed at ONE ROW or less of the stride it is indexed by: only row 0 is in the region. The stride and the index site are named in the comment above. Widen the claim -- a `size` on its view entry in tools/data/dll_addr_manifest.json is the Tree/MOVE_MICROSTEPS precedent.");

} // namespace mh::sim
