// GENERATED by tools/gen_tombstones.py -- DO NOT EDIT.
// Regenerate after a ledger adjudicates a row `dead` or after re-dumping
// tools/data/en_functions.json; `gen_tombstones.py --check` is the drift gate
// (lint_repo.py runs it).
//
// The extents of every function a migration ledger records as DEAD -- an evidenced
// nothing-reaches-it. The tombstone instrument (hook/tombstone.cpp) fills these bodies with
// traps when [tombstone] arm_dead=1, so a wrong `dead` claim fires by name instead of
// staying an unread line in a ledger. Promoted bodies are NOT listed here: they are
// enumerated at runtime from the note_promoted registry against promotable_ranges.
#pragma once
#include <cstdint>

#include "hook/promoted.h"

namespace mh::addr {

// Entry..end INCLUSIVE, EN build (/eng/mh.exe), image base 0x00400000, no ASLR.
inline constexpr mh::hook::owner_range tombstone_dead_ranges[] = {
    {"llm_tact_ui_char_panel_row_draw",                              0x00434322u, 0x0043468cu}, // tact
    {"llm_tact_ui_sidebar_row_draw_right",                           0x004348bfu, 0x00434af6u}, // tact
    {"llm_strat_unit_path_encode_directions",                        0x0044955fu, 0x004495f8u}, // sim_resid
    {"llm_strat_ai_ctrl_group_member_scan_dead",                     0x0044ac4bu, 0x0044ac94u}, // ai
    {"llm_strat_unit_order_dispatch_default",                        0x00469de6u, 0x00469e71u}, // orders_issue
    {"llm_strat_unit_reset_order_and_target",                        0x00469efeu, 0x00469fe5u}, // orders_issue
    {"llm_strat_order_issue_0xf_adjacent",                           0x0046a221u, 0x0046a324u}, // orders_issue
    {"llm_strat_unit_order_move_default_enqueue",                    0x0046a4cbu, 0x0046a56cu}, // orders_issue
    {"llm_strat_unit_order_attack_target_preset_weapon_enqueue",     0x0046bde6u, 0x0046bf9bu}, // orders_issue
    {"llm_strat_unit_order_attack_building_reposition_enqueue",      0x0046c471u, 0x0046c6c5u}, // orders_issue
    {"llm_strat_unit_order_attack_building",                         0x0046c6c6u, 0x0046c79fu}, // orders_issue
    {"llm_strat_unit_order_move_relative_enqueue",                   0x0046c99du, 0x0046ca98u}, // orders_issue
    {"llm_strat_order_recruit_unit",                                 0x0046d952u, 0x0046d9a8u}, // orders_issue
    {"llm_strat_bldg_order_production_add_count",                    0x0046dbd0u, 0x0046dc46u}, // orders_issue
    {"llm_strat_bldg_order_production_add_count_enqueue",            0x0046dc47u, 0x0046dcbdu}, // orders_issue
    {"llm_strat_bldg_order_production_remove_enqueue",               0x0046dd27u, 0x0046dd8fu}, // orders_issue
    {"llm_strat_turret_order_target_unit_enqueue",                   0x0046ddf0u, 0x0046de4fu}, // orders_issue
    {"llm_strat_turret_order_target_building_enqueue",               0x0046deb0u, 0x0046df0fu}, // orders_issue
    {"llm_strat_bldg_order_set_worker_count",                        0x0046df10u, 0x0046df62u}, // orders_issue
    {"llm_strat_bldg_order_set_worker_count_enqueue",                0x0046df63u, 0x0046dfb5u}, // orders_issue
    {"llm_strat_bldg_order_toggle_active_enqueue",                   0x0046e252u, 0x0046e2adu}, // orders_issue
    {"llm_strat_bldg_order_hangar_recharge_enqueue",                 0x0046e523u, 0x0046e563u}, // orders_issue
    {"llm_strat_bldg_order_cancel_reset",                            0x0046e564u, 0x0046e5a4u}, // orders_issue
    {"llm_strat_bldg_order_cancel_reset_enqueue",                    0x0046e5a5u, 0x0046e5e5u}, // orders_issue
    {"llm_strat_bldg_order_mine_rescan",                             0x0046e668u, 0x0046e6a8u}, // orders_issue
    {"llm_strat_bldg_order_mine_rescan_enqueue",                     0x0046e6a9u, 0x0046e6e9u}, // orders_issue
    {"llm_strat_bldg_order_purge_dead_docked_enqueue",               0x0046e72bu, 0x0046e76bu}, // orders_issue
    {"llm_strat_order_issue_0xd5",                                   0x0046e8deu, 0x0046e93au}, // orders_issue
    {"llm_strat_order_issue_0xd5_enqueue",                           0x0046e93bu, 0x0046e997u}, // orders_issue
    {"llm_strat_bldg_order_cargo_bind_slot",                         0x0046e998u, 0x0046e9d8u}, // orders_issue
    {"llm_strat_bldg_order_cargo_bind_slot_enqueue",                 0x0046e9d9u, 0x0046ea19u}, // orders_issue
    {"llm_strat_bldg_order_flush_cargo_hold_enqueue",                0x0046ea5bu, 0x0046ea9bu}, // orders_issue
    {"llm_strat_bldg_order_load_passengers_enqueue",                 0x0046eaebu, 0x0046eb39u}, // orders_issue
    {"llm_strat_bldg_order_unload_passengers_enqueue",               0x0046eb89u, 0x0046ebd7u}, // orders_issue
    {"llm_strat_bldg_order_load_resource_enqueue",                   0x0046ec35u, 0x0046ec91u}, // orders_issue
    {"llm_strat_bldg_order_unload_resource_enqueue",                 0x0046ecefu, 0x0046ed4bu}, // orders_issue
    {"llm_strat_bldg_order_depart_dispatch_by_type_enqueue",         0x0046efe4u, 0x0046f13fu}, // orders_issue
    {"llm_strat_bldg_order_start_research_project_enqueue",          0x0046f18fu, 0x0046f1ddu}, // orders_issue
    {"llm_strat_order_ctrlgrp_select_member_raw",                    0x0046f22bu, 0x0046f277u}, // orders_issue
    {"llm_strat_order_ctrlgrp_flash_member_raw",                     0x0046f2c5u, 0x0046f311u}, // orders_issue
    {"llm_strat_order_debug_roll_random",                            0x0046f312u, 0x0046f34bu}, // orders_issue
    {"llm_strat_order_debug_roll_random_enqueue",                    0x0046f34cu, 0x0046f380u}, // orders_issue
    {"llm_strat_order_game_speed_increase",                          0x0046f381u, 0x0046f3bau}, // orders_issue
    {"llm_strat_order_game_speed_increase_enqueue",                  0x0046f3bbu, 0x0046f3f4u}, // orders_issue
    {"llm_strat_order_game_speed_decrease",                          0x0046f3f5u, 0x0046f42eu}, // orders_issue
    {"llm_strat_order_game_speed_decrease_enqueue",                  0x0046f42fu, 0x0046f468u}, // orders_issue
    {"llm_strat_order_recheck_projects_enqueue",                     0x0046f735u, 0x0046f76eu}, // orders_issue
    {"llm_strat_order_recheck_buildings_enqueue",                    0x0046f7a9u, 0x0046f7e2u}, // orders_issue
    {"llm_strat_order_recheck_planet_system_all_players_enqueue",    0x0046f81du, 0x0046f851u}, // orders_issue
    {"llm_strat_order_credit_conquest_kills_enqueue",                0x0046f88cu, 0x0046f8c5u}, // orders_issue
    {"llm_strat_order_set_player_relation_raw",                      0x0046f922u, 0x0046f97du}, // orders_issue
    {"llm_strat_order_set_player_control_mode_enqueue",              0x0046fa3eu, 0x0046fa99u}, // orders_issue
    {"llm_strat_order_debug_energy_refill_full_enqueue",             0x0046fafbu, 0x0046fb5bu}, // orders_issue
    {"llm_strat_order_debug_charge_add_scaled_enqueue",              0x0046fbbdu, 0x0046fc1du}, // orders_issue
    {"llm_strat_order_debug_charge_add_full_group_enqueue",          0x0046fc7fu, 0x0046fcdfu}, // orders_issue
    {"llm_strat_order_fow_reveal_full_enqueue",                      0x0046fd33u, 0x0046fd85u}, // orders_issue
    {"llm_strat_unit_release_path_and_targets",                      0x004888f4u, 0x00488a21u}, // sim_resid
    {"llm_strat_group_formation_trim_far_members",                   0x0048d636u, 0x0048d705u}, // sim_resid
    {"llm_strat_bldg_footprint_destroy_occupants",                   0x00493a96u, 0x00493c27u}, // sim_resid
    {"llm_strat_group_move_request_build",                           0x00494f0cu, 0x00495089u}, // sim_resid
    {"llm_strat_unit_assign_path_from_job_result",                   0x0049508au, 0x00495213u}, // sim_resid
    {"llm_strat_unit_path_store_result",                             0x00495aa0u, 0x00495b6eu}, // sim_resid
    {"llm_strat_unit_assign_shared_path",                            0x00495f87u, 0x0049610eu}, // sim_resid
    {"llm_strat_bldg_set_footprint_passable",                        0x0049a688u, 0x0049a848u}, // sim_resid
    {"llm_unit_alive_count_resync",                                  0x004a01d6u, 0x004a026au}, // sim_resid
    {"llm_strat_ai_bldg_queue_has_type",                             0x004d39bbu, 0x004d3a26u}, // ai
    {"llm_strat_ai_unit_in_group",                                   0x004d48c8u, 0x004d48f9u}, // ai
    {"llm_strat_ai_group_split_half",                                0x004d4e6bu, 0x004d4f15u}, // ai
    {"llm_strat_ai_engage_rank_candidates_by_range",                 0x004d5245u, 0x004d53adu}, // ai
    {"llm_strat_unit_order_attack_dispatch",                         0x004d5801u, 0x004d585du}, // orders_issue
    {"llm_strat_ai_unit_move_near_random_point",                     0x004d5fe7u, 0x004d601eu}, // ai
    {"llm_strat_ai_group_scatter_near_point",                        0x004d6028u, 0x004d60f4u}, // ai
    {"llm_strat_ai_group_scatter_idle_members",                      0x004d60f5u, 0x004d61d2u}, // ai
    {"llm_strat_ai_group_issue_default_order_all",                   0x004d65f0u, 0x004d6645u}, // ai
    {"llm_strat_ai_group_is_within_radius",                          0x004d6646u, 0x004d66d0u}, // ai
    {"llm_strat_ai_group_is_gathered",                               0x004d6772u, 0x004d6815u}, // ai
    {"llm_strat_ai_group_tick_arrivals",                             0x004d6816u, 0x004d68e5u}, // ai
    {"llm_strat_ai_group_rally_stragglers",                          0x004d68e6u, 0x004d69cdu}, // ai
    {"llm_strat_ai_player_get_phase_flags",                          0x004ddadfu, 0x004ddb06u}, // ai
    {"llm_strat_ai_player_set_phase_flags",                          0x004ddb07u, 0x004ddb30u}, // ai
    {"llm_strat_ai_calc_resource_sum_5x5",                           0x004e2eb9u, 0x004e3005u}, // ai
    {"llm_strat_ai_calc_building_extract_value",                     0x004e3006u, 0x004e30aau}, // ai
    {"llm_strat_ai_calc_site_resource_score",                        0x004e30abu, 0x004e30e8u}, // ai
    {"llm_strat_ai_sum_player_mine_resources",                       0x004e32efu, 0x004e340eu}, // ai
    {"llm_strat_ai_count_nearby_turrets",                            0x004e40aeu, 0x004e419du}, // ai
    {"llm_strat_ai_apply_building_proximity_bonus",                  0x004e41a6u, 0x004e4259u}, // ai
    {"llm_strat_ai_expand_adjacent_mine_relay",                      0x004e4a95u, 0x004e4e35u}, // ai CLAMPED from 0x004e4e53 (shared tail / disjoint body)
    {"llm_strat_ai_mine_exists_nearby",                              0x004e612eu, 0x004e6227u}, // ai
    {"llm_strat_ai_group_form_perimeter_patrol",                     0x004e7938u, 0x004e7ad1u}, // ai
    {"llm_strat_ai_group_members_ready",                             0x004e93a5u, 0x004e9420u}, // ai
    {"llm_strat_ai_group_readiness_state",                           0x004e95c1u, 0x004e964au}, // ai
    {"llm_strat_ai_log_scan_targets",                                0x004eb430u, 0x004eb48du}, // ai
    {"llm_strat_ai_build_target_list",                               0x004eb9abu, 0x004ebe79u}, // ai CLAMPED from 0x004ebe83 (shared tail / disjoint body)
    {"llm_strat_ai_collect_unclaimed_scan_targets",                  0x004ebe84u, 0x004ebf08u}, // ai
    {"llm_strat_ai_group_scan_building_targets",                     0x004ebf09u, 0x004ec1ebu}, // ai CLAMPED from 0x004ec1ed (shared tail / disjoint body)
    {"llm_strat_ai_collect_group_scan_targets",                      0x004ec1f6u, 0x004ec2cfu}, // ai
    {"llm_strat_ai_scan_targets_by_owner_and_id_for_engage",         0x004ed1aeu, 0x004ed230u}, // ai
    {"llm_strat_ai_scan_targets_by_type_for_engage",                 0x004ed231u, 0x004ed2acu}, // ai
    {"llm_strat_ai_scan_enemy_turrets_in_weapon_range",              0x004ed34au, 0x004ed494u}, // ai
    {"llm_strat_ai_scan_area_for_engage_candidates",                 0x004ed5f0u, 0x004ed74au}, // ai
    {"llm_strat_ai_unit_scan_engage_candidates_at_max_weapon_range", 0x004ed74bu, 0x004ed78cu}, // ai
    {"llm_strat_ai_scan_targets_by_capability_mask_for_engage",      0x004ed7ecu, 0x004ed88fu}, // ai
    {"llm_strat_ai_scan_for_engage_candidates",                      0x004eda5au, 0x004eda8au}, // ai
    {"llm_strat_ai_group_dispatch_action_flags",                     0x004eda8bu, 0x004edcc9u}, // ai
    {"llm_strat_ai_unit_select_attack_target",                       0x004ee05cu, 0x004ee30au}, // ai
    {"llm_strat_ai_group_report_unit_states",                        0x004ee8eau, 0x004eec6bu}, // ai
    {"llm_strat_ai_tick_all_groups",                                 0x004eec6cu, 0x004eeebcu}, // ai CLAMPED from 0x004eef17 (shared tail / disjoint body)
};
inline constexpr int tombstone_dead_range_count = 107;

// SAFE-END caps for the RUNTIME arms (promoted remainders, force_arm): for these
// functions the flat [entry..end] contains bytes that are NOT exclusively theirs -- a
// disjoint-body gap holding another function, or a shared epilogue tail that outside
// code jumps into (tools/data/interior_flow_refs.json). Arming must stop at `end` here.
inline constexpr mh::hook::owner_range tombstone_tail_caps[] = {
    {"llm_ui_bldg_progress_status_text_select",            0x0041111eu, 0x0041122cu},
    {"llm_ui_hud_minimap_click_handler",                   0x0041181au, 0x004118fau},
    {"game_SetEvent",                                      0x00413a52u, 0x00413aeeu},
    {"llm_ui_chat_input_process_scancodes",                0x00414a4eu, 0x00414a88u},
    {"llm_ui_bldg_selected_panel_tick",                    0x0041695eu, 0x00416b28u},
    {"llm_ui_group_tab_on_click",                          0x00419221u, 0x00419411u},
    {"llm_ui_icon_group_dispatch",                         0x0041afcfu, 0x0041b01eu},
    {"llm_boot_stage_tick",                                0x004262b4u, 0x004262cdu},
    {"llm_tact_unit_update_anim",                          0x0042c547u, 0x0042c686u},
    {"llm_tact_unit_pose_tag_select",                      0x0042dddeu, 0x0042de22u},
    {"llm_tact_unit_weapons_tick",                         0x0042f338u, 0x0042f65du},
    {"llm_tact_unit_mine_arm_tick",                        0x0042f935u, 0x0042f9cfu},
    {"llm_tact_unit_move_advance",                         0x00430f5au, 0x00431139u},
    {"llm_tact_unit_owner_tick",                           0x004335a0u, 0x00433680u},
    {"game_HandleProgress",                                0x0043ff0cu, 0x0043ff2au},
    {"game_UpdateProgress",                                0x004402b0u, 0x004402ceu},
    {"llm_progress_finalize_acquire",                      0x004404ccu, 0x004404eau},
    {"llm_strat_input_update",                             0x00441b88u, 0x00441f57u},
    {"llm_strat_bldg_get_progress_percent",                0x00449ffeu, 0x0044a0f4u},
    {"llm_debug_console_dispatch",                         0x0044b67fu, 0x0044b73cu},
    {"llm_strat_tile_is_storage_door_exit",                0x00453482u, 0x004534b8u},
    {"llm_strat_player_set_color",                         0x00454c51u, 0x00454c6fu},
    {"cfg_final_unit_Construct",                           0x004564c2u, 0x00456826u},
    {"llm_strat_bldg_init_defaults",                       0x0045a068u, 0x0045a087u},
    {"cfg_final_planet_Construct",                         0x0045b69cu, 0x0045b6d2u},
    {"llm_strat_unit_facing_offset_init",                  0x0045fac0u, 0x0045fc2au},
    {"llm_strat_walker_frame_blend_index",                 0x00460a93u, 0x00460b90u},
    {"map_CreateBuilding",                                 0x004622cbu, 0x004626ddu},
    {"llm_bldg_construct_finalize",                        0x00462e66u, 0x00462eabu},
    {"llm_strat_storage_find_home_for_unit",               0x00463328u, 0x00463397u},
    {"llm_unit_recruit",                                   0x00463ec8u, 0x00463f3cu},
    {"llm_strat_order_queue_dispatch",                     0x00466892u, 0x004672abu},
    {"llm_strat_bldg_instant_construct_find_slot",         0x0046d229u, 0x0046d24eu},
    {"llm_strat_bldg_instant_construct_find_slot_enqueue", 0x0046d514u, 0x0046d539u},
    {"llm_unit_order_disembark_soldiers",                  0x0046e76cu, 0x0046e7a1u},
    {"llm_strat_bldg_order_load_resource",                 0x0046ebd8u, 0x0046ec26u},
    {"llm_strat_bldg_order_unload_resource",               0x0046ec92u, 0x0046ecd2u},
    {"llm_strat_order_set_player_control_mode",            0x0046f97eu, 0x0046f9adu},
    {"llm_strat_building_tick",                            0x0046fd86u, 0x0046fd87u},
    {"llm_strat_reason_to_housing_bldg",                   0x0047401cu, 0x0047403au},
    {"llm_strat_bldg_register_online",                     0x004747d6u, 0x0047486eu},
    {"llm_strat_bldg_anim_state_barracks_garage_a",        0x00476627u, 0x004766fau},
    {"llm_strat_bldg_anim_state_vehicles_h",               0x004769a9u, 0x00476a91u},
    {"llm_strat_bldg_anim_state_soldiers_h",               0x00476e9du, 0x00476f85u},
    {"llm_strat_bldg_anim_state_helipad",                  0x004773f4u, 0x004774bfu},
    {"llm_strat_bldg_anim_state_airfield_a",               0x00477881u, 0x0047796bu},
    {"llm_strat_bldg_anim_state_port",                     0x004786f5u, 0x00478933u},
    {"llm_strat_bldg_completion_dispatch",                 0x004795ddu, 0x00479736u},
    {"llm_strat_bldg_unmap_footprint",                     0x0047b36bu, 0x0047b4abu},
    {"llm_strat_turret_fire",                              0x0047bf8eu, 0x0047c0f9u},
    {"llm_strat_unit_update_rotation",                     0x0047d741u, 0x0047d8c1u},
    {"llm_strat_unit_weapon_reload_tick",                  0x0047de7du, 0x0047de99u},
    {"llm_strat_unit_state_enter_walk_in",                 0x004803bfu, 0x00480700u},
    {"llm_strat_unit_state_remove_silent",                 0x0048592du, 0x00485b9au},
    {"llm_strat_unit_state_step_adjacent",                 0x00485babu, 0x00485d32u},
    {"llm_strat_unit_state_plot_turn_path",                0x00485d43u, 0x00485eaau},
    {"llm_strat_unit_state_idle_scatter",                  0x00485ebbu, 0x004860f5u},
    {"llm_strat_unit_free_slot",                           0x00487b25u, 0x00487b84u},
    {"llm_strat_unit_teardown",                            0x00487ba5u, 0x00487ccfu},
    {"llm_strat_storage_place_exit_ground",                0x00489f54u, 0x0048a152u},
    {"llm_strat_unit_fire_weapon",                         0x0048bb6cu, 0x0048bddfu},
    {"llm_strat_prod_try_start_unit",                      0x00492843u, 0x004928e9u},
    {"llm_strat_unit_type_group_index",                    0x00492b60u, 0x00492ba4u},
    {"llm_strat_unit_housing_count_add",                   0x0049779bu, 0x004977e1u},
    {"llm_strat_unit_housing_count_remove",                0x00497842u, 0x00497888u},
    {"llm_bldg_storage_accepts_unit_type",                 0x00497ac4u, 0x00497b0eu},
    {"llm_strat_storage_type_accepts_unit",                0x00497b91u, 0x00497c69u},
    {"llm_strat_player_presence_lost",                     0x00498089u, 0x00498771u},
    {"llm_strat_minimap_init",                             0x0049ad06u, 0x0049b250u},
    {"llm_strat_advisor_tick",                             0x0049b5b0u, 0x0049b60fu},
    {"llm_net_lockstep_dispatch",                          0x0049c2cdu, 0x0049c350u},
    {"llm_snd_debug_cfg_browser_dispatch",                 0x0049fab3u, 0x0049facfu},
    {"llm_frame_dispatch",                                 0x004a035eu, 0x004a03c5u},
    {"llm_wnd_on_activate",                                0x004a0452u, 0x004a048bu},
    {"WinMain",                                            0x004a0b38u, 0x004a0ce9u},
    {"llm_strat_minimap_render",                           0x004a17b3u, 0x004a1893u},
    {"map_fow_UpdateFoWPlus_impl",                         0x004a6817u, 0x004a68c1u},
    {"cfg_CountObjects",                                   0x004a96dcu, 0x004a9775u},
    {"cfg_ReadObjects",                                    0x004a98c6u, 0x004a9944u},
    {"cfg_ObjectInit",                                     0x004aa261u, 0x004aa27du},
    {"cfg_CopyStaticToDynamic",                            0x004aac19u, 0x004aac35u},
    {"llm_ui_menu_state_tick",                             0x004b7c3bu, 0x004b7cbdu},
    {"llm_tutorial_step_driver",                           0x004ba8afu, 0x004ba9b2u},
    {"llm_ui_screen_fade_transition_tick",                 0x004bc4afu, 0x004bc4c8u},
    {"llm_lobby_build_players_from_slots",                 0x004bea15u, 0x004bea51u},
    {"llm_lobby_build_players_step",                       0x004bea62u, 0x004bea69u},
    {"llm_lobby_build_players_tail_copy",                  0x004beab8u, 0x004beae2u},
    {"llm_lobby_host_net_dispatch",                        0x004bfd35u, 0x004c045au},
    {"llm_strat_ui_shipment_list_item_draw",               0x004c4c09u, 0x004c4c48u},
    {"llm_ui_planet_sel_route_icon_place",                 0x004c5995u, 0x004c5a2au},
    {"llm_ui_outcome_dialog",                              0x004c6c4fu, 0x004c6d69u},
    {"llm_ui_bldg_info_panel_populate_stat_line",          0x004c97e4u, 0x004c985du},
    {"llm_snd_mixer_check_error",                          0x004cbe7au, 0x004cbf07u},
    {"llm_cd_audio_query_mode_and_position",               0x004cc609u, 0x004cc622u},
    {"llm_ui_acm_result_dispatch",                         0x004cc9f9u, 0x004cca15u},
    {"llm_ui_avi_icm_result_to_string",                    0x004ccc03u, 0x004ccc6au},
    {"llm_ui_avi_check_result",                            0x004ccdddu, 0x004cce9cu},
    {"llm_input_di_keyboard_destroy",                      0x004d1008u, 0x004d0a47u},
    {"llm_input_dimouse_shutdown",                         0x004d10d0u, 0x004d0cc3u},
    {"llm_strat_ai_unit_squad_firepower_value",            0x004d3437u, 0x004d3523u},
    {"llm_strat_bldg_count_by_type",                       0x004d37f2u, 0x004d3882u},
    {"llm_strat_ai_group_create",                          0x004d4d85u, 0x004d4e60u},
    {"llm_strat_ai_commit_attack_order",                   0x004d55efu, 0x004d56dfu},
    {"llm_strat_ai_group_scatter_random_worker",           0x004d5f4cu, 0x004d5fe6u},
    {"llm_gfx_save_screenshot_rle",                        0x004d71c7u, 0x004d70c8u},
    {"llm_strat_bldg_has_aa_weapon",                       0x004d746cu, 0x004d74ceu},
    {"llm_strat_ai_unit_flag_and_move",                    0x004d7e22u, 0x004d7e64u},
    {"llm_strat_ai_bldg_has_heli_unit",                    0x004d8a9du, 0x004d8b7fu},
    {"llm_strat_target_release_ref",                       0x004dac44u, 0x004dadfau},
    {"llm_strat_ai_scr_parse",                             0x004ddb31u, 0x004ddc5du},
    {"llm_lzss_decompress_block",                          0x004ddc70u, 0x004ddcd6u},
    {"FUN_004de18e",                                       0x004de18eu, 0x004de18fu},
    {"CRT_004de84e",                                       0x004de84eu, 0x004de89cu},
    {"CRT_004df43c",                                       0x004df43cu, 0x004df45au},
    {"CRT_004e1898",                                       0x004e1898u, 0x004e1926u},
    {"llm_strat_econ_track_unit_resource_spend",           0x004e215fu, 0x004e21ddu},
    {"llm_strat_ai_queue_flush_unit_train_entries",        0x004e2c8eu, 0x004e2c66u},
    {"llm_strat_ai_queue_rotate_newest_to_front",          0x004e2cacu, 0x004e2d4au},
    {"llm_strat_ai_expand_adjacent_mine_relay",            0x004e4a95u, 0x004e4e35u},
    {"llm_strat_ai_group_form_standby_from_pool3",         0x004e722au, 0x004e72e0u},
    {"llm_strat_ai_group_expansion_form_or_repurpose",     0x004e769eu, 0x004e7924u},
    {"llm_strat_ai_group_find_nearest_building_of_types",  0x004e98a7u, 0x004e99b4u},
    {"llm_strat_ai_group_task_drain_reserve_attack",       0x004e9c98u, 0x004ea061u},
    {"llm_strat_ai_group_task_recruit_from_pool3",         0x004ea5d9u, 0x004ea65cu},
    {"llm_strat_ai_build_target_list",                     0x004eb9abu, 0x004ebe79u},
    {"llm_strat_ai_group_scan_building_targets",           0x004ebf09u, 0x004ec1ebu},
    {"llm_strat_ai_holding_pen_scan_targets",              0x004ec35fu, 0x004ec515u},
    {"llm_strat_ai_target_list_refresh_mothers",           0x004ec58au, 0x004ec5e3u},
    {"llm_strat_ai_unit_should_abandon_target",            0x004ec84du, 0x004ec86eu},
    {"llm_strat_ai_scan_targets_for_engage",               0x004ed130u, 0x004ed1a6u},
    {"llm_strat_ai_active_unit_tick",                      0x004ee30bu, 0x004ed12fu},
    {"llm_strat_ai_tick_all_groups",                       0x004eec6cu, 0x004eeebcu},
    {"CRT_004ef8e0",                                       0x004ef8e0u, 0x004ef928u},
    {"_nexpand",                                           0x004f02d3u, 0x004f030cu},
    {"CRT_004f07c5",                                       0x004f07c5u, 0x004f0837u},
    {"__EnterWVIDEO",                                      0x004f1136u, 0x004f1147u},
    {"FUN_004f115c",                                       0x004f115cu, 0x004f117au},
    {"FUN_004f1180",                                       0x004f1180u, 0x004f1184u},
    {"raise",                                              0x004f125cu, 0x004f1294u},
    {"_nheapshrink",                                       0x004f2116u, 0x004f2129u},
    {"__fpatan_chk",                                       0x004f2650u, 0x004f27afu},
    {"sys_open_device_and_file_handles_once",              0x004f2850u, 0x004f28d5u},
    {"__RemoveThreadData",                                 0x004f32b0u, 0x004f32f5u},
    {"CRT_004f3511",                                       0x004f3511u, 0x004f35b1u},
    {"LZW_Compress",                                       0x004f48e0u, 0x004f4935u},
    {"LZW_Decompress",                                     0x004f4b7eu, 0x004f4be7u},
    {"llm_pf_expand_step",                                 0x0055b665u, 0x0055b754u},
    {"llm_pf_expand_wavefront",                            0x0055bd1du, 0x0055bd6au},
    {"llm_pf_select_resolution",                           0x0055bd7fu, 0x0055bde8u},
    {"llm_pf_seed_goals",                                  0x0055e233u, 0x0055e3b1u},
    {"llm_strat_pathfind_flood_expand_ring",               0x00580223u, 0x005802e0u},
    {"llm_strat_pathfind_flood_search_loop",               0x005808a9u, 0x005808f6u},
    {"llm_strat_pathfind_route_extract",                   0x0058090bu, 0x00580929u},
    {"llm_strat_pathfind_route_backtrace_recurse",         0x00580aaeu, 0x00580b3eu},
    {"FUN_00580d89",                                       0x00580d89u, 0x00580e18u},
    {"llm_strat_pathfind_flood_select_grid_level",         0x00580e29u, 0x00580e92u},
    {"llm_strat_pathfind_flood_seed_from_route",           0x005834bfu, 0x00583655u},
    {"llm_strat_pathfind_backfill_flood_step",             0x00583820u, 0x00583882u},
    {"llm_strat_pathfind_backfill_resolve_target",         0x0058411bu, 0x00584176u},
    {"llm_strat_trace_greedy_path",                        0x0066a9acu, 0x0066b358u},
    {"llm_strat_pathtrace_normalize_repeat_dir_table",     0x0066b4a1u, 0x0066b515u},
};
inline constexpr int tombstone_tail_cap_count = 161;

// SECTION-5 RESIDUE -- rows the force-arm paths must NOT trap, derived from
// tools/data/reconciliation_hostreach_residue.json (the same file the promotion
// reconciliation's full `--check` reads, so an exclusion cannot outlive its adjudication).
// Each is a `verified` row whose ORIGINAL body stays reachable from host code ON PURPOSE;
// trapping one turns a decided end state into a red run whose redness depends on which
// scenario you happened to run. The runtime PRINTS every skip with its class -- a silent
// exclusion is the drift this table exists to prevent.
inline constexpr mh::hook::residue_row tombstone_residue_exclusions[] = {
    {"llm_map_fog_of_war_recompute", 0x00428b11u, "downstream_of_named_residue",
     "reached only through map_LoadPlanetFromDisk, itself a NAMED RESIDUE (the save closure is ours in no configuration)"},
};
inline constexpr int tombstone_residue_exclusion_count = 1;

} // namespace mh::addr
