// GENERATED by tools/gen_libmh_hostapi.py -- DO NOT EDIT; regenerate instead.
// The SELFTEST HOST for the host-callback ABI (LIB-ABI stage D's no-op-host arm),
// BOTH tables (LIB-IFACE-SPLIT): entries in a NOTIFY group are return-default
// no-ops; entries in a REQUIRED group call mh_hostapi_trap(name) before returning
// a default, so a required entry reached without a real host impl is caught BY
// NAME, never silently. An entry in both tables shares one stub.
// A ledger row's `noop_return` overrides the 0 default where the caller consumes the
// value (stage E: overlay_dismiss/wait_player/outcome_dialog return 1;
// sync_overlay_show returns -1 -- the no-button value peer-removal branches on).
#include "../libmh/include/libmh_host_api.gen.h"
#include "../libmh/include/libmh_tact_host_api.gen.h"
#include "hostapi_selftest_support.h"

namespace {
void h_apply_frame_input() { mh_hostapi_trap("apply_frame_input"); }
int32_t h_asset_read(const char *, void *, uint32_t) { mh_hostapi_trap("asset_read"); return (int32_t)0; }
int32_t h_asset_size(const char *) { mh_hostapi_trap("asset_size"); return (int32_t)0; }
void h_vfs_close(int32_t) { mh_hostapi_trap("vfs_close"); }
int32_t h_vfs_open(const char *, int32_t) { mh_hostapi_trap("vfs_open"); return (int32_t)0; }
int32_t h_vfs_read(int32_t, void *, uint32_t) { mh_hostapi_trap("vfs_read"); return (int32_t)0; }
int32_t h_vfs_seek(int32_t, int32_t, int32_t) { mh_hostapi_trap("vfs_seek"); return (int32_t)0; }
int32_t h_vfs_tell(int32_t) { mh_hostapi_trap("vfs_tell"); return (int32_t)0; }
int32_t h_vfs_write(int32_t, const void *, uint32_t) { mh_hostapi_trap("vfs_write"); return (int32_t)0; }
uint32_t h_cfg_ReadMapFile(void *) { mh_hostapi_trap("cfg_ReadMapFile"); return (uint32_t)0; }
void h_map_ReadMap_pre(uint32_t) { mh_hostapi_trap("map_ReadMap_pre"); }
void h_map_load_regions(int32_t) { mh_hostapi_trap("map_load_regions"); }
void h_map_save_regions(int32_t) { mh_hostapi_trap("map_save_regions"); }
int32_t h_planet_tlo_load(uint32_t) { mh_hostapi_trap("planet_tlo_load"); return (int32_t)0; }
void h_save_player_data(void *) { mh_hostapi_trap("save_player_data"); }
int32_t h_transport_recv(int32_t *, void *, int32_t *) { mh_hostapi_trap("transport_recv"); return (int32_t)0; }
void h_transport_send(void *, int32_t) { mh_hostapi_trap("transport_send"); }
void *h_ansi_to_wide(void *, char *) { mh_hostapi_trap("ansi_to_wide"); return (void *)0; }
void *h_ansi_to_wide_scratch(char *) { mh_hostapi_trap("ansi_to_wide_scratch"); return (void *)0; }
char *h_wide_to_local(void *, char *) { mh_hostapi_trap("wide_to_local"); return (char *)0; }
uint32_t h_wide_to_local_bytes(void *) { mh_hostapi_trap("wide_to_local_bytes"); return (uint32_t)0; }
uint32_t h_ticks_ms() { mh_hostapi_trap("ticks_ms"); return (uint32_t)0; }
void h_fatal(int32_t) { mh_hostapi_trap("fatal"); }
void *h_media_diag_block() { mh_hostapi_trap("media_diag_block"); return (void *)0; }
void h_llm_gfx_convert_pixels_565_to_555(int16_t *) {  }
void h_llm_tlo_palette_convert_565_to_555() {  }
void h_llm_tlo_shade_table_build_tact() {  }
void h_llm_snd_play_matching_sample(uint32_t, void *, int32_t, int32_t, int32_t) {  }
void h_llm_gfx_apply_resolution_change() { mh_hostapi_trap("llm_gfx_apply_resolution_change"); }
void h_llm_gfx_apply_window_resolution(int32_t, int32_t) { mh_hostapi_trap("llm_gfx_apply_window_resolution"); }
void h_llm_tact_render_view() { mh_hostapi_trap("llm_tact_render_view"); }
int32_t h_llm_view_set_size_mode(int32_t) { mh_hostapi_trap("llm_view_set_size_mode"); return (int32_t)0; }
void h_llm_input_key_dequeue(uint32_t) { mh_hostapi_trap("llm_input_key_dequeue"); }
int32_t h_llm_input_key_queue_empty() { mh_hostapi_trap("llm_input_key_queue_empty"); return (int32_t)0; }
int32_t h_llm_input_mouse_buttons_get() { mh_hostapi_trap("llm_input_mouse_buttons_get"); return (int32_t)0; }
void h_llm_input_mouse_delta_pump() { mh_hostapi_trap("llm_input_mouse_delta_pump"); }
uint8_t *h_GetResourseFilePtr(char *) { mh_hostapi_trap("GetResourseFilePtr"); return (uint8_t *)0; }
uint32_t h_rsr_GetFileRealSize(char *) { mh_hostapi_trap("rsr_GetFileRealSize"); return (uint32_t)0; }
void h_llm_fatal_cleanup() { mh_hostapi_trap("llm_fatal_cleanup"); }
void h_utils_abort(int32_t) { mh_hostapi_trap("utils_abort"); }
}  // namespace

const libmh_host_api &mh_hostapi_selftest_table() {
    static const libmh_host_api t = {
        h_apply_frame_input,
        h_asset_read,
        h_asset_size,
        h_vfs_close,
        h_vfs_open,
        h_vfs_read,
        h_vfs_seek,
        h_vfs_tell,
        h_vfs_write,
        h_cfg_ReadMapFile,
        h_map_ReadMap_pre,
        h_map_load_regions,
        h_map_save_regions,
        h_planet_tlo_load,
        h_save_player_data,
        h_transport_recv,
        h_transport_send,
        h_ansi_to_wide,
        h_ansi_to_wide_scratch,
        h_wide_to_local,
        h_wide_to_local_bytes,
        h_ticks_ms,
        h_fatal,
        h_media_diag_block,
    };
    return t;
}

const libmh_tact_host_api &mh_hostapi_selftest_tact_table() {
    static const libmh_tact_host_api t = {
        h_llm_gfx_convert_pixels_565_to_555,
        h_llm_tlo_palette_convert_565_to_555,
        h_llm_tlo_shade_table_build_tact,
        h_llm_snd_play_matching_sample,
        h_llm_gfx_apply_resolution_change,
        h_llm_gfx_apply_window_resolution,
        h_llm_tact_render_view,
        h_llm_view_set_size_mode,
        h_llm_input_key_dequeue,
        h_llm_input_key_queue_empty,
        h_llm_input_mouse_buttons_get,
        h_llm_input_mouse_delta_pump,
        h_GetResourseFilePtr,
        h_rsr_GetFileRealSize,
        h_llm_fatal_cleanup,
        h_utils_abort,
    };
    return t;
}
