#pragma once
// GENERATED by tools/gen_libmh_contract.py -- do not hand-edit; rerun the generator.
//
// The mh.dll side of the F4D export contract: one table slot per libmh symbol mh.dll
// needs, plus the two crossing counters that make 'did this run go through the DLL
// boundary' a number instead of an inference. mh/seams/libmh_bind.cpp fills the table;
// libmh_contract.gen.cpp defines it and the forwarding thunks over it.

#define MH_LIBMH_CONTRACT_COUNT 93

// Slot indices, in the committed order (= libmh.def's order). Only the hand-defined rows
// name theirs in source; the rest are reached by the generated thunks.
enum mh_libmh_slot {
    MH_LIBMH_SLOT_mh_ai_ai_say = 0,
    MH_LIBMH_SLOT_mh_rebind_arm_from_config = 1,
    MH_LIBMH_SLOT_mh_state_bind_relocated = 2,
    MH_LIBMH_SLOT_mh_state_bind_stock = 3,
    MH_LIBMH_SLOT_mh_state_world_capture = 4,
    MH_LIBMH_SLOT_mh_state_world_capture_capacity = 5,
    MH_LIBMH_SLOT_mh_save_container_load_promotion_active = 6,
    MH_LIBMH_SLOT_mh_save_container_promotion_active = 7,
    MH_LIBMH_SLOT_mh_orders_admission_counts = 8,
    MH_LIBMH_SLOT_mh_state_emit_text = 9,
    MH_LIBMH_SLOT_mh_state_event_sink_dispatch_count = 10,
    MH_LIBMH_SLOT_mh_lockstep_fixes = 11,
    MH_LIBMH_SLOT_mh_save_install_container_load_promotion = 12,
    MH_LIBMH_SLOT_mh_save_install_container_promotion = 13,
    MH_LIBMH_SLOT_mh_hosthook_install_export_ok = 14,
    MH_LIBMH_SLOT_mh_save_install_load_promotion = 15,
    MH_LIBMH_SLOT_mh_ai_install_promotion = 16,
    MH_LIBMH_SLOT_mh_orders_issue_install_promotion = 17,
    MH_LIBMH_SLOT_mh_lockstep_install_promotion = 18,
    MH_LIBMH_SLOT_mh_orders_install_promotion = 19,
    MH_LIBMH_SLOT_mh_save_install_promotion = 20,
    MH_LIBMH_SLOT_mh_sim_install_promotion_batch_h = 21,
    MH_LIBMH_SLOT_mh_sim_install_promotion_bldg_tick_animation_state = 22,
    MH_LIBMH_SLOT_mh_sim_install_promotion_bldg_type_callbacks = 23,
    MH_LIBMH_SLOT_mh_sim_install_promotion_building_tick = 24,
    MH_LIBMH_SLOT_mh_sim_install_promotion_dispatch = 25,
    MH_LIBMH_SLOT_mh_sim_install_promotion_hostreach = 26,
    MH_LIBMH_SLOT_mh_sim_install_promotion_lib_trans = 27,
    MH_LIBMH_SLOT_mh_sim_install_promotion_lt_frame = 28,
    MH_LIBMH_SLOT_mh_sim_install_promotion_resid = 29,
    MH_LIBMH_SLOT_mh_sim_install_promotion_sim_step_direct = 30,
    MH_LIBMH_SLOT_mh_sim_install_promotion_state_handlers = 31,
    MH_LIBMH_SLOT_mh_sim_install_promotion_unit_tick = 32,
    MH_LIBMH_SLOT_mh_sim_install_promotion_xtl = 33,
    MH_LIBMH_SLOT_mh_ai_island_move = 34,
    MH_LIBMH_SLOT_mh_state_live = 35,
    MH_LIBMH_SLOT_mh_save_load_promotion_active = 36,
    MH_LIBMH_SLOT_mh_state_world_lockstep_hash = 37,
    MH_LIBMH_SLOT_mh_sim_mark_promoted_dispatch_installed = 38,
    MH_LIBMH_SLOT_mh_tact_mission_start = 39,
    MH_LIBMH_SLOT_mh_state_moved_after_bind = 40,
    MH_LIBMH_SLOT_mh_state_moved_before_bind = 41,
    MH_LIBMH_SLOT_mh_sim_order_queue_dispatch_entry_thunk = 42,
    MH_LIBMH_SLOT_mh_state_owner_count = 43,
    MH_LIBMH_SLOT_mh_state_owner_table = 44,
    MH_LIBMH_SLOT_mh_orders_admission_plan = 45,
    MH_LIBMH_SLOT_mh_ai_promotion_active = 46,
    MH_LIBMH_SLOT_mh_lockstep_promotion_active = 47,
    MH_LIBMH_SLOT_mh_orders_promotion_active = 48,
    MH_LIBMH_SLOT_mh_save_promotion_active = 49,
    MH_LIBMH_SLOT_mh_sim_register_promotion_sim_step_rebound = 50,
    MH_LIBMH_SLOT_mh_state_relocated_count = 51,
    MH_LIBMH_SLOT_mh_rebind_report_arming = 52,
    MH_LIBMH_SLOT_mh_rebind_set_armed = 53,
    MH_LIBMH_SLOT_mh_sim_set_dispatch_observer = 54,
    MH_LIBMH_SLOT_mh_lockstep_set_extend_floor = 55,
    MH_LIBMH_SLOT_mh_lockstep_set_fixes = 56,
    MH_LIBMH_SLOT_mh_lockstep_set_icon_counters = 57,
    MH_LIBMH_SLOT_mh_sim_set_land_players_observer = 58,
    MH_LIBMH_SLOT_mh_ai_set_logger = 59,
    MH_LIBMH_SLOT_mh_lockstep_set_logger = 60,
    MH_LIBMH_SLOT_mh_orders_set_logger = 61,
    MH_LIBMH_SLOT_mh_save_set_logger = 62,
    MH_LIBMH_SLOT_mh_sim_set_session_begin_multi_observer = 63,
    MH_LIBMH_SLOT_mh_sim_set_sim_step_pre_hook = 64,
    MH_LIBMH_SLOT_mh_sim_set_time_resync_instrument_hooks = 65,
    MH_LIBMH_SLOT_mh_sim_sim_step_entry_thunk = 66,
    MH_LIBMH_SLOT_mh_sim_sim_step_promoted = 67,
    MH_LIBMH_SLOT_mh_sim_sim_step_promoted_via_rebind = 68,
    MH_LIBMH_SLOT_mh_lockstep_sim_tick_entry_thunk = 69,
    MH_LIBMH_SLOT_mh_lockstep_sim_tick_requested = 70,
    MH_LIBMH_SLOT_mh_orders_admission_stage_active = 71,
    MH_LIBMH_SLOT_mh_orders_admission_stage_cancel = 72,
    MH_LIBMH_SLOT_mh_orders_admission_stage_feed = 73,
    MH_LIBMH_SLOT_mh_tact_state = 74,
    MH_LIBMH_SLOT_mh_lockstep_time_tick_entry_thunk = 75,
    MH_LIBMH_SLOT_mh_lockstep_time_tick_requested = 76,
    MH_LIBMH_SLOT_mh_libmh_in_trap_count = 77,
    MH_LIBMH_SLOT_libmh_bound_count = 78,
    MH_LIBMH_SLOT_libmh_hook_api_unbound = 79,
    MH_LIBMH_SLOT_libmh_host_api_unbound = 80,
    MH_LIBMH_SLOT_libmh_import_world_resync = 81,
    MH_LIBMH_SLOT_libmh_in_is_open = 82,
    MH_LIBMH_SLOT_libmh_in_open = 83,
    MH_LIBMH_SLOT_libmh_in_unbound = 84,
    MH_LIBMH_SLOT_libmh_region_count = 85,
    MH_LIBMH_SLOT_libmh_set_event_sink = 86,
    MH_LIBMH_SLOT_libmh_set_hook_api = 87,
    MH_LIBMH_SLOT_libmh_set_host_api = 88,
    MH_LIBMH_SLOT_libmh_set_session_seed = 89,
    MH_LIBMH_SLOT_libmh_set_tact_host_api = 90,
    MH_LIBMH_SLOT_libmh_set_text_sink = 91,
    MH_LIBMH_SLOT_libmh_tact_host_api_unbound = 92,
};

extern "C" {
// The bound addresses, one per row, in slot order. A null slot means 'libmh did not
// export this row' -- which the bind treats as a refusal of the whole module, so at
// runtime the table is either entirely filled or entirely null.
extern void *g_libmh_fn[MH_LIBMH_CONTRACT_COUNT];
extern const char *const g_libmh_fn_name[MH_LIBMH_CONTRACT_COUNT];
// THE STANDING ARM (F4D done_when). Incremented inside the thunks, so they count real
// calls rather than intentions: crossings on the bound path, absent_calls on the other.
// A brokered lane with crossings == 0 has not exercised the spine boundary, whatever its
// bind line says, and tools/check_module_bind.py --libmh reds on it.
extern unsigned g_libmh_crossings;
extern unsigned g_libmh_absent_calls;
}
