/* GENERATED by tools/gen_libmh_hostapi.py -- DO NOT EDIT; regenerate instead.
 * Sources: tools/data/libmh_call_ledger.json (host-callback:* rows) x
 * tools/data/dll_call_protos.json (signatures) x the accessor-site scan of
 * src/mh_dll/mh/** (membership). `--check` is the drift gate.
 *
 * the TACT table -- every entry tact/ reaches through mh::tact_host(). FROZEN by design: the sim
 * table is the abstraction target; this one changes only when tact/ code does.
 *
 * ONE OF TWO TABLES (LIB-IFACE-SPLIT): sim (libmh_host_api, via mh::host()) and
 * tact (libmh_tact_host_api, via mh::tact_host()), bound separately, each with its
 * own version handshake and unbound walk. An entry both sides call appears in BOTH
 * -- duplication is the design; nothing is assigned exclusively. Membership is
 * DERIVED from the accessor sites, so this file changes only when source sites do.
 *
 * mh.dll binds every entry over its mh::call:: thunks; a headless host binds no-ops
 * for the NOTIFY groups and real impls or NAMED traps for the REQUIRED ones -- each group's
 * header line says which it is. C++ struct-pointer params are void* here on purpose --
 * the true type is in the trailing comment and in addr/mh_structs.gen.h. */
#ifndef LIBMH_TACT_HOST_API_GEN_H
#define LIBMH_TACT_HOST_API_GEN_H

#include <stdint.h>

/* FNV-1a over the ABI-relevant text (categories, names, signatures). Pass to
 * libmh_set_tact_host_api(); the implementation refuses a value it was not compiled with. */
#define LIBMH_TACT_HOST_API_VERSION 0xAE411064u
#define LIBMH_TACT_HOST_API_ENTRY_COUNT 16u

#ifdef __cplusplus
extern "C" {
#endif

typedef struct libmh_tact_host_api {

    /* ---- render-notify (3): visual/UI notifications; a headless host binds no-ops ---- */
    /* [tact modules: tact] */
    /* sprite pixel format conversion */
    void (*llm_gfx_convert_pixels_565_to_555)(int16_t *sprite_blob);
    /* [tact modules: tact] */
    /* palette format conversion */
    void (*llm_tlo_palette_convert_565_to_555)(void);
    /* [tact modules: tact] */
    /* lighting LUT precompute */
    void (*llm_tlo_shade_table_build_tact)(void);

    /* ---- sound (1): audio playback/control; a headless host binds no-ops ---- */
    /* [tact modules: tact] */
    /* DEFERRED at LIFT-NOTIFY slice 1 (2026-09-03, per the epistemics sanity check): the entry carries */
    /* a snd_cfg_entry POINTER payload, which the 4x-int32 event record cannot represent and R4 forbids */
    /* shipping raw; converting needs an id-based redesign (the cfg entry's index is derivable from the */
    /* table base). Stays a table entry until then. Original reason: sample lookup + voice play. */
    void (*llm_snd_play_matching_sample)(uint32_t channel_index, void *cfg /* mh::game::mh_llm_snd_cfg_entry * */, int32_t volume, int32_t pan, int32_t note_or_rate);

    /* ---- display (4): REQUIRED despite being visual: each of these either returns a value the sim reads or reconfigures state libmh reads back in the same call (R3/R3b), so a no-op DIVERGES ---- */
    /* [tact modules: tact] */
    /* REQUIRED under R3b (class flipped to match at LIFT-TABLE S1, 2026-09-09 -- the row said KEPT */
    /* REQUIRED in prose while shipping notify:1, i.e. telling a headless host it could bind a no-op). */
    /* KEPT REQUIRED under R3b (LIFT-TACT slice B2, 2026-09-09), same reversal and same reason as its */
    /* sibling llm_gfx_apply_window_resolution. Closure 107 functions, sixteen regions read by */
    /* translated libmh. The same-call readback is measured rather than assumed: it writes */
    /* MAP_REGION_LIST_HEAD, and llm_tact_mission_end_return_to_strategic calls map_LoadPlanetFromDisk */
    /* on the very next line, which reaches llm_map_region_pool_reset / merge_small_regions / */
    /* recompute_adjacency (checked against the committed call graph). */
    void (*llm_gfx_apply_resolution_change)(void);
    /* [tact modules: tact] */
    /* REQUIRED under R3b (class flipped to match at LIFT-TABLE S1, 2026-09-09 -- the row said KEPT */
    /* REQUIRED in prose while shipping notify:1, i.e. telling a headless host it could bind a no-op). */
    /* KEPT REQUIRED under R3b (LIFT-TACT slice B2, 2026-09-09) -- the conversion was WRITTEN and then */
    /* REVERTED on the gate's measurement, which is the epistemics clause doing its job. Its closure is */
    /* 81 functions and it re-derives fifteen regions translated libmh reads, including */
    /* GFX_DRAW_SURFACE and FRAMEBUFFER -- and llm_tact_mission_start, the one emitter, reads BOTH */
    /* later in the SAME CALL: the 480-row intro blit at tact_mission_start.cpp:150-151 uses */
    /* gfx_draw_surface as its source and gfx_framebuffer as its destination. A frame-edge drain would */
    /* run that blit between the old surface pointers. This is not a notification, it is the host */
    /* reconfiguring the display and libmh depending on the result, which is exactly the case R3b makes */
    /* required-class. */
    void (*llm_gfx_apply_window_resolution)(int32_t width, int32_t height);
    /* [tact modules: tact] */
    /* REQUIRED under R3b -- the founding instance of the rule (docs/libmh-abi.md sec 4). It returns */
    /* nothing, but its camera-viewport tile scan is the ONLY path to llm_tact_unit_update_anim, which */
    /* writes anim_frame_time/frame_index/anim_cycle_time/frame_interval/sprite_id into tact_units = */
    /* TACT_HASH_REGIONS[0], and it writes hovered_unit_id, which tact_frame reads at NINE later sites */
    /* in the same frame to issue orders. A host that defers this to a frame edge would order against */
    /* last frame's hover state. Class corrected at LIFT-TABLE S1 (2026-09-09): the row still carried */
    /* the pre-discovery `view-only state per xref sweep` reason AND a notify flag that told a headless */
    /* host it could bind a no-op. */
    void (*llm_tact_render_view)(void);
    /* [tact modules: tact] */
    /* REQUIRED under R3 -- its return IS consumed: sim_start_tutorial.cpp:44 assigns it into the */
    /* hashed view_size_mode() cell. A no-op returning 0 changes hashed sim state. Class corrected at */
    /* LIFT-TABLE S1 (2026-09-09); the old `resolution/zoom bookkeeping` reason described the effect */
    /* and missed the consumer. */
    int32_t (*llm_view_set_size_mode)(int32_t size_mode);

    /* ---- input (4): the input pump -- REQUIRED per R10: the host owns it and pushes, libmh never polls ---- */
    /* [tact modules: tact] */
    /* Pop the next key event from the host's input queue, or report empty. REQUIRED per R10, and NOT */
    /* convertible to a polled-state query: the game consumes AT MOST ONE hotkey per frame, and a 'what */
    /* is held right now' interface would change that semantics silently. WHAT A HOST SUPPLIES: a FIFO */
    /* of key events, drained one per call, in the order the player produced them. */
    void (*llm_input_key_dequeue)(uint32_t param_1);
    /* [tact modules: tact] */
    /* Report whether the key queue has anything in it, without consuming. The tactical frame asks this */
    /* before dequeuing; a host that answers wrongly either drops the player's input or feeds a */
    /* stale/garbage event into an order. It measures as tact-only in the translated tree, which is a */
    /* translation-frontier artefact -- the original has SIX non-tact callers (llm_strat_input_update, */
    /* llm_ui_menu_transition_settle, llm_ui_modal_key_pump, ...). */
    int32_t (*llm_input_key_queue_empty)(void);
    /* [tact modules: tact] */
    /* The current mouse button mask. Pushed-model exception by necessity: buttons are level state, not */
    /* events, and the game samples them per frame. WHAT A HOST SUPPLIES: the mask as of the frame */
    /* libmh is stepping, stable for the duration of that frame -- a mask that changes mid-frame */
    /* produces selections that begin and end in different worlds. */
    int32_t (*llm_input_mouse_buttons_get)(void);
    /* [tact modules: tact] */
    /* Accumulated mouse movement since the last call, and it is a PUMP: the act of asking clears the */
    /* accumulator. A host that returns absolute position here makes the cursor accelerate away. */
    void (*llm_input_mouse_delta_pump)(void);

    /* ---- io (2): files and packed resources -- REQUIRED: implement or bind a named trap ---- */
    /* [tact modules: tact] */
    /* Return a pointer to a named record inside the game's packed resource files (gfx, glyphs, mission */
    /* bytes): a generic loader, not map-specific. tact/ reads the returned bytes and, at one site, the */
    /* two 16-bit header words in front of them; it never frees the pointer, so the allocation must */
    /* stay valid for the rest of the session. THE FROZEN SHAPE: the sim side reshaped this entry to */
    /* asset_read (a copy) at SIMABI-VFS; tact's copy keeps the pointer-returning form, which is */
    /* exactly what duplication is for. */
    uint8_t *(*GetResourseFilePtr)(char *fileName);
    /* [tact modules: tact] */
    /* The uncompressed byte length of a packed resource record, asked BEFORE GetResourseFilePtr so */
    /* libmh can size its buffer. It must agree with the number of bytes that pointer then yields. */
    uint32_t (*rsr_GetFileRealSize)(char *file_name);

    /* ---- fatal (2): process death and its cleanup -- REQUIRED: these must not return ---- */
    /* [tact modules: tact] */
    /* Release the game's own resources on the fatal path, ahead of utils_abort. Also called from two */
    /* TACTICAL bodies that are not parsers (tact_door, tact_unit_spawn), which is why it survives the */
    /* mission-load cluster's disposition. It must be safe to call with the world inconsistent -- that */
    /* is the only state it is ever called in. */
    void (*llm_fatal_cleanup)(void);
    /* [tact modules: tact] */
    /* Terminate the process. IT MUST NOT RETURN: libmh calls it on unrecoverable asset and state */
    /* errors and the code after the call assumes it is unreachable. Nine translation units reach it. */
    /* (The routing census reports 0 direct callers, which is a blind spot rather than a fact -- */
    /* utils_abort is not a node in the trimmed call graph at all; its site_modules field, a source */
    /* scan, has it right.) A host that wants to survive the condition must unwind on its own side; */
    /* returning here resumes a body that has already decided it cannot continue. */
    void (*utils_abort)(int32_t status);
} libmh_tact_host_api;

#ifdef __cplusplus
} /* extern "C" */
#endif

/* X-macro over every entry, in struct order: X(name, category, notify).
 * category is the GROUP NAME as a string literal; notify is 1 where a headless host
 * may bind a no-op. Group membership is the ledger's class, one place, not a rule.
 * Derive the name table / offsetof table / notify flags from this -- do not hand-list. */
#define LIBMH_TACT_HOST_API_FOR_EACH(X) \
    X(llm_gfx_convert_pixels_565_to_555, "render-notify", 1) \
    X(llm_tlo_palette_convert_565_to_555, "render-notify", 1) \
    X(llm_tlo_shade_table_build_tact, "render-notify", 1) \
    X(llm_snd_play_matching_sample, "sound", 1) \
    X(llm_gfx_apply_resolution_change, "display", 0) \
    X(llm_gfx_apply_window_resolution, "display", 0) \
    X(llm_tact_render_view, "display", 0) \
    X(llm_view_set_size_mode, "display", 0) \
    X(llm_input_key_dequeue, "input", 0) \
    X(llm_input_key_queue_empty, "input", 0) \
    X(llm_input_mouse_buttons_get, "input", 0) \
    X(llm_input_mouse_delta_pump, "input", 0) \
    X(GetResourseFilePtr, "io", 0) \
    X(rsr_GetFileRealSize, "io", 0) \
    X(llm_fatal_cleanup, "fatal", 0) \
    X(utils_abort, "fatal", 0)

#endif /* LIBMH_TACT_HOST_API_GEN_H */
