/* GENERATED by tools/gen_libmh_inbound.py -- DO NOT EDIT.
 *
 * The INBOUND (host -> libmh) surface's derived half: the order-id table that
 * libmh_issue_order dispatches on, the entry-name table libmh_in_unbound walks, and the
 * version constant both sides handshake with. The DESIGNED half -- the C prototypes a
 * host actually calls -- is hand-authored in libmh_host_in.h, the same division
 * libmh_host_events.h and libmh_host_api.gen.h already use.
 *
 * LIBMH_HOST_IN_VERSION IS COMPUTED, not maintained: it is a hash over every covered
 * row's (body, entry, arity). Adding, removing or re-arity-ing an entry moves it
 * automatically, so a stale host is refused by libmh_in_open without anyone having
 * remembered to bump a constant.
 *
 * `gen_libmh_inbound.py --check` is the drift gate. */
#ifndef LIBMH_HOST_IN_GEN_H
#define LIBMH_HOST_IN_GEN_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LIBMH_HOST_IN_VERSION 0x8777535Eu

/* ---- order ids (libmh_issue_order) ---------------------------------------------- */
/* Each id names an owned order-issuing body; argv carries that body's committed
 * parameters, in declaration order, widened to int32_t. libmh builds the 68-byte wire
 * record itself (orders/order_codec.h stays the single encoding), so a host names an
 * INTENT and never an encoding. */
#define LIBMH_ORD_BLDG_INSTANT_CONSTRUCT_FIND_SLOT                  0u /* llm_strat_bldg_instant_construct_find_slot, arity 5 */
#define LIBMH_ORD_BLDG_ORDER_ASSIGN_WORKERS                         1u /* llm_strat_bldg_order_assign_workers, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_DEPART_CONFIRM_DISPATCH                2u /* llm_strat_bldg_order_depart_confirm_dispatch, arity 0 */
#define LIBMH_ORD_BLDG_ORDER_DEPART_DISPATCH_BY_TYPE                3u /* llm_strat_bldg_order_depart_dispatch_by_type, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_FLUSH_CARGO_HOLD                       4u /* llm_strat_bldg_order_flush_cargo_hold, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_HANGAR_RECHARGE                        5u /* llm_strat_bldg_order_hangar_recharge, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_LOAD_PASSENGERS                        6u /* llm_strat_bldg_order_load_passengers, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_LOAD_RESOURCE                          7u /* llm_strat_bldg_order_load_resource, arity 4 */
#define LIBMH_ORD_BLDG_ORDER_PRODUCTION_ADD                         8u /* llm_strat_bldg_order_production_add, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_PRODUCTION_REMOVE                      9u /* llm_strat_bldg_order_production_remove, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_PURGE_DEAD_DOCKED                     10u /* llm_strat_bldg_order_purge_dead_docked, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_REPAIR_CYCLE_START                    11u /* llm_strat_bldg_order_repair_cycle_start, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_RESTART_CONSTRUCTION                  12u /* llm_strat_bldg_order_restart_construction, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_START_RESEARCH_PROJECT                13u /* llm_strat_bldg_order_start_research_project, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_TOGGLE_ACTIVE                         14u /* llm_strat_bldg_order_toggle_active, arity 2 */
#define LIBMH_ORD_BLDG_ORDER_UNASSIGN_WORKERS                      15u /* llm_strat_bldg_order_unassign_workers, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_UNLOAD_PASSENGERS                     16u /* llm_strat_bldg_order_unload_passengers, arity 3 */
#define LIBMH_ORD_BLDG_ORDER_UNLOAD_RESOURCE                       17u /* llm_strat_bldg_order_unload_resource, arity 4 */
#define LIBMH_ORD_BLDG_ORDER_UPGRADE                               18u /* llm_strat_bldg_order_upgrade, arity 2 */
#define LIBMH_ORD_GROUP_ISSUE_ATTACK_ORDER                         19u /* llm_strat_group_issue_attack_order, arity 3 */
#define LIBMH_ORD_GROUP_ISSUE_ENTER_BUILDING_ORDER                 20u /* llm_strat_group_issue_enter_building_order, arity 3 */
#define LIBMH_ORD_GROUP_ISSUE_MOVE_ORDER_CONFIRMED                 21u /* llm_strat_group_issue_move_order_confirmed, arity 2 */
#define LIBMH_ORD_GROUP_ISSUE_MOVE_ORDER_DEFERRED                  22u /* llm_strat_group_issue_move_order_deferred, arity 3 */
#define LIBMH_ORD_ORDER_COLLECT_AVAILABLE_PROJECTS                 23u /* llm_strat_order_collect_available_projects, arity 1 */
#define LIBMH_ORD_ORDER_CREATE_UNIT_DEBUG                          24u /* llm_strat_order_create_unit_debug, arity 4 */
#define LIBMH_ORD_ORDER_CREDIT_CONQUEST_KILLS                      25u /* llm_strat_order_credit_conquest_kills, arity 1 */
#define LIBMH_ORD_ORDER_CTRLGRP_FLASH_MEMBER                       26u /* llm_strat_order_ctrlgrp_flash_member, arity 3 */
#define LIBMH_ORD_ORDER_CTRLGRP_SELECT_MEMBER                      27u /* llm_strat_order_ctrlgrp_select_member, arity 3 */
#define LIBMH_ORD_ORDER_DEBUG_DAMAGE_SCALED                        28u /* llm_strat_order_debug_damage_scaled, arity 2 */
#define LIBMH_ORD_ORDER_DEBUG_ENERGY_REFILL_FULL                   29u /* llm_strat_order_debug_energy_refill_full, arity 2 */
#define LIBMH_ORD_ORDER_DEBUG_KILL_GROUP                           30u /* llm_strat_order_debug_kill_group, arity 2 */
#define LIBMH_ORD_ORDER_FOW_REVEAL_FULL                            31u /* llm_strat_order_fow_reveal_full, arity 1 */
#define LIBMH_ORD_ORDER_GRANT_RESOURCE                             32u /* llm_strat_order_grant_resource, arity 3 */
#define LIBMH_ORD_ORDER_POPULATION_DELTA_DEBUG                     33u /* llm_strat_order_population_delta_debug, arity 2 */
#define LIBMH_ORD_ORDER_QUEUE_CONSTRUCTION_DEBUG                   34u /* llm_strat_order_queue_construction_debug, arity 4 */
#define LIBMH_ORD_ORDER_RECHECK_BUILDINGS                          35u /* llm_strat_order_recheck_buildings, arity 1 */
#define LIBMH_ORD_ORDER_RECHECK_PLANET_SYSTEM_ALL_PLAYERS          36u /* llm_strat_order_recheck_planet_system_all_players, arity 0 */
#define LIBMH_ORD_ORDER_RECHECK_PROJECTS                           37u /* llm_strat_order_recheck_projects, arity 1 */
#define LIBMH_ORD_ORDER_SET_PLAYER_CONTROL_MODE                    38u /* llm_strat_order_set_player_control_mode, arity 3 */
#define LIBMH_ORD_ORDER_SET_PLAYER_RELATION                        39u /* llm_strat_order_set_player_relation, arity 3 */
#define LIBMH_ORD_TURRET_ORDER_TARGET_BUILDING                     40u /* llm_strat_turret_order_target_building, arity 4 */
#define LIBMH_ORD_TURRET_ORDER_TARGET_UNIT                         41u /* llm_strat_turret_order_target_unit, arity 4 */
#define LIBMH_ORD_UNIT_ORDER_AUTO_LAUNCH_FROM_STORAGE              42u /* llm_strat_unit_order_auto_launch_from_storage, arity 4 */
#define LIBMH_ORD_UNIT_ORDER_EXIT_STORAGE                          43u /* llm_strat_unit_order_exit_storage, arity 5 */
#define LIBMH_ORD_UNIT_ORDER_MOVE                                  44u /* llm_strat_unit_order_move, arity 5 */
#define LIBMH_ORD_UNIT_ORDER_MOVE_RELATIVE                         45u /* llm_strat_unit_order_move_relative, arity 4 */
#define LIBMH_ORD_UNIT_ORDER_DISEMBARK_SOLDIERS                    46u /* llm_unit_order_disembark_soldiers, arity 2 */
#define LIBMH_ORD_COUNT                                            47u

/* ---- entry ids (libmh_in_unbound / the trap) ------------------------------------ */
/* One per ENTRY this header owns, so the startup walk can report an entry whose
 * implementation is not wired BY NAME rather than letting it read as a working
 * entry that did nothing -- the hostapitest holey-table arm, applied to this
 * direction. Entries served by the REPLAY SPINE in libmh.h are listed below but
 * are NOT in this table: they are LIB-REF's to implement. */
#define LIBMH_IN_ENTRY_AMBIENT_RESEED                                0u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_BEGIN_PLACEMENT                          1u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_FINISH_CURRENT_ORDER                     2u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_FOOTPRINT_IS_CLEAR                       3u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_GET_COORDS                               4u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_INIT_ALL                                 5u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_IS_NETWORK_CRITICAL                      6u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_SHUTTLE_SLOT_IS_FREE                     7u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_SLOT_HAS_SOLDIERS                        8u /* 1 row */
#define LIBMH_IN_ENTRY_BLDG_USES_WORKERS                             9u /* 1 row */
#define LIBMH_IN_ENTRY_CLOCK_REBASE                                 10u /* 1 row */
#define LIBMH_IN_ENTRY_CLOCK_RELOAD_RESYNC                          11u /* 1 row */
#define LIBMH_IN_ENTRY_CLOCK_RESYNC_AND_TICK                        12u /* 1 row */
#define LIBMH_IN_ENTRY_CTRLGROUP_ADD_MEMBER                         13u /* 1 row */
#define LIBMH_IN_ENTRY_CTRLGROUP_ASSIGN                             14u /* 1 row */
#define LIBMH_IN_ENTRY_CTRLGROUP_CONTAINS                           15u /* 1 row */
#define LIBMH_IN_ENTRY_CTRLGROUP_REMOVE_MEMBER                      16u /* 1 row */
#define LIBMH_IN_ENTRY_DEPLOY_STARTING_SQUAD                        17u /* 1 row */
#define LIBMH_IN_ENTRY_ENTER_TACTICAL_MISSION                       18u /* 1 row */
#define LIBMH_IN_ENTRY_GAME_PLAYER_SET_HUMAN                        19u /* 1 row */
#define LIBMH_IN_ENTRY_INVASION_ALERTS_RESET                        20u /* 1 row */
#define LIBMH_IN_ENTRY_ISSUE_ORDER                                  21u /* 47 rows */
#define LIBMH_IN_ENTRY_LOCATE_ACTIVE_PORT                           22u /* 1 row */
#define LIBMH_IN_ENTRY_MAP_PIXEL_DELTA                              23u /* 1 row */
#define LIBMH_IN_ENTRY_MAP_TILE_DELTA                               24u /* 1 row */
#define LIBMH_IN_ENTRY_MAP_TILE_DIST                                25u /* 1 row */
#define LIBMH_IN_ENTRY_ORDER_ACK_VOICE                              26u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_DISTANCE                              27u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_DISTANCE_FACTOR                       28u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_MAP_SESSION_INIT                      29u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_SESSION_BEGIN                         30u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_SESSION_BEGIN_MULTI                   31u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_SWITCH                                32u /* 1 row */
#define LIBMH_IN_ENTRY_PLANET_TRANSITION_FINALIZE                   33u /* 1 row */
#define LIBMH_IN_ENTRY_PLAYER_INDEX_BY_SIDE                         34u /* 1 row */
#define LIBMH_IN_ENTRY_PLAYER_PRESENCE_LOST                         35u /* 1 row */
#define LIBMH_IN_ENTRY_POST_EVENT                                   36u /* 1 row */
#define LIBMH_IN_ENTRY_PROD_SET_TRANSFER_DESTINATION                37u /* 1 row */
#define LIBMH_IN_ENTRY_PROD_SHUTTLE_SLOT_SPAWN_ARRIVAL              38u /* 1 row */
#define LIBMH_IN_ENTRY_PROD_TRANSFER_PROGRESS                       39u /* 1 row */
#define LIBMH_IN_ENTRY_PROGRESS_RECHECK_ALL                         40u /* 1 row */
#define LIBMH_IN_ENTRY_SESSION_GLOBALS_RESET                        41u /* 2 rows */
#define LIBMH_IN_ENTRY_STORAGE_PURGE_DEAD_DOCKED                    42u /* 1 row */
#define LIBMH_IN_ENTRY_STRAT_MODE_INIT                              43u /* 5 rows */
#define LIBMH_IN_ENTRY_UNIT_GET_COORDS                              44u /* 1 row */
#define LIBMH_IN_ENTRY_UNIT_IS_BOARDING                             45u /* 1 row */
#define LIBMH_IN_ENTRY_COUNT                                        46u

/* Rows served by the replay spine already declared in libmh.h (LIB-REF owns
 * their implementation, so they are outside this table and its walk): */
/*   libmh_import_world                     4 rows */
/*   libmh_sim_step                         4 rows */
/*   libmh_submit_order                     1 row */

/* The entry's stable name, or NULL past the end -- what the walk and the trap print. */
const char *libmh_in_entry_name(uint32_t entry_id);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* LIBMH_HOST_IN_GEN_H */
