// GENERATED by tools/gen_order_issue_golden.py -- DO NOT HAND-EDIT.
#pragma once
#include <cstdint>
namespace mh::orders::issue::golden {

enum g_op : uint8_t {
    G_IMM = 0, G_PARAM, G_OR, G_OR8, G_AND, G_ADD, G_SUB, G_IMUL,
    G_SHL, G_SHR, G_SAR, G_MOVZX16, G_MOVZX8, G_MOVSX16, G_MOVSX8, G_UNKNOWN
};

// A value is a flat node array; the LAST node is the result. `a`/`b` are indices into the
// same array, or -1. For G_IMM the constant is in `imm`; for G_PARAM the parameter index is
// in `imm`; for binary ops with a constant operand, `b` is -1 and the constant is in `imm`.
struct g_node { uint8_t op; int8_t a; int8_t b; int32_t imm; };
struct g_val  { const g_node *nodes; uint8_t n; };          // n == 0 means "not present"
struct g_scratch { g_val index; g_val value; uint32_t at; };
struct g_site {
    const char *wrapper;  uint32_t wrapper_va;  uint32_t site_va;
    uint8_t lane;                      // 0 = replicated (dispatch), 1 = immediate (enqueue)
    bool after_branch;  bool scratch_reset_before;  bool dead;
    g_val unit_index, owner_and_kind, param0, order_code;
    const g_scratch *scratch;  uint8_t scratch_n;
};

static constexpr g_node N1[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N2[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N3[] = {{G_IMM, -1, -1, 128}};
static constexpr g_node N4[] = {{G_IMM, -1, -1, 128}};
static constexpr g_node N5[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N6[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N7[] = {{G_IMM, -1, -1, 126}};
static constexpr g_node N8[] = {{G_IMM, -1, -1, 126}};
static constexpr g_node N9[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N10[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N12[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N13[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N14[] = {{G_IMM, -1, -1, 131}};
static constexpr g_node N15[] = {{G_IMM, -1, -1, 131}};
static constexpr g_node N16[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N17[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N18[] = {{G_IMM, -1, -1, 131}};
static constexpr g_node N19[] = {{G_IMM, -1, -1, 131}};
static constexpr g_node N20[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N21[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N22[] = {{G_IMM, -1, -1, 214}};
static constexpr g_node N23[] = {{G_IMM, -1, -1, 214}};
static constexpr g_node N24[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N25[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N26[] = {{G_IMM, -1, -1, 214}};
static constexpr g_node N27[] = {{G_IMM, -1, -1, 214}};
static constexpr g_node N28[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N29[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N30[] = {{G_IMM, -1, -1, 129}};
static constexpr g_node N31[] = {{G_IMM, -1, -1, 129}};
static constexpr g_node N32[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N33[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N34[] = {{G_IMM, -1, -1, 129}};
static constexpr g_node N35[] = {{G_IMM, -1, -1, 129}};
static constexpr g_node N36[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N37[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N38[] = {{G_IMM, -1, -1, 223}};
static constexpr g_node N39[] = {{G_IMM, -1, -1, 223}};
static constexpr g_node N40[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N41[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N42[] = {{G_IMM, -1, -1, 223}};
static constexpr g_node N43[] = {{G_IMM, -1, -1, 223}};
static constexpr g_node N44[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N45[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N46[] = {{G_IMM, -1, -1, 121}};
static constexpr g_node N47[] = {{G_IMM, -1, -1, 121}};
static constexpr g_node N48[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N49[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N50[] = {{G_IMM, -1, -1, 121}};
static constexpr g_node N51[] = {{G_IMM, -1, -1, 121}};
static constexpr g_node N52[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N53[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N54[] = {{G_IMM, -1, -1, 219}};
static constexpr g_node N55[] = {{G_IMM, -1, -1, 219}};
static constexpr g_node N56[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N57[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N59[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N60[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N61[] = {{G_IMM, -1, -1, 219}};
static constexpr g_node N62[] = {{G_IMM, -1, -1, 219}};
static constexpr g_node N63[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N64[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N66[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N67[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N68[] = {{G_IMM, -1, -1, 221}};
static constexpr g_node N69[] = {{G_IMM, -1, -1, 221}};
static constexpr g_node N70[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N71[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N72[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N73[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N75[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N76[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N77[] = {{G_IMM, -1, -1, 221}};
static constexpr g_node N78[] = {{G_IMM, -1, -1, 221}};
static constexpr g_node N79[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N80[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N81[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N82[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N84[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N85[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N86[] = {{G_IMM, -1, -1, 116}};
static constexpr g_node N87[] = {{G_IMM, -1, -1, 116}};
static constexpr g_node N88[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N89[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N90[] = {{G_IMM, -1, -1, 116}};
static constexpr g_node N91[] = {{G_IMM, -1, -1, 116}};
static constexpr g_node N92[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N93[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N94[] = {{G_IMM, -1, -1, 212}};
static constexpr g_node N95[] = {{G_IMM, -1, -1, 212}};
static constexpr g_node N96[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N97[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N99[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N100[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N101[] = {{G_IMM, -1, -1, 212}};
static constexpr g_node N102[] = {{G_IMM, -1, -1, 212}};
static constexpr g_node N103[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N104[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N106[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N107[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N108[] = {{G_IMM, -1, -1, 211}};
static constexpr g_node N109[] = {{G_IMM, -1, -1, 211}};
static constexpr g_node N110[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N111[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N113[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N114[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N115[] = {{G_IMM, -1, -1, 211}};
static constexpr g_node N116[] = {{G_IMM, -1, -1, 211}};
static constexpr g_node N117[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N118[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N120[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N121[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N122[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N123[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N124[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N125[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N126[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N127[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N129[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N130[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N131[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N132[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N133[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N134[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N135[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N136[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N138[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N139[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N140[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N141[] = {{G_IMM, -1, -1, 109}};
static constexpr g_node N142[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N143[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N144[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N145[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N147[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N148[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N149[] = {{G_IMM, -1, -1, 111}};
static constexpr g_node N150[] = {{G_IMM, -1, -1, 111}};
static constexpr g_node N151[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N152[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N154[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N155[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N156[] = {{G_IMM, -1, -1, 111}};
static constexpr g_node N157[] = {{G_IMM, -1, -1, 111}};
static constexpr g_node N158[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N159[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N161[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N162[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N163[] = {{G_IMM, -1, -1, 230}};
static constexpr g_node N164[] = {{G_IMM, -1, -1, 230}};
static constexpr g_node N165[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N166[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N167[] = {{G_IMM, -1, -1, 230}};
static constexpr g_node N168[] = {{G_IMM, -1, -1, 230}};
static constexpr g_node N169[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N170[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N171[] = {{G_IMM, -1, -1, 106}};
static constexpr g_node N172[] = {{G_IMM, -1, -1, 106}};
static constexpr g_node N173[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N174[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N175[] = {{G_IMM, -1, -1, 107}};
static constexpr g_node N176[] = {{G_IMM, -1, -1, 107}};
static constexpr g_node N177[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N178[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N179[] = {{G_IMM, -1, -1, 210}};
static constexpr g_node N180[] = {{G_IMM, -1, -1, 210}};
static constexpr g_node N181[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N182[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N184[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N185[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N186[] = {{G_IMM, -1, -1, 210}};
static constexpr g_node N187[] = {{G_IMM, -1, -1, 210}};
static constexpr g_node N188[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N189[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N191[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N192[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N193[] = {{G_IMM, -1, -1, 137}};
static constexpr g_node N194[] = {{G_IMM, -1, -1, 137}};
static constexpr g_node N195[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N196[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N198[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N199[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N200[] = {{G_IMM, -1, -1, 137}};
static constexpr g_node N201[] = {{G_IMM, -1, -1, 137}};
static constexpr g_node N202[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N203[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N205[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N206[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N207[] = {{G_IMM, -1, -1, 127}};
static constexpr g_node N208[] = {{G_IMM, -1, -1, 127}};
static constexpr g_node N209[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N210[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N212[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N213[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N214[] = {{G_IMM, -1, -1, 220}};
static constexpr g_node N215[] = {{G_IMM, -1, -1, 220}};
static constexpr g_node N216[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N217[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N219[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N220[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N221[] = {{G_IMM, -1, -1, 220}};
static constexpr g_node N222[] = {{G_IMM, -1, -1, 220}};
static constexpr g_node N223[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N224[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N226[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N227[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N228[] = {{G_IMM, -1, -1, 222}};
static constexpr g_node N229[] = {{G_IMM, -1, -1, 222}};
static constexpr g_node N230[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N231[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N232[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N233[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N235[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N236[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N237[] = {{G_IMM, -1, -1, 222}};
static constexpr g_node N238[] = {{G_IMM, -1, -1, 222}};
static constexpr g_node N239[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N240[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N241[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N242[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N244[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N245[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N246[] = {{G_IMM, -1, -1, 130}};
static constexpr g_node N247[] = {{G_IMM, -1, -1, 130}};
static constexpr g_node N248[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N249[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N250[] = {{G_IMM, -1, -1, 238}};
static constexpr g_node N251[] = {{G_IMM, -1, -1, 238}};
static constexpr g_node N252[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N253[] = {{G_PARAM, -1, -1, 3}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N254[] = {{G_IMM, -1, -1, 235}};
static constexpr g_node N255[] = {{G_IMM, -1, -1, 235}};
static constexpr g_node N256[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N257[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N258[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N259[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N260[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N261[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N263[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N264[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N265[] = {{G_IMM, -1, -1, 250}};
static constexpr g_node N266[] = {{G_IMM, -1, -1, 250}};
static constexpr g_node N267[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N268[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N269[] = {{G_IMM, -1, -1, 250}};
static constexpr g_node N270[] = {{G_IMM, -1, -1, 250}};
static constexpr g_node N271[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N272[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N273[] = {{G_IMM, -1, -1, 53}};
static constexpr g_node N274[] = {{G_IMM, -1, -1, 53}};
static constexpr g_node N275[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N276[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N278[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N279[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N280[] = {{G_IMM, -1, -1, 52}};
static constexpr g_node N281[] = {{G_IMM, -1, -1, 52}};
static constexpr g_node N282[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N283[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N285[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N286[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N287[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N288[] = {{G_IMM, -1, -1, 248}};
static constexpr g_node N289[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N290[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N291[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N292[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N294[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N295[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N296[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N297[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N298[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N299[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N300[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N301[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N303[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N304[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N305[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N306[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N307[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N308[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N309[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N310[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N312[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N313[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N314[] = {{G_IMM, -1, -1, 246}};
static constexpr g_node N315[] = {{G_IMM, -1, -1, 246}};
static constexpr g_node N316[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N317[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N318[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N319[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N321[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N322[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N323[] = {{G_IMM, -1, -1, 246}};
static constexpr g_node N324[] = {{G_IMM, -1, -1, 246}};
static constexpr g_node N325[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N326[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N327[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N328[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N330[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N331[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N332[] = {{G_IMM, -1, -1, 247}};
static constexpr g_node N333[] = {{G_IMM, -1, -1, 248}};
static constexpr g_node N334[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N335[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N336[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N337[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N339[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N340[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N341[] = {{G_IMM, -1, -1, 231}};
static constexpr g_node N342[] = {{G_IMM, -1, -1, 231}};
static constexpr g_node N343[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N344[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N345[] = {{G_IMM, -1, -1, 231}};
static constexpr g_node N346[] = {{G_IMM, -1, -1, 231}};
static constexpr g_node N347[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N348[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N349[] = {{G_IMM, -1, -1, 249}};
static constexpr g_node N350[] = {{G_IMM, -1, -1, 249}};
static constexpr g_node N351[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N352[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N354[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N355[] = {{G_PARAM, -1, -1, 0}, {G_AND, 0, -1, 15}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N356[] = {{G_IMM, -1, -1, 249}};
static constexpr g_node N357[] = {{G_IMM, -1, -1, 249}};
static constexpr g_node N358[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N359[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N361[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N362[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N363[] = {{G_IMM, -1, -1, 233}};
static constexpr g_node N364[] = {{G_IMM, -1, -1, 233}};
static constexpr g_node N365[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N366[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N367[] = {{G_IMM, -1, -1, 233}};
static constexpr g_node N368[] = {{G_IMM, -1, -1, 233}};
static constexpr g_node N369[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N370[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N371[] = {{G_IMM, -1, -1, 232}};
static constexpr g_node N372[] = {{G_IMM, -1, -1, 232}};
static constexpr g_node N373[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N374[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N375[] = {{G_IMM, -1, -1, 232}};
static constexpr g_node N376[] = {{G_IMM, -1, -1, 232}};
static constexpr g_node N377[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N378[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N379[] = {{G_IMM, -1, -1, 237}};
static constexpr g_node N380[] = {{G_IMM, -1, -1, 237}};
static constexpr g_node N381[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N382[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N383[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N384[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N386[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N387[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N388[] = {{G_IMM, -1, -1, 213}};
static constexpr g_node N389[] = {{G_IMM, -1, -1, 213}};
static constexpr g_node N390[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N391[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N392[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N393[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N395[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N396[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N397[] = {{G_IMM, -1, -1, 213}};
static constexpr g_node N398[] = {{G_IMM, -1, -1, 213}};
static constexpr g_node N399[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N400[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N401[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N402[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N404[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N405[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N406[] = {{G_IMM, -1, -1, 15}};
static constexpr g_node N407[] = {{G_IMM, -1, -1, 54}};
static constexpr g_node N408[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N409[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N410[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N411[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N413[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N414[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N415[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N416[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N417[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N418[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N419[] = {{G_IMM, -1, -1, 236}};
static constexpr g_node N420[] = {{G_IMM, -1, -1, 236}};
static constexpr g_node N421[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N422[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N424[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N425[] = {{G_PARAM, -1, -1, 3}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N426[] = {{G_IMM, -1, -1, 242}};
static constexpr g_node N427[] = {{G_IMM, -1, -1, 242}};
static constexpr g_node N428[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N429[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N430[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N431[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N432[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N433[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N435[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N436[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N437[] = {{G_IMM, -1, -1, 239}};
static constexpr g_node N438[] = {{G_IMM, -1, -1, 239}};
static constexpr g_node N439[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N440[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N441[] = {{G_IMM, -1, -1, 239}};
static constexpr g_node N442[] = {{G_IMM, -1, -1, 239}};
static constexpr g_node N443[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N444[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N445[] = {{G_IMM, -1, -1, 241}};
static constexpr g_node N446[] = {{G_IMM, -1, -1, 241}};
static constexpr g_node N447[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N448[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N449[] = {{G_IMM, -1, -1, 241}};
static constexpr g_node N450[] = {{G_IMM, -1, -1, 241}};
static constexpr g_node N451[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N452[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N453[] = {{G_IMM, -1, -1, 240}};
static constexpr g_node N454[] = {{G_IMM, -1, -1, 240}};
static constexpr g_node N455[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N456[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N457[] = {{G_IMM, -1, -1, 240}};
static constexpr g_node N458[] = {{G_IMM, -1, -1, 240}};
static constexpr g_node N459[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N460[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N461[] = {{G_IMM, -1, -1, 243}};
static constexpr g_node N462[] = {{G_IMM, -1, -1, 243}};
static constexpr g_node N463[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N464[] = {{G_PARAM, -1, -1, 0}};
static constexpr g_node N466[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N467[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N468[] = {{G_IMM, -1, -1, 245}};
static constexpr g_node N469[] = {{G_IMM, -1, -1, 245}};
static constexpr g_node N470[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N471[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N472[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N473[] = {{G_PARAM, -1, -1, 2}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N475[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N476[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N477[] = {{G_IMM, -1, -1, 245}};
static constexpr g_node N478[] = {{G_IMM, -1, -1, 245}};
static constexpr g_node N479[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N480[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N481[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N482[] = {{G_PARAM, -1, -1, 2}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N484[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N485[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N486[] = {{G_IMM, -1, -1, 244}};
static constexpr g_node N487[] = {{G_IMM, -1, -1, 244}};
static constexpr g_node N488[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N489[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N490[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N491[] = {{G_PARAM, -1, -1, 2}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N493[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N494[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N495[] = {{G_IMM, -1, -1, 244}};
static constexpr g_node N496[] = {{G_IMM, -1, -1, 244}};
static constexpr g_node N497[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N498[] = {{G_PARAM, -1, -1, 1}};
static constexpr g_node N499[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N500[] = {{G_PARAM, -1, -1, 2}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N502[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N503[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N504[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N505[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N506[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N507[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 64}};
static constexpr g_node N508[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N509[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N511[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N512[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N513[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N514[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N515[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N516[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 64}};
static constexpr g_node N517[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N518[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N520[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N521[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N522[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N523[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N524[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N525[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}};
static constexpr g_node N526[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N527[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N529[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N530[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N531[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N532[] = {{G_IMM, -1, -1, 123}};
static constexpr g_node N533[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N534[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}};
static constexpr g_node N535[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N536[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N538[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N539[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N540[] = {{G_IMM, -1, -1, 29}};
static constexpr g_node N541[] = {{G_IMM, -1, -1, 29}};
static constexpr g_node N542[] = {{G_IMM, -1, -1, 8}};
static constexpr g_node N543[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N544[] = {{G_IMM, -1, -1, 9}};
static constexpr g_node N545[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N546[] = {{G_IMM, -1, -1, 10}};
static constexpr g_node N547[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N548[] = {{G_IMM, -1, -1, 11}};
static constexpr g_node N549[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N550[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N551[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N553[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N554[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N555[] = {{G_IMM, -1, -1, 28}};
static constexpr g_node N556[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N557[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N558[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N559[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N560[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N561[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N562[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N563[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N564[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N565[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N566[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N567[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N568[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N569[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N570[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N572[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N573[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N574[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N575[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N576[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N577[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N578[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N579[] = {{G_IMM, -1, -1, 28}};
static constexpr g_node N580[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N581[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N582[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N583[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N584[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N585[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N586[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N587[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N589[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N590[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N591[] = {{G_IMM, -1, -1, 28}};
static constexpr g_node N592[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N593[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N594[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N595[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N596[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N597[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N598[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N599[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N600[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N601[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N602[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 64}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N603[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N604[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N605[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N606[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}};
static constexpr g_node N608[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N609[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N610[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N611[] = {{G_IMM, -1, -1, 28}};
static constexpr g_node N612[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N613[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N614[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N615[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N616[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N617[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N618[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N619[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N621[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N622[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N623[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N624[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N625[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N626[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N627[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N628[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N629[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N630[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N631[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N632[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N633[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N634[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N635[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N636[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N637[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N638[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N640[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N641[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N642[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N643[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N644[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N645[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N646[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N647[] = {{G_IMM, -1, -1, 46}};
static constexpr g_node N648[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N649[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N650[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N651[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N652[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N653[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N654[] = {{G_IMM, -1, -1, 27}};
static constexpr g_node N655[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N656[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N657[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N658[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N659[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N660[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N661[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N662[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N663[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N664[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N665[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N666[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N667[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N668[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N669[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N671[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N672[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N673[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N674[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N675[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N676[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N677[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N678[] = {{G_IMM, -1, -1, 46}};
static constexpr g_node N679[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N680[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N681[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N682[] = {{G_IMM, -1, -1, 27}};
static constexpr g_node N683[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N684[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N685[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N686[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N687[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N688[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N689[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N690[] = {{G_UNKNOWN, -1, -1, 0}, {G_SAR, 0, -1, 5}};
static constexpr g_node N691[] = {{G_IMM, -1, -1, 3}};
static constexpr g_node N692[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N693[] = {{G_IMM, -1, -1, 4}};
static constexpr g_node N694[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N695[] = {{G_IMM, -1, -1, 5}};
static constexpr g_node N696[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N697[] = {{G_IMM, -1, -1, 6}};
static constexpr g_node N698[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N700[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N701[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N702[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N703[] = {{G_IMM, -1, -1, 26}};
static constexpr g_node N704[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N705[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N706[] = {{G_IMM, -1, -1, 30}};
static constexpr g_node N707[] = {{G_IMM, -1, -1, 30}};
static constexpr g_node N708[] = {{G_IMM, -1, -1, 8}};
static constexpr g_node N709[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N710[] = {{G_IMM, -1, -1, 9}};
static constexpr g_node N711[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N712[] = {{G_IMM, -1, -1, 10}};
static constexpr g_node N713[] = {{G_PARAM, -1, -1, 2}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N714[] = {{G_IMM, -1, -1, 11}};
static constexpr g_node N715[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N716[] = {{G_IMM, -1, -1, 7}};
static constexpr g_node N717[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N719[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N720[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N721[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N722[] = {{G_IMM, -1, -1, 32}};
static constexpr g_node N723[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N724[] = {{G_UNKNOWN, -1, -1, 0}, {G_ADD, 0, -1, 2}, {G_UNKNOWN, -1, -1, 0}, {G_AND, 1, 2, 0}};
static constexpr g_node N725[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N726[] = {{G_UNKNOWN, -1, -1, 0}, {G_ADD, 0, -1, 2}, {G_UNKNOWN, -1, -1, 0}, {G_AND, 1, 2, 0}};
static constexpr g_node N727[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N728[] = {{G_PARAM, -1, -1, 2}, {G_UNKNOWN, -1, -1, 0}, {G_AND, 0, 1, 0}};
static constexpr g_node N729[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N730[] = {{G_PARAM, -1, -1, 3}, {G_UNKNOWN, -1, -1, 0}, {G_AND, 0, 1, 0}};
static constexpr g_node N732[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N733[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N734[] = {{G_IMM, -1, -1, 31}};
static constexpr g_node N735[] = {{G_IMM, -1, -1, 35}};
static constexpr g_node N736[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N737[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N738[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N739[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N740[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N741[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N742[] = {{G_IMM, -1, -1, 36}};
static constexpr g_node N743[] = {{G_IMM, -1, -1, 56}};
static constexpr g_node N744[] = {{G_IMM, -1, -1, 2}};
static constexpr g_node N745[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N746[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N747[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N748[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N749[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N751[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N752[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N753[] = {{G_IMM, -1, -1, 41}};
static constexpr g_node N754[] = {{G_IMM, -1, -1, 11}};
static constexpr g_node N755[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N756[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N757[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N758[] = {{G_UNKNOWN, -1, -1, 0}};
static constexpr g_node N760[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N761[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N762[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N763[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N764[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N765[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N766[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N767[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N768[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N769[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N770[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N771[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N772[] = {{G_IMM, -1, -1, 12}};
static constexpr g_node N773[] = {{G_PARAM, -1, -1, 4}};
static constexpr g_node N775[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N776[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N777[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N778[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N779[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N780[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N781[] = {{G_IMM, -1, -1, 24}};
static constexpr g_node N782[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N783[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N784[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N785[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N786[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N788[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N789[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N790[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N791[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N792[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N793[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N794[] = {{G_IMM, -1, -1, 16}};
static constexpr g_node N795[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N796[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N797[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N798[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N799[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N800[] = {{G_IMM, -1, -1, 12}};
static constexpr g_node N801[] = {{G_PARAM, -1, -1, 4}};
static constexpr g_node N803[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N804[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N805[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N806[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N807[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N808[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N809[] = {{G_IMM, -1, -1, 16}};
static constexpr g_node N810[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N811[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N812[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N813[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N814[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N815[] = {{G_IMM, -1, -1, 12}};
static constexpr g_node N816[] = {{G_PARAM, -1, -1, 4}};
static constexpr g_node N818[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N819[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N820[] = {{G_IMM, -1, -1, 51}};
static constexpr g_node N821[] = {{G_IMM, -1, -1, 10}};
static constexpr g_node N822[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N823[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N824[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N825[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N827[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N828[] = {{G_PARAM, -1, -1, 0}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N829[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N830[] = {{G_IMM, -1, -1, 251}};
static constexpr g_node N831[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N832[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N833[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N834[] = {{G_IMM, -1, -1, 51}};
static constexpr g_node N835[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N836[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N837[] = {{G_IMM, -1, -1, 51}};
static constexpr g_node N838[] = {{G_IMM, -1, -1, 10}};
static constexpr g_node N839[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N840[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N841[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N842[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N844[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N845[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N846[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N847[] = {{G_IMM, -1, -1, 51}};
static constexpr g_node N848[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N849[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N850[] = {{G_IMM, -1, -1, 16}};
static constexpr g_node N851[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N852[] = {{G_IMM, -1, -1, 0}};
static constexpr g_node N853[] = {{G_PARAM, -1, -1, 2}};
static constexpr g_node N854[] = {{G_IMM, -1, -1, 1}};
static constexpr g_node N855[] = {{G_PARAM, -1, -1, 3}};
static constexpr g_node N857[] = {{G_PARAM, -1, -1, 1}, {G_MOVZX16, 0, -1, 0}};
static constexpr g_node N858[] = {{G_PARAM, -1, -1, 0}, {G_OR8, 0, -1, 128}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N859[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_node N860[] = {{G_UNKNOWN, -1, -1, 0}, {G_MOVZX8, 0, -1, 0}, {G_MOVZX16, 1, -1, 0}};
static constexpr g_scratch SC11[] = {{{N9, 1}, {N10, 1}, 4644829u}};
static constexpr g_scratch SC58[] = {{{N56, 1}, {N57, 1}, 4647619u}};
static constexpr g_scratch SC65[] = {{{N63, 1}, {N64, 1}, 4647698u}};
static constexpr g_scratch SC74[] = {{{N70, 1}, {N71, 1}, 4647937u}, {{N72, 1}, {N73, 1}, 4647950u}};
static constexpr g_scratch SC83[] = {{{N79, 1}, {N80, 1}, 4648030u}, {{N81, 1}, {N82, 1}, 4648043u}};
static constexpr g_scratch SC98[] = {{{N96, 1}, {N97, 1}, 4648465u}};
static constexpr g_scratch SC105[] = {{{N103, 1}, {N104, 1}, 4648544u}};
static constexpr g_scratch SC112[] = {{{N110, 1}, {N111, 1}, 4648307u}};
static constexpr g_scratch SC119[] = {{{N117, 1}, {N118, 1}, 4648386u}};
static constexpr g_scratch SC128[] = {{{N124, 1}, {N125, 1}, 4643617u}, {{N126, 1}, {N127, 1}, 4643632u}};
static constexpr g_scratch SC137[] = {{{N133, 1}, {N134, 1}, 4643859u}, {{N135, 1}, {N136, 1}, 4643872u}};
static constexpr g_scratch SC146[] = {{{N142, 1}, {N143, 1}, 4643978u}, {{N144, 1}, {N145, 1}, 4643991u}};
static constexpr g_scratch SC153[] = {{{N151, 1}, {N152, 1}, 4644095u}};
static constexpr g_scratch SC160[] = {{{N158, 1}, {N159, 1}, 4644200u}};
static constexpr g_scratch SC183[] = {{{N181, 1}, {N182, 1}, 4647015u}};
static constexpr g_scratch SC190[] = {{{N188, 1}, {N189, 1}, 4647094u}};
static constexpr g_scratch SC197[] = {{{N195, 1}, {N196, 1}, 4649319u}};
static constexpr g_scratch SC204[] = {{{N202, 1}, {N203, 1}, 4649398u}};
static constexpr g_scratch SC211[] = {{{N209, 1}, {N210, 1}, 4644987u}};
static constexpr g_scratch SC218[] = {{{N216, 1}, {N217, 1}, 4647777u}};
static constexpr g_scratch SC225[] = {{{N223, 1}, {N224, 1}, 4647856u}};
static constexpr g_scratch SC234[] = {{{N230, 1}, {N231, 1}, 4648123u}, {{N232, 1}, {N233, 1}, 4648136u}};
static constexpr g_scratch SC243[] = {{{N239, 1}, {N240, 1}, 4648216u}, {{N241, 1}, {N242, 1}, 4648229u}};
static constexpr g_scratch SC262[] = {{{N256, 1}, {N257, 1}, 4642862u}, {{N258, 1}, {N259, 1}, 4642875u}, {{N260, 1}, {N261, 1}, 4642888u}};
static constexpr g_scratch SC277[] = {{{N275, 1}, {N276, 1}, 4649710u}};
static constexpr g_scratch SC284[] = {{{N282, 1}, {N283, 1}, 4649556u}};
static constexpr g_scratch SC293[] = {{{N289, 1}, {N290, 1}, 4652201u}, {{N291, 1}, {N292, 1}, 4652214u}};
static constexpr g_scratch SC302[] = {{{N298, 1}, {N299, 1}, 4652007u}, {{N300, 1}, {N301, 1}, 4652020u}};
static constexpr g_scratch SC311[] = {{{N307, 1}, {N308, 1}, 4651910u}, {{N309, 1}, {N310, 1}, 4651923u}};
static constexpr g_scratch SC320[] = {{{N316, 1}, {N317, 1}, 4651716u}, {{N318, 1}, {N319, 1}, 4651729u}};
static constexpr g_scratch SC329[] = {{{N325, 1}, {N326, 1}, 4651813u}, {{N327, 1}, {N328, 1}, 4651826u}};
static constexpr g_scratch SC338[] = {{{N334, 1}, {N335, 1}, 4652104u}, {{N336, 1}, {N337, 1}, 4652117u}};
static constexpr g_scratch SC353[] = {{{N351, 1}, {N352, 1}, 4652296u}};
static constexpr g_scratch SC360[] = {{{N358, 1}, {N359, 1}, 4652379u}};
static constexpr g_scratch SC385[] = {{{N381, 1}, {N382, 1}, 4650339u}, {{N383, 1}, {N384, 1}, 4650352u}};
static constexpr g_scratch SC394[] = {{{N390, 1}, {N391, 1}, 4647175u}, {{N392, 1}, {N393, 1}, 4647188u}};
static constexpr g_scratch SC403[] = {{{N399, 1}, {N400, 1}, 4647268u}, {{N401, 1}, {N402, 1}, 4647281u}};
static constexpr g_scratch SC412[] = {{{N408, 1}, {N409, 1}, 4629180u}, {{N410, 1}, {N411, 1}, 4629193u}};
static constexpr g_scratch SC423[] = {{{N421, 1}, {N422, 1}, 4650519u}};
static constexpr g_scratch SC434[] = {{{N428, 1}, {N429, 1}, 4643374u}, {{N430, 1}, {N431, 1}, 4643387u}, {{N432, 1}, {N433, 1}, 4643397u}};
static constexpr g_scratch SC465[] = {{{N463, 1}, {N464, 1}, 4643196u}};
static constexpr g_scratch SC474[] = {{{N470, 1}, {N471, 1}, 4651434u}, {{N472, 1}, {N473, 2}, 4651448u}};
static constexpr g_scratch SC483[] = {{{N479, 1}, {N480, 1}, 4651626u}, {{N481, 1}, {N482, 2}, 4651640u}};
static constexpr g_scratch SC492[] = {{{N488, 1}, {N489, 1}, 4651250u}, {{N490, 1}, {N491, 2}, 4651264u}};
static constexpr g_scratch SC501[] = {{{N497, 1}, {N498, 1}, 4651342u}, {{N499, 1}, {N500, 2}, 4651356u}};
static constexpr g_scratch SC510[] = {{{N506, 1}, {N507, 2}, 4644476u}, {{N508, 1}, {N509, 1}, 4644489u}};
static constexpr g_scratch SC519[] = {{{N515, 1}, {N516, 2}, 4644572u}, {{N517, 1}, {N518, 1}, 4644585u}};
static constexpr g_scratch SC528[] = {{{N524, 1}, {N525, 2}, 4644284u}, {{N526, 1}, {N527, 1}, 4644297u}};
static constexpr g_scratch SC537[] = {{{N533, 1}, {N534, 2}, 4644380u}, {{N535, 1}, {N536, 1}, 4644393u}};
static constexpr g_scratch SC552[] = {{{N542, 1}, {N543, 1}, 4638526u}, {{N544, 1}, {N545, 1}, 4638539u}, {{N546, 1}, {N547, 3}, 4638557u}, {{N548, 1}, {N549, 1}, 4638570u}, {{N550, 1}, {N551, 2}, 4638583u}};
static constexpr g_scratch SC571[] = {{{N557, 1}, {N558, 2}, 4636680u}, {{N559, 1}, {N560, 2}, 4636711u}, {{N561, 1}, {N562, 1}, 4636724u}, {{N563, 1}, {N564, 1}, 4636737u}, {{N565, 1}, {N566, 3}, 4636755u}, {{N567, 1}, {N568, 1}, 4636768u}, {{N569, 1}, {N570, 2}, 4636781u}};
static constexpr g_scratch SC588[] = {{{N580, 1}, {N581, 2}, 4637114u}, {{N582, 1}, {N583, 2}, 4637145u}, {{N584, 1}, {N585, 1}, 4637158u}, {{N586, 1}, {N587, 1}, 4637171u}};
static constexpr g_scratch SC607[] = {{{N593, 1}, {N594, 2}, 4637917u}, {{N595, 1}, {N596, 2}, 4637948u}, {{N597, 1}, {N598, 1}, 4637961u}, {{N599, 1}, {N600, 1}, 4637974u}, {{N601, 1}, {N602, 3}, 4637992u}, {{N603, 1}, {N604, 1}, 4638005u}, {{N605, 1}, {N606, 2}, 4638018u}};
static constexpr g_scratch SC620[] = {{{N612, 1}, {N613, 2}, 4638308u}, {{N614, 1}, {N615, 2}, 4638339u}, {{N616, 1}, {N617, 1}, 4638352u}, {{N618, 1}, {N619, 1}, 4638365u}};
static constexpr g_scratch SC639[] = {{{N625, 1}, {N626, 2}, 4632500u}, {{N627, 1}, {N628, 2}, 4632531u}, {{N629, 1}, {N630, 1}, 4632544u}, {{N631, 1}, {N632, 1}, 4632557u}, {{N633, 1}, {N634, 3}, 4632575u}, {{N635, 1}, {N636, 1}, 4632588u}, {{N637, 1}, {N638, 1}, 4632601u}};
static constexpr g_scratch SC670[] = {{{N656, 1}, {N657, 2}, 4634159u}, {{N658, 1}, {N659, 2}, 4634190u}, {{N660, 1}, {N661, 1}, 4634203u}, {{N662, 1}, {N663, 1}, 4634216u}, {{N664, 1}, {N665, 3}, 4634234u}, {{N666, 1}, {N667, 1}, 4634247u}, {{N668, 1}, {N669, 1}, 4634260u}};
static constexpr g_scratch SC699[] = {{{N687, 1}, {N688, 2}, 4636213u}, {{N689, 1}, {N690, 2}, 4636244u}, {{N691, 1}, {N692, 1}, 4636257u}, {{N693, 1}, {N694, 1}, 4636270u}, {{N695, 1}, {N696, 3}, 4636288u}, {{N697, 1}, {N698, 1}, 4636301u}};
static constexpr g_scratch SC718[] = {{{N708, 1}, {N709, 1}, 4635803u}, {{N710, 1}, {N711, 1}, 4635816u}, {{N712, 1}, {N713, 3}, 4635834u}, {{N714, 1}, {N715, 1}, 4635847u}, {{N716, 1}, {N717, 1}, 4635860u}};
static constexpr g_scratch SC731[] = {{{N723, 1}, {N724, 4}, 4640335u}, {{N725, 1}, {N726, 4}, 4640379u}, {{N727, 1}, {N728, 3}, 4640397u}, {{N729, 1}, {N730, 3}, 4640416u}};
static constexpr g_scratch SC750[] = {{{N744, 1}, {N745, 1}, 4630442u}, {{N746, 1}, {N747, 1}, 4630493u}, {{N748, 1}, {N749, 1}, 4630506u}};
static constexpr g_scratch SC759[] = {{{N755, 1}, {N756, 1}, 4630640u}, {{N757, 1}, {N758, 1}, 4630653u}};
static constexpr g_scratch SC774[] = {{{N768, 1}, {N769, 1}, 4628497u}, {{N770, 1}, {N771, 1}, 4628510u}, {{N772, 1}, {N773, 1}, 4628523u}};
static constexpr g_scratch SC787[] = {{{N783, 1}, {N784, 1}, 4631802u}, {{N785, 1}, {N786, 1}, 4631815u}};
static constexpr g_scratch SC802[] = {{{N796, 1}, {N797, 1}, 4629549u}, {{N798, 1}, {N799, 1}, 4629562u}, {{N800, 1}, {N801, 1}, 4629575u}};
static constexpr g_scratch SC817[] = {{{N811, 1}, {N812, 1}, 4629750u}, {{N813, 1}, {N814, 1}, 4629763u}, {{N815, 1}, {N816, 1}, 4629776u}};
static constexpr g_scratch SC826[] = {{{N822, 1}, {N823, 1}, 4638972u}, {{N824, 1}, {N825, 1}, 4638985u}};
static constexpr g_scratch SC843[] = {{{N839, 1}, {N840, 1}, 4639263u}, {{N841, 1}, {N842, 1}, 4639276u}};
static constexpr g_scratch SC856[] = {{{N852, 1}, {N853, 1}, 4630097u}, {{N854, 1}, {N855, 1}, 4630110u}};
inline constexpr g_site SITES[] = {
    {"llm_strat_bldg_order_activate", 4645106u, 4645157u, 0, false, false, false, {N1, 2}, {N2, 3}, {N3, 1}, {N4, 1}, nullptr, 0},
    {"llm_strat_bldg_order_assign_workers", 4644790u, 4644856u, 0, false, false, false, {N5, 2}, {N6, 3}, {N7, 1}, {N8, 1}, SC11, 1},
    {"llm_strat_bldg_order_cancel_reset", 4646244u, 4646295u, 0, false, false, true, {N12, 2}, {N13, 3}, {N14, 1}, {N15, 1}, nullptr, 0},
    {"llm_strat_bldg_order_cancel_reset_enqueue", 4646309u, 4646360u, 1, false, false, true, {N16, 2}, {N17, 3}, {N18, 1}, {N19, 1}, nullptr, 0},
    {"llm_strat_bldg_order_cargo_bind_slot", 4647320u, 4647371u, 0, false, false, true, {N20, 2}, {N21, 3}, {N22, 1}, {N23, 1}, nullptr, 0},
    {"llm_strat_bldg_order_cargo_bind_slot_enqueue", 4647385u, 4647436u, 1, false, false, true, {N24, 2}, {N25, 3}, {N26, 1}, {N27, 1}, nullptr, 0},
    {"llm_strat_bldg_order_deactivate", 4645236u, 4645287u, 0, false, false, false, {N28, 2}, {N29, 3}, {N30, 1}, {N31, 1}, nullptr, 0},
    {"llm_strat_bldg_order_deactivate_enqueue", 4645301u, 4645352u, 1, false, false, false, {N32, 2}, {N33, 3}, {N34, 1}, {N35, 1}, nullptr, 0},
    {"llm_strat_bldg_order_flush_cargo_hold", 4647450u, 4647501u, 0, false, false, false, {N36, 2}, {N37, 3}, {N38, 1}, {N39, 1}, nullptr, 0},
    {"llm_strat_bldg_order_flush_cargo_hold_enqueue", 4647515u, 4647566u, 1, false, false, true, {N40, 2}, {N41, 3}, {N42, 1}, {N43, 1}, nullptr, 0},
    {"llm_strat_bldg_order_hangar_recharge", 4646114u, 4646165u, 0, false, false, false, {N44, 2}, {N45, 3}, {N46, 1}, {N47, 1}, nullptr, 0},
    {"llm_strat_bldg_order_hangar_recharge_enqueue", 4646179u, 4646230u, 1, false, false, true, {N48, 2}, {N49, 3}, {N50, 1}, {N51, 1}, nullptr, 0},
    {"llm_strat_bldg_order_load_passengers", 4647580u, 4647646u, 0, false, false, false, {N52, 2}, {N53, 3}, {N54, 1}, {N55, 1}, SC58, 1},
    {"llm_strat_bldg_order_load_passengers_enqueue", 4647659u, 4647725u, 1, false, false, true, {N59, 2}, {N60, 3}, {N61, 1}, {N62, 1}, SC65, 1},
    {"llm_strat_bldg_order_load_resource", 4647896u, 4647977u, 0, false, false, false, {N66, 2}, {N67, 3}, {N68, 1}, {N69, 1}, SC74, 2},
    {"llm_strat_bldg_order_load_resource_enqueue", 4647989u, 4648070u, 1, false, false, true, {N75, 2}, {N76, 3}, {N77, 1}, {N78, 1}, SC83, 2},
    {"llm_strat_bldg_order_mine_rescan", 4646504u, 4646555u, 0, false, false, true, {N84, 2}, {N85, 3}, {N86, 1}, {N87, 1}, nullptr, 0},
    {"llm_strat_bldg_order_mine_rescan_enqueue", 4646569u, 4646620u, 1, false, false, true, {N88, 2}, {N89, 3}, {N90, 1}, {N91, 1}, nullptr, 0},
    {"llm_strat_bldg_order_mother_depart", 4648426u, 4648492u, 0, false, false, false, {N92, 2}, {N93, 3}, {N94, 1}, {N95, 1}, SC98, 1},
    {"llm_strat_bldg_order_mother_depart_enqueue", 4648505u, 4648571u, 1, false, false, false, {N99, 2}, {N100, 3}, {N101, 1}, {N102, 1}, SC105, 1},
    {"llm_strat_bldg_order_port_depart", 4648268u, 4648334u, 0, false, false, false, {N106, 2}, {N107, 3}, {N108, 1}, {N109, 1}, SC112, 1},
    {"llm_strat_bldg_order_port_depart_enqueue", 4648347u, 4648413u, 1, false, false, false, {N113, 2}, {N114, 3}, {N115, 1}, {N116, 1}, SC119, 1},
    {"llm_strat_bldg_order_production_add", 4643552u, 4643659u, 0, true, false, false, {N120, 2}, {N121, 3}, {N122, 1}, {N123, 1}, SC128, 2},
    {"llm_strat_bldg_order_production_add_count", 4643792u, 4643899u, 0, true, false, true, {N129, 2}, {N130, 3}, {N131, 1}, {N132, 1}, SC137, 2},
    {"llm_strat_bldg_order_production_add_count_enqueue", 4643911u, 4644018u, 1, true, false, true, {N138, 2}, {N139, 3}, {N140, 1}, {N141, 1}, SC146, 2},
    {"llm_strat_bldg_order_production_remove", 4644030u, 4644122u, 0, true, false, false, {N147, 2}, {N148, 3}, {N149, 1}, {N150, 1}, SC153, 1},
    {"llm_strat_bldg_order_production_remove_enqueue", 4644135u, 4644227u, 1, true, false, true, {N154, 2}, {N155, 3}, {N156, 1}, {N157, 1}, SC160, 1},
    {"llm_strat_bldg_order_purge_dead_docked", 4646634u, 4646685u, 0, false, false, false, {N161, 2}, {N162, 3}, {N163, 1}, {N164, 1}, nullptr, 0},
    {"llm_strat_bldg_order_purge_dead_docked_enqueue", 4646699u, 4646750u, 1, false, false, true, {N165, 2}, {N166, 3}, {N167, 1}, {N168, 1}, nullptr, 0},
    {"llm_strat_bldg_order_repair_cycle_start", 4645680u, 4645883u, 0, true, false, false, {N169, 2}, {N170, 3}, {N171, 1}, {N172, 1}, nullptr, 0},
    {"llm_strat_bldg_order_restart_construction", 4646374u, 4646425u, 0, false, false, false, {N173, 2}, {N174, 3}, {N175, 1}, {N176, 1}, nullptr, 0},
    {"llm_strat_bldg_order_shuttle_depart", 4646976u, 4647042u, 0, false, false, false, {N177, 2}, {N178, 3}, {N179, 1}, {N180, 1}, SC183, 1},
    {"llm_strat_bldg_order_shuttle_depart_enqueue", 4647055u, 4647121u, 1, false, false, false, {N184, 2}, {N185, 3}, {N186, 1}, {N187, 1}, SC190, 1},
    {"llm_strat_bldg_order_start_research_project", 4649280u, 4649346u, 0, false, false, false, {N191, 2}, {N192, 3}, {N193, 1}, {N194, 1}, SC197, 1},
    {"llm_strat_bldg_order_start_research_project_enqueue", 4649359u, 4649425u, 1, false, false, true, {N198, 2}, {N199, 3}, {N200, 1}, {N201, 1}, SC204, 1},
    {"llm_strat_bldg_order_unassign_workers", 4644948u, 4645014u, 0, false, false, false, {N205, 2}, {N206, 3}, {N207, 1}, {N208, 1}, SC211, 1},
    {"llm_strat_bldg_order_unload_passengers", 4647738u, 4647804u, 0, false, false, false, {N212, 2}, {N213, 3}, {N214, 1}, {N215, 1}, SC218, 1},
    {"llm_strat_bldg_order_unload_passengers_enqueue", 4647817u, 4647883u, 1, false, false, true, {N219, 2}, {N220, 3}, {N221, 1}, {N222, 1}, SC225, 1},
    {"llm_strat_bldg_order_unload_resource", 4648082u, 4648163u, 0, false, false, false, {N226, 2}, {N227, 3}, {N228, 1}, {N229, 1}, SC234, 2},
    {"llm_strat_bldg_order_unload_resource_enqueue", 4648175u, 4648256u, 1, false, false, true, {N235, 2}, {N236, 3}, {N237, 1}, {N238, 1}, SC243, 2},
    {"llm_strat_bldg_order_upgrade", 4645550u, 4645601u, 0, false, false, false, {N244, 2}, {N245, 3}, {N246, 1}, {N247, 1}, nullptr, 0},
    {"llm_strat_order_collect_available_projects", 4650631u, 4650674u, 0, false, false, false, {N248, 1}, {N249, 2}, {N250, 1}, {N251, 1}, nullptr, 0},
    {"llm_strat_order_create_unit_debug", 4642816u, 4642909u, 0, false, true, false, {N252, 1}, {N253, 2}, {N254, 1}, {N255, 1}, SC262, 3},
    {"llm_strat_order_credit_conquest_kills", 4651090u, 4651133u, 0, false, false, false, {N263, 1}, {N264, 2}, {N265, 1}, {N266, 1}, nullptr, 0},
    {"llm_strat_order_credit_conquest_kills_enqueue", 4651148u, 4651191u, 1, false, false, true, {N267, 1}, {N268, 2}, {N269, 1}, {N270, 1}, nullptr, 0},
    {"llm_strat_order_ctrlgrp_flash_member_raw", 4649669u, 4649733u, 1, false, true, true, {N271, 2}, {N272, 2}, {N273, 1}, {N274, 1}, SC277, 1},
    {"llm_strat_order_ctrlgrp_select_member_raw", 4649515u, 4649579u, 1, false, true, true, {N278, 2}, {N279, 2}, {N280, 1}, {N281, 1}, SC284, 1},
    {"llm_strat_order_debug_charge_add_full_group_enqueue", 4652159u, 4652242u, 1, false, true, true, {N285, 1}, {N286, 3}, {N287, 1}, {N288, 1}, SC293, 2},
    {"llm_strat_order_debug_charge_add_scaled_enqueue", 4651965u, 4652048u, 1, false, true, true, {N294, 1}, {N295, 3}, {N296, 1}, {N297, 1}, SC302, 2},
    {"llm_strat_order_debug_damage_scaled", 4651868u, 4651951u, 0, false, true, false, {N303, 1}, {N304, 3}, {N305, 1}, {N306, 1}, SC311, 2},
    {"llm_strat_order_debug_energy_refill_full", 4651674u, 4651757u, 0, false, true, false, {N312, 1}, {N313, 3}, {N314, 1}, {N315, 1}, SC320, 2},
    {"llm_strat_order_debug_energy_refill_full_enqueue", 4651771u, 4651854u, 1, false, true, true, {N321, 1}, {N322, 3}, {N323, 1}, {N324, 1}, SC329, 2},
    {"llm_strat_order_debug_kill_group", 4652062u, 4652145u, 0, false, true, false, {N330, 1}, {N331, 3}, {N332, 1}, {N333, 1}, SC338, 2},
    {"llm_strat_order_debug_roll_random", 4649746u, 4649789u, 0, false, false, true, {N339, 1}, {N340, 2}, {N341, 1}, {N342, 1}, nullptr, 0},
    {"llm_strat_order_debug_roll_random_enqueue", 4649804u, 4649842u, 1, false, false, true, {N343, 1}, {N344, 1}, {N345, 1}, {N346, 1}, nullptr, 0},
    {"llm_strat_order_fow_reveal_full", 4652256u, 4652324u, 0, false, true, false, {N347, 1}, {N348, 3}, {N349, 1}, {N350, 1}, SC353, 1},
    {"llm_strat_order_fow_reveal_full_enqueue", 4652339u, 4652407u, 1, false, true, true, {N354, 1}, {N355, 3}, {N356, 1}, {N357, 1}, SC360, 1},
    {"llm_strat_order_game_speed_decrease", 4649973u, 4650016u, 0, false, false, true, {N361, 1}, {N362, 2}, {N363, 1}, {N364, 1}, nullptr, 0},
    {"llm_strat_order_game_speed_decrease_enqueue", 4650031u, 4650074u, 1, false, false, true, {N365, 1}, {N366, 2}, {N367, 1}, {N368, 1}, nullptr, 0},
    {"llm_strat_order_game_speed_increase", 4649857u, 4649900u, 0, false, false, true, {N369, 1}, {N370, 2}, {N371, 1}, {N372, 1}, nullptr, 0},
    {"llm_strat_order_game_speed_increase_enqueue", 4649915u, 4649958u, 1, false, false, true, {N373, 1}, {N374, 2}, {N375, 1}, {N376, 1}, nullptr, 0},
    {"llm_strat_order_grant_resource", 4650295u, 4650373u, 0, false, true, false, {N377, 1}, {N378, 2}, {N379, 1}, {N380, 1}, SC385, 2},
    {"llm_strat_order_issue_0xd5", 4647134u, 4647215u, 0, false, false, true, {N386, 2}, {N387, 3}, {N388, 1}, {N389, 1}, SC394, 2},
    {"llm_strat_order_issue_0xd5_enqueue", 4647227u, 4647308u, 1, false, false, true, {N395, 2}, {N396, 3}, {N397, 1}, {N398, 1}, SC403, 2},
    {"llm_strat_order_issue_0xf_adjacent", 4629025u, 4629220u, 0, true, true, true, {N404, 2}, {N405, 3}, {N406, 1}, {N407, 1}, SC412, 2},
    {"llm_strat_order_issue_0xf_adjacent", 4629025u, 4629257u, 0, true, true, true, {N413, 2}, {N414, 2}, {N415, 1}, {N416, 1}, nullptr, 0},
    {"llm_strat_order_population_delta_debug", 4650477u, 4650540u, 0, false, true, false, {N417, 1}, {N418, 2}, {N419, 1}, {N420, 1}, SC423, 1},
    {"llm_strat_order_queue_construction_debug", 4643328u, 4643418u, 0, false, true, false, {N424, 1}, {N425, 2}, {N426, 1}, {N427, 1}, SC434, 3},
    {"llm_strat_order_recheck_buildings", 4650863u, 4650906u, 0, false, false, false, {N435, 1}, {N436, 2}, {N437, 1}, {N438, 1}, nullptr, 0},
    {"llm_strat_order_recheck_buildings_enqueue", 4650921u, 4650964u, 1, false, false, true, {N439, 1}, {N440, 2}, {N441, 1}, {N442, 1}, nullptr, 0},
    {"llm_strat_order_recheck_planet_system_all_players", 4650979u, 4651022u, 0, false, false, false, {N443, 1}, {N444, 2}, {N445, 1}, {N446, 1}, nullptr, 0},
    {"llm_strat_order_recheck_planet_system_all_players_enqueue", 4651037u, 4651075u, 1, false, false, true, {N447, 1}, {N448, 1}, {N449, 1}, {N450, 1}, nullptr, 0},
    {"llm_strat_order_recheck_projects", 4650747u, 4650790u, 0, false, false, false, {N451, 1}, {N452, 2}, {N453, 1}, {N454, 1}, nullptr, 0},
    {"llm_strat_order_recheck_projects_enqueue", 4650805u, 4650848u, 1, false, false, true, {N455, 1}, {N456, 2}, {N457, 1}, {N458, 1}, nullptr, 0},
    {"llm_strat_order_recruit_unit", 4643154u, 4643217u, 0, false, true, true, {N459, 1}, {N460, 2}, {N461, 1}, {N462, 1}, SC465, 1},
    {"llm_strat_order_set_player_control_mode", 4651390u, 4651569u, 0, true, true, false, {N466, 1}, {N467, 2}, {N468, 1}, {N469, 1}, SC474, 2},
    {"llm_strat_order_set_player_control_mode_enqueue", 4651582u, 4651661u, 1, false, true, true, {N475, 1}, {N476, 2}, {N477, 1}, {N478, 1}, SC483, 2},
    {"llm_strat_order_set_player_relation", 4651206u, 4651285u, 0, false, true, false, {N484, 1}, {N485, 2}, {N486, 1}, {N487, 1}, SC492, 2},
    {"llm_strat_order_set_player_relation_raw", 4651298u, 4651377u, 1, false, true, true, {N493, 1}, {N494, 2}, {N495, 1}, {N496, 1}, SC501, 2},
    {"llm_strat_turret_order_target_building", 4644432u, 4644516u, 0, false, false, false, {N502, 2}, {N503, 3}, {N504, 1}, {N505, 1}, SC510, 2},
    {"llm_strat_turret_order_target_building_enqueue", 4644528u, 4644612u, 1, false, false, true, {N511, 2}, {N512, 3}, {N513, 1}, {N514, 1}, SC519, 2},
    {"llm_strat_turret_order_target_unit", 4644240u, 4644324u, 0, false, false, false, {N520, 2}, {N521, 3}, {N522, 1}, {N523, 1}, SC528, 2},
    {"llm_strat_turret_order_target_unit_enqueue", 4644336u, 4644420u, 1, false, false, true, {N529, 2}, {N530, 3}, {N531, 1}, {N532, 1}, SC537, 2},
    {"llm_strat_unit_order_attack_building", 4638406u, 4638610u, 0, true, true, true, {N538, 2}, {N539, 3}, {N540, 1}, {N541, 1}, SC552, 5},
    {"llm_strat_unit_order_attack_building_reposition", 4636572u, 4637001u, 0, true, true, false, {N553, 2}, {N554, 3}, {N555, 1}, {N556, 3}, SC571, 7},
    {"llm_strat_unit_order_attack_building_reposition", 4636572u, 4637038u, 0, true, true, false, {N572, 2}, {N573, 2}, {N574, 1}, {N575, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_building_reposition", 4636572u, 4637198u, 0, true, false, false, {N576, 2}, {N577, 3}, {N578, 1}, {N579, 1}, SC588, 4},
    {"llm_strat_unit_order_attack_building_reposition_enqueue", 4637809u, 4638234u, 1, true, true, true, {N589, 2}, {N590, 3}, {N591, 1}, {N592, 3}, SC607, 7},
    {"llm_strat_unit_order_attack_building_reposition_enqueue", 4637809u, 4638392u, 1, true, false, true, {N608, 2}, {N609, 3}, {N610, 1}, {N611, 1}, SC620, 4},
    {"llm_strat_unit_order_attack_target", 4632350u, 4632905u, 0, true, true, false, {N621, 2}, {N622, 3}, {N623, 1}, {N624, 3}, SC639, 7},
    {"llm_strat_unit_order_attack_target", 4632350u, 4632942u, 0, true, true, false, {N640, 2}, {N641, 2}, {N642, 1}, {N643, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target", 4632350u, 4633158u, 0, true, false, false, {N644, 2}, {N645, 3}, {N646, 1}, {N647, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target", 4632350u, 4633187u, 0, true, false, false, {N648, 2}, {N649, 3}, {N650, 1}, {N651, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target_alt", 4634009u, 4634564u, 0, true, true, false, {N652, 2}, {N653, 3}, {N654, 1}, {N655, 3}, SC670, 7},
    {"llm_strat_unit_order_attack_target_alt", 4634009u, 4634601u, 0, true, true, false, {N671, 2}, {N672, 2}, {N673, 1}, {N674, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target_alt", 4634009u, 4634817u, 0, true, false, false, {N675, 2}, {N676, 3}, {N677, 1}, {N678, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target_alt", 4634009u, 4634846u, 0, true, false, false, {N679, 2}, {N680, 3}, {N681, 1}, {N682, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_target_preset_weapon_enqueue", 4636134u, 4636517u, 1, true, true, true, {N683, 2}, {N684, 3}, {N685, 1}, {N686, 3}, SC699, 6},
    {"llm_strat_unit_order_attack_target_preset_weapon_enqueue", 4636134u, 4636560u, 1, true, false, true, {N700, 2}, {N701, 3}, {N702, 1}, {N703, 1}, nullptr, 0},
    {"llm_strat_unit_order_attack_unit", 4635668u, 4635887u, 0, true, true, false, {N704, 2}, {N705, 3}, {N706, 1}, {N707, 1}, SC718, 5},
    {"llm_strat_unit_order_auto_launch_from_storage", 4640139u, 4640481u, 0, true, true, false, {N719, 2}, {N720, 3}, {N721, 3}, {N722, 1}, SC731, 4},
    {"llm_strat_unit_order_auto_launch_from_storage", 4640139u, 4640544u, 0, true, true, false, {N732, 2}, {N733, 3}, {N734, 1}, {N735, 1}, nullptr, 0},
    {"llm_strat_unit_order_dispatch_default", 4627942u, 4628068u, 0, false, true, true, {N736, 2}, {N737, 3}, {N738, 3}, {N739, 3}, nullptr, 0},
    {"llm_strat_unit_order_exit_storage", 4630201u, 4630533u, 0, true, true, false, {N740, 2}, {N741, 3}, {N742, 1}, {N743, 1}, SC750, 3},
    {"llm_strat_unit_order_exit_storage", 4630201u, 4630680u, 0, true, false, false, {N751, 2}, {N752, 3}, {N753, 1}, {N754, 1}, SC759, 2},
    {"llm_strat_unit_order_exit_storage", 4630201u, 4630717u, 0, true, true, false, {N760, 2}, {N761, 2}, {N762, 1}, {N763, 1}, nullptr, 0},
    {"llm_strat_unit_order_move", 4628454u, 4628626u, 0, false, true, false, {N764, 2}, {N765, 3}, {N766, 3}, {N767, 3}, SC774, 3},
    {"llm_strat_unit_order_move", 4628454u, 4628663u, 0, true, true, false, {N775, 2}, {N776, 2}, {N777, 1}, {N778, 1}, nullptr, 0},
    {"llm_strat_unit_order_move_confirmed_with_bump", 4631759u, 4631880u, 0, false, true, false, {N779, 2}, {N780, 3}, {N781, 1}, {N782, 3}, SC787, 2},
    {"llm_strat_unit_order_move_confirmed_with_bump", 4631759u, 4631917u, 0, true, true, false, {N788, 2}, {N789, 2}, {N790, 1}, {N791, 1}, nullptr, 0},
    {"llm_strat_unit_order_move_default", 4629506u, 4629640u, 0, false, true, false, {N792, 2}, {N793, 3}, {N794, 1}, {N795, 3}, SC802, 3},
    {"llm_strat_unit_order_move_default", 4629506u, 4629677u, 0, true, true, false, {N803, 2}, {N804, 2}, {N805, 1}, {N806, 1}, nullptr, 0},
    {"llm_strat_unit_order_move_default_enqueue", 4629707u, 4629841u, 1, false, true, true, {N807, 2}, {N808, 3}, {N809, 1}, {N810, 3}, SC817, 3},
    {"llm_strat_unit_order_move_relative", 4638842u, 4639040u, 0, true, true, false, {N818, 2}, {N819, 3}, {N820, 1}, {N821, 1}, SC826, 2},
    {"llm_strat_unit_order_move_relative", 4638842u, 4639077u, 0, true, true, false, {N827, 2}, {N828, 2}, {N829, 1}, {N830, 1}, nullptr, 0},
    {"llm_strat_unit_order_move_relative", 4638842u, 4639121u, 0, true, false, false, {N831, 2}, {N832, 3}, {N833, 1}, {N834, 1}, nullptr, 0},
    {"llm_strat_unit_order_move_relative_enqueue", 4639133u, 4639331u, 1, true, true, true, {N835, 2}, {N836, 3}, {N837, 1}, {N838, 1}, SC843, 2},
    {"llm_strat_unit_order_move_relative_enqueue", 4639133u, 4639373u, 1, true, false, true, {N844, 2}, {N845, 3}, {N846, 1}, {N847, 1}, nullptr, 0},
    {"llm_strat_unit_order_scatter_from_spawn", 4630054u, 4630175u, 1, false, true, false, {N848, 2}, {N849, 3}, {N850, 1}, {N851, 3}, SC856, 2},
    {"llm_strat_unit_reset_order_and_target", 4628222u, 4628348u, 1, false, true, true, {N857, 2}, {N858, 3}, {N859, 3}, {N860, 3}, nullptr, 0},
};
inline constexpr int SITE_COUNT = 120;

inline bool g_streq(const char *a, const char *b) {
    while (*a && *b) {
        if (*a != *b) return false;
        ++a;
        ++b;
    }
    return *a == *b;
}

// Look one up by wrapper name + site VA. Returns nullptr if absent.
inline const g_site *find(const char *wrapper, uint32_t site_va) {
    for (int i = 0; i < SITE_COUNT; ++i) {
        if (SITES[i].site_va == site_va && g_streq(SITES[i].wrapper, wrapper)) return &SITES[i];
    }
    return nullptr;
}

// All sites for one wrapper, in program order. Returns the count; fills `out` up to `max`.
inline int find_all(const char *wrapper, const g_site **out, int max) {
    int n = 0;
    for (int i = 0; i < SITE_COUNT; ++i) {
        if (g_streq(SITES[i].wrapper, wrapper)) {
            if (n < max) out[n] = &SITES[i];
            ++n;
        }
    }
    return n;
}

}  // namespace mh::orders::issue::golden
