//
// sim_dispatch_calls.gen.h -- GENERATED by tools/gen_module_calls.py --recording. Do not hand-edit.
// Regenerate with the command in the module's own note; the STRUCT is the input, so this
// file cannot drift from it without the build breaking at the aggregate initializer.
//
// The offline oracle's stub half of `dispatch_calls`. Every member records the call and its
// arguments into one log and returns a per-member configurable value, so a simtest case
// asserts on WHICH callees ran, IN WHAT ORDER, and WITH WHAT ARGUMENTS -- the three things a
// state-only comparison cannot see. Arguments are widened to long long (pointers via
// intptr_t) and floating-point ones kept separately, so a test reads back exactly the value
// the member's declared type carried.
//
// To make one member behave specially (an out-parameter, a canned return that depends on the
// arguments), copy the table and overwrite that member -- it is an aggregate:
//     dispatch_calls c = rec::recording_calls();
//     c.some_member = &my_own_stub;
#pragma once
#include <cstdint>
#include <cstring>
#include <vector>

#include "sim/sim_order_dispatch.h"

namespace mh::sim::rec {

enum dc_fn : int {
    DC_game_SpendResource,
    DC_game_TryStartProject,
    DC_game_ui_PrintTextMessage,
    DC_llm_bldg_construct_finalize,
    DC_llm_bldg_finish_current_order,
    DC_llm_bldg_footprint_is_clear,
    DC_llm_bldg_load_resource_tail_noop,
    DC_llm_bldg_pay_build_cost,
    DC_llm_bldg_queue_construction,
    DC_llm_bldg_reset_construction_anim,
    DC_llm_bldg_scrap_stored_units,
    DC_llm_bldg_set_connected_flag,
    DC_llm_bldg_transfer_notify_noop,
    DC_llm_combat_credit_planet_conquest_kills,
    DC_llm_debug_roll_random,
    DC_llm_diplomacy_set_relation,
    DC_llm_game_player_set_ai,
    DC_llm_game_player_set_human,
    DC_llm_game_speed_decrease,
    DC_llm_game_speed_increase,
    DC_llm_map_fow_reveal_full,
    DC_llm_net_lockstep_wait_player_overlay_show,
    DC_ovl_mode_saved_set,
    DC_llm_net_send_lockstep_extend,
    DC_llm_prod_bldg_depart_finalize,
    DC_llm_prod_shuttle_depart,
    DC_llm_prod_shuttle_fuel_apply,
    DC_llm_prod_shuttle_fuel_check,
    DC_llm_prod_shuttle_load_passengers,
    DC_llm_prod_shuttle_load_resource,
    DC_llm_prod_shuttle_slot_bind_default,
    DC_llm_prod_shuttle_unload_passengers,
    DC_llm_prod_shuttle_unload_resource,
    DC_llm_progress_collect_available_projects,
    DC_llm_progress_recheck_buildings,
    DC_llm_progress_recheck_planet_system_all_players,
    DC_llm_progress_recheck_projects,
    DC_llm_resource_add,
    DC_llm_snd_play,
    DC_llm_storage_cancel_pending_docked,
    DC_llm_strat_ai_notify_bldg_constructed,
    DC_llm_strat_ai_notify_unit_lifecycle,
    DC_llm_strat_ai_queue_release_order,
    DC_llm_strat_bldg_assign_workers,
    DC_llm_strat_bldg_clear_staffed_flag,
    DC_llm_strat_bldg_flush_cargo_hold,
    DC_llm_strat_bldg_get_coords,
    DC_llm_strat_bldg_notify_ui,
    DC_llm_strat_bldg_pay_cycle_inputs,
    DC_llm_strat_bldg_set_staffed_flag,
    DC_llm_strat_bldg_unassign_workers,
    DC_llm_strat_dist_out_of_range,
    DC_llm_strat_population_add,
    DC_llm_strat_population_remove,
    DC_llm_strat_prod_bind_planet,
    DC_llm_strat_refresh_building,
    DC_llm_strat_storage_purge_dead_docked,
    DC_llm_strat_target_release_ref,
    DC_llm_strat_unit_create,
    DC_llm_strat_unit_get_coords,
    DC_llm_strat_unit_notify_status,
    DC_llm_strat_unit_set_state_of,
    DC_llm_unit_apply_production_completion,
    DC_llm_unit_bldg_apply_lethal_damage,
    DC_llm_unit_bldg_apply_scaled_damage,
    DC_llm_unit_bldg_energy_refill_full,
    DC_llm_unit_create_soldier,
    DC_llm_unit_force_disembark,
    DC_llm_unit_recruit,
    DC_llm_unit_set_order_param,
    DC_llm_unit_state_is_boarding,
    DC_llm_unit_status_bit_clear,
    DC_llm_unit_status_bit_set,
    DC_llm_unit_transport_unload_docked,
    DC_llm_unit_transport_unload_field,
    DC_w_sprintf__vss,
    DC_COUNT,
};

inline const char *dc_name(int fn) {
    static const char *const n[DC_COUNT] = {
        "game_SpendResource",
        "game_TryStartProject",
        "game_ui_PrintTextMessage",
        "llm_bldg_construct_finalize",
        "llm_bldg_finish_current_order",
        "llm_bldg_footprint_is_clear",
        "llm_bldg_load_resource_tail_noop",
        "llm_bldg_pay_build_cost",
        "llm_bldg_queue_construction",
        "llm_bldg_reset_construction_anim",
        "llm_bldg_scrap_stored_units",
        "llm_bldg_set_connected_flag",
        "llm_bldg_transfer_notify_noop",
        "llm_combat_credit_planet_conquest_kills",
        "llm_debug_roll_random",
        "llm_diplomacy_set_relation",
        "llm_game_player_set_ai",
        "llm_game_player_set_human",
        "llm_game_speed_decrease",
        "llm_game_speed_increase",
        "llm_map_fow_reveal_full",
        "llm_net_lockstep_wait_player_overlay_show",
        "ovl_mode_saved_set",
        "llm_net_send_lockstep_extend",
        "llm_prod_bldg_depart_finalize",
        "llm_prod_shuttle_depart",
        "llm_prod_shuttle_fuel_apply",
        "llm_prod_shuttle_fuel_check",
        "llm_prod_shuttle_load_passengers",
        "llm_prod_shuttle_load_resource",
        "llm_prod_shuttle_slot_bind_default",
        "llm_prod_shuttle_unload_passengers",
        "llm_prod_shuttle_unload_resource",
        "llm_progress_collect_available_projects",
        "llm_progress_recheck_buildings",
        "llm_progress_recheck_planet_system_all_players",
        "llm_progress_recheck_projects",
        "llm_resource_add",
        "llm_snd_play",
        "llm_storage_cancel_pending_docked",
        "llm_strat_ai_notify_bldg_constructed",
        "llm_strat_ai_notify_unit_lifecycle",
        "llm_strat_ai_queue_release_order",
        "llm_strat_bldg_assign_workers",
        "llm_strat_bldg_clear_staffed_flag",
        "llm_strat_bldg_flush_cargo_hold",
        "llm_strat_bldg_get_coords",
        "llm_strat_bldg_notify_ui",
        "llm_strat_bldg_pay_cycle_inputs",
        "llm_strat_bldg_set_staffed_flag",
        "llm_strat_bldg_unassign_workers",
        "llm_strat_dist_out_of_range",
        "llm_strat_population_add",
        "llm_strat_population_remove",
        "llm_strat_prod_bind_planet",
        "llm_strat_refresh_building",
        "llm_strat_storage_purge_dead_docked",
        "llm_strat_target_release_ref",
        "llm_strat_unit_create",
        "llm_strat_unit_get_coords",
        "llm_strat_unit_notify_status",
        "llm_strat_unit_set_state_of",
        "llm_unit_apply_production_completion",
        "llm_unit_bldg_apply_lethal_damage",
        "llm_unit_bldg_apply_scaled_damage",
        "llm_unit_bldg_energy_refill_full",
        "llm_unit_create_soldier",
        "llm_unit_force_disembark",
        "llm_unit_recruit",
        "llm_unit_set_order_param",
        "llm_unit_state_is_boarding",
        "llm_unit_status_bit_clear",
        "llm_unit_status_bit_set",
        "llm_unit_transport_unload_docked",
        "llm_unit_transport_unload_field",
        "w_sprintf__vss",
    };
    return (fn >= 0 && fn < DC_COUNT) ? n[fn] : "?";
}

// One recorded call. `a` holds the integral and pointer arguments in declaration order, `d`
// the floating-point ones in declaration order -- two sequences, because a double does not
// survive a long long and an int does not survive a double.
struct dc_event {
    int       fn;
    int       na, nd;
    long long a[6];
    double    d[1];
};

struct dc_log {
    std::vector<dc_event> events;
    // What each stub returns. Zero by default, which is the quiet answer for every one of
    // these callees -- a test that needs a nonzero status sets ret[DC_x] itself.
    long long ret[DC_COUNT];

    void reset() {
        events.clear();
        std::memset(ret, 0, sizeof(ret));
    }
    int count(int fn) const {
        int n = 0;
        for (const dc_event &e : events)
            if (e.fn == fn) ++n;
        return n;
    }
    // The k-th call of `fn` (0-based), or null. `last` is nth(fn, count(fn)-1).
    const dc_event *nth(int fn, int k) const {
        for (const dc_event &e : events)
            if (e.fn == fn && k-- == 0) return &e;
        return nullptr;
    }
    const dc_event *last(int fn) const { return nth(fn, count(fn) - 1); }
    // Index of the first call of `fn` in the whole sequence, or -1. Order between DIFFERENT
    // callees is the property a lockstep/network path most needs asserted.
    int first_index(int fn) const {
        for (int i = 0; i < (int)events.size(); ++i)
            if (events[i].fn == fn) return i;
        return -1;
    }
};

// The single log the stubs below record into. One per process is enough: simtest is
// single-threaded and every case calls reset() first.
inline dc_log &dc() {
    static dc_log g;
    return g;
}

inline void dc_stub_game_SpendResource(int32_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_game_SpendResource;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline int32_t dc_stub_game_TryStartProject(uint16_t a0, int32_t a1, uint32_t a2) {
    dc_event e{};
    e.fn   = DC_game_TryStartProject;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_game_TryStartProject];
}
inline uint32_t dc_stub_game_ui_PrintTextMessage(void *a0) {
    dc_event e{};
    e.fn   = DC_game_ui_PrintTextMessage;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)(intptr_t)a0;
    dc().events.push_back(e);
    return (uint32_t)dc().ret[DC_game_ui_PrintTextMessage];
}
inline int32_t dc_stub_llm_bldg_construct_finalize(uint32_t a0, int32_t a1, uint16_t a2, char a3, uint32_t a4, uint32_t a5) {
    dc_event e{};
    e.fn   = DC_llm_bldg_construct_finalize;
    e.na   = 6;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    e.a[4] = (long long)a4;
    e.a[5] = (long long)a5;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_bldg_construct_finalize];
}
inline void dc_stub_llm_bldg_finish_current_order(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_bldg_finish_current_order;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_bldg_footprint_is_clear(int32_t a0, int32_t a1, int32_t a2, uint32_t a3) {
    dc_event e{};
    e.fn   = DC_llm_bldg_footprint_is_clear;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_bldg_footprint_is_clear];
}
inline void dc_stub_llm_bldg_load_resource_tail_noop() {
    dc_event e{};
    e.fn = DC_llm_bldg_load_resource_tail_noop;
    e.na = 0;
    e.nd = 0;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_bldg_pay_build_cost(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_bldg_pay_build_cost;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_bldg_pay_build_cost];
}
inline int32_t dc_stub_llm_bldg_queue_construction(int32_t a0, int32_t a1, int32_t a2, int32_t a3) {
    dc_event e{};
    e.fn   = DC_llm_bldg_queue_construction;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_bldg_queue_construction];
}
inline void dc_stub_llm_bldg_reset_construction_anim(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_bldg_reset_construction_anim;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_bldg_scrap_stored_units(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_bldg_scrap_stored_units;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_bldg_set_connected_flag(uint16_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_bldg_set_connected_flag;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_bldg_transfer_notify_noop() {
    dc_event e{};
    e.fn = DC_llm_bldg_transfer_notify_noop;
    e.na = 0;
    e.nd = 0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_combat_credit_planet_conquest_kills(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_combat_credit_planet_conquest_kills;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_debug_roll_random() {
    dc_event e{};
    e.fn = DC_llm_debug_roll_random;
    e.na = 0;
    e.nd = 0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_diplomacy_set_relation(int32_t a0, int32_t a1, uint8_t a2) {
    dc_event e{};
    e.fn   = DC_llm_diplomacy_set_relation;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_game_player_set_ai(uint8_t a0) {
    dc_event e{};
    e.fn   = DC_llm_game_player_set_ai;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_game_player_set_human(uint8_t a0) {
    dc_event e{};
    e.fn   = DC_llm_game_player_set_human;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_game_speed_decrease(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_game_speed_decrease;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_game_speed_increase(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_game_speed_increase;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_map_fow_reveal_full(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_map_fow_reveal_full;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_net_lockstep_wait_player_overlay_show(int32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_net_lockstep_wait_player_overlay_show;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_net_lockstep_wait_player_overlay_show];
}
inline void dc_stub_ovl_mode_saved_set(uint8_t a0) {
    dc_event e{};
    e.fn   = DC_ovl_mode_saved_set;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_net_send_lockstep_extend(double a0) {
    dc_event e{};
    e.fn   = DC_llm_net_send_lockstep_extend;
    e.na   = 0;
    e.nd   = 1;
    e.d[0] = (double)a0;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_prod_bldg_depart_finalize(uint16_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_bldg_depart_finalize;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_bldg_depart_finalize];
}
inline int32_t dc_stub_llm_prod_shuttle_depart(uint16_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_depart;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_depart];
}
inline int32_t dc_stub_llm_prod_shuttle_fuel_apply(uint16_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_fuel_apply;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_fuel_apply];
}
inline int32_t dc_stub_llm_prod_shuttle_fuel_check(uint16_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_fuel_check;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_fuel_check];
}
inline uint32_t dc_stub_llm_prod_shuttle_load_passengers(uint16_t a0, int32_t a1, uint32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_load_passengers;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (uint32_t)dc().ret[DC_llm_prod_shuttle_load_passengers];
}
inline int32_t dc_stub_llm_prod_shuttle_load_resource(uint32_t a0, int32_t a1, uint32_t a2, uint32_t a3) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_load_resource;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_load_resource];
}
inline int32_t dc_stub_llm_prod_shuttle_slot_bind_default(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_slot_bind_default;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_slot_bind_default];
}
inline int32_t dc_stub_llm_prod_shuttle_unload_passengers(uint16_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_unload_passengers;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_prod_shuttle_unload_passengers];
}
inline uint8_t dc_stub_llm_prod_shuttle_unload_resource(uint16_t a0, int32_t a1, uint16_t a2, int32_t a3) {
    dc_event e{};
    e.fn   = DC_llm_prod_shuttle_unload_resource;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    dc().events.push_back(e);
    return (uint8_t)dc().ret[DC_llm_prod_shuttle_unload_resource];
}
inline void dc_stub_llm_progress_collect_available_projects(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_progress_collect_available_projects;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_progress_recheck_buildings(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_progress_recheck_buildings;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_progress_recheck_planet_system_all_players() {
    dc_event e{};
    e.fn = DC_llm_progress_recheck_planet_system_all_players;
    e.na = 0;
    e.nd = 0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_progress_recheck_projects(uint32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_progress_recheck_projects;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
}
inline void dc_stub_llm_resource_add(int32_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_resource_add;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_snd_play(int32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_snd_play;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_storage_cancel_pending_docked(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_storage_cancel_pending_docked;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_ai_notify_bldg_constructed(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) {
    dc_event e{};
    e.fn   = DC_llm_strat_ai_notify_bldg_constructed;
    e.na   = 6;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    e.a[4] = (long long)a4;
    e.a[5] = (long long)a5;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_ai_notify_unit_lifecycle(uint16_t a0, uint16_t a1, uint32_t a2, uint32_t a3) {
    dc_event e{};
    e.fn   = DC_llm_strat_ai_notify_unit_lifecycle;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_ai_queue_release_order(int32_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_ai_queue_release_order;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_strat_bldg_assign_workers(uint32_t a0, uint32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_assign_workers;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_strat_bldg_assign_workers];
}
inline void dc_stub_llm_strat_bldg_clear_staffed_flag(uint16_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_clear_staffed_flag;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_bldg_flush_cargo_hold(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_flush_cargo_hold;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_bldg_get_coords(uint16_t a0, int32_t a1, int32_t *a2, int32_t *a3) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_get_coords;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)(intptr_t)a2;
    e.a[3] = (long long)(intptr_t)a3;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_bldg_notify_ui(uint16_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_notify_ui;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_strat_bldg_pay_cycle_inputs(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_pay_cycle_inputs;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_strat_bldg_pay_cycle_inputs];
}
inline void dc_stub_llm_strat_bldg_set_staffed_flag(uint16_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_set_staffed_flag;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_strat_bldg_unassign_workers(uint16_t a0, uint32_t a1, uint32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_bldg_unassign_workers;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_strat_bldg_unassign_workers];
}
inline uint32_t dc_stub_llm_strat_dist_out_of_range(int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    dc_event e{};
    e.fn   = DC_llm_strat_dist_out_of_range;
    e.na   = 6;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    e.a[4] = (long long)a4;
    e.a[5] = (long long)a5;
    dc().events.push_back(e);
    return (uint32_t)dc().ret[DC_llm_strat_dist_out_of_range];
}
inline void dc_stub_llm_strat_population_add(uint16_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_population_add;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_population_remove(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_population_remove;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_strat_prod_bind_planet(int32_t a0, int32_t a1, int32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_prod_bind_planet;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_strat_prod_bind_planet];
}
inline void dc_stub_llm_strat_refresh_building(uint16_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_refresh_building;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_storage_purge_dead_docked(int32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_strat_storage_purge_dead_docked;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_target_release_ref(uint32_t a0, int32_t a1, uint32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_target_release_ref;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline uint32_t dc_stub_llm_strat_unit_create(uint32_t a0, uint32_t a1, uint16_t a2, uint16_t a3, uint8_t a4) {
    dc_event e{};
    e.fn   = DC_llm_strat_unit_create;
    e.na   = 5;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    e.a[4] = (long long)a4;
    dc().events.push_back(e);
    return (uint32_t)dc().ret[DC_llm_strat_unit_create];
}
inline void dc_stub_llm_strat_unit_get_coords(uint16_t a0, int32_t a1, int32_t *a2, int32_t *a3) {
    dc_event e{};
    e.fn   = DC_llm_strat_unit_get_coords;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)(intptr_t)a2;
    e.a[3] = (long long)(intptr_t)a3;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_unit_notify_status(uint32_t a0, int32_t a1, uint32_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_unit_notify_status;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_strat_unit_set_state_of(int32_t a0, int32_t a1, int16_t a2) {
    dc_event e{};
    e.fn   = DC_llm_strat_unit_set_state_of;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_apply_production_completion(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_apply_production_completion;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_bldg_apply_lethal_damage(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_bldg_apply_lethal_damage;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_bldg_apply_scaled_damage(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_bldg_apply_scaled_damage;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_bldg_energy_refill_full(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_bldg_energy_refill_full;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline uint32_t dc_stub_llm_unit_create_soldier(uint32_t a0, uint32_t a1, uint16_t a2, uint16_t a3, char a4) {
    dc_event e{};
    e.fn   = DC_llm_unit_create_soldier;
    e.na   = 5;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    e.a[3] = (long long)a3;
    e.a[4] = (long long)a4;
    dc().events.push_back(e);
    return (uint32_t)dc().ret[DC_llm_unit_create_soldier];
}
inline void dc_stub_llm_unit_force_disembark(uint32_t a0, int32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_force_disembark;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_unit_recruit(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_recruit;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_unit_recruit];
}
inline void dc_stub_llm_unit_set_order_param(int32_t a0, int32_t a1, int16_t a2) {
    dc_event e{};
    e.fn   = DC_llm_unit_set_order_param;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline int32_t dc_stub_llm_unit_state_is_boarding(int32_t a0) {
    dc_event e{};
    e.fn   = DC_llm_unit_state_is_boarding;
    e.na   = 1;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_llm_unit_state_is_boarding];
}
inline void dc_stub_llm_unit_status_bit_clear(int32_t a0, int32_t a1, uint8_t a2) {
    dc_event e{};
    e.fn   = DC_llm_unit_status_bit_clear;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_status_bit_set(int32_t a0, int32_t a1, uint8_t a2) {
    dc_event e{};
    e.fn   = DC_llm_unit_status_bit_set;
    e.na   = 3;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    e.a[2] = (long long)a2;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_transport_unload_docked(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_transport_unload_docked;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline void dc_stub_llm_unit_transport_unload_field(uint32_t a0, uint32_t a1) {
    dc_event e{};
    e.fn   = DC_llm_unit_transport_unload_field;
    e.na   = 2;
    e.nd   = 0;
    e.a[0] = (long long)a0;
    e.a[1] = (long long)a1;
    dc().events.push_back(e);
}
inline int32_t dc_stub_w_sprintf__vss(void *a0, const wchar_t *a1, const wchar_t *a2, const wchar_t *a3) {
    dc_event e{};
    e.fn   = DC_w_sprintf__vss;
    e.na   = 4;
    e.nd   = 0;
    e.a[0] = (long long)(intptr_t)a0;
    e.a[1] = (long long)(intptr_t)a1;
    e.a[2] = (long long)(intptr_t)a2;
    e.a[3] = (long long)(intptr_t)a3;
    dc().events.push_back(e);
    return (int32_t)dc().ret[DC_w_sprintf__vss];
}

// Member for member, in declaration order -- an aggregate initializer does not convert, so a
// stub whose signature drifted from its member is a compile error here rather than a wrong
// number in a test.
inline dispatch_calls recording_calls() {
    dispatch_calls c = {
        dc_stub_game_SpendResource,
        dc_stub_game_TryStartProject,
        dc_stub_game_ui_PrintTextMessage,
        dc_stub_llm_bldg_construct_finalize,
        dc_stub_llm_bldg_finish_current_order,
        dc_stub_llm_bldg_footprint_is_clear,
        dc_stub_llm_bldg_load_resource_tail_noop,
        dc_stub_llm_bldg_pay_build_cost,
        dc_stub_llm_bldg_queue_construction,
        dc_stub_llm_bldg_reset_construction_anim,
        dc_stub_llm_bldg_scrap_stored_units,
        dc_stub_llm_bldg_set_connected_flag,
        dc_stub_llm_bldg_transfer_notify_noop,
        dc_stub_llm_combat_credit_planet_conquest_kills,
        dc_stub_llm_debug_roll_random,
        dc_stub_llm_diplomacy_set_relation,
        dc_stub_llm_game_player_set_ai,
        dc_stub_llm_game_player_set_human,
        dc_stub_llm_game_speed_decrease,
        dc_stub_llm_game_speed_increase,
        dc_stub_llm_map_fow_reveal_full,
        dc_stub_llm_net_lockstep_wait_player_overlay_show,
        dc_stub_ovl_mode_saved_set,
        dc_stub_llm_net_send_lockstep_extend,
        dc_stub_llm_prod_bldg_depart_finalize,
        dc_stub_llm_prod_shuttle_depart,
        dc_stub_llm_prod_shuttle_fuel_apply,
        dc_stub_llm_prod_shuttle_fuel_check,
        dc_stub_llm_prod_shuttle_load_passengers,
        dc_stub_llm_prod_shuttle_load_resource,
        dc_stub_llm_prod_shuttle_slot_bind_default,
        dc_stub_llm_prod_shuttle_unload_passengers,
        dc_stub_llm_prod_shuttle_unload_resource,
        dc_stub_llm_progress_collect_available_projects,
        dc_stub_llm_progress_recheck_buildings,
        dc_stub_llm_progress_recheck_planet_system_all_players,
        dc_stub_llm_progress_recheck_projects,
        dc_stub_llm_resource_add,
        dc_stub_llm_snd_play,
        dc_stub_llm_storage_cancel_pending_docked,
        dc_stub_llm_strat_ai_notify_bldg_constructed,
        dc_stub_llm_strat_ai_notify_unit_lifecycle,
        dc_stub_llm_strat_ai_queue_release_order,
        dc_stub_llm_strat_bldg_assign_workers,
        dc_stub_llm_strat_bldg_clear_staffed_flag,
        dc_stub_llm_strat_bldg_flush_cargo_hold,
        dc_stub_llm_strat_bldg_get_coords,
        dc_stub_llm_strat_bldg_notify_ui,
        dc_stub_llm_strat_bldg_pay_cycle_inputs,
        dc_stub_llm_strat_bldg_set_staffed_flag,
        dc_stub_llm_strat_bldg_unassign_workers,
        dc_stub_llm_strat_dist_out_of_range,
        dc_stub_llm_strat_population_add,
        dc_stub_llm_strat_population_remove,
        dc_stub_llm_strat_prod_bind_planet,
        dc_stub_llm_strat_refresh_building,
        dc_stub_llm_strat_storage_purge_dead_docked,
        dc_stub_llm_strat_target_release_ref,
        dc_stub_llm_strat_unit_create,
        dc_stub_llm_strat_unit_get_coords,
        dc_stub_llm_strat_unit_notify_status,
        dc_stub_llm_strat_unit_set_state_of,
        dc_stub_llm_unit_apply_production_completion,
        dc_stub_llm_unit_bldg_apply_lethal_damage,
        dc_stub_llm_unit_bldg_apply_scaled_damage,
        dc_stub_llm_unit_bldg_energy_refill_full,
        dc_stub_llm_unit_create_soldier,
        dc_stub_llm_unit_force_disembark,
        dc_stub_llm_unit_recruit,
        dc_stub_llm_unit_set_order_param,
        dc_stub_llm_unit_state_is_boarding,
        dc_stub_llm_unit_status_bit_clear,
        dc_stub_llm_unit_status_bit_set,
        dc_stub_llm_unit_transport_unload_docked,
        dc_stub_llm_unit_transport_unload_field,
        dc_stub_w_sprintf__vss,
    };
    return c;
}

} // namespace mh::sim::rec
