//
// mh_log_sink.cpp -- the async log sink's engine. Contract and rationale: include/mh_log_sink.h.
//
// SHAPE
//   producers (any thread) --push--> lock-free MPSC queue --pop--> ONE consumer --> per-file handles
//
// THE QUEUE is Vyukov's intrusive MPSC list: a producer does one InterlockedExchange on `g_head` and
// then links the previous head to its node; the consumer walks from `g_tail`. No lock is ever taken
// by a producer, so a thread that faults (or is suspended, or is killed) in the middle of an enqueue
// can never block anybody else. Nodes come from a PRIVATE heap (HeapCreate), not the process heap,
// so a corrupt process heap -- the usual reason for a crash -- cannot poison log writes, and the
// crash path (below) neither allocates nor frees.
//
// THE CONSUMER is "whoever holds g_consumer" (a tid-stamped CAS flag, not a lock a producer ever
// sees). Normally that is the writer thread. At crash/exit the dying thread takes it over.
//
// THE CRASH DRAIN -- why it cannot deadlock.
//   * Producers hold nothing the drain needs: there is no queue lock. The only shared exclusion is
//     the consumer flag, and only the writer thread (or another drain) holds it.
//   * If the WRITER holds it, it is inside a bounded pass doing file I/O; the drain waits for it
//     with a hard deadline (`ms`), polling with Sleep(0/1). If the writer is wedged in a hung
//     WriteFile the deadline expires and the drain returns WITHOUT draining -- a bounded loss of the
//     final lines, never a hang (the crash handler still writes the marker + signals the launcher).
//   * If the faulting thread IS the writer (owner tid == ours) it takes the flag over directly: the
//     interrupted pass cannot resume, so nothing else is using the handle cache.
//   * A producer preempted between its exchange and its link leaves a momentary gap (head != tail
//     but tail->next == null). The drain re-polls until the deadline instead of treating it as empty.
//   * In crash mode nothing is freed and no slow-op line is generated: no heap lock is touched, and
//     the drain never re-enters the queue.
//   * The flag is RELEASED afterwards: an exception the game handles (a first-chance access
//     violation in a __try) must not leave the writer thread parked forever.
//
// EXIT. ExitProcess kills every thread BEFORE DLL_PROCESS_DETACH runs, so mh_logq_shutdown() finds a
// dead writer and drains inline with the same crash-safe routine. A FreeLibrary-style detach finds a
// live writer, asks it to stop, waits (bounded), then drains whatever remains.
//
// LATENCY. The writer sleeps on an auto-reset event only when the queue is empty; a producer signals
// it only when the writer has announced it sleeps. A line is on disk within one scheduler wake-up
// plus its own WriteFile -- the UI harness reads these logs live and sees no batching delay. Runs of
// consecutive records for the SAME file in one pass are coalesced into one WriteFile (<= 64 KB).
//
// HANDLES stay open (16-entry LRU) while a file is being written and are closed after 1 s idle -- so
// a session folder is never pinned by us, and a path change (new session folder) simply stops
// touching the old entry, which idles out. Opened with SHARE_READ|WRITE|DELETE so readers, other
// writers of the same file and a rotation by another image all keep working.
//
#include "include/mh_log_sink.h"
#include "include/mh_log_rotate.h"
#include "include/mh_run_context.h"

namespace {

constexpr int   CACHE_N       = 16;
constexpr int   WBUF_CAP      = 64 * 1024;
constexpr DWORD SLOW_MS       = 50;
constexpr DWORD IDLE_CLOSE_MS = 1000;
constexpr int   MAX_LINE      = 1024 * 1024; // a single TEXT record is truncated past this
// mp:LOG2: a BINARY record is never truncated (a cut recording is a corrupt file); one past this is
// refused whole and counted. Far above any real file: the 8.3 MB world blob goes in as ONE record.
constexpr int   MAX_BIN_RECORD = 256 * 1024 * 1024;
constexpr DWORD NODE_INTERNAL  = 1; // generated by the sink itself (never re-reported as slow)
constexpr DWORD NODE_BIN       = 2; // a reliable binary record (own byte budget, own drop counter)

struct Node {
    Node *volatile next;
    long long cap;
    int       pathlen;
    int       len;
    DWORD     internal; // NODE_INTERNAL | NODE_BIN bits
    // path (pathlen+1 bytes) then payload (len bytes) follow
    char *path() { return (char *)(this + 1); }
    char *data() { return (char *)(this + 1) + pathlen + 1; }
};

struct CacheEnt {
    HANDLE h;
    DWORD  last_tick;
    char   path[MAX_PATH];
};

Node g_stub                      = {nullptr, 0, 0, 0, 1};
Node *volatile g_head            = &g_stub; // producers exchange here
Node         *g_tail             = &g_stub; // consumer only
HANDLE        g_heap             = nullptr;
HANDLE        g_event            = nullptr;
HANDLE        g_thread           = nullptr;
volatile LONG g_sleeping         = 0;
volatile LONG g_stop             = 0;
volatile LONG g_hold             = 0; // test hook: 1 = writer parked, 2 = parked HOLDING the consumer flag
volatile LONG g_writer_tid       = 0;
volatile LONG g_down             = 0; // set by shutdown: later writes are synchronous
volatile LONG g_writer_running   = 0; // the writer thread has actually started (DllMain's loader lock held it back until then)
volatile LONG g_consumer         = 0; // 0 = free, else owner tid
volatile LONG g_init             = 0; // 0 none, 1 starting, 2 ready
volatile LONG g_bytes            = 0;
volatile LONG g_bin_bytes        = 0; // mp:LOG2: queued binary payload, its own budget
volatile LONG g_bin_dropped      = 0;
volatile LONG g_bin_reported     = 0;
volatile LONG g_enq              = 0;
volatile LONG g_done             = 0;
volatile LONG g_dropped_total    = 0;
volatile LONG g_dropped_reported = 0;
volatile LONG g_slow_ops         = 0;
MH_LogQApi   *g_api              = nullptr;
HANDLE        g_map              = nullptr;
LARGE_INTEGER g_qpc_freq;

// consumer-owned state
CacheEnt  g_cache[CACHE_N];
char      g_wbuf[WBUF_CAP];
int       g_wlen = 0;
char      g_wpath[MAX_PATH];
long long g_wcap = 0;
char      g_net_log[MAX_PATH]; // last path seen that ends in mh_net.log -- home of the sink's own lines
bool      g_crash_mode = false;

inline bool ends_with_ci(const char *s, const char *suffix) {
    const int n = lstrlenA(s), m = lstrlenA(suffix);
    return n >= m && lstrcmpiA(s + n - m, suffix) == 0;
}

inline long long now_us() {
    LARGE_INTEGER t;
    QueryPerformanceCounter(&t);
    return (t.QuadPart * 1000000LL) / g_qpc_freq.QuadPart;
}

// ---- producer ------------------------------------------------------------------------------------
void push_node(Node *n) {
    n->next    = nullptr;
    Node *prev = (Node *)InterlockedExchangePointer((PVOID volatile *)&g_head, n);
    prev->next = n; // the only window where the consumer sees a gap; see the header comment
    InterlockedIncrement(&g_enq);
    MemoryBarrier();
    if (g_sleeping && g_event) SetEvent(g_event);
}

Node *make_node(const char *path, const void *a, int al, const void *b, int bl, long long cap, DWORD internal) {
    if (g_heap == nullptr) return nullptr;
    if (al < 0) al = 0;
    if (bl < 0) bl = 0;
    if (a == nullptr) al = 0;
    if (b == nullptr) bl = 0;
    const bool bin = cap <= MH_LOGQ_CAP_BIN; // BIN and BIN_CREATE
    if (bin) {
        if ((long long)al + bl > MAX_BIN_RECORD) { // refused whole, never cut
            InterlockedIncrement(&g_bin_dropped);
            return nullptr;
        }
    } else if (al + bl > MAX_LINE) {
        if (al > MAX_LINE) al = MAX_LINE;
        bl = MAX_LINE - al;
    }
    const int      pl     = lstrlenA(path);
    const int      need   = (int)sizeof(Node) + pl + 1 + al + bl;
    volatile LONG *budget = bin ? &g_bin_bytes : &g_bytes;
    const LONG     limit  = bin ? MH_LOGQ_MAX_BIN_BYTES : MH_LOGQ_MAX_BYTES;
    if (InterlockedExchangeAdd(budget, need) + need > limit && !(internal & NODE_INTERNAL)) {
        InterlockedExchangeAdd(budget, -need);
        InterlockedIncrement(bin ? &g_bin_dropped : &g_dropped_total);
        return nullptr;
    }
    Node *n = (Node *)HeapAlloc(g_heap, 0, (SIZE_T)need);
    if (n == nullptr) {
        InterlockedExchangeAdd(budget, -need);
        InterlockedIncrement(bin ? &g_bin_dropped : &g_dropped_total);
        return nullptr;
    }
    n->cap      = cap;
    n->pathlen  = pl;
    n->len      = al + bl;
    n->internal = internal | (bin ? NODE_BIN : 0);
    CopyMemory(n->path(), path, (SIZE_T)pl + 1);
    if (al) CopyMemory(n->data(), a, (SIZE_T)al);
    if (bl) CopyMemory(n->data() + al, b, (SIZE_T)bl);
    return n;
}

void write2_impl(const char *path, const void *a, int al, const void *b, int bl, long long cap) {
    if (g_down) { // after mh_logq_shutdown nobody consumes: write synchronously rather than lose the line
        if (cap == MH_LOGQ_CAP_ROTATE_NOW && al <= 0 && bl <= 0) {
            mh_log_rotate(path);
            return;
        }
        if (cap == MH_LOGQ_CAP_BIN_CREATE) mh_logq_detail::sync_create(path, a, al, b, bl);
        else mh_logq_detail::sync_append(path, a, al, b, bl);
        return;
    }
    Node *n = make_node(path, a, al, b, bl, cap, 0);
    if (n) push_node(n);
}

// ---- consumer ------------------------------------------------------------------------------------
void report_slow(const char *op, const char *path, DWORD ms, int bytes) {
    InterlockedIncrement(&g_slow_ops);
    if (g_crash_mode || g_net_log[0] == '\0') return;
    char  stamp[24];
    int   sn = mh_log_stamp(stamp);
    char  line[MAX_PATH + 96];
    int   ln = wsprintfA(line, "; log sink: slow %s %lu ms on %s (%d bytes)\n", op, ms, path, bytes);
    Node *n  = make_node(g_net_log, stamp, sn, line, ln, 0, 1);
    if (n) push_node(n);
}

HANDLE open_timed(const char *path) {
    const long long t0 = now_us();
    HANDLE          h  = CreateFileA(path, FILE_APPEND_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, nullptr,
                                     OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    const DWORD     ms = (DWORD)((now_us() - t0) / 1000);
    if (ms > SLOW_MS) report_slow("CreateFile", path, ms, 0);
    return h;
}

void close_ent(CacheEnt &e) {
    if (e.h == nullptr || e.h == INVALID_HANDLE_VALUE) {
        e.h = nullptr;
        return;
    }
    const long long t0 = now_us();
    CloseHandle(e.h);
    const DWORD ms = (DWORD)((now_us() - t0) / 1000);
    if (ms > SLOW_MS) report_slow("CloseHandle", e.path, ms, 0);
    e.h = nullptr;
}

CacheEnt *get_ent(const char *path) {
    CacheEnt *free_e = nullptr, *lru = &g_cache[0];
    for (int i = 0; i < CACHE_N; ++i) {
        CacheEnt &e = g_cache[i];
        if (e.h) {
            if (lstrcmpiA(e.path, path) == 0) return &e;
            if ((LONG)(e.last_tick - lru->last_tick) < 0 || lru->h == nullptr) lru = &e;
        } else if (!free_e) {
            free_e = &e;
        }
    }
    CacheEnt *slot = free_e ? free_e : lru;
    if (!free_e) close_ent(*slot);
    HANDLE h = open_timed(path);
    if (h == INVALID_HANDLE_VALUE) return nullptr;
    slot->h = h;
    lstrcpynA(slot->path, path, MAX_PATH);
    slot->last_tick = GetTickCount();
    return slot;
}

// Write `len` bytes for `path`; applies the rotation cap first. Never throws, never blocks forever
// beyond what the OS call itself does.
void write_file_bytes(const char *path, const char *buf, int len, long long cap) {
    if (len <= 0) return;
    for (int attempt = 0; attempt < 2; ++attempt) {
        CacheEnt *e = get_ent(path);
        if (e == nullptr) return;
        if (cap > 0 && mh_log_handle_over_cap(e->h, cap)) {
            close_ent(*e);
            if (mh_log_rotate(path)) {
                e = get_ent(path);
                if (e == nullptr) return;
            } else {
                e = get_ent(path); // the rename lost: keep appending to the same file
                if (e == nullptr) return;
            }
        }
        const long long t0    = now_us();
        DWORD           wrote = 0;
        const BOOL      ok    = WriteFile(e->h, buf, (DWORD)len, &wrote, nullptr);
        const DWORD     ms    = (DWORD)((now_us() - t0) / 1000);
        if (ms > SLOW_MS) report_slow("WriteFile", path, ms, len);
        e->last_tick = GetTickCount();
        if (ok) return;
        close_ent(*e); // stale handle (folder removed, disk hiccup): reopen once
    }
}

void flush_wbuf() {
    if (g_wlen > 0) {
        write_file_bytes(g_wpath, g_wbuf, g_wlen, g_wcap);
        g_wlen = 0;
    }
}

// mp:LOG2: the writer-side CREATE_ALWAYS of a BIN_CREATE record. Any cached append handle on the same
// file is closed first (its position and its sharing would otherwise fight the truncation), then the
// file is created/truncated and closed again; the payload that follows reopens it for append.
void create_truncate(const char *path) {
    for (int i = 0; i < CACHE_N; ++i)
        if (g_cache[i].h && lstrcmpiA(g_cache[i].path, path) == 0) close_ent(g_cache[i]);
    const long long t0 = now_us();
    HANDLE          h  = CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, nullptr,
                                     CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h != INVALID_HANDLE_VALUE) CloseHandle(h);
    const DWORD ms = (DWORD)((now_us() - t0) / 1000);
    if (ms > SLOW_MS) report_slow("CreateFile(truncate)", path, ms, 0);
}

void process(Node *n) {
    if (ends_with_ci(n->path(), "mh_net.log")) lstrcpynA(g_net_log, n->path(), MAX_PATH);
    if (n->cap == MH_LOGQ_CAP_BIN_CREATE) {
        flush_wbuf(); // an older generation of this file may still be staged
        create_truncate(n->path());
        if (n->len > 0) write_file_bytes(n->path(), n->data(), n->len, 0); // the header goes in at once
        // ...and the handle is CLOSED again before the record counts as done. A create record is a whole
        // file or a header, and its reader may open it with FILE_SHARE_READ alone (map_transfer resolve()
        // does): a write handle cached here made that open fail with a sharing violation, the stored map
        // read as "missing", and the client re-JOINed with its own differing file (x2a/map_absent red,
        // 2026-10-04). Appends that follow reopen it -- one extra open per recording, not per record.
        for (int i = 0; i < CACHE_N; ++i)
            if (g_cache[i].h && lstrcmpiA(g_cache[i].path, n->path()) == 0) close_ent(g_cache[i]);
        return;
    }
    if (n->len <= 0) {
        if (n->cap == MH_LOGQ_CAP_ROTATE_NOW) { // rotate-now record (mh_logq_rotate_now): order-preserving
            flush_wbuf();
            for (int i = 0; i < CACHE_N; ++i)
                if (g_cache[i].h && lstrcmpiA(g_cache[i].path, n->path()) == 0) close_ent(g_cache[i]);
            mh_log_rotate(n->path());
        }
        return;
    }
    if (g_wlen > 0 && (lstrcmpiA(g_wpath, n->path()) != 0 || g_wlen + n->len > WBUF_CAP || n->cap != g_wcap))
        flush_wbuf();
    if (n->len > WBUF_CAP) {
        write_file_bytes(n->path(), n->data(), n->len, n->cap);
        return;
    }
    if (g_wlen == 0) {
        lstrcpynA(g_wpath, n->path(), MAX_PATH);
        g_wcap = n->cap;
    }
    CopyMemory(g_wbuf + g_wlen, n->data(), (SIZE_T)n->len);
    g_wlen += n->len;
}

// Pop one node. Returns the payload-bearing node (which becomes the new stub) and, via `old`, the
// previous stub the caller may free. nullptr = nothing linked yet.
Node *pop(Node **old) {
    Node *tail = g_tail;
    Node *next = tail->next;
    if (next == nullptr) return nullptr;
    g_tail = next;
    *old   = tail;
    return next;
}

bool queue_empty_hint() { return g_tail->next == nullptr; }

// One pass: drain everything linked right now. `free_nodes` false in crash mode.
int consume_pass(bool free_nodes) {
    int count = 0;
    for (;;) {
        Node *old = nullptr;
        Node *n   = pop(&old);
        if (n == nullptr) break;
        process(n);
        ++count;
        // The byte budget is released on EVERY pass, freed or not: a non-freeing drain that kept the bytes
        // counted would shrink the bound for good, and once it reached zero every later line was dropped
        // (logrottest went red under gate load: a flush that ran before the writer thread started took the
        // inline path, and eight 1 MB drains filled the 8 MB bound).
        InterlockedExchangeAdd((n->internal & NODE_BIN) ? &g_bin_bytes : &g_bytes,
                               -((LONG)sizeof(Node) + n->pathlen + 1 + n->len));
        if (free_nodes) {
            // `n` is the new stub; its payload is consumed but the node itself must outlive the pop of
            // its successor, so free the PREVIOUS stub (never the static one).
            if (old != &g_stub) HeapFree(g_heap, 0, old);
        }
        // Count a record as done only when its bytes are on disk: done after the coalesced flush.
    }
    flush_wbuf();
    return count;
}

void emit_drop_line() {
    if (g_net_log[0] == '\0') return;
    const LONG total = g_dropped_total;
    const LONG fresh = total - g_dropped_reported;
    if (fresh > 0) {
        g_dropped_reported = total;
        char  stamp[24];
        int   sn = mh_log_stamp(stamp);
        char  line[96];
        int   ln = wsprintfA(line, "; log sink: queue full, dropped %ld line(s) (%ld total)\n", fresh, total);
        Node *n  = make_node(g_net_log, stamp, sn, line, ln, 0, NODE_INTERNAL);
        if (n) push_node(n);
    }
    // mp:LOG2: a dropped BINARY record means a corrupt recording, so it gets its own, louder line.
    const LONG btotal = g_bin_dropped;
    const LONG bfresh = btotal - g_bin_reported;
    if (bfresh > 0) {
        g_bin_reported = btotal;
        char  stamp[24];
        int   sn = mh_log_stamp(stamp);
        char  line[128];
        int   ln = wsprintfA(line, "; log sink: BINARY queue full, dropped %ld record(s) (%ld total) -- a recording is now incomplete\n",
                             bfresh, btotal);
        Node *n  = make_node(g_net_log, stamp, sn, line, ln, 0, NODE_INTERNAL);
        if (n) push_node(n);
    }
}

void close_idle(DWORD now, bool all) {
    for (int i = 0; i < CACHE_N; ++i)
        if (g_cache[i].h && (all || (DWORD)(now - g_cache[i].last_tick) >= IDLE_CLOSE_MS)) close_ent(g_cache[i]);
}

bool any_open() {
    for (int i = 0; i < CACHE_N; ++i)
        if (g_cache[i].h) return true;
    return false;
}

bool take_consumer(DWORD ms) {
    const LONG  tid = (LONG)GetCurrentThreadId();
    const DWORD t0  = GetTickCount();
    for (;;) {
        const LONG prev = InterlockedCompareExchange(&g_consumer, tid, 0);
        if (prev == 0 || prev == tid) return true;
        // The owner may be a writer that ExitProcess killed mid-pass: its thread handle is signalled and
        // nobody will ever release the flag. Steal it (the staged bytes in g_wbuf are flushed by the
        // caller) instead of waiting out the whole bound for a thread that cannot run again.
        if (prev == g_writer_tid && g_thread != nullptr && WaitForSingleObject(g_thread, 0) == WAIT_OBJECT_0 &&
            InterlockedCompareExchange(&g_consumer, tid, prev) == prev)
            return true;
        if ((DWORD)(GetTickCount() - t0) >= ms) return false;
        Sleep(1);
    }
}

void release_consumer() { InterlockedExchange(&g_consumer, 0); }

// Account for a finished pass: everything popped is now on disk.
void note_done(int count) {
    if (count > 0) InterlockedExchangeAdd(&g_done, count);
}

DWORD WINAPI writer_main(LPVOID) {
    g_writer_tid = (LONG)GetCurrentThreadId();
    InterlockedExchange(&g_writer_running, 1);
    while (!g_stop) {
        if (g_hold) { // selftest hook only (mh_logq_test_hold); never set in the game
            bool held = g_hold == 2 && take_consumer(INFINITE);
            while (g_hold && !g_stop) Sleep(1);
            if (held) release_consumer();
            continue;
        }
        if (take_consumer(INFINITE)) {
            note_done(consume_pass(true));
            emit_drop_line();
            note_done(consume_pass(true));
            close_idle(GetTickCount(), false);
            release_consumer();
        }
        InterlockedExchange(&g_sleeping, 1);
        MemoryBarrier();
        if (!queue_empty_hint()) {
            InterlockedExchange(&g_sleeping, 0);
            continue;
        }
        WaitForSingleObject(g_event, any_open() ? 250 : INFINITE);
        InterlockedExchange(&g_sleeping, 0);
    }
    return 0;
}

// ---- flush / drain -------------------------------------------------------------------------------
// Normal flush: ask the live writer to run and wait for the done-counter to catch the enqueue-counter
// as it stood at the call. A dead/absent writer is drained inline.
// "Alive" means RUNNING: a writer created from DllMain does not start until the loader lock drops, and
// a flush issued in that window must drain inline instead of waiting on a thread that cannot run.
bool writer_alive() {
    return g_thread != nullptr && g_writer_running && WaitForSingleObject(g_thread, 0) == WAIT_TIMEOUT;
}

// `crash`: the faulting thread may hold the heap lock, so free nothing and make no new nodes. A plain
// flush with no running writer is NOT that case and frees normally (shutdown passes crash: see there).
void drain_inline(DWORD ms, bool closeAll, bool crash) {
    if (!take_consumer(ms)) return;
    const bool prev = g_crash_mode;
    g_crash_mode    = crash || prev;
    flush_wbuf(); // bytes a killed/interrupted writer had staged but not yet written
    const DWORD t0 = GetTickCount();
    for (;;) {
        note_done(consume_pass(!g_crash_mode));
        // Gap check: a producer between exchange and link. head != tail means records exist.
        if (g_head == g_tail) break;
        if ((DWORD)(GetTickCount() - t0) >= ms) break;
        Sleep(0);
    }
    if (closeAll) close_idle(0, true);
    g_crash_mode = prev;
    release_consumer();
}

void flush_impl(DWORD ms) {
    if (!writer_alive()) {
        drain_inline(ms, false, false);
        return;
    }
    const LONG  target = g_enq; // everything enqueued before this call
    const DWORD t0     = GetTickCount();
    for (;;) {
        if ((LONG)(g_done - target) >= 0) return;
        if (g_event) SetEvent(g_event);
        if ((DWORD)(GetTickCount() - t0) >= ms) return;
        Sleep(1);
    }
}

void crash_drain_impl(DWORD ms) { drain_inline(ms, false, true); }

long enq_count_impl() { return g_enq; }
long done_count_impl() { return g_done; }

} // namespace

// ---- public ----------------------------------------------------------------------------------------
void mh_logq_init(void) {
    if (InterlockedCompareExchange(&g_init, 1, 0) != 0) return;
    QueryPerformanceFrequency(&g_qpc_freq);
    if (g_qpc_freq.QuadPart == 0) g_qpc_freq.QuadPart = 1000000;
    g_heap  = HeapCreate(0, 64 * 1024, 0);
    g_event = CreateEventA(nullptr, FALSE, FALSE, nullptr);
    if (g_heap == nullptr || g_event == nullptr) {
        InterlockedExchange(&g_init, 0);
        return; // callers fall back to synchronous appends
    }
    char name[64];
    wsprintfA(name, "Local\\mh_logq%u_%lu", (unsigned)MH_LOGQ_ABI, GetCurrentProcessId());
    g_map = CreateFileMappingA(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE, 0, sizeof(MH_LogQApi), name);
    if (g_map != nullptr && GetLastError() != ERROR_ALREADY_EXISTS) {
        g_api = (MH_LogQApi *)MapViewOfFile(g_map, FILE_MAP_WRITE, 0, 0, sizeof(MH_LogQApi));
        if (g_api) {
            g_api->size        = sizeof(MH_LogQApi);
            g_api->write2      = write2_impl;
            g_api->flush       = flush_impl;
            g_api->crash_drain = crash_drain_impl;
            g_api->enq_count   = enq_count_impl;
            g_api->done_count  = done_count_impl;
            MemoryBarrier();
            g_api->abi = MH_LOGQ_ABI; // last: readers key on it
        }
    }
    if (g_api == nullptr) {
        // Another image already owns the sink for this process (or the mapping failed). Do not run a
        // second one; clients find the owner's table through the mapping.
        return;
    }
    // CreateThread from DllMain is fine so long as nothing waits on it here (same pattern as the crash
    // marker's timer thread); it blocks on the loader lock until DllMain returns.
    g_thread = CreateThread(nullptr, 0, writer_main, nullptr, 0, nullptr);
    InterlockedExchange(&g_init, 2);
}

void mh_logq_shutdown(DWORD ms) {
    if (g_init != 2 || g_api == nullptr) return;
    const bool live = writer_alive();
    InterlockedExchange(&g_stop, 1);
    if (g_event) SetEvent(g_event);
    if (live) WaitForSingleObject(g_thread, ms);
    // crash-mode rules at exit too: ExitProcess may have killed a producer inside HeapAlloc on g_heap,
    // so its lock can be held forever; nothing needs freeing on the way out.
    drain_inline(ms, true, true);
    InterlockedExchange(&g_down, 1);
}

const MH_LogQApi *mh_logq_local_api(void) { return g_api; }

void mh_logq_stats(MH_LogQStats *out) {
    if (!out) return;
    out->enqueued         = g_enq;
    out->written          = g_done;
    out->dropped          = g_dropped_total;
    out->queued_bytes     = g_bytes;
    out->slow_ops         = g_slow_ops;
    out->bin_queued_bytes = g_bin_bytes;
    out->bin_dropped      = g_bin_dropped;
}

// SELFTEST HOOK (log_sink_selftest.cpp): park the writer so the queue-full and crash-drain arms are
// deterministic. mode 0 = run, 1 = parked without the consumer flag (a writer that is merely behind),
// 2 = parked HOLDING the consumer flag (a writer wedged in a hung WriteFile). Never called in the game.
void mh_logq_test_hold(int mode) {
    InterlockedExchange(&g_hold, mode);
    if (g_event) SetEvent(g_event);
}

// C-linkage entries for mh.c's DllMain (a C file) and the crash handler (a TU that must stay
// dependency-light, so it declares these two by hand).
extern "C" void MH_LogQ_Init(void) { mh_logq_init(); }
extern "C" void MH_LogQ_Shutdown(unsigned long ms) { mh_logq_shutdown((DWORD)ms); }
// The crash handler's entry (mh/seams/crash_marker.cpp).
extern "C" void MH_LogQ_CrashDrain(unsigned long ms) {
    const MH_LogQApi *a = mh_logq_local_api();
    if (a && a->crash_drain) a->crash_drain((DWORD)ms);
}
