//! The settings schema (dist RL13): what rows exist, where they live and how they behave.
//!
//! Two JSON documents are merged:
//!
//! * `settings_schema.json` -- GENERATED by `tools/gen_ini_registry.py` from `ini_keys.def`: one row
//!   per player-class ini key (`section`/`key`/`type`/`default`/`label`/`subtab`/`options`/flags).
//! * `launcher_schema.json` -- HAND-WRITTEN, same row shape: rows with `"store": "launcher"` and a
//!   `field` (settings that live in `launcher.toml`, not the ini), plus an `overrides` object keyed
//!   `section.key` (or `launcher.<field>`) that adds what the generated file cannot say: a `group`
//!   for the Diagnostics page, a `control`, int `min`/`max`, a value `provider`, a `page`, `hidden`.
//!
//! Adding a setting is a registry row plus strings in `i18n/*.toml`; nothing here or in `render.rs`
//! names a key. A row whose `subtab` is not in the document's list simply gets a tab of its own
//! (labelled `subtab.<id>`).

use std::collections::BTreeMap;

use serde::Deserialize;
use serde_json::Value;

/// The generated game-ini schema, embedded.
pub const GAME_SCHEMA_JSON: &str = include_str!("../../settings_schema.json");
/// The hand-written launcher schema, embedded.
pub const LAUNCHER_SCHEMA_JSON: &str = include_str!("../../launcher_schema.json");

/// The sub-tab that is not a Settings tab: its rows render on the Diagnostics page.
pub const DIAGNOSTICS_SUBTAB: &str = "diagnostics";

/// Where a row's value lives.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Store {
    /// `[section] key` in the game's `mh_net.ini`.
    Ini { section: String, key: String },
    /// A field of `launcher.toml`, reached through `LauncherStore`.
    Launcher { field: String },
}

/// The value domain, from the schema's `type`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Enum,
    Bool,
    Int,
    Str,
    Hotkey,
}

/// How the row is drawn; `Auto` picks from `Kind` and the option count.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum Control {
    #[default]
    Auto,
    /// Force a combo box even for a short option list.
    Combo,
    /// Segmented mode choice with the companion address box (the relay row).
    Relay,
}

/// A source of run-time option lists.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Provider {
    /// `""` (English) plus the packs found under `<game>\lang\`.
    LangPacks,
}

/// Which page a row renders on.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Page {
    Settings,
    Diagnostics,
}

/// One setting.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Row {
    /// Stable id: `section.key` for an ini row, `launcher.<field>` for a launcher row.
    pub id: String,
    pub store: Store,
    pub kind: Kind,
    /// Canonical text: bools are `"0"`/`"1"`.
    pub default: String,
    /// The schema's label id; string keys are `setting.<label>[.hint|.opt.<value>]`.
    pub label: String,
    pub subtab: String,
    pub options: Vec<String>,
    pub experimental: bool,
    pub restart: bool,
    pub pending: bool,
    /// Section heading on the Diagnostics page (`compat` -> "Compatibility").
    pub group: Option<String>,
    pub control: Control,
    pub min: Option<i64>,
    pub max: Option<i64>,
    /// Int values accepted although they lie outside `min..=max` (`video.fps_limit`: 0 = unlimited).
    pub allow: Vec<i64>,
    pub provider: Option<Provider>,
    pub page: Page,
    /// Not rendered as a row (derived at provision time, or drawn by a companion control).
    pub hidden: bool,
    /// For `Control::Relay`: the row id of the address box drawn under the mode choice.
    pub companion: Option<String>,
    /// Shown only while row `.0` has value `.1`.
    pub visible_if: Option<(String, String)>,
    /// After an Apply that changed this row, also write the value to this launcher field
    /// (the Language row mirrors the chosen pack into `ui_lang`).
    pub mirror: Option<String>,
}

impl Row {
    pub fn label_key(&self) -> String {
        format!("setting.{}", self.label)
    }
    pub fn hint_key(&self) -> String {
        format!("setting.{}.hint", self.label)
    }
    pub fn option_key(&self, value: &str) -> String {
        format!("setting.{}.opt.{value}", self.label)
    }
    pub fn is_launcher(&self) -> bool {
        matches!(self.store, Store::Launcher { .. })
    }
}

/// A Settings sub-tab.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SubTab {
    pub id: String,
    /// The i18n key (`subtab.display`).
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Schema {
    pub subtabs: Vec<SubTab>,
    pub rows: Vec<Row>,
}

// ---- JSON shapes ---------------------------------------------------------------------------------

#[derive(Debug, Default, Clone, Deserialize)]
struct Extras {
    group: Option<String>,
    control: Option<String>,
    min: Option<i64>,
    max: Option<i64>,
    #[serde(default)]
    allow: Vec<i64>,
    provider: Option<String>,
    page: Option<String>,
    hidden: Option<bool>,
    companion: Option<String>,
    visible_if: Option<VisibleIf>,
    mirror: Option<String>,
    /// Insert this row before the row with this id (ignored when that row does not exist).
    before: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
struct VisibleIf {
    row: String,
    equals: String,
}

#[derive(Debug, Deserialize)]
struct RawRow {
    #[serde(default)]
    store: Option<String>,
    section: Option<String>,
    key: Option<String>,
    field: Option<String>,
    #[serde(rename = "type")]
    ty: String,
    #[serde(default)]
    default: Value,
    label: String,
    subtab: String,
    #[serde(default)]
    options: Vec<Value>,
    #[serde(default)]
    experimental: bool,
    #[serde(default)]
    restart: bool,
    #[serde(default)]
    pending: bool,
    #[serde(flatten)]
    extras: Extras,
}

#[derive(Debug, Deserialize)]
struct RawSubTab {
    id: String,
    label: String,
}

#[derive(Debug, Deserialize)]
struct RawDoc {
    #[serde(default)]
    schema_version: u32,
    #[serde(default)]
    subtabs: Vec<RawSubTab>,
    #[serde(default)]
    settings: Vec<RawRow>,
    #[serde(default)]
    overrides: BTreeMap<String, Extras>,
}

fn value_text(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Bool(b) => if *b { "1" } else { "0" }.to_string(),
        Value::Null => String::new(),
        other => other.to_string(),
    }
}

fn parse_kind(t: &str) -> Result<Kind, String> {
    Ok(match t {
        "enum" => Kind::Enum,
        "bool" => Kind::Bool,
        "int" => Kind::Int,
        "string" => Kind::Str,
        "hotkey" => Kind::Hotkey,
        other => return Err(format!("unknown row type {other:?}")),
    })
}

impl Schema {
    /// The committed schema (generated game rows + the launcher's own). The two files are checked
    /// by `builtin_schema_parses` below and by `tools/gen_ini_registry.py --check`.
    pub fn builtin() -> Schema {
        Schema::from_json(GAME_SCHEMA_JSON, Some(LAUNCHER_SCHEMA_JSON))
            .expect("committed settings schemas must parse")
    }

    /// Parse and merge. `launcher` rows come after the game rows; its `overrides` apply to either.
    pub fn from_json(game: &str, launcher: Option<&str>) -> Result<Schema, String> {
        let mut docs = vec![serde_json::from_str::<RawDoc>(game)
            .map_err(|e| format!("settings_schema.json: {e}"))?];
        if let Some(l) = launcher {
            docs.push(
                serde_json::from_str::<RawDoc>(l)
                    .map_err(|e| format!("launcher_schema.json: {e}"))?,
            );
        }
        let mut overrides: BTreeMap<String, Extras> = BTreeMap::new();
        let mut subtabs: Vec<SubTab> = Vec::new();
        let mut raw_rows: Vec<RawRow> = Vec::new();
        for d in docs {
            if d.schema_version > 1 {
                return Err(format!("unsupported schema_version {}", d.schema_version));
            }
            for t in d.subtabs {
                if !subtabs.iter().any(|s| s.id == t.id) {
                    subtabs.push(SubTab {
                        id: t.id,
                        label: t.label,
                    });
                }
            }
            overrides.extend(d.overrides);
            raw_rows.extend(d.settings);
        }

        let mut rows: Vec<Row> = Vec::new();
        let mut befores: Vec<(String, String)> = Vec::new();
        for r in raw_rows {
            let kind = parse_kind(&r.ty)?;
            let (id, store) = match r.store.as_deref() {
                Some("launcher") => {
                    let field = r.field.clone().ok_or("launcher row without `field`")?;
                    (format!("launcher.{field}"), Store::Launcher { field })
                }
                None | Some("ini") => {
                    let section = r.section.clone().ok_or("ini row without `section`")?;
                    let key = r.key.clone().ok_or("ini row without `key`")?;
                    (format!("{section}.{key}"), Store::Ini { section, key })
                }
                Some(other) => return Err(format!("unknown store {other:?}")),
            };
            // Row-level extras first, then the override of the same id wins field by field.
            let ov = overrides.get(&id).cloned().unwrap_or_default();
            let ex = r.extras;
            let pick_s = |a: Option<String>, b: Option<String>| a.or(b);
            let group = pick_s(ov.group, ex.group);
            let control = match pick_s(ov.control, ex.control).as_deref() {
                None | Some("auto") => Control::Auto,
                Some("combo") => Control::Combo,
                Some("relay") => Control::Relay,
                Some(o) => return Err(format!("{id}: unknown control {o:?}")),
            };
            let provider = match pick_s(ov.provider, ex.provider).as_deref() {
                None => None,
                Some("lang_packs") => Some(Provider::LangPacks),
                Some(o) => return Err(format!("{id}: unknown provider {o:?}")),
            };
            let page = match pick_s(ov.page, ex.page).as_deref() {
                Some("diagnostics") => Page::Diagnostics,
                Some("settings") => Page::Settings,
                None if r.subtab == DIAGNOSTICS_SUBTAB => Page::Diagnostics,
                None => Page::Settings,
                Some(o) => return Err(format!("{id}: unknown page {o:?}")),
            };
            let default = {
                let d = value_text(&r.default);
                if kind == Kind::Bool {
                    match d.to_ascii_lowercase().as_str() {
                        "1" | "true" | "on" | "yes" => "1".to_string(),
                        _ => "0".to_string(),
                    }
                } else {
                    d
                }
            };
            let vis = ov.visible_if.or(ex.visible_if);
            if let Some(b) = pick_s(ov.before, ex.before) {
                befores.push((id.clone(), b));
            }
            rows.push(Row {
                id,
                store,
                kind,
                default,
                label: r.label,
                subtab: r.subtab.clone(),
                options: r.options.iter().map(value_text).collect(),
                experimental: r.experimental,
                restart: r.restart,
                pending: r.pending,
                group,
                control,
                min: ov.min.or(ex.min),
                max: ov.max.or(ex.max),
                allow: if ov.allow.is_empty() {
                    ex.allow.clone()
                } else {
                    ov.allow.clone()
                },
                provider,
                page,
                hidden: ov.hidden.or(ex.hidden).unwrap_or(false),
                companion: pick_s(ov.companion, ex.companion),
                visible_if: vis.map(|v| (v.row, v.equals)),
                mirror: pick_s(ov.mirror, ex.mirror),
            });
        }
        // `before` placement: move the row in front of its anchor, when the anchor exists.
        for (id, anchor) in befores {
            let (Some(from), Some(_)) = (
                rows.iter().position(|r| r.id == id),
                rows.iter().position(|r| r.id == anchor),
            ) else {
                continue;
            };
            let row = rows.remove(from);
            let to = rows
                .iter()
                .position(|r| r.id == anchor)
                .unwrap_or(rows.len());
            rows.insert(to, row);
        }
        // A row naming a sub-tab nobody declared gets a tab of its own.
        for r in &rows {
            if !subtabs.iter().any(|s| s.id == r.subtab) {
                subtabs.push(SubTab {
                    id: r.subtab.clone(),
                    label: format!("subtab.{}", r.subtab),
                });
            }
        }
        let mut ids: Vec<&str> = rows.iter().map(|r| r.id.as_str()).collect();
        ids.sort_unstable();
        if let Some(w) = ids.windows(2).find(|w| w[0] == w[1]) {
            return Err(format!("duplicate row id {}", w[0]));
        }
        Ok(Schema { subtabs, rows })
    }

    pub fn row(&self, id: &str) -> Option<&Row> {
        self.rows.iter().find(|r| r.id == id)
    }

    /// The Settings sub-tabs in display order: every sub-tab with at least one Settings-page row
    /// that is not hidden. The diagnostics sub-tab never appears (its rows have their own page).
    pub fn settings_subtabs(&self) -> Vec<&SubTab> {
        self.subtabs
            .iter()
            .filter(|t| {
                self.rows
                    .iter()
                    .any(|r| r.subtab == t.id && r.page == Page::Settings && !r.hidden)
            })
            .collect()
    }

    /// Visible rows of one Settings sub-tab, in schema order.
    pub fn rows_in_subtab<'a>(&'a self, subtab: &'a str) -> impl Iterator<Item = &'a Row> + 'a {
        self.rows
            .iter()
            .filter(move |r| r.subtab == subtab && r.page == Page::Settings && !r.hidden)
    }

    /// Rows for the Diagnostics page, grouped by `group` (ungrouped first, `None` -> `""`), in
    /// schema order within a group and first-appearance order between groups.
    pub fn diagnostics_groups(&self) -> Vec<(String, Vec<&Row>)> {
        let mut out: Vec<(String, Vec<&Row>)> = Vec::new();
        for r in self
            .rows
            .iter()
            .filter(|r| r.page == Page::Diagnostics && !r.hidden)
        {
            let g = r.group.clone().unwrap_or_default();
            match out.iter_mut().find(|(n, _)| *n == g) {
                Some((_, v)) => v.push(r),
                None => out.push((g, vec![r])),
            }
        }
        // Stable: ungrouped first, the rest in first-appearance order.
        out.sort_by_key(|(g, _)| !g.is_empty());
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_schema_parses() {
        let s = Schema::builtin();
        assert!(s.rows.len() >= 20, "{} rows", s.rows.len());
        // Ids are unique (from_json enforces it) and every ini row is spelled section.key.
        for r in &s.rows {
            match &r.store {
                Store::Ini { section, key } => assert_eq!(r.id, format!("{section}.{key}")),
                Store::Launcher { field } => assert_eq!(r.id, format!("launcher.{field}")),
            }
        }
    }

    #[test]
    fn settings_subtabs_follow_the_plan() {
        let s = Schema::builtin();
        let ids: Vec<&str> = s.settings_subtabs().iter().map(|t| t.id.as_str()).collect();
        assert_eq!(ids, ["display", "language", "multiplayer", "updates"]);
    }

    #[test]
    fn the_launcher_rows_land_where_the_plan_says() {
        let s = Schema::builtin();
        let ch = s.row("launcher.channel").expect("channel row");
        assert_eq!(ch.subtab, "updates");
        assert_eq!(ch.options, ["stable", "latest"]);
        let dc = s.row("launcher.discord").expect("discord row");
        assert_eq!((dc.subtab.as_str(), dc.kind), ("updates", Kind::Bool));
        let rm = s.row("launcher.relay_mode").expect("relay mode row");
        assert_eq!(rm.subtab, "multiplayer");
        assert_eq!(rm.control, Control::Relay);
        assert_eq!(rm.companion.as_deref(), Some("launcher.relay_custom"));
        assert!(s.row("launcher.relay_custom").unwrap().hidden);
        // The ini's [net] relay is derived at provision time and never edited directly.
        assert!(s.row("net.relay").unwrap().hidden);
    }

    #[test]
    fn overrides_apply_by_key() {
        let s = Schema::builtin();
        let port = s.row("net.port").unwrap();
        assert_eq!((port.min, port.max), (Some(1024), Some(65535)));
        assert_eq!(
            s.row("lang.pack").unwrap().provider,
            Some(Provider::LangPacks)
        );
        for id in ["video.backend", "input.backend"] {
            let r = s.row(id).unwrap();
            assert_eq!(r.group.as_deref(), Some("compat"));
            assert_eq!(r.page, Page::Diagnostics);
        }
        let groups = s.diagnostics_groups();
        assert_eq!(groups[0].0, "", "ungrouped rows (log level) come first");
        assert_eq!(groups[1].0, "compat");
    }

    /// RL13 done_when: a new registry row appears in the right sub-tab with no launcher code change.
    #[test]
    fn a_synthetic_registry_key_appears_in_its_subtab_with_no_code_change() {
        let mut doc: Value = serde_json::from_str(GAME_SCHEMA_JSON).unwrap();
        let rows = doc["settings"].as_array_mut().unwrap();
        rows.push(serde_json::json!({
            "section": "video", "key": "synthetic_probe", "type": "bool", "default": 1,
            "label": "video.synthetic_probe", "subtab": "multiplayer", "options": [],
            "experimental": true, "restart": true, "pending": false
        }));
        rows.push(serde_json::json!({
            "section": "future", "key": "knob", "type": "int", "default": 3,
            "label": "future.knob", "subtab": "brand_new_tab", "options": [],
            "experimental": false, "restart": false, "pending": false
        }));
        let s = Schema::from_json(&doc.to_string(), Some(LAUNCHER_SCHEMA_JSON)).unwrap();
        let in_mp: Vec<&str> = s
            .rows_in_subtab("multiplayer")
            .map(|r| r.id.as_str())
            .collect();
        assert!(in_mp.contains(&"video.synthetic_probe"), "{in_mp:?}");
        let r = s.row("video.synthetic_probe").unwrap();
        assert!(r.experimental && r.restart);
        assert_eq!(r.default, "1");
        // An undeclared sub-tab id becomes a tab of its own, labelled subtab.<id>.
        let tabs = s.settings_subtabs();
        let t = tabs
            .iter()
            .find(|t| t.id == "brand_new_tab")
            .expect("new tab");
        assert_eq!(t.label, "subtab.brand_new_tab");
        assert_eq!(s.rows_in_subtab("brand_new_tab").count(), 1);
    }

    #[test]
    fn bad_documents_are_rejected_not_half_applied() {
        assert!(Schema::from_json("{", None).is_err());
        let bad_type =
            r#"{"settings":[{"section":"a","key":"b","type":"nope","label":"a.b","subtab":"x"}]}"#;
        assert!(Schema::from_json(bad_type, None).is_err());
        let dup = r#"{"settings":[
            {"section":"a","key":"b","type":"int","label":"a.b","subtab":"x"},
            {"section":"a","key":"b","type":"int","label":"a.b","subtab":"x"}]}"#;
        assert!(Schema::from_json(dup, None)
            .unwrap_err()
            .contains("duplicate"));
        let v2 = r#"{"schema_version":2,"settings":[]}"#;
        assert!(Schema::from_json(v2, None).is_err());
    }
}
