#!/usr/bin/env python3
"""check_publishable.py -- fork F5A: the publishability ledger's gate.

WHAT THIS IS FOR. The public cut (F5M) has to produce a tree that is a DERIVED set, not a pile of
per-file judgement calls made on the day. `tools/data/publish_ledger.json` is that derivation: an
ordered list of rules, first-match-wins, giving every path `git ls-files` reports exactly one
disposition. This script is the half that makes the ledger falsifiable.

    publish        goes into the public tree
    withhold       does not, and is not expected to
    user_pending   does not YET -- a question (Q2..Q7) is the user's to answer; the row records
                   the recommendation and the reasoning so the answer is a yes/no, not a research
                   task. F5M cannot close while any of these remain.
    publish_after  does not YET -- a tracker item (F5B/F5C) must change the BYTES first (regenerate
                   a fixture, scrub an IP). The row flips when the file does, not when the plan does.

THE PUBLISH SET IS `disposition == publish`, NOTHING ELSE. `--publish-list` emits it; F5C proves
the build on it and F5M cuts from it.

---- WHY THE LEDGER IS ENUMERATED FROM GIT AND NOT FROM THE DOC ----

The fork inventory sec 3 was the previous ledger. It was measured four milestones ago, listed
by hand, and by HEAD it had drifted: it never held the two largest retail-byte surfaces in the tree
(191,736 expect-bytes across 40 patch manifests; 27 transcribed CRT bodies), and its verdict on the
LZW fixtures predated the user's own ruling on their source. Re-enumerating from it was the named
risk on the F5A item. So this script calls `git ls-files` every run and matches THAT against the
rules. A path the ledger has no rule for is a FAILURE -- a file added tomorrow fails closed rather
than defaulting to publishable.

---- THE THREE FALSIFIABILITY ARMS (the F4G libref_asset_dispositions precedent) ----

A declaration that cannot be proven wrong is decoration. Three arms, all in `--check`:

  1. UNCOVERED      a tracked path no rule matches            -> FAIL (the ledger cannot fall behind)
  2. DEAD RULE      a rule matching zero paths                -> FAIL (a rule cannot outlive its files)
  3. COUNT          rules account for every path git reports  -> FAIL (no silently stale path list)

and one more in `--closure`:

  4. STALE EXCEPTION  a declared closure exception that no longer reproduces -> FAIL

Arm 4 made the F5C handoff self-closing, and it worked exactly as designed: when F5C repointed
gen_lzw_fixtures.py at the committed save and flipped the `lzw-fixtures` row to `publish`, this
check went RED on the now-stale `save-selftest-lzw` exception until that row was deleted too
(2026-09-14). The ledger cannot quietly keep an excuse it no longer needs.

---- THE CLOSURE ARM: the contradiction class F5C exists for ----

The ratified done_when says a clean clone BUILDS. The publish ledger says some files stay behind.
Those two can contradict each other silently, and they did: save_selftest.cpp:21 unconditionally
`#include`s sv1_lzw_fixtures.gen.h, which the F0 ledger ruled unpublishable -- so the public tree
as specified did not compile (F5C fixed it at the source, by making the header derivable from a
committed save). Detecting this is cheap HERE and expensive later, so `--closure` scans the
PUBLISHED sources for build/run edges into non-published paths:

    C/C++   `#include "X"` lines, X resolved by path-suffix against the tracked file set
    Python  string constants (parsed with `ast`, so comments never count and docstrings are
            excluded) that name a tracked non-published path

save_selftest.cpp:21 is still the KNOWN-POSITIVE CONTROL, but no longer as a violation: F5C made
the header publishable, so `--selftest` now re-runs the detector over the REAL tree under a
SYNTHETIC ledger that withholds that one header, and requires the same real edge back at the same
real line. Phrasing it against the scanner rather than against a ledger verdict is what keeps the
control from being retired by the very fix it was watching for. `--selftest` also plants violations
of every shape in a temp tree. A scan that finds nothing and a scan that is broken look identical,
which is why the control and the plants both exist.

PROSE CITATIONS ARE NOT BUILD EDGES. A comment saying "GENERATED by tools/oneoff/...py" is F5E's  # CITATION-OK
citation re-authoring, not a compile dependency, and this detector deliberately does not see it --
that is why the C/C++ arm reads `#include` lines only and the Python arm goes through `ast`.

usage:
  python tools/check_publishable.py                 # arms 1-3 (exit 1 on violation)
  python tools/check_publishable.py --closure       # arm 4 + the build/run-edge scan
  python tools/check_publishable.py --report        # the pending summary, by question
  python tools/check_publishable.py --publish-list  # the publish set, one path per line
  python tools/check_publishable.py --publish-list --json
  python tools/check_publishable.py --selftest      # planted-violation reds + walker liveness
  python tools/check_publishable.py --public        # run INSIDE a public clone: the mirror arms
  python tools/check_publishable.py --public --closure

---- --public: THE SAME LEDGER, ASKED FROM THE OTHER SIDE (fork F5M) ----

Arms 1-3 above are written for the PRIVATE tree, and arm 2 inverts on the cut's output: there every
`withhold` rule is SUPPOSED to match nothing, so the ordinary check reports nine dead rules and a
correct public tree can never pass its own gate. `--public` asks the mirror question -- no withheld
path may be TRACKED (a leak), every `publish` rule must match at least one (a dead publish rule means
the seed dropped files), uncovered still fails -- and refuses to run on a private tree. Which tree it
is, is a declared thing, not a guess: the ledger's `_public_tree_marker` block.
"""

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(REPO, "tools", "data", "publish_ledger.json")

PUBLISHED = "publish"
VALID = ("publish", "withhold", "user_pending", "publish_after")

CXX_EXT = (".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".inc")
INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.MULTILINE)

# Basenames too generic to resolve a one-segment reference against. A bare "README.md" in a string
# literal says nothing about WHICH README; the multi-segment forms still resolve normally.
GENERIC_BASENAMES = {
    "README.md",
    "__init__.py",
    "manifest.json",
    "_ignore.json",
    "FIDELITY.md",
    "config.h",
    "main.cpp",
}


# --------------------------------------------------------------------------- globs


def glob_re(pattern):
    """fnmatch is not usable here: its `*` matches `/`, so `docs/*.md` would silently own
    `docs/sub/x.md`. Translate explicitly -- `**` crosses separators, `*` and `?` do not."""  # CITATION-OK
    out = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*":
            if pattern[i : i + 2] == "**":
                out.append(".*")
                i += 2
                continue
            out.append("[^/]*")
        elif c == "?":
            out.append("[^/]")
        else:
            out.append(re.escape(c))
        i += 1
    return re.compile("^" + "".join(out) + "$")


# --------------------------------------------------------------------------- ledger


def load_ledger(path=LEDGER):
    with open(path, encoding="utf-8") as fh:
        led = json.load(fh)
    seen = set()
    for r in led["rules"]:
        rid = r.get("id")
        if not rid:
            raise SystemExit("ledger: a rule has no id")
        if rid in seen:
            raise SystemExit("ledger: duplicate rule id %r" % rid)
        seen.add(rid)
        if r.get("disposition") not in VALID:
            raise SystemExit(
                "ledger: rule %s has disposition %r, expected one of %s"
                % (rid, r.get("disposition"), ", ".join(VALID))
            )
        if r["disposition"] == "user_pending" and not r.get("question"):
            raise SystemExit("ledger: user_pending rule %s names no question" % rid)
        if r["disposition"] == "publish_after" and not r.get("blocked_on"):
            raise SystemExit("ledger: publish_after rule %s names no blocked_on item" % rid)
        if not r.get("why"):
            raise SystemExit(
                "ledger: rule %s carries no reason -- a disposition without one is not a declaration"
                % rid
            )
        r["_res"] = [glob_re(g) for g in r["globs"]]
    marker = (led.get("_public_tree_marker") or {}).get("rule")
    if marker and marker not in seen:
        raise SystemExit(
            "ledger: _public_tree_marker names rule %r, which does not exist -- the public-tree "
            "detector would answer from nothing" % marker
        )
    return led


def tracked_paths(root=REPO):
    out = subprocess.run(
        ["git", "-C", root, "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    return [p.strip().replace("\\", "/") for p in out if p.strip()]


def classify(paths, led):
    """First matching rule owns the path. Returns (by_path, by_rule, uncovered)."""
    by_path = {}
    by_rule = {r["id"]: [] for r in led["rules"]}
    uncovered = []
    for p in paths:
        for r in led["rules"]:
            if any(rx.match(p) for rx in r["_res"]):
                by_path[p] = r
                by_rule[r["id"]].append(p)
                break
        else:
            uncovered.append(p)
    return by_path, by_rule, uncovered


# --------------------------------------------------------------------------- arms 1-3


def check(paths, led, say=print):
    by_path, by_rule, uncovered = classify(paths, led)
    ok = True

    if uncovered:
        ok = False
        say("FAIL uncovered: %d tracked path(s) carry no ledger disposition." % len(uncovered))
        say("     A new file FAILS CLOSED -- add a rule to tools/data/publish_ledger.json.")
        for p in uncovered[:40]:
            say("       %s" % p)
        if len(uncovered) > 40:
            say("       ... and %d more" % (len(uncovered) - 40))

    dead = [rid for rid, ps in by_rule.items() if not ps]
    if dead:
        ok = False
        say("FAIL dead rule: %d rule(s) match no tracked path." % len(dead))
        say("     The files a rule was written for are gone; delete the rule deliberately.")
        for rid in dead:
            say("       %s" % rid)

    accounted = sum(len(ps) for ps in by_rule.values())
    if accounted + len(uncovered) != len(paths):
        ok = False
        say(
            "FAIL count: rules account for %d + %d uncovered != %d paths git reports."
            % (accounted, len(uncovered), len(paths))
        )

    counts = {}
    for r in led["rules"]:
        counts[r["disposition"]] = counts.get(r["disposition"], 0) + len(by_rule[r["id"]])
    say(
        "paths %d  |  publish %d  withhold %d  user_pending %d  publish_after %d"
        % (
            len(paths),
            counts.get("publish", 0),
            counts.get("withhold", 0),
            counts.get("user_pending", 0),
            counts.get("publish_after", 0),
        )
    )

    measured = led.get("_measured", {}).get("tracked_paths")
    if measured is not None and measured != len(paths):
        say(
            "note: tree has %d paths, _measured recorded %d (%+d since the ledger was written)."
            % (len(paths), measured, len(paths) - measured)
        )

    say("check_publishable: %s" % ("PASS" if ok else "FAIL"))
    return ok


def report(paths, led, say=print):
    by_path, by_rule, _ = classify(paths, led)
    say("PENDING ROWS -- F5M cannot close while any remain")
    say("")
    total = 0
    for kind, key, head in (
        ("user_pending", "question", "waiting on the USER"),
        ("publish_after", "blocked_on", "waiting on a TRACKER ITEM"),
    ):
        rows = [r for r in led["rules"] if r["disposition"] == kind]
        if not rows:
            continue
        say("%s:" % head)
        for r in rows:
            n = len(by_rule[r["id"]])
            total += n
            say(
                "  %-34s %5d file(s)  %-4s  recommendation: %s"
                % (r["id"], n, r.get(key, "?"), r.get("recommendation", "--"))
            )
        say("")
    byq = {}
    for r in led["rules"]:
        if r["disposition"] == "user_pending":
            byq.setdefault(r["question"], 0)
            byq[r["question"]] += len(by_rule[r["id"]])
    if byq:
        say("by question: " + "  ".join("%s=%d" % (q, n) for q, n in sorted(byq.items())))
    say("pending files total: %d" % total)
    return total


def publish_list(paths, led):
    by_path, _, _ = classify(paths, led)
    return [p for p in paths if by_path.get(p) and by_path[p]["disposition"] == PUBLISHED]


# --------------------------------------------------------------------------- the public tree


def is_public_tree(paths, led):
    """Is this checkout the CUT'S OUTPUT rather than the private working tree?

    The answer is the ledger's `_public_tree_marker` rule owning ZERO tracked paths -- see that
    block for why the detector keys on one rule instead of on "nothing non-published is tracked".
    A ledger with no marker declared answers `private`, so the tools keep their old behaviour
    rather than silently switching arms."""
    marker = (led.get("_public_tree_marker") or {}).get("rule")
    if not marker:
        return False
    _by_path, by_rule, _unc = classify(paths, led)
    return not by_rule.get(marker)


def check_public(paths, led, say=print):
    """ARMS 1-3 TURNED INSIDE OUT, for running INSIDE a public clone (fork F5M).

    The private tree's arm 2 is "a rule matching zero paths FAILS". On the cut's output that is
    exactly backwards: EVERY withhold rule is supposed to match nothing there, so the ordinary
    check reports nine dead rules and the public tree can never satisfy its own gate. It is not a
    weaker question, it is the mirror question, and it catches the failure the public tree is the
    only place that can commit:

      P1  LEAK        a tracked path owned by a non-publish rule -> FAIL, naming the path. The
                      cut shipped something the ledger says stays private.
      P2  DEAD PUBLISH a publish rule matching nothing -> FAIL. The seed dropped files the ledger
                      says the public tree carries -- the silent half of a bad cut, which no
                      amount of looking at what IS there would show.
      P3  UNCOVERED   unchanged from the private arm: a tracked path no rule matches.

    Refuses outright on a private tree: run there it would report 1,381 "leaks", which is just the
    private tree being itself."""
    ok = True
    if not is_public_tree(paths, led):
        say(
            "FAIL --public: this checkout is NOT the cut's output -- the marker rule %r owns"
            % (led.get("_public_tree_marker") or {}).get("rule")
        )
        say("     tracked paths here, so this is the private working tree. Run the plain check.")
        return False

    by_path, by_rule, uncovered = classify(paths, led)

    leaks = [
        (p, r["id"], r["disposition"])
        for r in led["rules"]
        if r["disposition"] != PUBLISHED
        for p in by_rule[r["id"]]
    ]
    if leaks:
        ok = False
        say(
            "FAIL leak: %d tracked path(s) the ledger does NOT publish are in this tree."
            % len(leaks)
        )
        say("     The cut shipped something that was meant to stay private.")
        for p, rid, disp in leaks[:40]:
            say("       %s   (rule %s, %s)" % (p, rid, disp))
        if len(leaks) > 40:
            say("       ... and %d more" % (len(leaks) - 40))

    dead_pub = [
        r["id"] for r in led["rules"] if r["disposition"] == PUBLISHED and not by_rule[r["id"]]
    ]
    if dead_pub:
        ok = False
        say("FAIL dead publish rule: %d publish rule(s) match nothing here." % len(dead_pub))
        say("     The ledger says the public tree carries these files and it does not -- the seed")
        say("     dropped them. (On the PRIVATE tree this same shape means the rule outlived its")
        say("     files; here it means the cut did.)")
        for rid in dead_pub:
            say("       %s" % rid)

    if uncovered:
        ok = False
        say("FAIL uncovered: %d tracked path(s) carry no ledger disposition." % len(uncovered))
        for p in uncovered[:40]:
            say("       %s" % p)
        if len(uncovered) > 40:
            say("       ... and %d more" % (len(uncovered) - 40))

    say(
        "public tree: %d tracked path(s), %d publish rule(s) alive, %d leak(s), %d uncovered"
        % (
            len(paths),
            len([r for r in led["rules"] if r["disposition"] == PUBLISHED and by_rule[r["id"]]]),
            len(leaks),
            len(uncovered),
        )
    )
    say("check_publishable --public: %s" % ("PASS" if ok else "FAIL"))
    return ok


# --------------------------------------------------------------------------- arm 4: closure


def suffix_index(paths):
    """suffix -> set(paths). Every trailing segment run of every path; one-segment entries only
    when the basename is unique tree-wide and not generic, so `#include "config.h"` cannot be
    resolved to an arbitrary file."""
    idx = {}
    base_count = {}
    for p in paths:
        base_count[p.rsplit("/", 1)[-1]] = base_count.get(p.rsplit("/", 1)[-1], 0) + 1
    for p in paths:
        segs = p.split("/")
        for i in range(len(segs)):
            suf = "/".join(segs[i:])
            if i == len(segs) - 1:
                if base_count[suf] != 1 or suf in GENERIC_BASENAMES:
                    continue
            idx.setdefault(suf, set()).add(p)
    return idx


def _resolve(token, idx, published):
    """A reference resolves to a VIOLATION only when every tracked file it could name is
    non-published. If a published file matches too, the reference is satisfiable."""
    hits = idx.get(token)
    if not hits:
        return None
    if any(h in published for h in hits):
        return None
    return sorted(hits)[0]


def _py_string_constants(src):
    """String constants via ast: comments are gone by construction, docstrings excluded."""
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return []
    docstrings = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", None)
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                docstrings.add(id(body[0].value))
    out = []
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in docstrings
        ):
            out.append((getattr(node, "lineno", 0), node.value))
    return out


def _py_joined_paths(src):
    """`os.path.join(REPO, "tools", "gen_dll_calls.py")` is THE house idiom for naming another
    repo file, and it defeats a plain string scan: no literal in that call contains a separator, so
    every segment looks like prose. Reconstruct the join from its constant arguments (the leading
    non-constant root -- REPO, ROOT, HERE -- is dropped) and hand the result to the same resolver.
    Without this the Python arm cannot see lint_repo.py invoking another tool, which is precisely
    the edge that would break a public lint run."""
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return []
    out = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        f = node.func
        if not (isinstance(f, ast.Attribute) and f.attr == "join"):
            continue
        owner = f.value
        if not (isinstance(owner, ast.Attribute) and owner.attr == "path"):
            continue
        segs = []
        for a in node.args:
            if isinstance(a, ast.Constant) and isinstance(a.value, str):
                segs.append(a.value.replace("\\", "/").strip("/"))
            elif segs:
                segs = []  # a non-constant in the middle: the tail no longer names a fixed path
                break
        if len(segs) >= 2:
            out.append((getattr(node, "lineno", 0), "/".join(segs)))
    return out


TOKEN_RE = re.compile(r"[A-Za-z0-9_./\\-]+")


def closure_scan(paths, led, root=REPO, say=print):
    """Returns (violations, visited) -- violations are (source, line, needed_path, kind)."""
    by_path, _, _ = classify(paths, led)
    published = {p for p in paths if by_path.get(p) and by_path[p]["disposition"] == PUBLISHED}
    idx = suffix_index(paths)
    violations = []
    visited = 0

    for p in sorted(published):
        full = os.path.join(root, p.replace("/", os.sep))
        if not os.path.isfile(full):
            continue
        ext = os.path.splitext(p)[1].lower()
        if ext not in CXX_EXT and ext != ".py":
            continue
        try:
            with open(full, encoding="utf-8", errors="replace") as fh:
                src = fh.read()
        except OSError:
            continue
        visited += 1

        if ext in CXX_EXT:
            for m in INCLUDE_RE.finditer(src):
                tok = m.group(1).replace("\\", "/")
                hit = _resolve(tok, idx, published)
                if hit:
                    line = src.count("\n", 0, m.start()) + 1
                    violations.append((p, line, hit, "include"))
        else:
            for lineno, val in _py_string_constants(src):
                for tok in TOKEN_RE.findall(val.replace("\\", "/")):
                    # A Python string is not a compiler directive: a bare basename in one is far
                    # more often prose ("see the session log", "copy setup.dat into the lane") than a
                    # read, and both shapes were measured in this tree. So the Python arm requires
                    # at least TWO path segments, which a sentence practically never carries and a
                    # real relative read almost always does. The consequence is stated rather than
                    # hidden: a tool that reads a withheld ROOT document by name through
                    # os.path.join(REPO, ...) is invisible to this arm, and is caught by disposition --
                    # see the research-tooling ledger row.
                    if tok.count("/") < 1:
                        continue
                    hit = _resolve(tok, idx, published)
                    if hit:
                        violations.append((p, lineno, hit, "pyref"))
            for lineno, joined in _py_joined_paths(src):
                hit = _resolve(joined, idx, published)
                if hit:
                    violations.append((p, lineno, hit, "pyjoin"))

    return violations, visited


def closure(paths, led, root=REPO, say=print, public=False):
    """HARD vs CONDITIONAL, and only HARD fails.

    An edge into a `withhold` path is a contradiction TODAY: the file is not coming back, so a
    published source that needs it can never build. That is a failure.

    An edge into a `user_pending` or `publish_after` path is a contradiction ONLY IF the answer
    goes the other way. Those are not defects, they are the measured BLAST RADIUS of each open
    question -- 44 sources needing mh_export.gen.h is what Q3 costs if the user rules withhold, and
    the user deserves to see that number before answering rather than after. So they are grouped
    and reported, and F5M (not F5A) is where they must be zero.

    `public=True` (fork F5M) RUNS THE SAME SCAN and asserts the same zero hard edges, but
    drops the STALE-EXCEPTION arm and says so. A closure exception is a declaration about the
    PRIVATE tree -- "this published tool still reads a path the cut does not carry" -- and on
    the cut's output the path it names is not tracked at all, so the edge resolves to nothing
    and every exception reads as stale. That is the declaration being SATISFIED, not broken.
    The HARD arm is not vacuous there: a leaked withheld file IS tracked, IS classified
    `withhold`, and an edge into it fails exactly as it would here."""
    if public and not is_public_tree(paths, led):
        say("FAIL --public --closure: this checkout is NOT the cut's output. Run --closure plain.")
        return False
    violations, visited = closure_scan(paths, led, root, say)
    ok = True

    if visited == 0:
        say("FAIL walker liveness: the closure scan visited no published source file.")
        say("     A scan that finds nothing and a scan that is broken look identical.")
        return False

    by_path, _, _ = classify(paths, led)
    hard = [v for v in violations if by_path[v[2]]["disposition"] == "withhold"]
    cond = [v for v in violations if by_path[v[2]]["disposition"] != "withhold"]

    def _globs(v):
        return [glob_re(g) for g in ([v] if isinstance(v, str) else v)]

    declared = {}
    for ex in led.get("closure_exceptions", []):
        declared[ex["id"]] = {
            "ex": ex,
            "src": _globs(ex["source"]),
            "need": _globs(ex["needs"]),
            "hit": 0,
        }

    def _match(d, src, need):
        return any(r.match(src) for r in d["src"]) and any(r.match(need) for r in d["need"])

    for src, line, need, kind in violations:
        for d in declared.values():
            if _match(d, src, need):
                d["hit"] += 1
                break

    undeclared_hard = []
    for src, line, need, kind in hard:
        for d in declared.values():
            if _match(d, src, need):
                break
        else:
            undeclared_hard.append((src, line, need, kind))

    if undeclared_hard:
        ok = False
        say(
            "FAIL closure (HARD): %d published source(s) need a WITHHELD path."
            % len(undeclared_hard)
        )
        say("     The target is not coming back -- either publish it, stop publishing the source,")
        say("     or cut the edge. This is the save_selftest.cpp:21 failure class.")
        for src, line, need, kind in undeclared_hard[:40]:
            say("       %s:%d  (%s)  ->  %s" % (src, line, kind, need))
        if len(undeclared_hard) > 40:
            say("       ... and %d more" % (len(undeclared_hard) - 40))

    stale = [rid for rid, d in declared.items() if not d["hit"]] if not public else []
    if public:
        say(
            "note (--public): the stale-exception arm is not run here. A closure exception "
            "declares an edge into a path the CUT DOES NOT CARRY, so on the cut's output it "
            "resolves to nothing by construction -- reading that as stale would fail the public "
            "tree for being the public tree. The %d declared row(s) are the private tree's gate."
            % len(declared)
        )
    if stale:
        ok = False
        say(
            "FAIL stale exception: %d declared closure exception(s) no longer reproduce."
            % len(stale)
        )
        say(
            "     The contradiction is fixed -- DELETE the row (and flip the file's ledger disposition)."
        )
        for rid in stale:
            ex = declared[rid]["ex"]
            say(
                "       %s  (%s -> %s, blocked_on %s)"
                % (rid, ex["source"], ex["needs"], ex.get("blocked_on", "?"))
            )

    for rid, d in sorted(declared.items()):
        if d["hit"]:
            ex = d["ex"]
            say(
                "declared, still reproducing (%d edge(s), blocked_on %s): %s"
                % (d["hit"], ex.get("blocked_on", "?"), rid)
            )

    if cond:
        groups = {}
        for src, line, need, kind in cond:
            r = by_path[need]
            key = r.get("question") or r.get("blocked_on") or "?"
            groups.setdefault(key, {}).setdefault(need, set()).add(src)
        say("")
        say("CONDITIONAL -- edges that become contradictions only if the answer is 'withhold':")
        for key in sorted(groups):
            tot = sum(len(s) for s in groups[key].values())
            say(
                "  %-5s %3d edge(s) from %d distinct source(s):"
                % (key, tot, len({s for m in groups[key].values() for s in m}))
            )
            for need, srcs in sorted(groups[key].items(), key=lambda kv: -len(kv[1])):
                say("        %-62s %3d source(s)" % (need, len(srcs)))

    say("")
    say(
        "closure: scanned %d published source(s); %d hard (%d undeclared), %d conditional  -- %s"
        % (visited, len(hard), len(undeclared_hard), len(cond), "PASS" if ok else "FAIL")
    )
    return ok


def _disp_of(path, paths, led):
    by_path, _, _ = classify([path], led)
    r = by_path.get(path)
    if not r:
        return "UNCOVERED"
    d = r["disposition"]
    if d == "user_pending":
        return "user_pending/%s" % r.get("question")
    if d == "publish_after":
        return "publish_after/%s" % r.get("blocked_on")
    return d


# --------------------------------------------------------------------------- selftest


def selftest():
    """Every arm re-fired against a planted violation, in a temp tree, through these same
    functions. Plus the known-positive control: the real tree's save_selftest.cpp -> LZW edge must
    be found by the real detector, or the detector is not measuring anything."""
    ok = True
    results = []

    def expect(name, cond):
        nonlocal ok
        results.append((name, bool(cond)))
        if not cond:
            ok = False

    led = load_ledger()

    # ---- control: the detector fires on the REAL tree's real bytes ----------------------------
    # This used to assert that save_selftest.cpp -> sv1_lzw_fixtures.gen.h came back as a
    # VIOLATION, which it was while the fixtures were `publish_after`. F5C flipped that row to
    # `publish` (the header is now derived from the committed, user-ruled 11.sav), and the control
    # died with its subject -- a control that any ledger verdict can retire is not a control. So it
    # is now phrased against the SCANNER instead: the same real file, the same real line 21, but
    # the disposition it is measured under is synthetic. Prepend a rule (first-match-wins) that
    # withholds that one header and the real edge must reappear. This holds no matter what the
    # ledger later says about the header, and fails if the include is removed or the resolver
    # breaks -- which is the whole job of a known-positive.
    real = tracked_paths()
    vios, visited = closure_scan(real, led)
    expect("walker visited published sources in the real tree", visited > 100)

    probe_rule = {
        "id": "_selftest_probe",
        "disposition": "withhold",
        "globs": ["src/mh_dll/libmh_test/sv1_lzw_fixtures.gen.h"],
        "why": "selftest probe",
    }
    probe_rule["_res"] = [glob_re(g) for g in probe_rule["globs"]]
    probe_led = dict(led)
    probe_led["rules"] = [probe_rule] + list(led["rules"])
    probe_vios, probe_visited = closure_scan(real, probe_led)
    expect("probe walker visited the real tree", probe_visited > 100)
    control = [
        v
        for v in probe_vios
        if v[0] == "src/mh_dll/libmh_test/save_selftest.cpp"
        and v[2] == "src/mh_dll/libmh_test/sv1_lzw_fixtures.gen.h"
    ]
    expect(
        "KNOWN-POSITIVE (real tree, synthetic withhold): save_selftest.cpp -> "
        "sv1_lzw_fixtures.gen.h detected",
        len(control) == 1,
    )
    expect("KNOWN-POSITIVE: found at line 21", bool(control) and control[0][1] == 21)
    expect(
        "and it is NOT a violation under the real ledger (the row publishes)",
        not [v for v in vios if v[2] == "src/mh_dll/libmh_test/sv1_lzw_fixtures.gen.h"],
    )

    # ---- synthetic ledger + tree ---------------------------------------------------------------
    tmp = tempfile.mkdtemp(prefix="check_publishable_selftest_")
    try:

        def synth(rel, content):
            full = os.path.join(tmp, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as fh:
                fh.write(content)

        mini = {
            "_measured": {"tracked_paths": 4},
            "rules": [
                {
                    "id": "secret",
                    "disposition": "withhold",
                    "globs": ["secret/hidden.gen.h"],
                    "why": "x",
                },
                {
                    "id": "secret-py",
                    "disposition": "withhold",
                    "globs": ["secret/private_tool.py"],
                    "why": "x",
                },
                {"id": "code", "disposition": "publish", "globs": ["code/**"], "why": "x"},
            ],
            "closure_exceptions": [],
        }
        for r in mini["rules"]:
            r["_res"] = [glob_re(g) for g in r["globs"]]

        base = ["secret/hidden.gen.h", "secret/private_tool.py", "code/a.cpp", "code/b.py"]
        synth("secret/hidden.gen.h", "#pragma once\n")
        synth("secret/private_tool.py", "X = 1\n")
        synth("code/a.cpp", '#include "code/ok.h"\nint main(){return 0;}\n')
        synth("code/b.py", '"""doc mentioning secret/private_tool.py"""\nP = "code/data.txt"\n')
        synth("code/ok.h", "#pragma once\n")
        base_full = base + ["code/ok.h"]
        mini["_measured"]["tracked_paths"] = len(base_full)

        quiet = lambda *a, **k: None  # noqa: E731

        expect("baseline mini-ledger is green", check(base_full, mini, say=quiet))
        expect("baseline mini-closure is green", closure(base_full, mini, root=tmp, say=quiet))

        # arm 1: a new file with no rule
        expect(
            "RED: an undispositioned new path fails closed",
            not check(base_full + ["code2/new.cpp"], mini, say=quiet),
        )

        # arm 2: a rule that matches nothing
        dead = json.loads(json.dumps({k: v for k, v in mini.items() if k != "rules"}))
        dead["rules"] = [{k: v for k, v in r.items() if k != "_res"} for r in mini["rules"]]
        dead["rules"].append(
            {"id": "ghost", "disposition": "publish", "globs": ["gone/**"], "why": "x"}
        )
        for r in dead["rules"]:
            r["_res"] = [glob_re(g) for g in r["globs"]]
        expect("RED: a rule matching zero paths fails", not check(base_full, dead, say=quiet))

        # arm 3: count -- a duplicated path cannot inflate the accounting silently
        expect(
            "count arm agrees on the baseline",
            sum(len(v) for v in classify(base_full, mini)[1].values()) == len(base_full),
        )

        # arm 4a: a published C++ source including a withheld header
        synth("code/a.cpp", '#include "secret/hidden.gen.h"\nint main(){return 0;}\n')
        expect(
            "RED: published .cpp includes a withheld header",
            not closure(base_full, mini, root=tmp, say=quiet),
        )
        v, _ = closure_scan(base_full, mini, root=tmp)
        expect(
            "RED: the C++ violation names the right target",
            any(x[2] == "secret/hidden.gen.h" and x[3] == "include" for x in v),
        )
        synth("code/a.cpp", '#include "code/ok.h"\nint main(){return 0;}\n')

        # arm 4b: a published .py naming a withheld path in a live string
        synth(
            "code/b.py",
            '"""doc mentioning secret/private_tool.py"""\nP = "secret/private_tool.py"\n',
        )
        expect(
            "RED: published .py reads a withheld path",
            not closure(base_full, mini, root=tmp, say=quiet),
        )
        v, _ = closure_scan(base_full, mini, root=tmp)
        expect(
            "RED: the python violation names the right target",
            any(x[2] == "secret/private_tool.py" and x[3] == "pyref" for x in v),
        )

        # arm 4b': the os.path.join house idiom, whose segments carry no separator of their own
        synth(
            "code/b.py",
            'import os\nREPO = "."\nP = os.path.join(REPO, "secret", "private_tool.py")\n',
        )
        expect(
            "RED: os.path.join(REPO, 'secret', 'private_tool.py') is seen",
            not closure(base_full, mini, root=tmp, say=quiet),
        )
        v, _ = closure_scan(base_full, mini, root=tmp)
        expect(
            "RED: the join violation is reported as pyjoin",
            any(x[2] == "secret/private_tool.py" and x[3] == "pyjoin" for x in v),
        )

        # ... and a join whose tail is not constant names no fixed path, so it must NOT fire
        synth(
            "code/b.py",
            'import os\nREPO = "."\ndef f(n):\n    return os.path.join(REPO, "secret", n)\n',
        )
        expect(
            "GREEN: a join with a non-constant segment is not a resolvable path",
            closure(base_full, mini, root=tmp, say=quiet),
        )

        # the docstring/comment discrimination: prose is F5E's, not a build edge
        synth(
            "code/b.py",
            '"""doc mentioning secret/private_tool.py"""\n# also secret/private_tool.py\nP = 1\n',
        )
        expect(
            "GREEN: a docstring/comment mention is NOT a build edge",
            closure(base_full, mini, root=tmp, say=quiet),
        )

        # HARD vs CONDITIONAL: an edge into a user_pending target is measured, never failed
        cond_led = json.loads(json.dumps({k: v for k, v in mini.items() if k != "rules"}))
        cond_led["rules"] = [{k: v for k, v in r.items() if k != "_res"} for r in mini["rules"]]
        cond_led["rules"][0] = {
            "id": "secret",
            "disposition": "user_pending",
            "question": "Q9",
            "globs": ["secret/hidden.gen.h"],
            "why": "x",
        }
        for r in cond_led["rules"]:
            r["_res"] = [glob_re(g) for g in r["globs"]]
        cond_led["closure_exceptions"] = []
        synth("code/a.cpp", '#include "secret/hidden.gen.h"\nint main(){return 0;}\n')
        expect(
            "GREEN: an edge into a user_pending target is CONDITIONAL, not a failure",
            closure(base_full, cond_led, root=tmp, say=quiet),
        )
        expect(
            "...and the same edge into a withhold target still FAILS",
            not closure(base_full, mini, root=tmp, say=quiet),
        )
        synth("code/a.cpp", '#include "code/ok.h"\nint main(){return 0;}\n')
        synth("code/b.py", 'P = 1\n')

        # arm 4c: a declared exception that no longer reproduces
        withex = json.loads(json.dumps({k: v for k, v in mini.items() if k != "rules"}))
        withex["rules"] = [{k: v for k, v in r.items() if k != "_res"} for r in mini["rules"]]
        for r in withex["rules"]:
            r["_res"] = [glob_re(g) for g in r["globs"]]
        withex["closure_exceptions"] = [
            {
                "id": "gone",
                "source": "code/a.cpp",
                "needs": "secret/hidden.gen.h",
                "blocked_on": "FX",
                "why": "x",
            }
        ]
        expect(
            "RED: a declared exception that stopped reproducing fails",
            not closure(base_full, withex, root=tmp, say=quiet),
        )

        # and the same exception PASSES while the contradiction is real
        synth("code/a.cpp", '#include "secret/hidden.gen.h"\nint main(){return 0;}\n')
        expect(
            "GREEN: a declared exception that still reproduces passes",
            closure(base_full, withex, root=tmp, say=quiet),
        )

        # walker liveness
        empty_led = json.loads(json.dumps({k: v for k, v in mini.items() if k != "rules"}))
        empty_led["rules"] = [{"id": "all", "disposition": "withhold", "globs": ["**"], "why": "x"}]
        for r in empty_led["rules"]:
            r["_res"] = [glob_re(g) for g in r["globs"]]
        empty_led["closure_exceptions"] = []
        expect(
            "RED: a scan that visits nothing is refused, not reported green",
            not closure(base_full, empty_led, root=tmp, say=quiet),
        )

        # ---- fork F5M: the PUBLIC-tree arms, on a synthetic cut ------------------------------
        # `mini` above is a PRIVATE-shaped tree (it tracks secret/*). The public shape is the same
        # ledger with only the published members present, and the detector is told which rule
        # marks the private layers. Every arm below is planted and then removed, so a green
        # --public is a verdict and not an absence.
        def pub_led(rules):
            led2 = {
                "_public_tree_marker": {"rule": "private-layers"},
                "rules": [],
                "closure_exceptions": [],
            }
            led2["rules"] = [dict(r) for r in rules]
            for r in led2["rules"]:
                r["_res"] = [glob_re(g) for g in r["globs"]]
            return led2

        pub_rules = [
            {"id": "private-layers", "disposition": "withhold", "globs": ["diary/**"], "why": "x"},
            {"id": "secret", "disposition": "withhold", "globs": ["secret/**"], "why": "x"},
            {"id": "code", "disposition": "publish", "globs": ["code/**"], "why": "x"},
            {"id": "docs", "disposition": "publish", "globs": ["readme/**"], "why": "x"},
        ]
        cut = ["code/a.cpp", "code/b.py", "code/ok.h", "readme/r.md"]
        expect(
            "PUBLIC: a clean cut tree is GREEN", check_public(cut, pub_led(pub_rules), say=quiet)
        )
        expect(
            "PUBLIC: ...and the detector calls it the cut's output",
            is_public_tree(cut, pub_led(pub_rules)),
        )

        # P1 -- a planted WITHHELD file in the cut is a LEAK
        leaked = cut + ["secret/hidden.gen.h"]
        expect(
            "PUBLIC RED: a withheld path tracked in the cut is a LEAK",
            not check_public(leaked, pub_led(pub_rules), say=quiet),
        )
        msgs = []
        check_public(leaked, pub_led(pub_rules), say=msgs.append)
        expect(
            "PUBLIC RED: ...and the failure NAMES the leaked path",
            any("secret/hidden.gen.h" in m for m in msgs),
        )

        # P2 -- a planted DEAD PUBLISH rule: the seed dropped what the ledger says it carries
        expect(
            "PUBLIC RED: a publish rule matching nothing means the seed dropped files",
            not check_public(
                [p for p in cut if not p.startswith("readme/")], pub_led(pub_rules), say=quiet
            ),
        )
        msgs = []
        check_public(
            [p for p in cut if not p.startswith("readme/")], pub_led(pub_rules), say=msgs.append
        )
        expect("PUBLIC RED: ...and it names the dead rule", any("docs" in m for m in msgs))

        # P3 -- uncovered still fails, same as the private arm
        expect(
            "PUBLIC RED: an undispositioned path still fails closed",
            not check_public(cut + ["code2/new.cpp"], pub_led(pub_rules), say=quiet),
        )

        # the refusal: --public on a PRIVATE tree is a misuse, not a thousand leaks
        private_tree = cut + ["diary/a-session-log.md"]
        expect(
            "PUBLIC RED: --public refuses a tree that still carries the private layers",
            not check_public(private_tree, pub_led(pub_rules), say=quiet),
        )
        expect(
            "PUBLIC: ...and the detector calls that tree private",
            not is_public_tree(private_tree, pub_led(pub_rules)),
        )

        # a ledger with no marker declared answers `private`, so nothing switches arms silently
        nomark = pub_led(pub_rules)
        del nomark["_public_tree_marker"]
        expect("PUBLIC: an undeclared marker means `private`", not is_public_tree(cut, nomark))

        # --public --closure: the stale-exception arm is dropped, the HARD arm is not
        pub_cut = list(cut)
        synth("readme/r.md", "x\n")
        ex_led = pub_led(pub_rules)
        ex_led["closure_exceptions"] = [
            {"id": "gone", "source": "code/a.cpp", "needs": "secret/hidden.gen.h", "why": "x"}
        ]
        synth("code/a.cpp", '#include "code/ok.h"\nint main(){return 0;}\n')
        expect(
            "PUBLIC: a closure exception whose target the cut does not carry is NOT stale",
            closure(pub_cut, ex_led, root=tmp, say=quiet, public=True),
        )
        expect(
            "PUBLIC: ...and the same exception IS stale under the private arm",
            not closure(pub_cut, ex_led, root=tmp, say=quiet),
        )
        synth("code/a.cpp", '#include "secret/hidden.gen.h"\nint main(){return 0;}\n')
        expect(
            "PUBLIC RED: an edge into a LEAKED withheld file still fails under --public",
            not closure(leaked, pub_led(pub_rules), root=tmp, say=quiet, public=True),
        )
        synth("code/a.cpp", '#include "code/ok.h"\nint main(){return 0;}\n')

        # glob discipline: `*` must not cross a separator
        expect(
            "glob: docs/*.md does not own docs/sub/x.md",  # CITATION-OK
            not glob_re("docs/*.md").match("docs/sub/x.md"),  # CITATION-OK
        )
        expect(
            "glob: docs/** does own docs/sub/x.md",  # CITATION-OK
            bool(glob_re("docs/**").match("docs/sub/x.md")),  # CITATION-OK
        )

        # suffix index discipline: a generic basename must not resolve
        idx = suffix_index(["a/README.md", "b/README.md", "c/unique_thing.h"])
        expect("suffix: an ambiguous basename does not resolve", "README.md" not in idx)
        expect("suffix: a unique basename does resolve", "unique_thing.h" in idx)
        expect("suffix: the multi-segment form always resolves", "a/README.md" in idx)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # The detector, exercised on the REAL ledger and the REAL path list -- BOTH WAYS, so this arm
    # holds whichever tree it is run in (it runs in the public gate too, where "this tree is
    # private" would be a false assertion rather than a control).
    _marker = (led.get("_public_tree_marker") or {}).get("rule")
    _owned = set(classify(real, led)[1].get(_marker, []))
    _cut_shaped = [p for p in real if p not in _owned]
    _marker_glob = next(r for r in led["rules"] if r["id"] == _marker)["globs"][0]
    _sample = _marker_glob.replace("**", "x").replace("*", "x").replace("?", "x")
    expect(
        "PUBLIC: with no marker-rule path tracked, the detector says CUT",
        is_public_tree(_cut_shaped, led),
    )
    expect(
        "PUBLIC: add one back (%s) and it says PRIVATE" % _sample,
        not is_public_tree(_cut_shaped + [_sample], led),
    )

    for name, passed in results:
        print("  %-62s %s" % (name, "ok" if passed else "FAIL"))
    print("check_publishable --selftest: %s" % ("PASS" if ok else "FAIL"))
    return ok


# --------------------------------------------------------------------------- main


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--closure", action="store_true", help="the build/run-edge arm + stale-exception arm"
    )
    ap.add_argument("--report", action="store_true", help="pending summary by question")
    ap.add_argument("--publish-list", action="store_true", help="emit the publish set")
    ap.add_argument("--json", action="store_true", help="with --publish-list, emit JSON")
    ap.add_argument("--selftest", action="store_true", help="planted-violation reds")
    ap.add_argument(
        "--public",
        action="store_true",
        help="run INSIDE a public clone: no withheld path tracked, no dead publish rule",
    )
    args = ap.parse_args()

    if args.selftest:
        return 0 if selftest() else 1

    led = load_ledger()
    paths = tracked_paths()

    if args.publish_list:
        sel = publish_list(paths, led)
        if args.json:
            json.dump(
                {
                    "head": subprocess.run(
                        ["git", "-C", REPO, "rev-parse", "HEAD"], capture_output=True, text=True
                    ).stdout.strip(),
                    "count": len(sel),
                    "paths": sel,
                },
                sys.stdout,
                indent=1,
            )
            print()
        else:
            for p in sel:
                print(p)
        return 0

    if args.report:
        report(paths, led)
        return 0

    if args.closure:
        return 0 if closure(paths, led, public=args.public) else 1

    if args.public:
        return 0 if check_public(paths, led) else 1

    return 0 if check(paths, led) else 1


if __name__ == "__main__":
    sys.exit(main())
