#!/usr/bin/env python3
r"""
crash_report.py -- find and attribute Windows crash reports for a rig peer.

WHY THIS EXISTS. The rig could not tell a crash from a hang. When the game's sim thread dies the
process usually does NOT: the render loop keeps presenting, so `mh_frametime.log` goes on growing
and the harness -- which only ever watched the STEP COUNT -- reported

    [host] harness STALLED (at 1 steps for 120s)

That is the same words it uses for a genuine livelock, and it cost an hour on 2026-08-01 (AI1A):
the batch-A shadow arming crashed in llm_strat_unit_passive_engage_tick and
every symptom pointed at an infinite loop. Windows had written the answer to disk the whole time.

WHAT MAKES PER-LANE ATTRIBUTION EXACT. A WER report carries `AppPath` -- the FULL path of the
faulting binary -- so a crash in F:\games\mh_lanes\ui_sp_det\mh.focus.exe is distinguishable from one
in any other lane, and from another concurrent run's peer, without guessing by image name or by time
alone. That matters here specifically: this rig runs several lanes at once, they all run an exe
called `mh.focus.exe`, and killing or blaming by image name is a cross-test failure this repo already
refuses to do elsewhere (see local_kill in ui_test.py).

WHAT IT READS
  * %ProgramData%\Microsoft\Windows\WER\Report{Archive,Queue}\*\Report.wer  -- the report itself
  * %LOCALAPPDATA%\Microsoft\Windows\WER\Report{Archive,Queue}\*\Report.wer
  * %LOCALAPPDATA%\CrashDumps\*.dmp                                        -- if dump collection is on
Report.wer is a UTF-16LE `key=value` file. The fields that matter:
    AppPath        full path of the crashed binary   -> which LANE
    EventTime      FILETIME (100ns ticks since 1601) -> whether it belongs to THIS run
    Sig[0].Value   application name
    Sig[3].Value   FAULTING MODULE  (mh.focus.exe, or a DLL)
    Sig[6].Value   exception code   (c0000005 = access violation, ...)
    Sig[7].Value   exception OFFSET within the faulting module

TURNING THAT INTO A LOCATION. When the faulting module is the game exe, VA = offset + 0x00400000
(EN build, no ASLR -- the same premise the whole DLL rests on). The VA is then resolved against
docs/symbols.md, so the report names a FUNCTION rather than a hex number.

MH.DLL IS DIFFERENT (tracker TL-GATE1, closed by dist:RP3): it is a relocatable DLL, so there is no
fixed image base to add an offset to -- the WER/event-log "fault offset" for a DLL module IS
already an RVA (offset from wherever the loader happened to place it), and that RVA is invariant
regardless of load address. So a fault in `mh.dll` is resolved by parsing
`src/mh_dll/Release/mh.map` (the linker's own map, regenerated by every build) into an
{RVA: symbol} table -- RVA = the map's `Rva+Base` column minus its `Preferred load address`
header -- and looking the fault RVA up in THAT, never docs/symbols.md (which is EN mh.exe-VA
keyed and has no idea mh.dll even exists). See `resolve_mh_dll_rva()` below.

READING A DRAINED REPORT (tracker dist:RP3). `tools/drain_reports.py` pulls
`reports/<YYYY-MM>/<ulid>/{report.zip,meta.json,description.txt}` directories off the VPS
collector (dist:RP2) into a local store. `--report <dir>` reads ONE such directory (or a store
root, walked for every `meta.json` under it) instead of scanning this machine's local WER tree --
see `print_drained_report()` for the `meta.json` "crash" field contract LA4 (the Rust launcher,
not yet built) is expected to emit: `{"module": "mh.dll"|"mh.exe"|"mh.focus.exe", "offset":
"0x...."}`, documented in full in src/collector/README.md's "Draining reports" section.

Usage:
  python tools/crash_report.py                       # everything from the last 30 minutes
  python tools/crash_report.py --since-min 5
  python tools/crash_report.py --lane F:\\games\\mh_lanes\\ui_sp_det
  python tools/crash_report.py --report tmp/drained_reports/2026-09/01ULID...   # a drained report
  python tools/crash_report.py --json
"""

import argparse
import bisect
import calendar
import glob
import json
import os
import re
import struct
import subprocess
import time
import zipfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYMBOLS = os.path.join(REPO, "docs", "symbols.md")
MH_MAP = os.path.join(REPO, "src", "mh_dll", "Release", "mh.map")
IMAGE_BASE = 0x00400000  # EN mh.exe, no ASLR

# The NTSTATUS values this rig actually produces. An unknown code still reports its hex -- the point
# of the table is that the common ones do not need a web search mid-debug.
EXCEPTION_NAMES = {
    "c0000005": "ACCESS_VIOLATION",
    "c000001d": "ILLEGAL_INSTRUCTION",
    "c0000025": "NONCONTINUABLE_EXCEPTION",
    "c000008c": "ARRAY_BOUNDS_EXCEEDED",
    "c0000090": "FLT_INVALID_OPERATION",
    "c0000094": "INTEGER_DIVIDE_BY_ZERO",
    "c0000095": "INTEGER_OVERFLOW",
    "c00000fd": "STACK_OVERFLOW",
    "c0000374": "HEAP_CORRUPTION",
    "c000041d": "FATAL_USER_CALLBACK_EXCEPTION",
    "c0000409": "STACK_BUFFER_OVERRUN",
    "80000003": "BREAKPOINT",
    "e06d7363": "CPP_EXCEPTION",
}


def wer_dirs():
    """Every WER report root that could hold a report for a process we launched.

    Both the per-machine and the per-user trees, and both Queue (not yet reported) and Archive
    (reported). Which one a crash lands in depends on the machine's WER consent settings, so
    scanning one of them is a silent coverage gap rather than a simplification.
    """
    roots = []
    for base in (os.environ.get("ProgramData"), os.environ.get("LOCALAPPDATA")):
        if not base:
            continue
        for sub in ("ReportArchive", "ReportQueue"):
            p = os.path.join(base, "Microsoft", "Windows", "WER", sub)
            if os.path.isdir(p):
                roots.append(p)
    return roots


def filetime_to_epoch(ft):
    """FILETIME (100 ns ticks since 1601-01-01 UTC) -> unix epoch seconds."""
    try:
        return int(ft) / 1e7 - 11644473600
    except (TypeError, ValueError):
        return None


def parse_report(path):
    """Parse one Report.wer into a flat dict. Returns None if it is not readable as one."""
    for enc in ("utf-16", "utf-8-sig", "utf-8"):
        try:
            with open(path, encoding=enc) as f:
                txt = f.read()
            if "EventType=" in txt or "Sig[0].Name=" in txt:
                break
        except (OSError, UnicodeError):
            continue
    else:
        return None
    d = {}
    for line in txt.splitlines():
        if "=" in line:
            k, _, v = line.partition("=")
            d[k.strip()] = v.strip()
    return d or None


def _symbol_index():
    """(sorted function VAs, names) from the GENERATED symbol table.

    Deliberately docs/symbols.md and not a hand list: it is regenerated from Ghidra every session
    that renames anything, so a crash report cannot drift into naming a function by its old name.
    """
    if not os.path.isfile(SYMBOLS):
        return [], []
    addrs, names = [], []
    for m in re.finditer(
        r"^\|\s*`0x([0-9a-fA-F]{8})`\s*\|\s*`([^`]+)`",
        open(SYMBOLS, encoding="utf-8", errors="replace").read(),
        re.M,
    ):
        addrs.append(int(m.group(1), 16))
        names.append(m.group(2))
    order = sorted(range(len(addrs)), key=lambda i: addrs[i])
    return [addrs[i] for i in order], [names[i] for i in order]


_SYMS = None


def resolve_va(va):
    """`name+0xNN` for the function containing `va`, or None.

    Nearest-preceding-symbol, which is an ATTRIBUTION not a proof: a VA past the last function in a
    region will still bind to that function. The offset is printed so an implausible one is visible.
    """
    global _SYMS
    if _SYMS is None:
        _SYMS = _symbol_index()
    addrs, names = _SYMS
    if not addrs:
        return None
    i = bisect.bisect_right(addrs, va) - 1
    if i < 0:
        return None
    delta = va - addrs[i]
    if delta > 0x4000:  # further than any function in this binary is long
        return None
    return "%s+0x%x" % (names[i], delta) if delta else names[i]


# ─────────────────────────────── mh.dll resolution (tracker TL-GATE1) ───────────────────────────────

# One row of the map's "Publics by Value" table that is a FUNCTION: e.g.
#   " 0001:00000510       ?live@state@mh@@YAAAUlive_table@12@XZ 10001510 f   libmh_bind.obj"
# The `f` flag (a standalone token -- bounded by whitespace on both sides, so it cannot match part
# of a longer word) is what the linker uses to mark a symbol as a function, and it is the ONLY
# filter needed: measured against this repo's own map, every CODE-section row carries it and no
# DATA-section row ever does, so there is no need to separately cross-reference the section table.
# A section-table row itself (" 0001:00000010 00038340H .text$mn      CODE") never matches: its
# second hex token has a trailing "H" the RVA group here does not allow.
_MH_MAP_FUNC_RE = re.compile(
    r"^\s*[0-9A-Fa-f]{4}:[0-9A-Fa-f]{8}\s+(\S+)\s+([0-9A-Fa-f]{8})\s+f\s", re.M
)
_MH_MAP_BASE_RE = re.compile(r"Preferred load address is ([0-9A-Fa-f]+)")


def _mh_dll_symbol_index(map_path=None):
    """(sorted RVAs, names) of every FUNCTION the linker map recorded, or ([], []) if the map is
    absent (no Release build on this machine -- not an error, just nothing to resolve against).

    RVA = the map's `Rva+Base` column MINUS its `Preferred load address` header -- deliberately not
    the map's own per-section `Address` column (section-relative, not what a runtime fault offset
    is measured against) and deliberately not "VA - IMAGE_BASE" arithmetic like the exe path above:
    mh.dll RELOCATES, so there is no fixed image base to subtract at report-reading time. The RVA
    is invariant across relocation, which is the whole reason to use it.
    """
    path = map_path or MH_MAP
    if not os.path.isfile(path):
        return [], []
    text = open(path, encoding="utf-8", errors="replace").read()
    m = _MH_MAP_BASE_RE.search(text)
    if not m:
        return [], []
    base = int(m.group(1), 16)
    seen = set()
    addrs, names = [], []
    for name, rva_base_hex in _MH_MAP_FUNC_RE.findall(text):
        rva = int(rva_base_hex, 16) - base
        key = (rva, name)
        if key in seen:  # the map lists a symbol once per section entry; do not double-count it
            continue
        seen.add(key)
        addrs.append(rva)
        names.append(name)
    order = sorted(range(len(addrs)), key=lambda i: (addrs[i], names[i]))
    return [addrs[i] for i in order], [names[i] for i in order]


_MH_DLL_SYMS = None


def resolve_mh_dll_rva(rva, map_path=None):
    """`name+0xNN` for the mh.dll function containing RVA `rva`, or None.

    Nearest-preceding-symbol, upper-bounded by the NEXT distinct symbol's RVA when one exists (the
    map lists every function, so that bound is exact rather than a guessed cutoff) or a generous
    flat cap when `rva` is past the last one."""
    global _MH_DLL_SYMS
    if map_path is not None or _MH_DLL_SYMS is None:
        idx = _mh_dll_symbol_index(map_path)
        if map_path is None:
            _MH_DLL_SYMS = idx
    else:
        idx = _MH_DLL_SYMS
    addrs, names = idx
    if not addrs:
        return None
    i = bisect.bisect_right(addrs, rva) - 1
    if i < 0:
        return None
    delta = rva - addrs[i]
    j = i + 1
    while j < len(addrs) and addrs[j] == addrs[i]:
        j += 1
    cap = (addrs[j] - addrs[i]) if j < len(addrs) else 0x40000
    if delta > cap:
        return None
    return "%s+0x%x" % (names[i], delta) if delta else names[i]


_UNDNAME = None


def _find_undname():
    """undname.exe next to this box's MSVC install, or None -- see demangle_cpp()."""
    try:
        import sys as _sys

        _sys.path.insert(0, os.path.join(REPO, "tools"))
        import machine_config as mc
    except ImportError:
        return None
    base = os.path.join(mc.VS_INSTALL_ROOT, "VC", "Tools", "MSVC")
    if not os.path.isdir(base):
        return None
    for ver in sorted(os.listdir(base), reverse=True):
        for host in ("Hostx64", "Hostx86"):
            p = os.path.join(base, ver, "bin", host, "x86", "undname.exe")
            if os.path.isfile(p):
                return p
    return None


def demangle_cpp(name):
    """Best-effort MSVC demangling of ONE `?`-mangled C++ symbol, via undname.exe if this machine
    has MSVC installed (machine_config.VS_INSTALL_ROOT). Never a hard dependency: a non-mangled
    name (mh.dll carries plenty of `extern "C"` seam entry points, which already read as plain C++
    identifiers) or a machine with no MSVC both just return `name` unchanged."""
    if not name.startswith("?"):
        return name
    global _UNDNAME
    if _UNDNAME is None:
        _UNDNAME = _find_undname() or ""
    if not _UNDNAME:
        return name
    try:
        # NO FLAG ARGUMENT, and the one that used to be here made this function ALWAYS WRONG.
        # `undname.exe` takes no `-f` switch: it treats every argument as a symbol to undecorate,
        # so `undname -f <mangled>` printed TWO blocks -- `-f` first, the real symbol second -- and
        # the `re.search` below matched the first one. Every `?`-mangled mh.dll symbol therefore
        # demangled to the literal string "-f" on any machine that has undname installed, which is
        # every machine that can build the DLL. Measured 2026-09-17 by dist:LA4's acceptance run:
        # a deliberate fault in `crash_after_thread` resolved to `-f+0x17` instead of
        # `` `anonymous namespace'::crash_after_thread+0x17 ``. TL-GATE1's whole point is naming
        # the mh.dll function, so the defect was a constant wrong answer in the one output the
        # item exists to produce. `--last` is not an option either; the fix is to pass one symbol.
        r = subprocess.run([_UNDNAME, name], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired):
        return name
    m = re.search(r'is :- "(.*)"', r.stdout)
    return m.group(1) if m else name


def _demangle_symbol_str(sym):
    """demangle_cpp() applied to the NAME half of a resolve_mh_dll_rva() result (`name` or
    `name+0xNN`) -- the `+0xNN` suffix, if any, must survive untouched."""
    if sym is None:
        return None
    name, plus, rest = sym.partition("+")
    return demangle_cpp(name) + plus + rest


def resolve_module_fault(module, off_hex):
    """(va, rva, symbol) for a `module`+`off_hex` fault -- the ONE place both the WER/event-log
    scanners below and a drained report's `crash` field (print_drained_report()) turn a raw
    module+offset into a location, so the exe and mh.dll arithmetic each have exactly one
    implementation. `off_hex` may carry a leading "0x" or not; both are accepted.

    Game exe (`mh.exe` / `mh.focus.exe`): va = offset + IMAGE_BASE (EN, no ASLR), resolved against
    docs/symbols.md. mh.dll: the offset IS the RVA already (WER/the event log measure a DLL fault
    relative to the module's own base, and the launcher's `crash` field is defined the same way --
    see the module docstring); resolved against src/mh_dll/Release/mh.map, demangled best-effort.
    Any other module, or an unparseable offset: (None, None, None) -- an unresolved fault is
    reported as such, never silently mis-attributed to the wrong table.
    """
    try:
        off_int = int(off_hex, 16)
    except (TypeError, ValueError):
        return None, None, None
    m = (module or "").lower()
    if m in ("mh.focus.exe", "mh.exe"):
        va = off_int + IMAGE_BASE
        return va, None, resolve_va(va)
    if m == "mh.dll":
        raw = resolve_mh_dll_rva(off_int)
        return None, off_int, (_demangle_symbol_str(raw) if raw else None)
    return None, None, None


def _under(path, root):
    """Is `path` the file `root`, or a file inside the directory `root`?

    A plain startswith is WRONG and the selftest catches it: lane `...\\ui_sp_det` would then also
    claim every crash in `...\\ui_sp_det2`, silently attributing one lane's crash to its neighbour --
    the precise confusion per-lane attribution exists to prevent. Match on a path BOUNDARY.
    """
    p = os.path.normcase(os.path.abspath(path))
    r = os.path.normcase(os.path.abspath(root)).rstrip("\\/")
    return p == r or p.startswith(r + os.sep) or p.startswith(r + "/")


def scan(since=None, app_path=None, exe=None, roots=None):
    """Crash reports matching the filters, newest first.

    since     -- unix epoch; keep reports at or after it. None = no time filter.
    app_path  -- a lane DIRECTORY or a full exe path; matched case-insensitively against AppPath.
                 This is the per-lane attribution and it is why concurrent lanes do not confuse it.
    exe       -- image name filter (e.g. "mh.focus.exe") for when app_path is unknown.
    roots     -- WER report roots to walk. Defaults to this machine's. A caller that has PULLED
                 reports off another box (a rig VM peer -- ui_test.remote_crash_lines) passes the
                 staging directory here, so the same parser, the same AppPath attribution and the
                 same VA->symbol resolution serve local and remote peers. Duplicating any of that
                 for the remote case would mean two things to keep in step, and the half nobody
                 runs is the half that rots.
    """
    out = []
    for root in roots if roots is not None else wer_dirs():
        for rep in glob.glob(os.path.join(root, "*", "Report.wer")):
            try:
                mtime = os.path.getmtime(rep)
            except OSError:
                continue
            d = parse_report(rep)
            if not d:
                continue
            ap = d.get("AppPath", "")
            when = filetime_to_epoch(d.get("EventTime")) or mtime
            if since is not None and when < since:
                continue
            if app_path and not _under(ap, app_path):
                continue
            if exe and os.path.basename(ap).lower() != exe.lower():
                continue
            code = (d.get("Sig[6].Value") or "").lower()
            off = d.get("Sig[7].Value") or ""
            module = d.get("Sig[3].Value") or ""
            va, rva, symbol = resolve_module_fault(module, off)
            out.append(
                {
                    "report": rep,
                    "when": when,
                    "app_path": ap,
                    "app": d.get("Sig[0].Value") or os.path.basename(ap),
                    "module": module,
                    "code": code,
                    "code_name": EXCEPTION_NAMES.get(code, "?"),
                    "offset": off,
                    "va": va,
                    "rva": rva,
                    "symbol": symbol,
                }
            )
    out.sort(key=lambda r: r["when"], reverse=True)
    return out


EVENT_FIELD_RE = re.compile(r"^\s*(Faulting [\w -]+|Exception code|Fault offset)\s*:\s*(.*)$")
EVENT_DATE_RE = re.compile(r"^\s*Date:\s*([0-9T:\-]+)")


def parse_appcrash_events(text, since=None, app_path=None, exe=None):
    r"""Application-log Event 1000 records, in the same shape scan() returns.

    THE SECOND EVIDENCE SOURCE, and on this rig it is the ONLY one that works where it matters.
    Measured 2026-08-27: the rig VMs have HKLM\..\Windows Error Reporting\Disabled = 1, so no
    Report.wer is ever written there -- a WER-file detector aimed at a VM peer would have been one
    that can never fire, which is precisely the "we checked and there was no crash" false negative
    this module's docstring exists to refuse. The Application log's "Application Error" event is
    written anyway, and it carries the same three things the .wer does: faulting module, fault
    offset, exception code. U21's own evidence came from exactly here.

    Text is `wevtutil qe Application /f:text` output. The fields:
        Faulting application name: mh.focus.exe, version: ...
        Faulting module name:      mh.focus.exe, version: ...
        Exception code:            0xc0000005
        Fault offset:              0x0001f3a3
        Faulting application path: C:\games\mh\mh.focus.exe
    """
    out, cur, when = [], {}, None

    def flush():
        if not cur.get("Faulting application path") and not cur.get("Faulting application name"):
            return
        ap = cur.get("Faulting application path", "")
        if app_path and not _under(ap, app_path):
            return
        if exe and os.path.basename(ap).lower() != exe.lower():
            return
        if since is not None and when is not None and when < since:
            return
        module = (cur.get("Faulting module name", "") or "").split(",")[0].strip()
        code = (cur.get("Exception code", "") or "").strip().lower().replace("0x", "")
        off = (cur.get("Fault offset", "") or "").strip().lower().replace("0x", "")
        va, rva, symbol = resolve_module_fault(module, off)
        out.append(
            {
                "report": "Application event log (Event 1000)",
                "when": when,
                "app_path": ap,
                "app": (cur.get("Faulting application name", "") or "").split(",")[0].strip()
                or os.path.basename(ap),
                "module": module,
                "code": code,
                "code_name": EXCEPTION_NAMES.get(code, "?"),
                "offset": off,
                "va": va,
                "rva": rva,
                "symbol": symbol,
            }
        )

    for line in (text or "").splitlines():
        if line.startswith("Event["):
            flush()
            cur, when = {}, None
            continue
        m = EVENT_DATE_RE.match(line)
        if m and not when:
            try:
                when = calendar.timegm(time.strptime(m.group(1)[:19], "%Y-%m-%dT%H:%M:%S"))
            except ValueError:
                when = None
            continue
        m = EVENT_FIELD_RE.match(line)
        if m:
            cur.setdefault(m.group(1).strip(), m.group(2).strip())
    flush()
    out.sort(key=lambda r: r["when"] or 0, reverse=True)
    return out


def dumps(since=None):
    """Any .dmp files a configured LocalDumps collector wrote. Empty is normal -- dump collection is
    off by default on Windows, and its absence is NOT evidence that nothing crashed."""
    base = os.environ.get("LOCALAPPDATA")
    if not base:
        return []
    out = []
    for p in glob.glob(os.path.join(base, "CrashDumps", "*.dmp")):
        try:
            m = os.path.getmtime(p)
        except OSError:
            continue
        if since is None or m >= since:
            out.append({"path": p, "when": m, "size": os.path.getsize(p)})
    return sorted(out, key=lambda r: r["when"], reverse=True)


def describe(rec):
    """One line, and it leads with the thing you act on: where it faulted."""
    if rec["symbol"]:
        where = rec["symbol"]
    elif rec["va"]:
        where = "0x%08x" % rec["va"]
    elif rec.get("rva") is not None:
        where = "%s+0x%x (rva)" % (rec["module"], rec["rva"])
    else:
        where = "%s+%s" % (rec["module"], rec["offset"])
    return "%s crashed in %s -- %s (%s) at %s" % (
        rec["app"],
        where,
        rec["code_name"],
        rec["code"],
        time.strftime("%H:%M:%S", time.localtime(rec["when"])),
    )


def session_context(app_path):
    """SES1: "which MATCH was this peer in when it died", as a line, or None.

    A crash report has always been able to say WHERE in the binary a peer died and WHICH LANE it
    was. What it could not say is which match -- the logs of three matches shared one directory and
    nothing named them. A session directory now declares itself in `session.json`, and a peer that
    crashed mid-match leaves that file with `reason` still empty (SESSION_END never ran), which is
    both the marker of an unclean end and the id the OTHER peer's directory can be found by.

    Reads the NEWEST session directory under the lane's `logs\\`: a crash ends the process, so the
    newest session is the one it was in. Returns None for a peer that never joined a lobby -- which
    is the honest answer, not a gap."""
    lane = os.path.dirname(app_path) if os.path.splitext(app_path)[1] else app_path
    logs = os.path.join(lane, "logs")
    if not os.path.isdir(logs):
        return None
    try:
        cands = sorted(
            n
            for n in os.listdir(logs)
            if "_menu_" not in n and os.path.isdir(os.path.join(logs, n))
        )
    except OSError:
        return None
    for name in reversed(cands):
        fp = os.path.join(logs, name, "session.json")
        if not os.path.isfile(fp):
            continue
        try:
            with open(fp, encoding="utf-8", errors="replace") as fh:
                s = json.load(fh)
        except (OSError, ValueError):
            continue
        return "  [crash] session: match_id=%s slot=%s role=%s map=%s (%s) dir=%s" % (
            s.get("match_id") or "?",
            s.get("slot"),
            s.get("role") or "?",
            s.get("map") or "?",
            ("ended: %s" % s["reason"])
            if s.get("reason")
            else "NO SESSION_END -- died in the match",
            name,
        )
    return None


def report_for(app_path, since, limit=3, roots=None):
    """The lines a caller (ui_test) should print, or [] if nothing matched.

    Returns the report PATH too: the .wer holds the loaded-module list and the full signature set,
    which is the next thing anyone wants after the one-liner.
    """
    recs = scan(since=since, app_path=app_path, roots=roots)[:limit]
    lines = []
    for r in recs:
        lines.append("  [crash] " + describe(r))
        lines.append("  [crash] report: %s" % r["report"])
    if recs:
        ctx = session_context(app_path)
        if ctx:
            lines.append(ctx)
    return lines


# ─────────────────────────────── drained reports (tracker dist:RP3) ───────────────────────────────

# The `; [session] match_id=<32 hex>` line SES0 writes to mh_net.log, once per distinct match (see
# src/mh_dll/mh/seams/net_discovery.cpp). Both peers in a match write their OWN copy of this line to
# their OWN local log, so finding it inside a drained report's zip and comparing it against the
# report's meta.json match_id is a cross-check that the summary's match_id is not just present but
# CORRECT -- the two are independent sources (server-relayed metadata vs. a client-written log line).
SESSION_MATCH_ID_RE = re.compile(r"^; \[session\] match_id=([0-9a-fA-F]+)\s*$", re.M)


def session_match_ids_in_zip(zip_path):
    """Every match_id any `*.log` entry in the zip declares via SES0's line, in file order."""
    ids = []
    try:
        with zipfile.ZipFile(zip_path) as z:
            for name in z.namelist():
                if not name.lower().endswith(".log"):
                    continue
                try:
                    text = z.read(name).decode("utf-8", errors="replace")
                except (KeyError, OSError):
                    continue
                ids.extend(SESSION_MATCH_ID_RE.findall(text))
    except (OSError, zipfile.BadZipFile):
        pass
    return ids


# ─────────────────────────── raw crash markers swept into the zip (dist:LA9) ───────────────────────────────
#
# WHY THIS EXISTS. report.json's `crash` object is the PRIMARY path (below) -- it exists only when
# THIS launcher run's own live crash channel caught the fault. dist:LA9 widened a report's scope from
# one session directory to the whole `logs\` tree, and that sweep (report.rs's
# `add_crash_marker_files`) picks up every `mh_crash_*.marker` file sitting loose under `logs\`,
# including one an EARLIER, undrained crash left behind -- a report built well after the fact, with
# no live channel to populate `crash`, can still carry the exact evidence a live one would have. This
# reads that marker straight out of the zip and resolves it the same way `crash` is resolved, so
# nobody has to unzip a report by hand to find and read a stray `.marker` file.
MARKER_ENTRY_RE = re.compile(r"^crash/(mh_crash_[0-9a-f]+\.marker)$", re.I)


def parse_marker_text(text):
    """`key=value` marker text (`mh_crash_marker.h`'s `mh_crash_marker_text`) -> a dict. Blank lines
    and any key it does not recognise are ignored, the same tolerance the format's own header
    documents ("an unknown key is ignored by construction, which is the point of key=value")."""
    facts = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or "=" not in line:
            continue
        key, _, value = line.partition("=")
        facts[key.strip()] = value.strip()
    return facts


def marker_entries_in_zip(zip_path):
    """Every `crash/mh_crash_*.marker` entry in a report zip (dist:LA9's sweep), in the zip's own
    listing order."""
    try:
        with zipfile.ZipFile(zip_path) as z:
            return [n for n in z.namelist() if MARKER_ENTRY_RE.match(n)]
    except (OSError, zipfile.BadZipFile):
        return []


def resolve_marker_in_zip(zip_path, entry):
    """Read one `crash/mh_crash_*.marker` entry out of a report zip and resolve it exactly like
    `report.json`'s `crash` object does: `(va, rva, symbol, facts)`, or `None` if the entry cannot be
    read or names no module/offset. `facts` is the marker's own parsed key=value dict (match_id, pid,
    tid, build, when, ...) for anything beyond the location."""
    try:
        with zipfile.ZipFile(zip_path) as z:
            text = z.read(entry).decode("utf-8", errors="replace")
    except (OSError, KeyError, zipfile.BadZipFile):
        return None
    facts = parse_marker_text(text)
    module = facts.get("module", "")
    offset = facts.get("offset", "")
    if not module or not offset:
        return None
    va, rva, symbol = resolve_module_fault(module, offset)
    return va, rva, symbol, facts


# ─────────────────────────────── the minidump's Exception stream (dist:LA5) ───────────────────────────────
#
# WHY THIS EXISTS. report.json's `crash` object (module/offset/thread_id/code, above) already names a
# frame without ever opening the .dmp -- that is deliberate, and it stays the primary path: on this
# project's real configuration (a 64-bit launcher dumping a 32-bit game), a 64-bit MiniDumpWriteDump
# refuses the WOW64 target's EXCEPTION_POINTERS (ERROR_NOACCESS -- it reads the 32-bit pointers as
# 64-bit), so the dump used to carry no Exception stream at all. dist:LA5 changed that: the launcher
# now builds a real Exception stream into
# `minidump.dmp` from what mh.dll captured directly (`crash::append_exception_stream`,
# `src/launcher/src/crash.rs`), so a drained report that shipped a minidump can be cross-checked
# against it independently of `report.json` -- the two are written by different code paths inside
# the launcher, so agreement between them is evidence neither is wrong.
#
# A DEPENDENCY-FREE READER, ON PURPOSE. This project's Python side has never taken a minidump-parsing
# library, and LA5 does not need one: MINIDUMP_HEADER (32 bytes) + a MINIDUMP_DIRECTORY array (12
# bytes/entry) + one MINIDUMP_EXCEPTION_STREAM (168 bytes) is the whole of what this function reads,
# all fixed-size, all documented by Microsoft's minidumpapiset.h. See `src/launcher/src/crash.rs`'s
# `append_exception_stream` for the writer of exactly these bytes.
MINIDUMP_SIGNATURE = 0x504D444D  # 'PMDM', per minidumpapiset.h
MINIDUMP_EXCEPTION_STREAM_TYPE = 6


def parse_exception_stream(data):
    """(thread_id, exception_code, exception_address) from a minidump's bytes, or None if it is not a
    minidump, is too short, or carries no Exception stream (the pre-LA5 shape: every other stream
    present, no Exception one, because a 64-bit MiniDumpWriteDump cannot read a WOW64 target's
    exception record). Works over bytes rather than a path so it
    reads equally out of a plain `.dmp` file or a `minidump.dmp` zip entry (report.rs's layout puts
    the dump INSIDE report.zip, never extracted alongside meta.json)."""
    if len(data) < 32:
        return None
    sig, _version, n_streams, dir_rva = struct.unpack_from("<IIII", data, 0)
    if sig != MINIDUMP_SIGNATURE:
        return None
    dir_end = dir_rva + n_streams * 12
    if dir_rva < 0 or dir_end > len(data):
        return None
    exc_rva = None
    for i in range(n_streams):
        stream_type, _data_size, rva = struct.unpack_from("<III", data, dir_rva + i * 12)
        if stream_type == MINIDUMP_EXCEPTION_STREAM_TYPE:
            exc_rva = rva
            break
    if exc_rva is None or exc_rva + 32 > len(data):
        return None
    # ThreadId(4) __align(4) ExceptionCode(4) ExceptionFlags(4) ExceptionRecord(8)
    # ExceptionAddress(8) -- the six fields this function needs; the trailing
    # NumberParameters/ExceptionInformation[]/ThreadContext are left unread.
    thread_id, _align, code, _flags, _rec, address = struct.unpack_from("<IIIIQQ", data, exc_rva)
    return thread_id, code, address


def read_dmp_exception_stream(dmp_path):
    """`parse_exception_stream` over a plain `.dmp` file on disk."""
    try:
        with open(dmp_path, "rb") as f:
            return parse_exception_stream(f.read())
    except OSError:
        return None


def dmp_exception_stream_in_zip(zip_path, entry="minidump.dmp"):
    """`parse_exception_stream` over the `minidump.dmp` entry of a report zip, or None if the zip, the
    entry, or a stream inside it is absent -- all ordinary (the box is unticked far more often than
    not; see report.rs's `include_dump`)."""
    try:
        with zipfile.ZipFile(zip_path) as z:
            return parse_exception_stream(z.read(entry))
    except (OSError, KeyError, zipfile.BadZipFile):
        return None


def read_description_head(report_dir, n=300):
    p = os.path.join(report_dir, "description.txt")
    if not os.path.isfile(p):
        return ""
    try:
        with open(p, encoding="utf-8", errors="replace") as f:
            head = f.read(n).replace("\n", " ").strip()
    except OSError:
        return ""
    return head


def print_drained_report(report_dir, say=print):
    """Read ONE drained report directory (`tools/drain_reports.py`'s layout: meta.json +
    description.txt + report.zip) and print its resolution. Returns True if it named a crashing
    FUNCTION (the thing TL-GATE1's done_when asks for), False otherwise (no crash field and no
    resolvable marker, or an offset this build's symbol tables cannot place).

    THE `crash` FIELD CONTRACT (defined here for dist:LA4, the not-yet-built Rust launcher, to
    emit; documented in full in src/collector/README.md "Draining reports"): an OPTIONAL object in
    meta.json, `{"module": "mh.dll" | "mh.exe" | "mh.focus.exe", "offset": "0x...."}`. `offset`'s
    MEANING is module-dependent and is resolve_module_fault()'s job to know, not this function's:
    an exe offset is image-relative (+ IMAGE_BASE), an mh.dll offset is already an RVA. A report
    with no `crash` key is a normal bug report (no fault to resolve) -- not an error, but (dist:LA9)
    not necessarily the end of it either: `logs\\`'s own sweep may have carried a raw
    `crash/mh_crash_*.marker` file into the zip regardless (an earlier crash's marker, or one this
    run's launcher process never had a live channel open for), and this function resolves that too,
    straight out of the zip -- see `resolve_marker_in_zip`.
    """
    with open(os.path.join(report_dir, "meta.json"), encoding="utf-8") as f:
        meta = json.load(f)

    crash = meta.get("crash") or {}
    module = crash.get("module", "")
    offset = crash.get("offset", "")
    resolved = False
    zip_path = os.path.join(report_dir, "report.zip")
    if crash:
        va, rva, symbol = resolve_module_fault(module, offset)
        if symbol:
            where = symbol
            resolved = True
        elif va:
            where = "0x%08x (va, unresolved)" % va
        elif rva is not None:
            where = "%s+0x%x (rva, unresolved)" % (module, rva)
        else:
            where = "%s+%s (unresolved -- unknown module or offset)" % (module, offset)
        say("[report] %s -- crashed in %s" % (report_dir, where))
    else:
        say("[report] %s -- no crash field (exit_code=%s)" % (report_dir, meta.get("exit_code")))
        # dist:LA9. No live crash channel caught anything THIS run, but `logs\`'s own sweep may
        # still have swept in a `mh_crash_*.marker` an EARLIER, undrained crash left behind --
        # resolve it straight out of the zip rather than leaving it as a file someone has to find
        # and hand-copy out to read.
        if os.path.isfile(zip_path):
            for entry in marker_entries_in_zip(zip_path):
                found = resolve_marker_in_zip(zip_path, entry)
                if found is None:
                    continue
                va, rva, symbol, facts = found
                marker_module = facts.get("module", "?")
                if symbol:
                    where = symbol
                    resolved = True
                elif va:
                    where = "0x%08x (va, unresolved)" % va
                elif rva is not None:
                    where = "%s+0x%x (rva, unresolved)" % (marker_module, rva)
                else:
                    where = "%s+%s (unresolved -- unknown module or offset)" % (
                        marker_module,
                        facts.get("offset", "?"),
                    )
                say(
                    "   [report] %s -- crashed in %s (match_id=%s, no live crash channel -- found "
                    "in the report's own logs\\ sweep)" % (entry, where, facts.get("match_id", "?"))
                )

    # dist:LA5. If the report shipped a minidump AND it carries an Exception stream (both
    # optional -- the box has to be ticked, and the marker has to have named a `.ctx32` sidecar),
    # cross-check it against `crash`: two different pieces of the launcher wrote these, so agreement
    # is evidence neither is wrong, and a mismatch is worth a WARNING rather than a silent pick.
    if crash and os.path.isfile(zip_path):
        exc = dmp_exception_stream_in_zip(zip_path)
        if exc is not None:
            dmp_tid, dmp_code, _dmp_addr = exc
            meta_tid = crash.get("thread_id")
            meta_code = crash.get("code", "")
            try:
                meta_code_int = int(meta_code, 16) if meta_code else None
            except ValueError:
                meta_code_int = None
            if meta_tid is not None and meta_code_int is not None:
                if meta_tid == dmp_tid and meta_code_int == dmp_code:
                    say(
                        "   [report] minidump Exception stream: thread %d code 0x%08x -- "
                        "agrees with report.json's crash object" % (dmp_tid, dmp_code)
                    )
                else:
                    say(
                        "   [report] WARNING: minidump Exception stream (thread %d code 0x%08x) "
                        "disagrees with report.json's crash object (thread %s code %s)"
                        % (dmp_tid, dmp_code, meta_tid, meta_code)
                    )
            else:
                say(
                    "   [report] minidump Exception stream: thread %d code 0x%08x "
                    "(report.json carries no thread_id/code to cross-check against)"
                    % (dmp_tid, dmp_code)
                )
        # exc is None whenever the box was unticked, the zip carries no minidump.dmp, or the dump
        # predates dist:LA5 -- all ordinary, so this says nothing rather than a false "missing".

    match_id = meta.get("match_id")
    logged_ids = session_match_ids_in_zip(zip_path) if os.path.isfile(zip_path) else []
    if not match_id:
        xcheck = "no match_id in meta.json"
    elif not logged_ids:
        xcheck = "match_id NOT cross-checked (no `; [session] match_id=` line found in the zip)"
    elif all(i == match_id for i in logged_ids):
        xcheck = "match_id verified against %d session-log line(s) in the report" % len(logged_ids)
    else:
        xcheck = "WARNING: match_id in meta.json disagrees with the report's own session log(s)"

    say(
        "   [report] match_id=%s version=%s exit_code=%s -- %s"
        % (match_id, meta.get("version"), meta.get("exit_code"), xcheck)
    )
    desc = read_description_head(report_dir)
    if desc:
        say("   [report] desc: %s" % desc)
    return resolved


SELFTEST_REPORT = """Version=1
EventType=APPCRASH
EventTime=134300537436040744
Sig[0].Name=Application Name
Sig[0].Value=mh.focus.exe
Sig[3].Name=Fault Module Name
Sig[3].Value=mh.focus.exe
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000ee741
AppPath={APPPATH}
"""


# A real `wevtutil qe Application /f:text` pair: one game crash to find, one foreign crash to reject.
# The offset is U21's own (0x0001f3a3 -> 0x0041f3a3, llm_strat_pathfind_trace_route), so the parser is
# tested against the exact record this detector was built to catch.
SELFTEST_EVENTS = r"""Event[0]
  Log Name: Application
  Source: Application Error
  Date: 2026-07-25T18:23:11.4740000Z
  Event ID: 1000
  Description:
Faulting application name: mh.focus.exe, version: 0.0.0.0, time stamp: 0x3b0f2c1a
Faulting module name: mh.focus.exe, version: 0.0.0.0, time stamp: 0x3b0f2c1a
Exception code: 0xc0000005
Fault offset: 0x0001f3a3
Faulting process id: 0x1a2c
Faulting application path: C:\games\mh\mh.focus.exe
Report Id: 0d2f1e00-0000-0000-0000-000000000000

Event[1]
  Log Name: Application
  Source: Application Error
  Date: 2026-07-25T18:20:02.1000000Z
  Event ID: 1000
  Description:
Faulting application name: notepad.exe, version: 11.0.0.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.28000.2525, time stamp: 0xc6477a45
Exception code: 0xc0000409
Fault offset: 0x001829bd
Faulting process id: 0x3630
Faulting application path: C:\Windows\System32\notepad.exe
Report Id: 09d416cc-0000-0000-0000-000000000000
"""


def selftest():
    """Prove the scanner finds a crash, ATTRIBUTES it to the right lane, and can say no.

    A diagnostic that silently matches nothing is worse than no diagnostic: it turns "we checked and
    there was no crash" into a false negative at exactly the moment someone is deciding whether a
    stall is a hang. So the negative cases carry as much weight as the positive one, and the lane
    filter is checked against a SIBLING lane whose path shares a prefix -- the case a naive
    startswith() gets wrong.
    """
    import shutil
    import tempfile

    fails = []
    total = [0]

    def ck(name, ok):
        total[0] += 1
        print("  %-58s %s" % (name, "ok" if ok else "FAIL"))
        if not ok:
            fails.append(name)

    tmp = tempfile.mkdtemp(prefix="crashsel_")
    try:
        lane = os.path.join(tmp, "lanes", "ui_sp_det")
        sibling = os.path.join(tmp, "lanes", "ui_sp_det2")  # shares ui_sp_det as a PREFIX
        os.makedirs(lane)
        os.makedirs(sibling)
        root = os.path.join(tmp, "WER", "ReportArchive")
        for tag, d in (("a", lane), ("b", sibling)):
            rd = os.path.join(root, "AppCrash_mh.focus.exe_%s" % tag)
            os.makedirs(rd)
            with open(os.path.join(rd, "Report.wer"), "w", encoding="utf-16") as f:
                f.write(SELFTEST_REPORT.replace("{APPPATH}", os.path.join(d, "mh.focus.exe")))

        global wer_dirs
        real = wer_dirs
        wer_dirs = lambda: [root]  # noqa: E731
        try:
            everything = scan(since=None)
            ck("finds both synthetic reports", len(everything) == 2)

            mine = scan(since=None, app_path=lane)
            ck("lane filter selects exactly one", len(mine) == 1)
            ck(
                "lane filter does NOT match the prefix-sharing sibling",
                len(mine) == 1
                and os.path.normcase(mine[0]["app_path"]).startswith(
                    os.path.normcase(lane) + os.sep
                ),
            )
            ck("sibling lane finds its own", len(scan(since=None, app_path=sibling)) == 1)

            r = mine[0] if mine else {}
            ck("exception code parsed", r.get("code") == "c0000005")
            ck("exception NAMED, not just hex", r.get("code_name") == "ACCESS_VIOLATION")
            ck("VA = offset + image base", r.get("va") == 0x000EE741 + IMAGE_BASE)
            ck("EventTime decoded to a sane epoch", 1.4e9 < (r.get("when") or 0) < 4e9)

            when = r.get("when") or 0
            ck("since AFTER the event excludes it", scan(since=when + 60, app_path=lane) == [])
            ck("since BEFORE the event includes it", len(scan(since=when - 60, app_path=lane)) == 1)
            ck("exe filter matches", len(scan(since=None, app_path=lane, exe="mh.focus.exe")) == 1)
            ck(
                "exe filter rejects another image",
                scan(since=None, app_path=lane, exe="other.exe") == [],
            )
            ck("report_for() produces lines", len(report_for(lane, when - 60)) >= 2)
            # The PULLED-REPORTS path (ui_test.remote_crash_lines): same parser, explicit root,
            # and it must not fall back to this machine's WER tree when given one.
            ck(
                "explicit roots= finds a pulled report",
                len(scan(since=None, app_path=lane, roots=[root])) == 1,
            )
            ck(
                "explicit roots= that holds nothing finds nothing (no silent local fallback)",
                scan(since=None, app_path=lane, roots=[os.path.join(tmp, "empty")]) == [],
            )
            ck(
                "report_for(roots=) lines match the local ones",
                report_for(lane, when - 60, roots=[root]) == report_for(lane, when - 60),
            )
            ck(
                "report_for() is empty for a clean lane",
                report_for(os.path.join(tmp, "nope"), 0) == [],
            )
        finally:
            wer_dirs = real
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # The Application-log parser -- the source that works on a box with WER disabled, i.e. every
    # rig VM. Same record shape as scan(), so describe() and the ui_test callers do not branch.
    ev = parse_appcrash_events(SELFTEST_EVENTS)
    ck("event log: both crash events parsed", len(ev) == 2)
    if len(ev) == 2:
        g = [r for r in ev if r["app"] == "mh.focus.exe"]
        ck("event log: faulting app parsed", len(g) == 1)
        ck("event log: exception NAMED", g and g[0]["code_name"] == "ACCESS_VIOLATION")
        ck("event log: VA = offset + image base", g and g[0]["va"] == 0x0001F3A3 + IMAGE_BASE)
        ck("event log: names the FUNCTION, not a hex number", bool(g and g[0]["symbol"]))
        if g and g[0]["symbol"]:
            print("      0x0041f3a3 -> %s" % g[0]["symbol"])
        ck(
            "event log: app_path filter selects one",
            len(parse_appcrash_events(SELFTEST_EVENTS, app_path=r"C:\games\mh")) == 1,
        )
        ck(
            "event log: app_path filter rejects a prefix-sharing sibling",
            parse_appcrash_events(SELFTEST_EVENTS, app_path=r"C:\games\mh2") == [],
        )
        w = g[0]["when"] or 0
        ck(
            "event log: since AFTER excludes",
            parse_appcrash_events(SELFTEST_EVENTS, since=w + 60) == [],
        )
        ck(
            # -600, not -60: the two fixture events are ~3 min apart, so a 60 s window would
            # correctly exclude the older one and the check would be testing its own arithmetic.
            "event log: since BEFORE includes",
            len(parse_appcrash_events(SELFTEST_EVENTS, since=w - 600)) == 2,
        )
    ck("event log: empty input is empty output, not a crash", parse_appcrash_events("") == [])

    # The live half: the symbol resolver is only useful if it actually has symbols loaded.
    sym = resolve_va(0x004EE741)
    ck("resolves a real VA against docs/symbols.md", bool(sym))
    if sym:
        print("      0x004ee741 -> %s" % sym)

    # ---- mh.dll resolution (tracker TL-GATE1 / dist:RP3) -----------------------------------
    # Hermetic: a FIXTURE .map, never the real (gitignored, build-only) src/mh_dll/Release/mh.map
    # -- this must pass on a checkout with no DLL ever built. Preferred load address 0x10000000,
    # four FUNCTION rows plus one segment-0000 absolute symbol and one DATA-section row (neither
    # carries the `f` flag, so both must be excluded), one section-table row whose second hex
    # token has a trailing "H" (must not be mistaken for a symbol row).
    fixture_map = (
        " mh\n\n Timestamp is 00000000 (fixture)\n\n"
        " Preferred load address is 10000000\n\n"
        " Start         Length     Name                   Class\n"
        " 0001:00000000 00000100H .text$mn                CODE\n\n"
        "  Address         Publics by Value              Rva+Base       Lib:Object\n\n"
        " 0000:00000000       ___ImageBase               10000000     <linker-defined>\n"
        " 0001:00000010       _fn_alpha                  10000010 f   fixture.obj\n"
        " 0001:00000030       _fn_beta                   10000030 f   fixture.obj\n"
        " 0001:00000030       ?fn_beta_mangled@@YAXXZ    10000030 f   fixture.obj\n"
        " 0001:00000080       _fn_gamma_last             10000080 f   fixture.obj\n"
        " 0003:00000000       _some_data                 10020000     fixture.obj\n"
    )
    tmp2 = tempfile.mkdtemp(prefix="crashsel_map_")
    try:
        fmap = os.path.join(tmp2, "mh.map")
        with open(fmap, "w", encoding="utf-8") as f:
            f.write(fixture_map)

        addrs, names = _mh_dll_symbol_index(fmap)
        ck("mh.map fixture: exactly the 4 FUNCTION rows are indexed", len(addrs) == 4)
        ck(
            "mh.map fixture: the absolute + DATA rows (no `f` flag) are excluded",
            "___ImageBase" not in names and "_some_data" not in names,
        )
        ck(
            "mh.map fixture: RVA = Rva+Base - preferred load address",
            resolve_mh_dll_rva(0x10, fmap) == "_fn_alpha",
        )
        ck(
            "mh.map fixture: nearest-preceding symbol + offset",
            resolve_mh_dll_rva(0x15, fmap) == "_fn_alpha+0x5",
        )
        ck(
            # Two symbols share RVA 0x30 (`_fn_beta` and its mangled alias); bisect_right lands on
            # the LAST of a tied run in the (addr, name)-sorted index, so the alphabetically GREATER
            # name wins ('_' > '?' in ASCII) -- deterministic, just not "whichever was written
            # first in the map".
            "mh.map fixture: two symbols at one RVA -- resolves deterministically",
            resolve_mh_dll_rva(0x30, fmap) == "_fn_beta",
        )
        ck(
            "mh.map fixture: the LAST symbol still resolves with an offset",
            resolve_mh_dll_rva(0x90, fmap) == "_fn_gamma_last+0x10",
        )
        ck(
            "mh.map fixture: an RVA absurdly far past the last symbol is unresolved, not guessed",
            resolve_mh_dll_rva(0x50000, fmap) is None,
        )
        ck(
            "mh.map fixture: an RVA before the first symbol is unresolved",
            resolve_mh_dll_rva(0x5, fmap) is None,
        )
        ck(
            "demangle_cpp passes a non-mangled (extern \"C\") name through unchanged",
            demangle_cpp("_fn_alpha") == "_fn_alpha",
        )
        dm = demangle_cpp("?fn_beta_mangled@@YAXXZ")
        ck(
            "demangle_cpp never raises on a mangled name (undname present or not)",
            isinstance(dm, str) and dm,
        )

        # resolve_module_fault's DISPATCH -- exe (docs/symbols.md, +IMAGE_BASE), mh.dll (RVA via
        # the map above), and an unrecognised module (must resolve to nothing, not guess).
        global MH_MAP, _MH_DLL_SYMS
        real_map, real_cache = MH_MAP, _MH_DLL_SYMS
        MH_MAP, _MH_DLL_SYMS = fmap, None
        try:
            va, rva, symbol = resolve_module_fault("mh.dll", "0x10")
            ck(
                "resolve_module_fault(mh.dll, ...): RVA is the raw offset, no IMAGE_BASE added",
                rva == 0x10 and va is None,
            )
            ck("resolve_module_fault(mh.dll, ...): names the function", symbol == "_fn_alpha")
            va, rva, symbol = resolve_module_fault("mh.exe", "0x1f3a3")
            ck(
                "resolve_module_fault(mh.exe, ...): still VA = offset + IMAGE_BASE (no regression)",
                va == 0x1F3A3 + IMAGE_BASE and rva is None,
            )
            va, rva, symbol = resolve_module_fault("KERNELBASE.dll", "0x1234")
            ck(
                "resolve_module_fault(): an unrecognised module resolves to nothing",
                (va, rva, symbol) == (None, None, None),
            )

            # ---- print_drained_report(): the dist:RP3 `--report` path end to end ----------
            rtmp = tempfile.mkdtemp(prefix="crashsel_report_")
            try:
                match_id = "01a0af3cea0070a1a2a3a4a5a6a7a8a9"
                with zipfile.ZipFile(os.path.join(rtmp, "report.zip"), "w") as z:
                    z.writestr("mh_net.log", "; [session] match_id=%s\nhi\n" % match_id)
                    z.writestr("peer_mh_net.log", "; [session] match_id=%s\nho\n" % match_id)
                with open(os.path.join(rtmp, "description.txt"), "w", encoding="utf-8") as f:
                    f.write("deliberate fault inside mh.dll (fixture)")
                with open(os.path.join(rtmp, "meta.json"), "w", encoding="utf-8") as f:
                    json.dump(
                        {
                            "match_id": match_id,
                            "version": "fixture",
                            "exit_code": -1073741819,
                            "crash": {"module": "mh.dll", "offset": "0x30"},
                        },
                        f,
                    )
                printed = []
                resolved = print_drained_report(rtmp, say=printed.append)
                ck(
                    "print_drained_report(): resolves the crash (RP3/TL-GATE1's done_when)",
                    resolved,
                )
                ck(
                    "print_drained_report(): names the function in its first line",
                    any("fn_beta" in ln for ln in printed[:1]),
                )
                ck(
                    "print_drained_report(): the summary carries match_id",
                    any(("match_id=%s" % match_id) in ln for ln in printed),
                )
                ck(
                    "print_drained_report(): cross-checks match_id against the zip's session log(s)",
                    any("verified against 2 session-log" in ln for ln in printed),
                )

                # A mismatching second peer log must be flagged, not silently accepted.
                with zipfile.ZipFile(os.path.join(rtmp, "report.zip"), "w") as z:
                    z.writestr("mh_net.log", "; [session] match_id=%s\n" % match_id)
                    z.writestr("peer_mh_net.log", "; [session] match_id=%s\n" % ("0" * 32))
                printed2 = []
                print_drained_report(rtmp, say=printed2.append)
                ck(
                    "print_drained_report(): a disagreeing peer log is flagged, not hidden",
                    any("WARNING" in ln for ln in printed2),
                )

                # ---- dist:LA5: the minidump's Exception stream, cross-checked -----------------
                # A minimal but real minidump: header (32B) + a one-entry directory (12B) +
                # just the six fields of an Exception stream this reader consumes (32B) -- the same
                # shape `crash::append_exception_stream` produces, trimmed to what parsing needs.
                def fake_dmp(thread_id, code, address=0x1001_75B0):
                    # MINIDUMP_HEADER is 32 bytes whole (Signature/Version/NumberOfStreams/
                    # StreamDirectoryRva/CheckSum/TimeDateStamp are u32 x6, Flags a u64) -- the
                    # directory starts right after it.
                    header = struct.pack("<IIIIIIQ", MINIDUMP_SIGNATURE, 42899, 1, 32, 0, 0, 0)
                    directory = struct.pack("<III", MINIDUMP_EXCEPTION_STREAM_TYPE, 168, 44)
                    stream = struct.pack("<IIIIQQ", thread_id, 0, code, 0, 0, address)
                    return header + directory + stream

                ck(
                    "parse_exception_stream(): reads thread/code/address back out of a synthetic dump",
                    parse_exception_stream(fake_dmp(4242, 0xC0000005))
                    == (4242, 0xC0000005, 0x1001_75B0),
                )
                ck(
                    "parse_exception_stream(): not-a-minidump is None, not a crash",
                    parse_exception_stream(b"not a minidump at all") is None,
                )
                THREAD_LIST_STREAM_TYPE = 3
                ck(
                    "parse_exception_stream(): a header with no Exception stream entry is None",
                    parse_exception_stream(
                        struct.pack("<IIIIIIQ", MINIDUMP_SIGNATURE, 42899, 1, 32, 0, 0, 0)
                        + struct.pack("<III", THREAD_LIST_STREAM_TYPE, 4, 44)
                        + b"\x00" * 4
                    )
                    is None,
                )

                with zipfile.ZipFile(os.path.join(rtmp, "report.zip"), "w") as z:
                    z.writestr("mh_net.log", "; [session] match_id=%s\n" % match_id)
                    z.writestr("minidump.dmp", fake_dmp(4242, 0xC0000005))
                with open(os.path.join(rtmp, "meta.json"), "w", encoding="utf-8") as f:
                    json.dump(
                        {
                            "match_id": match_id,
                            "version": "fixture",
                            "exit_code": -1073741819,
                            "crash": {
                                "module": "mh.dll",
                                "offset": "0x30",
                                "thread_id": 4242,
                                "code": "0xc0000005",
                            },
                        },
                        f,
                    )
                printed_dmp = []
                print_drained_report(rtmp, say=printed_dmp.append)
                ck(
                    "print_drained_report(): agreeing Exception stream is reported, not silent",
                    any(
                        "Exception stream: thread 4242 code 0xc0000005" in ln and "agrees" in ln
                        for ln in printed_dmp
                    ),
                )

                with zipfile.ZipFile(os.path.join(rtmp, "report.zip"), "w") as z:
                    z.writestr("mh_net.log", "; [session] match_id=%s\n" % match_id)
                    # A different thread than report.json's crash object claims.
                    z.writestr("minidump.dmp", fake_dmp(9999, 0xC0000005))
                printed_dmp2 = []
                print_drained_report(rtmp, say=printed_dmp2.append)
                ck(
                    "print_drained_report(): a disagreeing Exception stream is flagged, not hidden",
                    any("WARNING" in ln and "9999" in ln for ln in printed_dmp2),
                )

                with zipfile.ZipFile(os.path.join(rtmp, "report.zip"), "w") as z:
                    z.writestr("mh_net.log", "; [session] match_id=%s\n" % match_id)
                    # No minidump.dmp entry at all -- the ordinary case (box unticked).
                ck(
                    "dmp_exception_stream_in_zip(): no minidump.dmp entry is None, not an error",
                    dmp_exception_stream_in_zip(os.path.join(rtmp, "report.zip")) is None,
                )

                # A report with no crash field at all is a normal bug report, not a failure.
                rtmp2 = tempfile.mkdtemp(prefix="crashsel_report2_")
                with open(os.path.join(rtmp2, "meta.json"), "w", encoding="utf-8") as f:
                    json.dump({"match_id": "x", "version": "fixture", "exit_code": 0}, f)
                printed3 = []
                resolved3 = print_drained_report(rtmp2, say=printed3.append)
                ck(
                    "print_drained_report(): no crash field -> not a failure, not resolved-crash",
                    resolved3 is False,
                )
                shutil.rmtree(rtmp2, ignore_errors=True)

                # ---- dist:LA9: a marker swept into the zip with no `crash` field to match ------
                # `report.json` carries no `crash` key (no live channel this run), but `logs\`'s own
                # sweep still put a raw `mh_crash_*.marker` into the zip -- resolve_marker_in_zip
                # must find it and resolve it exactly like `crash` would have, WITHOUT anyone
                # hand-copying the marker out of the zip first.
                rtmp3 = tempfile.mkdtemp(prefix="crashsel_report3_")
                try:
                    marker_text = (
                        "mh_crash=1\ncode=0xc0000005\nflags=0x00000000\npid=4242\ntid=1337\n"
                        "address=0x1001a5b0\npointers=0x00000000\nmodule=mh.dll\n"
                        "module_base=0x10000000\noffset=0x30\nmatch_id=%s\n"
                        "build=0.1.0-rc1+fixture\nwhen=20260918T090000Z\nctx=0\n" % match_id
                    )
                    with zipfile.ZipFile(os.path.join(rtmp3, "report.zip"), "w") as z:
                        z.writestr("crash/mh_crash_deadbeef12345678.marker", marker_text)
                        z.writestr("logs/20260918T090000Z_x_1_host/mh_net.log", "no crash here\n")
                    with open(os.path.join(rtmp3, "meta.json"), "w", encoding="utf-8") as f:
                        json.dump(
                            {
                                "match_id": match_id,
                                "version": "fixture",
                                "exit_code": 0,
                                # No "crash" key: this run's own launcher never caught a live fault.
                            },
                            f,
                        )
                    ck(
                        "marker_entries_in_zip(): finds the swept-in marker by its zip path",
                        marker_entries_in_zip(os.path.join(rtmp3, "report.zip"))
                        == ["crash/mh_crash_deadbeef12345678.marker"],
                    )
                    printed4 = []
                    resolved4 = print_drained_report(rtmp3, say=printed4.append)
                    ck(
                        "print_drained_report(): resolves a marker with no `crash` field to match",
                        resolved4,
                    )
                    ck(
                        "print_drained_report(): names the function from the swept-in marker",
                        any("fn_beta" in ln for ln in printed4),
                    )
                    ck(
                        "print_drained_report(): the marker line says it found no live channel",
                        any("no live crash channel" in ln for ln in printed4),
                    )
                finally:
                    shutil.rmtree(rtmp3, ignore_errors=True)
            finally:
                shutil.rmtree(rtmp, ignore_errors=True)
        finally:
            MH_MAP, _MH_DLL_SYMS = real_map, real_cache
    finally:
        shutil.rmtree(tmp2, ignore_errors=True)

    # ---- the live half, only if this machine happens to have a Release build -----------------
    if os.path.isfile(MH_MAP):
        _MH_DLL_SYMS_BACKUP = None
        live = resolve_mh_dll_rva(
            0x175A0
        )  # _MH_Seam_SessionPacing, per src/mh_dll's net_lockstep.obj
        ck("resolves a real mh.dll RVA against the real Release/mh.map", bool(live))
        if live:
            print("      mh.dll RVA 0x175a0 -> %s" % live)
    else:
        print("  (skipping the live mh.map check -- no Release build on this machine)")

    print("crash_report selftest: %d check(s), %d failure(s)" % (total[0], len(fails)))
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument(
        "--since-min", type=float, default=30.0, help="look back this many minutes (0 = no limit)"
    )
    ap.add_argument("--lane", help="lane directory or exe path -- match AppPath against it")
    ap.add_argument("--exe", help="image name filter, e.g. mh.focus.exe")
    ap.add_argument(
        "--dir",
        action="append",
        help="scan this WER root instead of the local ones (repeatable). For a directory of "
        "reports pulled off a rig VM; ui_test does this automatically for VM peers.",
    )
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--report",
        help="read a DRAINED report (dist:RP3's tools/drain_reports.py layout) instead of "
        "scanning WER -- a single <ulid> directory, or a store root walked for every report "
        "under it (e.g. tmp/drained_reports)",
    )
    ap.add_argument("--selftest", action="store_true", help="prove the scanner + its filters work")
    a = ap.parse_args()

    if a.selftest:
        return selftest()

    if a.report:
        found = 0
        for root, _dirs, files in os.walk(a.report):
            if "meta.json" in files:
                found += 1
                print_drained_report(root)
        if not found:
            print("no drained report (meta.json) found under %s" % a.report)
            return 1
        return 0

    since = None if a.since_min <= 0 else time.time() - a.since_min * 60
    recs = scan(since=since, app_path=a.lane, exe=a.exe, roots=a.dir)
    dmp = [] if a.dir else dumps(since)  # local-only signal; says nothing about a pulled set
    if a.json:
        print(json.dumps({"crashes": recs, "dumps": dmp}, indent=1))
        return 0
    if not recs:
        # Say what was searched. "no crashes" over the wrong window or the wrong lane looks exactly
        # like "no crashes", which is the failure mode this whole file exists to remove.
        print(
            "no crash reports in %s%s%s"
            % (
                ("the last %g min" % a.since_min) if since else "any window",
                (" for %s" % a.lane) if a.lane else "",
                (" [%s]" % a.exe) if a.exe else "",
            )
        )
        print("searched: %s" % (", ".join(a.dir or wer_dirs()) or "(no WER directories found)"))
        # G186 (measured 2026-09-15): WerFault cannot run on a non-interactive desktop, and rig
        # lanes run on the isolated mh_rig desktop BY DEFAULT -- so for a local lane this negative
        # is NO INFORMATION, not "no fault". Only a --no-desktop run (or a postmortem debugger)
        # can produce the record whose absence this message reports.
        print(
            "NOTE: a lane on the isolated mh_rig desktop (the default) is INVISIBLE to WER -- "
            "this result cannot rule out a fault there: on a non-interactive desktop "
            "NOTHING postmortem runs -- not WER, not LocalDumps, not the AeDebug JIT debugger"
        )
    for r in recs:
        print(describe(r))
        print("   app  : %s" % r["app_path"])
        print(
            "   fault: module=%s offset=%s%s%s"
            % (
                r["module"],
                r["offset"],
                (" va=0x%08x" % r["va"]) if r["va"] else "",
                (" rva=0x%x" % r["rva"]) if r.get("rva") is not None else "",
            )
        )
        print("   report: %s" % r["report"])
    for d in dmp:
        print(
            "dump: %s (%.1f MB, %s)"
            % (d["path"], d["size"] / 1e6, time.strftime("%H:%M:%S", time.localtime(d["when"])))
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
