#!/usr/bin/env python3
"""gen_st0_goldens.py -- lift the ST0 sin/cos goldens out of a rig log (LIB-REF-SPLIT).

WHY THIS IS A TOOL AND NOT A ONE-OFF. The capture recurs: any change to crt/crt_math.h's vendored
bodies or to crt/crt_st0_sweep.h's input list invalidates the committed table, and the repo's script
policy says a recurring shape belongs in an engine with the varying part in data. The varying part
here is which run's log you point it at.

THE MEASUREMENT ITSELF is seams/reimpl_probe.cpp's st0_goldens_probe, armed with
`[st0] goldens=1` (it was `[harness] st0_goldens=1` until fork F4E moved the key out of the
harness DLL's section and into the one this probe already logs under; a surviving old key is
REFUSED, not ignored). It calls the ORIGINAL bodies at 0x004dabc6 / 0x004dabbc -- which only
exist in a hosted process -- and the vendored transcription, compares them bit for bit at BOTH x87
precision settings, and logs one line per (precision, input):

    ; [st0] <pc> <idx> <input bits> <sin bits> <cos bits> [DISAGREE]

TO RE-CAPTURE:
    1. add `[st0] goldens=1` to a scenario's extra ini
    2. python tools/test_ui.py --only menu_walk
    3. python tools/gen_st0_goldens.py workdir/mh_lanes/ui_menu_walk/logs/<run>/mh_net.log

IT REFUSES A RUN THAT DISAGREED. Goldens taken from a sweep that reported a divergence would pin the
divergence, so the tool reads the run's own verdict rather than trusting the caller to have looked.
"""

import argparse
import io
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "src", "mh_dll", "mh_nettest", "st0_sincos_goldens.h")
ROW = re.compile(r"\[st0\] (\d+) +(\d+) ([0-9A-Fa-f]{16}) ([0-9A-Fa-f]{16}) ([0-9A-Fa-f]{16})(.*)")
END = re.compile(r"\[st0\] SWEEP END -- (\d+) input\(s\) x 2 precisions, (\d+) DISAGREEMENT")

BANNER = '''//
// mh_nettest/st0_sincos_goldens.h -- GENERATED by tools/gen_st0_goldens.py from a rig log.
// MEASURED, not derived (LIB-REF-SPLIT). Do not hand-edit: re-capture instead.
//
// The bit patterns llm_math_fsin_reduce_loop @0x004dabc6 and llm_math_cos_impl @0x004dabbc produce
// for crt/crt_st0_sweep.h's inputs, read out of the ORIGINAL BODIES AT THEIR ADDRESSES in a hosted
// process. This is the reference arm crt/crt_math.h's vendored transcription is proved against, and
// it is a committed table because the measurement needs mh.exe mapped and net_selftest never loads
// it.
//
// WHY NOT A TRANSCRIBED REFERENCE, which is what every other body in crt_vendor_selftest uses: the
// vendored sin/cos IS the transcription, so a transcribed reference would be the same instructions
// compared against themselves -- an oracle that agrees with the bug by construction. These numbers
// come from the other side of that circle.
//
// BOTH PRECISION SETTINGS, because FSIN/FCOS round their result to the live x87 control word. PC=53
// is what harness.cpp's pin_fpu installs and what ships; PC=64 is the bare default; a body correct
// at only one would look fine for months -- an offline probe can agree while the same comparison
// through the real header does not.
//
// THE FIRST CAPTURE REPORTED 21 DISAGREEMENTS, which is why this file exists rather than a confident
// comment. All 21 were the C2/FPREM reduction cases: the vendored body built its 2*pi divisor with
// `fldpi; fadd st,st`, and FADD -- unlike FLD -- is precision-control-affected, so at PC=53 it
// dropped the low mantissa bits the original keeps. Every in-range input agreed the whole time, so a
// sweep without the large magnitudes would have shipped it green. See crt/crt_math.h's constant note.
//
// PROVENANCE: %(log)s, tree at %(commit)s.
// The run's own verdict: %(inputs)s input(s) x 2 precisions, %(dis)s DISAGREEMENT(S).
#pragma once
#include <cstdint>

#include "crt/crt_st0_sweep.h"

namespace mh::crt::goldens {

struct st0_row {
    uint64_t in;
    uint64_t sin_bits;
    uint64_t cos_bits;
};
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("log", help="the lane's mh_net.log from a run with [st0] goldens=1")
    args = ap.parse_args()

    text = io.open(args.log, encoding="utf-8", errors="replace").read()
    end = END.search(text)
    if end is None:
        sys.exit("no `[st0] SWEEP END` line in %s -- was [st0] goldens=1 armed?" % args.log)
    inputs, dis = end.group(1), end.group(2)
    if dis != "0":
        # Goldens from a divergent sweep would pin the divergence as the reference.
        sys.exit(
            "REFUSED: that run reported %s DISAGREEMENT(S). Fix the vendored body and re-capture; "
            "a golden table taken from a divergent sweep is a fixture that agrees with the bug."
            % dis
        )

    rows = {}
    for m in ROW.finditer(text):
        rows.setdefault(int(m.group(1)), {})[int(m.group(2))] = (m.group(3), m.group(4), m.group(5))
    if sorted(rows) != [53, 64]:
        sys.exit("expected PC=53 and PC=64 sweeps, found %s" % sorted(rows))
    n = len(rows[53])
    if len(rows[64]) != n:
        sys.exit("the two precision sweeps have different lengths (%d vs %d)" % (n, len(rows[64])))
    # The inputs come from ONE generator, so a mismatch means the log interleaved two runs.
    for i in range(n):
        if rows[53][i][0] != rows[64][i][0]:
            sys.exit(
                "input %d differs between the two precision sweeps -- two runs in one log?" % i
            )

    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=REPO
    ).stdout.strip()
    rel = os.path.relpath(os.path.abspath(args.log), REPO).replace("\\", "/")
    out = [BANNER % {"log": rel, "commit": commit, "inputs": inputs, "dis": dis}]
    for pc in (53, 64):
        out.append(
            "// PC=%d%s"
            % (
                pc,
                " -- harness.cpp pin_fpu, the shipping setting"
                if pc == 53
                else " -- the bare x87 default",
            )
        )
        out.append("inline constexpr st0_row ST0_GOLDENS_PC%d[] = {" % pc)
        for i in range(n):
            a, b, c = rows[pc][i]
            out.append("    {0x%sull, 0x%sull, 0x%sull}," % (a, b, c))
        out.append("};")
        out.append(
            "static_assert((int)(sizeof ST0_GOLDENS_PC%d / sizeof *ST0_GOLDENS_PC%d) == ST0_SWEEP_N,"
            % (pc, pc)
        )
        out.append(
            '              "the PC=%d goldens and crt_st0_sweep.h disagree about how many inputs '
            'there are");' % pc
        )
        out.append("")
    out.append("} // namespace mh::crt::goldens")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("wrote %s (2 x %d rows, from %s)" % (os.path.relpath(OUT, REPO), n, rel))
    return 0


if __name__ == "__main__":
    sys.exit(main())
