#!/usr/bin/env python3
"""
gen_dll_addrs.py -- generate src/mh_dll/mh/addr/mh_addrs.gen.h from
tools/data/dll_addr_manifest.json, verifying named symbols against the
EN-canonical generated symbol table (docs/symbols.md).

The injected mh.dll is EN-only (targets /eng/mh.exe exclusively) since the
2026-07-22 mh_lib refactor. This tool is the
single path from "a VA the DLL needs" to "a constant the code can use":
edit the manifest, re-run, commit both.

Verification: every manifest entry whose name looks like a dumped symbol
(llm_* function or _G_LLM_* global) MUST resolve to the same VA in
docs/symbols.md; a mismatch is a hard error (a Ghidra rename/move surfaced --
fix the manifest, or regenerate docs/symbols.md first). Entries with
non-dumped names (FUN_*-era descriptive aliases, DAT_*, hand-named cfg::/map::
symbols, anchors) are exempt: their VA is authoritative in the manifest
(provenance: the retired mh_port CODE_MAP, name-checked at E1).

Usage:
  python tools/gen_dll_addrs.py           # regenerate the header in place
  python tools/gen_dll_addrs.py --check   # drift gate: exit 1 if the header
                                          # on disk differs from a fresh regen
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "tools" / "data" / "dll_addr_manifest.json"
SYMBOLS_MD = REPO / "docs" / "symbols.md"
HEADER = REPO / "src" / "mh_dll" / "mh" / "addr" / "mh_addrs.gen.h"


def load_symbol_table():
    """Parse docs/symbols.md generated tables -> {name: va_int}."""
    table = {}
    row = re.compile(r"^\|\s*`0x([0-9a-fA-F]{8})`\s*\|\s*`([^`]+)`")
    for line in SYMBOLS_MD.read_text(encoding="utf-8", errors="replace").splitlines():
        m = row.match(line)
        if m:
            table[m.group(2)] = int(m.group(1), 16)
    return table


def is_dumped_name(name: str) -> bool:
    return name.startswith("llm_") or name.startswith("_G_LLM_")


def verify(entries, symtab, kind, errors):
    for e in entries:
        name, va = e["name"], int(e["en"], 16)
        if kind == "anchor" or not is_dumped_name(name):
            continue
        got = symtab.get(name)
        if got is None:
            errors.append(
                f"{kind} {name}: not found in docs/symbols.md "
                f"(renamed in Ghidra? regenerate symbols.md, then fix the manifest)"
            )
        elif got != va:
            errors.append(f"{kind} {name}: manifest 0x{va:08x} != symbols.md 0x{got:08x}")


def emit(manifest) -> str:
    out = []
    out.append(
        "// GENERATED by tools/gen_dll_addrs.py from tools/data/dll_addr_manifest.json -- DO NOT EDIT."
    )
    out.append(
        "// Regenerate after editing the manifest; `gen_dll_addrs.py --check` is the drift gate."
    )
    out.append("//")
    out.append(
        "// EN build (/eng/mh.exe) virtual addresses; image base 0x00400000, no ASLR. The DLL is"
    )
    out.append("// EN-ONLY: it probes the loaded exe at init and refuses to arm")
    out.append("// on anything else. Data VAs are RU/EN-identical (proven at E1); code VAs are EN.")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace mh::addr {")
    out.append("")
    out.append("// ---- code: function entries ----")
    for e in manifest["code"]:
        note = (" // " + e["note"]) if e.get("note") else ""
        out.append(f"inline constexpr uintptr_t {e['name']:<40} = 0x{int(e['en'], 16):08x}u;{note}")
    out.append("")
    out.append("// ---- code anchors: mid-function sites (call-splice / byte-poke targets) ----")
    for e in manifest["anchors"]:
        note = " // in " + e["parent"] + ((": " + e["note"]) if e.get("note") else "")
        out.append(f"inline constexpr uintptr_t {e['name']:<40} = 0x{int(e['en'], 16):08x}u;{note}")
    out.append("")
    out.append("// ---- data: globals (identical across RU/EN) ----")
    for e in manifest["data"]:
        note = (" // " + e["note"]) if e.get("note") else ""
        out.append(f"inline constexpr uintptr_t {e['name']:<40} = 0x{int(e['en'], 16):08x}u;{note}")
    out.append("")
    out.append("} // namespace mh::addr")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true", help="drift gate: fail if header differs from regen"
    )
    args = ap.parse_args()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8-sig"))
    symtab = load_symbol_table()

    errors = []
    seen = {}
    for kind in ("code", "anchors", "data"):
        for e in manifest[kind]:
            if e["name"] in seen:
                errors.append(f"duplicate name {e['name']} ({seen[e['name']]} + {kind})")
            seen[e["name"]] = kind
        verify(manifest[kind], symtab, kind.rstrip("s"), errors)
    if errors:
        print("MANIFEST ERRORS:")
        for err in errors:
            print("  " + err)
        return 1

    text = emit(manifest)
    if args.check:
        on_disk = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if on_disk != text:
            print(f"DRIFT: {HEADER} differs from a fresh regen -- run gen_dll_addrs.py and commit.")
            return 1
        print(
            f"ok: {HEADER.name} matches manifest ({len(manifest['code'])} code, "
            f"{len(manifest['anchors'])} anchors, {len(manifest['data'])} data)"
        )
        return 0

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(text, encoding="utf-8", newline="\n")
    print(
        f"wrote {HEADER} ({len(manifest['code'])} code, {len(manifest['anchors'])} anchors, "
        f"{len(manifest['data'])} data entries; {len(symtab)} symbols loaded for verification)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
