#!/usr/bin/env python3
"""gen_vcxproj_filters.py -- derive every .vcxproj.filters from its .vcxproj by ONE rule.

WHAT THIS IS FOR (fork F5P). Visual Studio shows a project's files as a flat list unless a sibling
`<project>.vcxproj.filters` groups them into folders. Every project in this tree presented that flat
list; after F5O moved 1262 files into the directory of the target that owns them, a flat list is
also actively misleading -- `sim\\sim_state.cpp` and `..\\libmh\\sim\\sim_state.cpp` are the SAME
file reached from two projects, and the tree is the only thing that says so.

THE FOLDERS MIRROR THE DISK, AND THAT IS THE WHOLE DESIGN. A .filters file is free-form: VS lets
you invent any taxonomy you like ("Source Files" / "Header Files" is merely the wizard's default,
which is why mh_tools' hand-written one said that and nothing else). An invented taxonomy is a
SECOND layout that has to be maintained beside the real one and that silently stops matching it --
exactly the hand-list failure mode F5O's directory move existed to end. So there is one mechanical
rule and no judgement anywhere in this file:

    R1. An item's Filter is the DIRECTORY PART of its Include path, relative to the project
        directory, with leading `..\\` segments folded away.

            ..\\libmh\\sim\\sim_state.cpp   ->  libmh\\sim
            ..\\mh\\addr\\mh_calls.gen.cpp  ->  mh\\addr
            ..\\..\\mh_net_proto\\src\\x.cpp ->  mh_net_proto\\src
            ai\\ai_build.cpp               ->  ai
            libmh_dllmain.cpp              ->  (none -- the project root)

        Folding `..` away is what makes the sibling directory show up under its own name, so a
        reader of libmh_dll's tree sees `libmh\\sim` and `mh\\addr` as two top-level folders and can
        tell at a glance which files this project OWNS (unprefixed) and which it BORROWS.

    R2. Every intermediate folder gets its own `<Filter Include=...>` row (VS requires the parents
        to exist) with a UniqueIdentifier derived as uuid5(fixed namespace, "<project>|<filter>").
        DERIVED, NOT RANDOM: a fresh uuid4 per run would make every regeneration a diff, so the
        drift gate below could never tell a stale file from a re-rolled one. The GUID is a stable
        function of the project name and the folder path, so regeneration is byte-identical.

    R3. Items are emitted in the order the .vcxproj lists them, grouped into one ItemGroup per item
        type in the order the types first appear. Same reason: byte-stability under regeneration.

WHO GENERATES WHAT.

  * The THREE GENERATED projects (libmh, libmh_dll, libmh_std) are NOT handled here. Their .vcxproj
    is itself generated by tools/gen_libmh_vcxproj.py from the module tree, so their .filters is
    emitted by that same tool in the same pass -- it imports the renderer below, so there is one
    rule, not two. This script REFUSES to touch them (see GENERATED) rather than racing it.
  * Every other project under src/ is handled here, its .filters committed, and
    `--check` is a lint_repo row so a hand-edit or a stale file fails the gate.

mh_nettest (1026 entries) IS INCLUDED, and the tracker's "wait for F5I" note did not apply to this
half: F5I split that project in two, and the successor -- libmh_test, generated -- got its .filters
from the same renderer on the same day, with nothing hand-carried across the split. That is the
argument for deriving rather than hand-listing, made once more by the event it was written about.

USAGE

  python tools/gen_vcxproj_filters.py --write             regenerate all hand projects
  python tools/gen_vcxproj_filters.py --check             fail if any is stale/missing/hand-edited
  python tools/gen_vcxproj_filters.py --selftest          planted-staleness reds + walker liveness
  python tools/gen_vcxproj_filters.py --check <a.vcxproj> just those projects

EVERY RUN ALSO VALIDATES the rendered file the way VS's project loader would (validate_pair): the
XML parses in the MSBuild namespace, the item set matches the .vcxproj exactly in both directions,
every Filter an item names has a row, and every nested row's parents exist. A .filters that fails
any of those is the one thing in this area that can break a project LOAD, so it is checked on the
way out rather than trusted.
"""

import argparse
import glob
import io
import os
import sys
import uuid
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "src")
MSB = "{http://schemas.microsoft.com/developer/msbuild/2003}"

# The four whose .vcxproj AND .filters both come out of tools/gen_libmh_vcxproj.py.
GENERATED = (
    "libmh.vcxproj",
    "libmh_dll.vcxproj",
    "libmh_std.vcxproj",
    "libmh_test.vcxproj",  # fork F5I
)

# Item elements that carry an Include= but are NOT files and must never reach a .filters tree.
NON_FILE_ITEMS = (
    "ProjectConfiguration",
    "ProjectReference",
    "Reference",
    "PackageReference",
    "BuildMacro",
    "ProjectCapability",
)

# A non-vacuity floor. This tool walking to zero projects (a moved tree, a broken glob) would make
# --check pass by finding nothing to check -- the exact shape lint_fp_flags.py emptied into at F5O.
MIN_HAND_PROJECTS = 8

# Fixed namespace for the derived folder GUIDs. Arbitrary but FROZEN: changing it rewrites every
# UniqueIdentifier in the tree, which VS reads as "all folders are new" and would churn the diff.
GUID_NS = uuid.UUID("3f1c9a54-6b2e-5d7f-9a10-4c8e2b6d0f31")

XML_ESCAPES = (("&", "&amp;"), ("<", "&lt;"), (">", "&gt;"), ('"', "&quot;"))


class Refusal(Exception):
    """A structural surprise. Raised rather than guessed at -- see the header."""


def _esc(s):
    for a, b in XML_ESCAPES:
        s = s.replace(a, b)
    return s


def folder_guid(project, filt):
    return "{%s}" % str(uuid.uuid5(GUID_NS, "%s|%s" % (project, filt))).upper()


def filter_for(include):
    """R1: the directory part, leading `..` folded away. '' means the project root (no Filter)."""
    parts = include.replace("/", "\\").split("\\")
    parts = parts[:-1]
    while parts and parts[0] == "..":
        parts.pop(0)
    if ".." in parts:
        raise Refusal(
            "include path %r has a `..` that is not leading -- the R1 fold is defined for the "
            "reach-a-sibling-directory shape only; fix the .vcxproj or extend the rule" % include
        )
    parts = [p for p in parts if p not in ("", ".")]
    return "\\".join(parts)


def parse_items(text):
    """[(tag, include)] in document order, for the file items of a .vcxproj."""
    root = ET.fromstring(text)
    items = []
    for group in root.findall("%sItemGroup" % MSB):
        for el in group:
            tag = el.tag[len(MSB) :] if el.tag.startswith(MSB) else el.tag
            inc = el.get("Include")
            if inc is None or tag in NON_FILE_ITEMS:
                continue
            if "|" in inc or "$(" in inc:
                raise Refusal("item <%s Include=%r> does not look like a file path" % (tag, inc))
            items.append((tag, inc))
    return items


def render(project, items):
    """R1+R2+R3 -> the .filters text. `project` only feeds the derived folder GUIDs."""
    folders = set()
    for _tag, inc in items:
        filt = filter_for(inc)
        while filt:
            folders.add(filt)
            filt = filt.rsplit("\\", 1)[0] if "\\" in filt else ""

    out = [
        "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
        '<Project ToolsVersion="4.0" '
        'xmlns="http://schemas.microsoft.com/developer/msbuild/2003">\n',
        "  <!-- GENERATED by tools/gen_vcxproj_filters.py - do not hand-edit; rerun the "
        "generator.\n"
        "       The folder tree MIRRORS THE ON-DISK LAYOUT (fork F5P); it is not a taxonomy. -->\n",
    ]
    if folders:
        out.append("  <ItemGroup>\n")
        for filt in sorted(folders):
            out.append('    <Filter Include="%s">\n' % _esc(filt))
            out.append(
                "      <UniqueIdentifier>%s</UniqueIdentifier>\n" % folder_guid(project, filt)
            )
            out.append("    </Filter>\n")
        out.append("  </ItemGroup>\n")

    order = []
    for tag, _inc in items:
        if tag not in order:
            order.append(tag)
    for tag in order:
        out.append("  <ItemGroup>\n")
        for itag, inc in items:
            if itag != tag:
                continue
            filt = filter_for(inc)
            if filt:
                out.append('    <%s Include="%s">\n' % (tag, _esc(inc)))
                out.append("      <Filter>%s</Filter>\n" % _esc(filt))
                out.append("    </%s>\n" % tag)
            else:
                out.append('    <%s Include="%s" />\n' % (tag, _esc(inc)))
        out.append("  </ItemGroup>\n")
    out.append("</Project>\n")
    return "".join(out)


def render_from_vcxproj_text(project, text):
    return render(project, parse_items(text))


def filters_path_for(vcxproj_path):
    return vcxproj_path + ".filters"


def project_name(vcxproj_path):
    return os.path.splitext(os.path.basename(vcxproj_path))[0]


# ---- validation (R5: what a VS project load would object to) --------------------------------


def validate_pair(vcxproj_text, filters_text, label):
    """Returns a list of problem strings; empty == the pair is loadable."""
    bad = []
    try:
        root = ET.fromstring(filters_text.lstrip("﻿"))
    except ET.ParseError as exc:
        return ["%s: not well-formed XML (%s)" % (label, exc)]
    if not root.tag.startswith(MSB):
        return ["%s: root element is not in the MSBuild namespace" % label]

    declared = set()
    got = []
    for group in root.findall("%sItemGroup" % MSB):
        for el in group:
            tag = el.tag[len(MSB) :] if el.tag.startswith(MSB) else el.tag
            inc = el.get("Include")
            if inc is None:
                bad.append("%s: <%s> with no Include" % (label, tag))
                continue
            if tag == "Filter":
                if inc in declared:
                    bad.append("%s: duplicate <Filter Include=%r>" % (label, inc))
                declared.add(inc)
                if el.find("%sUniqueIdentifier" % MSB) is None:
                    bad.append("%s: filter %r has no UniqueIdentifier" % (label, inc))
            else:
                node = el.find("%sFilter" % MSB)
                got.append((tag, inc, node.text if node is not None else None))

    for filt in sorted(declared):
        if "\\" in filt and filt.rsplit("\\", 1)[0] not in declared:
            bad.append("%s: filter %r has no parent row" % (label, filt))
    for tag, inc, filt in got:
        if filt and filt not in declared:
            bad.append("%s: item %r names filter %r which has no row" % (label, inc, filt))
        if (filt or "") != filter_for(inc):
            bad.append(
                "%s: item %r has filter %r, R1 says %r" % (label, inc, filt or "", filter_for(inc))
            )

    want = parse_items(vcxproj_text)
    have = [(t, i) for t, i, _f in got]
    if want != have:
        missing = [x for x in want if x not in have]
        extra = [x for x in have if x not in want]
        if missing:
            bad.append(
                "%s: %d item(s) in the .vcxproj are absent from the .filters (first: %r)"
                % (label, len(missing), missing[0])
            )
        if extra:
            bad.append(
                "%s: %d item(s) in the .filters are not in the .vcxproj (first: %r)"
                % (label, len(extra), extra[0])
            )
        if not missing and not extra:
            bad.append("%s: item ORDER differs from the .vcxproj" % label)
    return bad


# ---- the hand-project roster ------------------------------------------------------------------


def hand_projects():
    found = sorted(
        p.replace("/", os.sep)
        for p in glob.glob(os.path.join(SRC, "**", "*.vcxproj"), recursive=True)
    )
    if not found:
        raise Refusal("no .vcxproj found under src/ -- the walker is dead, not the tree empty")
    hand = [p for p in found if os.path.basename(p) not in GENERATED]
    gen = [p for p in found if os.path.basename(p) in GENERATED]
    if len(gen) != len(GENERATED):
        raise Refusal(
            "expected the %d generated projects (%s) under src/, found %d -- if one was renamed, "
            "update GENERATED here AND tools/gen_libmh_vcxproj.py"
            % (len(GENERATED), ", ".join(GENERATED), len(gen))
        )
    if len(hand) < MIN_HAND_PROJECTS:
        raise Refusal(
            "only %d hand project(s) under src/, floor is %d -- a --check over a near-empty roster "
            "is a pass that proves nothing" % (len(hand), MIN_HAND_PROJECTS)
        )
    return hand


# ---- the shared check/write engine ------------------------------------------------------------


def process(paths, write, quiet=False, tag="gen_vcxproj_filters"):
    rc = 0
    for vcx in paths:
        try:
            label = os.path.relpath(vcx, REPO).replace(os.sep, "/")
        except ValueError:  # a temp copy on another drive (the selftest)
            label = vcx.replace(os.sep, "/")
        vtext = io.open(vcx, encoding="utf-8-sig").read()
        text = render_from_vcxproj_text(project_name(vcx), vtext)
        bad = validate_pair(vtext, text, label)
        if bad:
            for ln in bad:
                print("[%s] FAIL: %s" % (tag, ln))
            rc = 1
            continue
        fpath = filters_path_for(vcx)
        if write:
            io.open(fpath, "w", encoding="utf-8", newline="\r\n").write(text)
            if not quiet:
                print(
                    "wrote %s.filters (%d entries, %d folders)"
                    % (
                        label,
                        text.count(" Include=") - text.count("<Filter Include="),
                        text.count("<Filter Include="),
                    )
                )
            continue
        if not os.path.exists(fpath):
            print("[%s] FAIL: %s.filters does not exist -- run the generator" % (tag, label))
            rc = 1
            continue
        if io.open(fpath, encoding="utf-8-sig").read() != text.lstrip("﻿"):
            print(
                "[%s] FAIL: %s.filters is stale or hand-edited -- rerun "
                "tools/gen_vcxproj_filters.py --write" % (tag, label)
            )
            rc = 1
            continue
        if not quiet:
            print("[%s] OK: %s.filters is current" % (tag, label))
    return rc


# ---- selftest ---------------------------------------------------------------------------------
#
# The gate's whole value is that a stale or hand-edited .filters goes RED. A --check that passes
# because its comparison never fires is indistinguishable from a clean tree, so every red is
# re-fired here against a planted defect in a temp copy, plus the liveness controls that catch the
# walker having quietly stopped finding anything.


def selftest():
    import shutil
    import tempfile

    ok = True

    def ck(what, cond):
        nonlocal ok
        print("  %-64s %s" % (what, "PASS" if cond else "FAIL"))
        if not cond:
            ok = False

    # --- rule unit checks (R1) ---
    ck("R1 folds one `..`", filter_for("..\\libmh\\sim\\x.cpp") == "libmh\\sim")
    ck("R1 folds two `..`", filter_for("..\\..\\mh_net_proto\\src\\x.cpp") == "mh_net_proto\\src")
    ck("R1 keeps a local dir", filter_for("ai\\x.cpp") == "ai")
    ck("R1 gives the root no filter", filter_for("mh.c") == "")
    ck("R1 accepts forward slashes", filter_for("../libmh/sim/x.cpp") == "libmh\\sim")
    try:
        filter_for("a\\..\\b\\x.cpp")
        ck("R1 refuses a non-leading `..`", False)
    except Refusal:
        ck("R1 refuses a non-leading `..`", True)
    ck(
        "folder GUIDs are derived, not random",
        folder_guid("mh", "seams") == folder_guid("mh", "seams")
        and folder_guid("mh", "seams") != folder_guid("mh_net", "seams"),
    )

    # --- walker liveness ---
    try:
        hand = hand_projects()
        ck(
            "the walker finds the hand projects (>= %d)" % MIN_HAND_PROJECTS,
            len(hand) >= MIN_HAND_PROJECTS,
        )
        ck(
            "the generated three are excluded from the hand roster",
            not any(os.path.basename(p) in GENERATED for p in hand),
        )
    except Refusal as exc:
        ck("the walker finds the hand projects (%s)" % exc, False)
        hand = []

    # --- planted-defect reds, in a temp copy so nothing in the tree is touched ---
    victim = None
    for p in hand:
        if os.path.basename(p) == "mh.vcxproj":
            victim = p
    if victim is None and hand:
        victim = hand[0]
    if victim:
        d = tempfile.mkdtemp(prefix="f5p_selftest_")
        try:
            vcx = os.path.join(d, os.path.basename(victim))
            shutil.copyfile(victim, vcx)
            ck(
                "a freshly written pair passes --check",
                process([vcx], True, quiet=True) == 0 and process([vcx], False, quiet=True) == 0,
            )

            good = io.open(filters_path_for(vcx), encoding="utf-8-sig").read()

            io.open(filters_path_for(vcx), "w", encoding="utf-8", newline="").write(
                good.replace("<Filter>seams</Filter>", "<Filter>Source Files</Filter>", 1)
            )
            ck("planted WRONG filter folder -> --check RED", process([vcx], False, quiet=True) == 1)

            io.open(filters_path_for(vcx), "w", encoding="utf-8", newline="").write(good)
            ck("restored pair -> --check green again", process([vcx], False, quiet=True) == 0)

            # a dropped entry: the .vcxproj gained a file and nobody regenerated
            i = good.index('    <ClInclude Include=')
            j = good.index("\n", good.index("</ClInclude>", i)) + 1
            io.open(filters_path_for(vcx), "w", encoding="utf-8", newline="").write(
                good[:i] + good[j:]
            )
            ck("planted DROPPED entry -> --check RED", process([vcx], False, quiet=True) == 1)

            os.remove(filters_path_for(vcx))
            ck("planted MISSING file -> --check RED", process([vcx], False, quiet=True) == 1)

            # validate_pair is the load proof; fire its arms directly
            vtext = io.open(vcx, encoding="utf-8-sig").read()
            text = render_from_vcxproj_text(project_name(vcx), vtext)
            ck("validate_pair passes the real render", validate_pair(vtext, text, "x") == [])
            row = (
                '    <Filter Include="seams">\n'
                "      <UniqueIdentifier>%s</UniqueIdentifier>\n"
                "    </Filter>\n" % folder_guid(project_name(vcx), "seams")
            )
            ck("the seams folder row is in the render", row in text)
            ck(
                "validate_pair catches a missing <Filter Include> row",
                bool(validate_pair(vtext, text.replace(row, "", 1), "x")),
            )
            ck(
                "validate_pair catches malformed XML",
                bool(validate_pair(vtext, text.replace("</Project>", ""), "x")),
            )
            ck(
                "validate_pair catches an item the .vcxproj does not have",
                bool(
                    validate_pair(
                        vtext,
                        text.replace(
                            "</Project>",
                            '  <ItemGroup>\n    <ClCompile Include="ghost.cpp" '
                            "/>\n  </ItemGroup>\n</Project>",
                        ),
                        "x",
                    )
                ),
            )
        finally:
            shutil.rmtree(d, ignore_errors=True)
    else:
        ck("a victim project to plant into", False)

    print("gen_vcxproj_filters --selftest: %s" % ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("projects", nargs="*", help="vcxproj paths (default: every hand project)")
    ap.add_argument("--check", action="store_true", help="fail if a committed .filters is stale")
    ap.add_argument("--write", action="store_true", help="(re)generate the .filters files")
    ap.add_argument("--selftest", action="store_true", help="planted-staleness reds + liveness")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if args.check == args.write:
        ap.error("give exactly one of --check / --write")
    try:
        paths = [os.path.abspath(p) for p in args.projects] or hand_projects()
    except Refusal as exc:
        print("[gen_vcxproj_filters] FAIL: %s" % exc)
        return 1
    try:
        return process(paths, args.write)
    except Refusal as exc:
        print("[gen_vcxproj_filters] FAIL: %s" % exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
