#pragma once
// GENERATED by tools/gen_harness_contract.py -- do not hand-edit; rerun the generator.
//
// mh_harness.dll's TWO import tables (fork F4E). HOST rows resolve out of mh.dll, SPINE rows
// out of libmh.dll; harness_contract.gen.cpp defines both plus one signature-free naked
// forwarding thunk per row, attached to the real symbol by a /alternatename linker directive
// so not one of harness.cpp's call sites changes.

#define MH_HARNESS_HOST_COUNT 27
#define MH_HARNESS_SPINE_COUNT 30

extern "C" {
// The bound addresses, in slot order. A null slot is not a configuration -- the binds below
// resolve every row before adopting any, and the harness refuses to arm if either table came
// back short. A thunk that finds one null therefore TRAPS rather than answering zero.
extern void *g_mh_harness_host_fn[MH_HARNESS_HOST_COUNT];
extern void *g_mh_harness_spine_fn[MH_HARNESS_SPINE_COUNT];
extern const char *const g_mh_harness_host_name[MH_HARNESS_HOST_COUNT];
extern const char *const g_mh_harness_spine_name[MH_HARNESS_SPINE_COUNT];

// Resolve a table out of an ALREADY-LOADED module (GetModuleHandle, never LoadLibrary --
// video.cpp:969's rule, adopted verbatim for this edge by docs/dll-split.md). Returns the
// number of rows resolved; the caller refuses unless it equals the count above.
int mh_harness_bind_host(void);
int mh_harness_bind_spine(void);

// NO CROSSING COUNTERS, and their absence is a decision rather than an omission. F4D's
// exist because mh.dll's absent path answers zero in silence, so only a number separates a
// lane that crossed from one that did not. This boundary cannot be in that state: every
// row either crosses or traps, and an instrument that armed and called nothing wrote no
// hashes, which check_arm_order refuses by name. Two stronger witnesses, and the hot
// per-step path pays nothing for them.
}

