"""CLI: emit the runtime text-id <-> string table as a Markdown doc.

  python -m src.formats.cfgkit.dump_text_ids [--init ...] [--lang ...]
                                             --out <path>

The game addresses localized strings through ``cfg::G_TEXT_PTRS[id]`` (see
``llm_lobby_network_setup_screen`` and friends, which read ``G_TEXT_PTRS[0x261]``
etc.). That ``id`` is **not** the file order of the ``TEXT`` entries in
initlang.cfg -- it is the numeric value of the ``K_*`` DEFINE that keys each
``TEXT`` line. This script reuses the cfgkit parser (:func:`parse_files`) to
recover both, joins them, and writes an id-sorted table so a decompiled
``G_TEXT_PTRS[0xNNN]`` reference can be read back to its actual string.

Pure-python (no Ghidra/ReVA needed). Regenerate whenever initlang.cfg changes.
"""
from __future__ import annotations

import argparse
import sys

from ._paths import CLEAN
from .parse import parse_files
from .aliases import AliasTable

MARK_BEGIN = "<!-- generated-text-ids:begin -->"
MARK_END = "<!-- generated-text-ids:end -->"


def _cell(s: str) -> str:
    """Make a string safe for a one-line Markdown table cell."""
    return (s.replace("\\", "\\\\").replace("|", "\\|")
             .replace("\r", " ").replace("\n", " "))


def build_rows(init: str, lang: str):
    """Return id-sorted ``[(id, wire_key, english_alias, text)]`` + stats."""
    model = parse_files(init, lang)
    defs = dict(model.defines)
    aliases = AliasTable.load("mod_src/cfg/aliases.yaml")
    rows, missing, seen = [], [], {}
    for key, val in model.texts:
        if key not in defs:
            missing.append(key)
            continue
        tid = defs[key]
        if tid in seen:
            missing.append(f"DUP:{tid}:{key}")
        seen[tid] = key
        rows.append((tid, key, aliases.wire2en.get(key, ""), val))
    rows.sort(key=lambda r: r[0])
    return rows, missing, len(model.texts)


def render_md(rows, missing, total) -> str:
    lines = [
        "# G_TEXT_PTRS id ↔ text table",
        "",
        "Runtime localized-string table: `cfg::G_TEXT_PTRS[id]` -> string. **`id` is "
        "the `K_*` DEFINE value**, not the `TEXT` file order in initlang.cfg. "
        "Generated by `python -m src.formats.cfgkit.dump_text_ids` from the clean "
        "RU `mh_ex/init/initlang.cfg` -- do not hand-edit.",
        "",
        f"{len(rows)} strings (of {total} `TEXT` entries), ids "
        f"{rows[0][0]}–{rows[-1][0]}.",
        "",
        MARK_BEGIN,
        "",
        "| Id | Hex | Key (wire) | English | Text (RU) |",
        "| ---: | --- | --- | --- | --- |",
    ]
    for tid, key, en, val in rows:
        lines.append(f"| {tid} | 0x{tid:x} | `{key}` | {_cell(en)} | {_cell(val)} |")
    lines += ["", MARK_END, ""]
    if missing:
        lines += [f"<!-- unmapped/dup keys: {missing} -->", ""]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--init", default=CLEAN + "/mh/init/INIT.CFG")
    ap.add_argument("--lang", default=CLEAN + "/mh_ex/init/initlang.cfg")
    # No default: this table is game-config-derived, the tree does not always carry it, and a
    # default output path would name a file the public cut deliberately omits. Name it explicitly.
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    rows, missing, total = build_rows(args.init, args.lang)
    open(args.out, "w", encoding="utf-8").write(render_md(rows, missing, total))
    print(f"wrote {args.out}: {len(rows)} ids (of {total} texts)"
          + (f", {len(missing)} unmapped" if missing else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
