// GENERATED by tools/gen_inmem_manifest.py from src/patcher/projectile_pool_relocate_EN.mh.patch.json -- do not hand-edit.
//
// mh.exe (retail)
//
// The manifest as COMPILED-IN DATA: mh.dll applies it to the loaded image instead of mhpatch
// applying it to a file. `refs` are the dwords inside the cave and the patch bytes that are
// RELATIVE and therefore only valid at one placement -- recovered by decoding, not scanning,
// so `refs_complete` is a proof and not a hope. See mh/patch/inmem_patch.h.
#pragma once
#include "hook/promoted.h"
#include "patch/inmem_patch.h"

namespace mh::patch::manifest_projectile_pool_relocate_en {

inline constexpr inmem_section SECTIONS[] = {
    {".mhpool", 0x010f0000u, 0x2c4fcu, nullptr, 0u, 0xe0000040u},
};

inline constexpr uint8_t P0_EXPECT[] = {0x11, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P0_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P0_REPL[]   = {0x79, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P1_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P1_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P1_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P2_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P2_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P2_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P3_EXPECT[] = {0xa2, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P3_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P3_REPL[]   = {0x0a, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P4_EXPECT[] = {0xa0, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P4_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P4_REPL[]   = {0x08, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P5_EXPECT[] = {0xf5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P5_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P5_REPL[]   = {0x5d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P6_EXPECT[] = {0xa2, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P6_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P6_REPL[]   = {0x0a, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P7_EXPECT[] = {0xa0, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P7_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P7_REPL[]   = {0x08, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P8_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P8_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P8_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P9_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P9_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P9_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P10_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P10_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P10_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P11_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P11_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P11_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P12_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P12_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P12_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P13_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P13_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P13_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P14_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P14_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P14_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P15_EXPECT[] = {0x0b, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P15_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P15_REPL[]   = {0x73, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P16_EXPECT[] = {0x0d, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P16_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P16_REPL[]   = {0x75, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P17_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P17_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P17_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P18_EXPECT[] = {0xb0, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P18_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P18_REPL[]   = {0x18, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P19_EXPECT[] = {0xe9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P19_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P19_REPL[]   = {0x51, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P20_EXPECT[] = {0xed, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P20_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P20_REPL[]   = {0x55, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P21_EXPECT[] = {0xf1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P21_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P21_REPL[]   = {0x59, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P22_EXPECT[] = {0xf1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P22_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P22_REPL[]   = {0x59, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P23_EXPECT[] = {0xf1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P23_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P23_REPL[]   = {0x59, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P24_EXPECT[] = {0xf1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P24_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P24_REPL[]   = {0x59, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P25_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P25_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P25_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P26_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P26_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P26_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P27_EXPECT[] = {0xf5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P27_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P27_REPL[]   = {0x5d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P28_EXPECT[] = {0xf5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P28_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P28_REPL[]   = {0x5d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P29_EXPECT[] = {0x01, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P29_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P29_REPL[]   = {0x69, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P30_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P30_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P30_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P31_EXPECT[] = {0xf1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P31_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P31_REPL[]   = {0x59, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P32_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P32_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P32_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P33_EXPECT[] = {0xf5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P33_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P33_REPL[]   = {0x5d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P34_EXPECT[] = {0xf5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P34_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P34_REPL[]   = {0x5d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P35_EXPECT[] = {0x01, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P35_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P35_REPL[]   = {0x69, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P36_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P36_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P36_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P37_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P37_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P37_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P38_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P38_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P38_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P39_EXPECT[] = {0xf9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P39_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P39_REPL[]   = {0x61, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P40_EXPECT[] = {0xf9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P40_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P40_REPL[]   = {0x61, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P41_EXPECT[] = {0xa4, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P41_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P41_REPL[]   = {0x0c, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P42_EXPECT[] = {0xa6, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P42_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P42_REPL[]   = {0x0e, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P43_EXPECT[] = {0xa8, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P43_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P43_REPL[]   = {0x10, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P44_EXPECT[] = {0xaa, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P44_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P44_REPL[]   = {0x12, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P45_EXPECT[] = {0xac, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P45_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P45_REPL[]   = {0x14, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P46_EXPECT[] = {0xae, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P46_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P46_REPL[]   = {0x16, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P47_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P47_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P47_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P48_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P48_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P48_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P49_EXPECT[] = {0xa6, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P49_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P49_REPL[]   = {0x0e, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P50_EXPECT[] = {0xa8, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P50_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P50_REPL[]   = {0x10, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P51_EXPECT[] = {0xd9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P51_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P51_REPL[]   = {0x41, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P52_EXPECT[] = {0xd9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P52_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P52_REPL[]   = {0x41, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P53_EXPECT[] = {0xe1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P53_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P53_REPL[]   = {0x49, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P54_EXPECT[] = {0xe1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P54_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P54_REPL[]   = {0x49, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P55_EXPECT[] = {0xd1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P55_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P55_REPL[]   = {0x39, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P56_EXPECT[] = {0xd1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P56_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P56_REPL[]   = {0x39, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P57_EXPECT[] = {0xc1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P57_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P57_REPL[]   = {0x29, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P58_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P58_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P58_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P59_EXPECT[] = {0x05, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P59_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P59_REPL[]   = {0x6d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P60_EXPECT[] = {0x07, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P60_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P60_REPL[]   = {0x6f, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P61_EXPECT[] = {0x05, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P61_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P61_REPL[]   = {0x6d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P62_EXPECT[] = {0x07, 0xdc, 0xe1, 0x00};
inline constexpr uint8_t P62_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P62_REPL[]   = {0x6f, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P63_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P63_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P63_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P64_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P64_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P64_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P65_EXPECT[] = {0xe1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P65_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P65_REPL[]   = {0x49, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P66_EXPECT[] = {0xfd, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P66_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P66_REPL[]   = {0x65, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P67_EXPECT[] = {0xe1, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P67_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P67_REPL[]   = {0x49, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P68_EXPECT[] = {0xe5, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P68_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P68_REPL[]   = {0x4d, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P69_EXPECT[] = {0xfd, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P69_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P69_REPL[]   = {0x65, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P70_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P70_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P70_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P71_EXPECT[] = {0x9c, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P71_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P71_REPL[]   = {0x04, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P72_EXPECT[] = {0xc9, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P72_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P72_REPL[]   = {0x31, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P73_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P73_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P73_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr uint8_t P74_EXPECT[] = {0x98, 0xdb, 0xe1, 0x00};
inline constexpr uint8_t P74_MASK[]   = {0xff, 0xff, 0xff, 0xff};
inline constexpr uint8_t P74_REPL[]   = {0x00, 0x00, 0x0f, 0x01};
inline constexpr inmem_site SITES[] = {
    {0x0043fd8eu, P0_EXPECT, P0_MASK, P0_REPL, 4u},
    {0x0043fd93u, P1_EXPECT, P1_MASK, P1_REPL, 4u},
    {0x0044135fu, P2_EXPECT, P2_MASK, P2_REPL, 4u},
    {0x004419cau, P3_EXPECT, P3_MASK, P3_REPL, 4u},
    {0x004419e4u, P4_EXPECT, P4_MASK, P4_REPL, 4u},
    {0x00441a0au, P5_EXPECT, P5_MASK, P5_REPL, 4u},
    {0x00441a21u, P6_EXPECT, P6_MASK, P6_REPL, 4u},
    {0x00441a54u, P7_EXPECT, P7_MASK, P7_REPL, 4u},
    {0x00447dc5u, P8_EXPECT, P8_MASK, P8_REPL, 4u},
    {0x004482b1u, P9_EXPECT, P9_MASK, P9_REPL, 4u},
    {0x0044e722u, P10_EXPECT, P10_MASK, P10_REPL, 4u},
    {0x0044e746u, P11_EXPECT, P11_MASK, P11_REPL, 4u},
    {0x004560dau, P12_EXPECT, P12_MASK, P12_REPL, 4u},
    {0x00464955u, P13_EXPECT, P13_MASK, P13_REPL, 4u},
    {0x0046499cu, P14_EXPECT, P14_MASK, P14_REPL, 4u},
    {0x004649b1u, P15_EXPECT, P15_MASK, P15_REPL, 4u},
    {0x004649beu, P16_EXPECT, P16_MASK, P16_REPL, 4u},
    {0x004649cbu, P17_EXPECT, P17_MASK, P17_REPL, 4u},
    {0x004649d8u, P18_EXPECT, P18_MASK, P18_REPL, 4u},
    {0x00464a8bu, P19_EXPECT, P19_MASK, P19_REPL, 4u},
    {0x00464a98u, P20_EXPECT, P20_MASK, P20_REPL, 4u},
    {0x00464acdu, P21_EXPECT, P21_MASK, P21_REPL, 4u},
    {0x00464b1eu, P22_EXPECT, P22_MASK, P22_REPL, 4u},
    {0x00464b4bu, P23_EXPECT, P23_MASK, P23_REPL, 4u},
    {0x00464b99u, P24_EXPECT, P24_MASK, P24_REPL, 4u},
    {0x00464bb3u, P25_EXPECT, P25_MASK, P25_REPL, 4u},
    {0x00464bd4u, P26_EXPECT, P26_MASK, P26_REPL, 4u},
    {0x00464bf7u, P27_EXPECT, P27_MASK, P27_REPL, 4u},
    {0x00464bfdu, P28_EXPECT, P28_MASK, P28_REPL, 4u},
    {0x00464c07u, P29_EXPECT, P29_MASK, P29_REPL, 4u},
    {0x00464c13u, P30_EXPECT, P30_MASK, P30_REPL, 4u},
    {0x00464c21u, P31_EXPECT, P31_MASK, P31_REPL, 4u},
    {0x00464c2cu, P32_EXPECT, P32_MASK, P32_REPL, 4u},
    {0x00464c50u, P33_EXPECT, P33_MASK, P33_REPL, 4u},
    {0x00464c56u, P34_EXPECT, P34_MASK, P34_REPL, 4u},
    {0x00464c60u, P35_EXPECT, P35_MASK, P35_REPL, 4u},
    {0x00464c6au, P36_EXPECT, P36_MASK, P36_REPL, 4u},
    {0x00464c8du, P37_EXPECT, P37_MASK, P37_REPL, 4u},
    {0x00464ca6u, P38_EXPECT, P38_MASK, P38_REPL, 4u},
    {0x00464cbau, P39_EXPECT, P39_MASK, P39_REPL, 4u},
    {0x00464cc6u, P40_EXPECT, P40_MASK, P40_REPL, 4u},
    {0x00464cd8u, P41_EXPECT, P41_MASK, P41_REPL, 4u},
    {0x00464ce6u, P42_EXPECT, P42_MASK, P42_REPL, 4u},
    {0x00464cf4u, P43_EXPECT, P43_MASK, P43_REPL, 4u},
    {0x00464d02u, P44_EXPECT, P44_MASK, P44_REPL, 4u},
    {0x00464d10u, P45_EXPECT, P45_MASK, P45_REPL, 4u},
    {0x00464d1eu, P46_EXPECT, P46_MASK, P46_REPL, 4u},
    {0x00464d27u, P47_EXPECT, P47_MASK, P47_REPL, 4u},
    {0x00464d36u, P48_EXPECT, P48_MASK, P48_REPL, 4u},
    {0x00464d71u, P49_EXPECT, P49_MASK, P49_REPL, 4u},
    {0x00464d7eu, P50_EXPECT, P50_MASK, P50_REPL, 4u},
    {0x00464d9eu, P51_EXPECT, P51_MASK, P51_REPL, 4u},
    {0x00464da4u, P52_EXPECT, P52_MASK, P52_REPL, 4u},
    {0x00464daeu, P53_EXPECT, P53_MASK, P53_REPL, 4u},
    {0x00464db4u, P54_EXPECT, P54_MASK, P54_REPL, 4u},
    {0x00464dbeu, P55_EXPECT, P55_MASK, P55_REPL, 4u},
    {0x00464dc4u, P56_EXPECT, P56_MASK, P56_REPL, 4u},
    {0x00464dceu, P57_EXPECT, P57_MASK, P57_REPL, 4u},
    {0x00464dd8u, P58_EXPECT, P58_MASK, P58_REPL, 4u},
    {0x00464e06u, P59_EXPECT, P59_MASK, P59_REPL, 4u},
    {0x00464e13u, P60_EXPECT, P60_MASK, P60_REPL, 4u},
    {0x00464e20u, P61_EXPECT, P61_MASK, P61_REPL, 4u},
    {0x00464e2cu, P62_EXPECT, P62_MASK, P62_REPL, 4u},
    {0x00464e3au, P63_EXPECT, P63_MASK, P63_REPL, 4u},
    {0x00464e5du, P64_EXPECT, P64_MASK, P64_REPL, 4u},
    {0x00464e77u, P65_EXPECT, P65_MASK, P65_REPL, 4u},
    {0x00464e81u, P66_EXPECT, P66_MASK, P66_REPL, 4u},
    {0x00464e91u, P67_EXPECT, P67_MASK, P67_REPL, 4u},
    {0x00464e9bu, P68_EXPECT, P68_MASK, P68_REPL, 4u},
    {0x00464ea9u, P69_EXPECT, P69_MASK, P69_REPL, 4u},
    {0x00464eb7u, P70_EXPECT, P70_MASK, P70_REPL, 4u},
    {0x00464eecu, P71_EXPECT, P71_MASK, P71_REPL, 4u},
    {0x00464f02u, P72_EXPECT, P72_MASK, P72_REPL, 4u},
    {0x00464f08u, P73_EXPECT, P73_MASK, P73_REPL, 4u},
    {0x00464f12u, P74_EXPECT, P74_MASK, P74_REPL, 4u},
};

// F4C-COMP: the ORIGINAL bodies these sites land in (tools/data/en_functions.json).
inline constexpr inmem_body BODIES[] = {
    {"llm_strat_sim_step", 0x0043f512u, 0x0043fe1du},
    {"llm_strat_projectile_tick", 0x00440e1cu, 0x004418a4u},
    {"llm_strat_projectile_draw", 0x004419a8u, 0x00441a8du},
    {"map_SavePlanetToDisk", 0x00447bb3u, 0x00448106u},
    {"map_LoadPlanetFromDisk", 0x00448107u, 0x00448660u},
    {"llm_strat_render_view", 0x0044e5a4u, 0x0044eb5fu},
    {"map_FillDefaults", 0x0045603eu, 0x004564c1u},
    {"llm_strat_projectile_spawn", 0x00464932u, 0x00464f3au},
};

inline constexpr inmem_ref REFS[] = {
    {0, 0, 0u, ref_kind::abs32_to_section, 0, 0x00000079u},
    {0, 1, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 2, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 3, 0u, ref_kind::abs32_to_section, 0, 0x0000000au},
    {0, 4, 0u, ref_kind::abs32_to_section, 0, 0x00000008u},
    {0, 5, 0u, ref_kind::abs32_to_section, 0, 0x0000005du},
    {0, 6, 0u, ref_kind::abs32_to_section, 0, 0x0000000au},
    {0, 7, 0u, ref_kind::abs32_to_section, 0, 0x00000008u},
    {0, 8, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 9, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 10, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 11, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 12, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 13, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 14, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 15, 0u, ref_kind::abs32_to_section, 0, 0x00000073u},
    {0, 16, 0u, ref_kind::abs32_to_section, 0, 0x00000075u},
    {0, 17, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 18, 0u, ref_kind::abs32_to_section, 0, 0x00000018u},
    {0, 19, 0u, ref_kind::abs32_to_section, 0, 0x00000051u},
    {0, 20, 0u, ref_kind::abs32_to_section, 0, 0x00000055u},
    {0, 21, 0u, ref_kind::abs32_to_section, 0, 0x00000059u},
    {0, 22, 0u, ref_kind::abs32_to_section, 0, 0x00000059u},
    {0, 23, 0u, ref_kind::abs32_to_section, 0, 0x00000059u},
    {0, 24, 0u, ref_kind::abs32_to_section, 0, 0x00000059u},
    {0, 25, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 26, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 27, 0u, ref_kind::abs32_to_section, 0, 0x0000005du},
    {0, 28, 0u, ref_kind::abs32_to_section, 0, 0x0000005du},
    {0, 29, 0u, ref_kind::abs32_to_section, 0, 0x00000069u},
    {0, 30, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 31, 0u, ref_kind::abs32_to_section, 0, 0x00000059u},
    {0, 32, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 33, 0u, ref_kind::abs32_to_section, 0, 0x0000005du},
    {0, 34, 0u, ref_kind::abs32_to_section, 0, 0x0000005du},
    {0, 35, 0u, ref_kind::abs32_to_section, 0, 0x00000069u},
    {0, 36, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 37, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 38, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 39, 0u, ref_kind::abs32_to_section, 0, 0x00000061u},
    {0, 40, 0u, ref_kind::abs32_to_section, 0, 0x00000061u},
    {0, 41, 0u, ref_kind::abs32_to_section, 0, 0x0000000cu},
    {0, 42, 0u, ref_kind::abs32_to_section, 0, 0x0000000eu},
    {0, 43, 0u, ref_kind::abs32_to_section, 0, 0x00000010u},
    {0, 44, 0u, ref_kind::abs32_to_section, 0, 0x00000012u},
    {0, 45, 0u, ref_kind::abs32_to_section, 0, 0x00000014u},
    {0, 46, 0u, ref_kind::abs32_to_section, 0, 0x00000016u},
    {0, 47, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 48, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 49, 0u, ref_kind::abs32_to_section, 0, 0x0000000eu},
    {0, 50, 0u, ref_kind::abs32_to_section, 0, 0x00000010u},
    {0, 51, 0u, ref_kind::abs32_to_section, 0, 0x00000041u},
    {0, 52, 0u, ref_kind::abs32_to_section, 0, 0x00000041u},
    {0, 53, 0u, ref_kind::abs32_to_section, 0, 0x00000049u},
    {0, 54, 0u, ref_kind::abs32_to_section, 0, 0x00000049u},
    {0, 55, 0u, ref_kind::abs32_to_section, 0, 0x00000039u},
    {0, 56, 0u, ref_kind::abs32_to_section, 0, 0x00000039u},
    {0, 57, 0u, ref_kind::abs32_to_section, 0, 0x00000029u},
    {0, 58, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 59, 0u, ref_kind::abs32_to_section, 0, 0x0000006du},
    {0, 60, 0u, ref_kind::abs32_to_section, 0, 0x0000006fu},
    {0, 61, 0u, ref_kind::abs32_to_section, 0, 0x0000006du},
    {0, 62, 0u, ref_kind::abs32_to_section, 0, 0x0000006fu},
    {0, 63, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 64, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 65, 0u, ref_kind::abs32_to_section, 0, 0x00000049u},
    {0, 66, 0u, ref_kind::abs32_to_section, 0, 0x00000065u},
    {0, 67, 0u, ref_kind::abs32_to_section, 0, 0x00000049u},
    {0, 68, 0u, ref_kind::abs32_to_section, 0, 0x0000004du},
    {0, 69, 0u, ref_kind::abs32_to_section, 0, 0x00000065u},
    {0, 70, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 71, 0u, ref_kind::abs32_to_section, 0, 0x00000004u},
    {0, 72, 0u, ref_kind::abs32_to_section, 0, 0x00000031u},
    {0, 73, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
    {0, 74, 0u, ref_kind::abs32_to_section, 0, 0x00000000u},
};

inline constexpr inmem_manifest MANIFEST = {
    "projectile_pool_relocate_EN",
    "1cd5810c5c0b845f0b7c8359a494243d9bec51397c8becfe149841be09c2562d",
    SECTIONS, 1,
    SITES, 75,
    REFS, 75,
    BODIES, 8,
    /*refs_complete=*/true,
};

static_assert(8 <= mh::hook::MAX_PATCHED_BODIES,
              "projectile_pool_relocate_EN registers more bodies than mh::hook's patched-body table holds -- raise MAX_PATCHED_BODIES");

} // namespace mh::patch::manifest_projectile_pool_relocate_en
